 ############################## 
 # Lord Rommel - 11.02.2011   #
 ############################## 
 # Country definition for FRA # 
 ############################## 
 
province = { id = 37   anti_air = 4 air_base = { size = 10 current_size = 10 } naval_base = { size = 10 current_size = 10 }} #Brest
province = { id = 89   anti_air = 1 air_base = { size = 10 current_size = 10 } naval_base = { size = 4 current_size = 4 }} #Marseille
province = { id = 86   anti_air = 5 naval_base = { size = 8 current_size = 8 }} #Toulon
province = { id = 87   naval_base = { size = 1 current_size = 1 }} #Nice
province = { id = 39   naval_base = { size = 1 current_size = 1 }} #Lorient
province = { id = 40   naval_base = { size = 1 current_size = 1 }} #Saint-Nazaires
province = { id = 45   naval_base = { size = 2 current_size = 2 }} #Le Havre
province = { id = 53   naval_base = { size = 2 current_size = 2 }} #Dieppe
province = { id = 49   naval_base = { size = 2 current_size = 2 }} #Calais
province = { id = 718  anti_air = 3 air_base = { size = 4 current_size = 4 } naval_base = { size = 4 current_size = 4 }} #Casablanca
province = { id = 68   anti_air = 4 air_base = { size = 4 current_size = 4 } naval_base = { size = 6 current_size = 6 }} #Bordeaux
province = { id = 978  anti_air = 3 air_base = { size = 4 current_size = 4 } naval_base = { size = 2 current_size = 2 }} #Dakar
province = { id = 1399 anti_air = 3 air_base = { size = 4 current_size = 4 } naval_base = { size = 4 current_size = 4 }} #Saigon
province = { id = 1395 anti_air = 4 air_base = { size = 4 current_size = 4 } naval_base = { size = 4 current_size = 4 } oilpool = 10 supplypool = 10 } #Hanoi
province = { id = 43   anti_air = 3 air_base = { size = 4 current_size = 4 } naval_base = { size = 6 current_size = 6 }} #Cherbourg
province = { id = 747  anti_air = 4 air_base = { size = 4 current_size = 4 } naval_base = { size = 5 current_size = 5 }} #Tunis
province = { id = 727  anti_air = 4 air_base = { size = 4 current_size = 4 } naval_base = { size = 5 current_size = 5 } oilpool = 100 supplypool = 100 } #Algiers
province = { id = 55   anti_air = 5 air_base = { size = 10 current_size = 10 }} #Paris
province = { id = 104  anti_air = 3 air_base = { size = 10 current_size = 10 }} #Metz
province = { id = 52   anti_air = 1 air_base = { size = 10 current_size = 10 }} #Lille
province = { id = 99 air_base = { size = 2 current_size = 2 } anti_air = 1 } #Reims 
province = { id = 61 air_base = { size = 1 current_size = 1 }} #Tours 
province = { id = 85 air_base = { size = 1 current_size = 1 }} #Lyon 
province = { id = 97 air_base = { size = 1 current_size = 1 }} #Belfort 
province = { id = 77   anti_air = 2 } #Toulouse
province = { id = 66   air_base = { size = 10 current_size = 10 }} #Orleans
province = { id = 57   air_base = { size = 8 current_size = 8 }} #Nants
province = { id = 69   naval_base = { size = 2 current_size = 2 } air_base = { size = 2 current_size = 2 }} #La Rochelle
province = { id = 1019 anti_air = 2 air_base = { size = 4 current_size = 4 } naval_base = { size = 2 current_size = 2 } oilpool = 10 supplypool = 10 } #Beirut
province = { id = 728  anti_air = 2 air_base = { size = 4 current_size = 4 } naval_base = { size = 2 current_size = 2 }} #Oran
province = { id = 962  anti_air = 2 air_base = { size = 4 current_size = 4 } naval_base = { size = 1 current_size = 1 }} #Abidjan
province = { id = 915  naval_base = { size = 1 current_size = 1 }} #Libreville
province = { id = 1002 anti_air = 1 naval_base = { size = 2 current_size = 2 } oilpool = 10 supplypool = 10 } #Tamatave
province = { id = 833  anti_air = 1 naval_base = { size = 1 current_size = 1 } oilpool = 10 supplypool = 10 } #Dijbouti
#province = { id = 1768 air_base = { size = 1 current_size = 1 } naval_base = { size = 1 current_size = 1 }} #Martinique
province = { id = 1743 naval_base = { size = 1 current_size = 1 } supplypool = 1 } # Papeete
province = { id = 1586 naval_base = { size = 1 current_size = 1 }} #Nouvelle-Caledonie 
province = { id = 1582 naval_base = { size = 1 current_size = 1 } air_base = { size = 1 current_size = 1 }} #Espiritu Santo
province = { id = 1768 naval_base = { size = 1 current_size = 1 }} #Martinique

#Anti Aircraft Batteries
province = { id = 74   anti_air = 1 } #Vichy
province = { id = 57   anti_air = 2 } #Nantes
province = { id = 107  anti_air = 2 } #Strasbourg
province = { id = 95   anti_air = 1 } #Chaumont
province = { id = 44   anti_air = 1 } #Caen
province = { id = 105  anti_air = 2 } #Mulhouse

#Maginot line
province = { id = 96  landfort = 4 }#Longwy
province = { id = 104 landfort = 9 }#Metz
province = { id = 107 landfort = 9 }#Strasbourg
province = { id = 105 landfort = 9 }#Colmar

#Ligne Alpine
province = { id = 91  landfort = 4 }#Chambery
province = { id = 90  landfort = 4 }#Grenoble
province = { id = 87  landfort = 4 }#Nice

#Mareth-Linie
province = { id = 744 landfort = 2 }#Gabes
province = { id = 740 landfort = 1 }#Kasserine
  
 ##################### 
 # Country main data # 
 ##################### 
  
 country = 
 { tag                    = FRA 
   capital                = 55 
   # Resource Reserves 
   energy                 = 1000
   metal                  = 1000
   rare_materials         = 500
   oil                    = 400 
   supplies               = 400 
   money                  = 50 
   manpower               = 200 
   transports             = 475
   escorts                = 81 

   peacetime_ic_mod = 0.5

   ai_settings	= { flags = { convoy_gift_on_release = yes } }
	policy = {
        date = { year = 0 month = january day = 0 }
        democratic = 10
        political_left = 6
        free_market = 8
        freedom = 10
        professional_army = 5
        defense_lobby = 7
        interventionism = 6
   }
   
   	headofgovernment = { type = 9 id = 2040 }
   
   allowed_divisions = { 
        infantry = yes 
        cavalry = yes 
        bergsjaeger = yes
		motorized = yes
   } 

   #inventions = { 2700061 2700063 2700065 }  
   dormant_teams = { 1456 }  
   dormant_leaders = {  24231 24232 24233 24234 24235  } #polish generals in france
   
   diplomacy = {
               relation = { tag = AST value = 150 }
               relation = { tag = AUS value = -10 }
               relation = { tag = BEL value = 120 guaranteed = { day = 7 month = january year = 1935 } }
               relation = { tag = BHU value = 150 }
               relation = { tag = BUL value = 20 }
               relation = { tag = CAN value = 150 }
               relation = { tag = CZE value = 150 }
               relation = { tag = ENG value = 150 }
               relation = { tag = ETH value = 25 }
               relation = { tag = FIN value = 85 }
               relation = { tag = GER value = -35 }
               relation = { tag = GRE value = 20 }
               relation = { tag = HOL value = 75 guaranteed = { day = 7 month = january year = 1935 } }
               relation = { tag = HUN value = -70 }
               relation = { tag = IRE value = 25 }
               relation = { tag = IRQ value = 100 }
               relation = { tag = ITA value = -50 }
               relation = { tag = LUX value = 120 guaranteed = { day = 7 month = january year = 1935 } }
               relation = { tag = NEP value = 150 }
               relation = { tag = NOR guaranteed = { day = 29 month = august year = 1934 } }
               relation = { tag = NZL value = 150 }
               relation = { tag = OMN value = 150 }
               relation = { tag = POL value = 100 guaranteed = { day = 7 month = january year = 1935 } }
               relation = { tag = ROM value = 50 }
               relation = { tag = SAF value = 150 }
               relation = { tag = SAU value = 10 }
               relation = { tag = SCH value = 0 guaranteed = { day = 16 month = may year = 1935 }  }
               relation = { tag = SIA value = -100 }
               relation = { tag = SOV value = 100 }
               relation = { tag = SPR value = 75 }
               relation = { tag = TUR value = 50 guaranteed = { day = 7 month = january year = 1935 } }
               relation = { tag = YEM value = 150 }
               relation = { tag = YUG value = 50 guaranteed = { day = 7 month = january year = 1935 } }
			   relation = { tag = U04 value = 50 guaranteed = { day = 7 month = january year = 1935 } }
    } 
	
   SpyInfo = {  country = "FRA" NumberOfSpies = 8 } 
   
   nationalprovinces  = {  
   #Metropole France
   51 #Dunkirk#
   49 #Calais#
   52 #Lille#
   50 #Amiens#
   103 #Hirson#=>Valenciennes
   101 #Laon#=>Valenciennes
   53 #Dieppe#
   102 #Sedan#
   56 #Chateau Thierry=>Compiegne#
   55 #Paris#
   45 #Le Havre#
   44 #Caen#
   46 #Bayeux#
   43 #Cherbourg#
   37 #Brest#
   41 #Saint Brieuc=>Rennes(split)#
   38 #Rennes#
   42 #Avranches#
   47 #Falaise=>Argentan#
   48 #Evreux=>Argentan(split)#
   99 #Reims#
   100 #Verdun#
   96 #Longwy#
   104 #Metz=>Strassburg(split)#
   107 #Strasbourg#
   105 #Colmar#
   106 #Nancy#
   54 #Troyes#
   60 #Chartres#
   58 #Le Mans#
   59 #Angers#
   39 #Lorient#
   40 #Saint Nazaire=>Nantes#
   66 #Orleans#
   95 #Chaumont#
   97 #Belfort#
   63 #Auxerre#
   65 #Bourges#
   61 #Tours#
   62 #Poitiers=>Cholet(split)#
   57 #Nantes=>Cholet(split)#
   69 #La Rochelle#
   73 #Limoges#
   72 #Chateauroux#
   74 #Vichy#
   64 #Le Creusot#
   98 #Pontarlier=>Besancon#
   88 #Bourg-en-Bresse#
   85 #Lyon#
   68 #Bordeaux#
   70 #Angouleme=>La Rochelle(split)#
   75 #Perigueux#
   76 #Tulle#
   71 #Clermont-Ferrand#
   78 #Saint Etienne#
   92 #Valence#
   91 #Chambery#
   90 #Grenoble#
   93 #Avignon#
   81 #Rodez#
   77 #Toulouse#
   84 #Agen#
   67 #Mont-de-Marsan#
   83 #Pau#
   80 #Perpignan#
   79 #Beziers#
   82 #Montpellier#
   89 #Marseille#
   86 #Toulon#
   87 #Nice#
   94 #Corsica#
   #Schweiz
   391 #Geneva
   } 
   
   ownedprovinces = {
   #Metropole France
   51 #Dunkirk
   49 #Calais
   52 #Lille
   50 #Amiens
   103 #Hirson
   101 #Laon
   53 #Dieppe
   102 #Sedan
   56 #Chateau Thierry
   55 #Paris
   45 #Le Havre
   44 #Caen
   46 #Bayeux
   43 #Cherbourg
   37 #Brest
   41 #Saint Brieuc
   38 #Rennes
   42 #Avranches
   47 #Falaise
   48 #Evreux
   99 #Reims
   100 #Verdun
   96 #Longwy
   104 #Metz
   107 #Strasbourg
   105 #Colmar
   106 #Nancy
   54 #Troyes
   60 #Chartres
   58 #Le Mans
   59 #Angers
   39 #Lorient
   40 #Saint Nazaire
   66 #Orleans
   95 #Chaumont
   97 #Belfort
   63 #Auxerre
   65 #Bourges
   61 #Tours
   62 #Poitiers
   57 #Nantes
   69 #La Rochelle
   73 #Limoges
   72 #Chateauroux
   74 #Vichy
   64 #Le Creusot
   98 #Pontarlier
   88 #Bourg-en-Bresse
   85 #Lyon
   68 #Bordeaux
   70 #Angouleme
   75 #Perigueux
   76 #Tulle
   71 #Clermont-Ferrand
   78 #Saint Etienne
   92 #Valence
   91 #Chambery
   90 #Grenoble
   93 #Avignon
   81 #Rodez
   77 #Toulouse
   84 #Agen
   67 #Mont-de-Marsan
   83 #Pau
   80 #Perpignan
   79 #Beziers
   82 #Montpellier
   89 #Marseille
   86 #Toulon
   87 #Nice
   94 #Corsica
### Karibik
   2000 #Cayenne#
   1767 #Guadeloupe#
   1768 #Martinique#
   #Maroc
   724 #Qujda#
   726 #Er Rachidia=>Bouarfa#
   725 #Ouarzazate=>Quezzane#
   721 #Fes=>Marakesh(split)#
   717 #Rabat#
   718 #Casablanca#
   722 #Marrakesh#
   723 #Khenifra=>Marakesh(split)#
   720 #Agadir#
   719 #Tiznit#
   #Algerien
   738 #Tamanrasset#
   737 #Touggourt#
   739 #Colom Bechar#
   743 #Tebessa#
   734 #Constantine#
   735 #Bona#
   731 #Batna#
   732 #Djelfa#
   736 #Bougie#
   733 #Geryville#
   727 #Algiers#
   730 #Orleansville#
   728 #Oran#
   729 #Tlemcen#
   #Tunesien
   741 #Tataouine#
   744 #Gabes#
   740 #Kasserine#
   742 #Medenine#
   745 #Sousse#
   746 #El Kef#
   747 #Tunis#
   748 #Bizerte#
   749 #Beja#
   # Libanon/Syrien
   1019 #Beirut#
   1020 #Golan#
   1016 #Damascus#
   1018 #Trablos#
   1017 #Hims#
   1021 #Aleppo#
   1014 #Deir ez Zor#	
   1015 #El Qmisli#
   1054 #Hatay
   # Indochina
   1392 #Hai Phong#
   1393 #Hoa Binh#
   1395 #Hanoi#
   1404 #Muang Xay#
   1391 #Muang Xaignabouli#
   1405 #Vientiane#
   1396 #Dong Hoi#
   1394 #Pakxe#
   1397 #Da Nang#
   1399 #Saigon#
   1398 #Lumphat=>Pakse#
   1401 #Siem Reap#
   1402 #Battambang#
   1400 #Phnom Penh#
   1403 #Can Tho#
### Afrika   
   833 #Djibouti#	
   981 #Nouakchott=>Port Etienne#
   982 #Kiffa#
   943 #Zinder#
   944 #Niamey#
   942 #Say#
   984 #Gao#
   985 #Tombouctou# 
   974 #Mopti#
   978 #Dakar#
   980 #Ziguinchor#
   966 #Conakry#
   965 #Labe#
   975 #Kayes#
   971 #Nioro du Sahel#
   972 #Segou#
   973 #Sikasso#
   976 #Bamako#
   959 #Bobo-Dioulasso#
   957 #Ouagadougou#
   949 #Natitingou#
   951 #Cotonou#
   967 #Kankan#
   960 #Yamoussoukro#
   962 #Abidjan#
   910 #Bertoua#
   922 #Faya#
   920 #Fort Lamy#
   924 #Moundou#
   925 #Maroua#
   923 #Bambari#
   926 #Bangui#
   909 #Yaounde#
   928 #N'Gaoundere#
   911 #Douala#
   914 #Franceville#
   915 #Libreville#
   907 #Brazzaville#
   908 #Quesso=>Impfondo#
   #Madagaskar
   1001 #Tananarive#
   1002 #Tamatave#
   1003 #Fort Dauphin#
   # 
   996 #Saint Denis de la Reunion#
   1586 #Nouvelle-Caledonie#
   1585 #Ouvea#
   1584 #Tanna#
   1583 #Malekula#
   1582 #Espiritu Santo#
   1581 #Efate#
   #
   950 #Lome#
   948 #Kara#
   917 #Pointe-Noire#
   918 #Fort Gentil#
   919 #Bouar#
   927 #Ouadda#
   921 #Abeche#
   946 #Agadez#
   947 #Tahoua#
   945 #Tenkodogo#
   958 #Tougan#
   961 #Bouake#
   968 #Korhogo#
   970 #San Pedro#
   977 #Tambacounda#
   983 #Saint-Louis#
   986 #Atar#
   999 #Muruni
   1000 #Mamoudzou
   1740 #Rikitea
   1743 #Papeete#
   1744 #Taiohae
   1730 #Mata'utu
   1752 #St-Martin
   2135 #Saint-Pierre
   } 
 
   controlledprovinces  = {
   #Metropole France
   51 #Dunkirk
   49 #Calais
   52 #Lille
   50 #Amiens
   103 #Hirson
   101 #Laon
   53 #Dieppe
   102 #Sedan
   56 #Chateau Thierry
   55 #Paris
   45 #Le Havre
   44 #Caen
   46 #Bayeux
   43 #Cherbourg
   37 #Brest
   41 #Saint Brieuc
   38 #Rennes
   42 #Avranches
   47 #Falaise
   48 #Evreux
   99 #Reims
   100 #Verdun
   96 #Longwy
   104 #Metz
   107 #Strasbourg
   105 #Colmar
   106 #Nancy
   54 #Troyes
   60 #Chartres
   58 #Le Mans
   59 #Angers
   39 #Lorient
   40 #Saint Nazaire
   66 #Orleans
   95 #Chaumont
   97 #Belfort
   63 #Auxerre
   65 #Bourges
   61 #Tours
   62 #Poitiers
   57 #Nantes
   69 #La Rochelle
   73 #Limoges
   72 #Chateauroux
   74 #Vichy
   64 #Le Creusot
   98 #Pontarlier
   88 #Bourg-en-Bresse
   85 #Lyon
   68 #Bordeaux
   70 #Angouleme
   75 #Perigueux
   76 #Tulle
   71 #Clermont-Ferrand
   78 #Saint Etienne
   92 #Valence
   91 #Chambery
   90 #Grenoble
   93 #Avignon
   81 #Rodez
   77 #Toulouse
   84 #Agen
   67 #Mont-de-Marsan
   83 #Pau
   80 #Perpignan
   79 #Beziers
   82 #Montpellier
   89 #Marseille
   86 #Toulon
   87 #Nice
   94 #Corsica
   #
   2000 #Cayenne
   1767 #Guadeloupe
   1768 #Martinique
   #Maroc
   724 #Qujda
   726 #Er Rachidia
   725 #Ouarzazate
   721 #Fes
   717 #Rabat
   718 #Casablanca
   722 #Marrakesh
   723 #Khenifra
   720 #Agadir
   719 #Tiznit
   #Algerien
   738 #Tamanrasset
   737 #Touggourt
   739 #Colom Bechar
   743 #Tebessa
   734 #Constantine
   735 #Bona
   731 #Batna
   732 #Djelfa
   736 #Bougie
   733 #Geryville
   727 #Algiers
   730 #Orleansville
   728 #Oran
   729 #Tlemcen
   #Tunesien
   741 #Tataouine
   744 #Gabes
   740 #Kasserine
   742 #Medenine
   745 #Sousse
   746 #El Kef
   747 #Tunis
   748 #Bizerte
   749 #Beja
   # Libanon/Syrien
   1019 #Beirut
   1020 #Golan
   1016 #Damascus
   1018 #Trablos
   1017 #Hims
   1021 #Aleppo
   1014 #Deir ez Zor	
   1015 #El Qmisli
   1054 #Hatay
   # Indochina
   1392 #Hai Phong
   1393 #Hoa Binh
   1395 #Hanoi
   1404 #Muang Xay
   1391 #Muang Xaignabouli
   1405 #Viang-chan
   1396 #Dong Hoi
   1394 #Pakxe
   1397 #Da Nang
   1399 #Saigon
   1398 #Lumphat
   1401 #Siem Reap
   1402 #Battambang
   1400 #Phnom Penh
   1403 #Can Tho
   #Afrika   
   833 #Djibouti	
   981 #Nawaksut
   982 #Kiffa
   943 #Zinder
   944 #Niamey
   942 #Say
   984 #Gao
   985 #Timbuktu 
   974 #Mopti
   978 #Dakar
   980 #Ziguinchor
   966 #Conakry
   965 #Labe
   975 #Kayes
   971 #Nioro du Sahel
   972 #Segou
   973 #Sikasso
   976 #Bamako
   959 #Bobo-Dioulasso
   957 #Ouagadougou
   949 #Natitingou
   951 #Cotonou
   967 #Kankan
   960 #Yamoussoukro
   962 #Abidjan
   910 #Bertoua
   922 #Faya
   920 #Fort Lamy
   924 #Moundou
   925 #Maroua
   923 #Bambari
   926 #Bangui
   909 #Yaounde
   928 #N'Gaoundere
   911 #Douala
   914 #Franceville
   915 #Libreville
   907 #Brazzaville
   908 #Quesso
   #Madagaskar
   1001 #Tananarive
   1002 #Tamatave
   1003 #Fort Dauphin
   # 
   996 #Saint Denis de la Reunion    
   1586 #Nouvelle-Caledonie
   1585 #Ouvea
   1584 #Tanna
   1583 #Malekula
   1582 #Espiritu Santo
   1581 #Efate
   #
   950 #Lome
   948 #Kara
   917 #Pointe-Noire
   918 #Fort Gentil
   919 #Bouar
   927 #Ouadda
   921 #Abech
   946 #Agadez
   947 #Tahoua
   945 #Tenkodogo
   958 #Tougan
   961 #Bouake
   968 #Korhogo
   970 #San Pedro
   977 #Tambacounda
   983 #Saint-Louis
   986 #Atar
   999 #Muruni
   1000 #Mamoudzou
   1740 #Rikitea
   1743 #Papeete
   1744 #Taiohae
   1730 #Mata'utu
   1752 #St-Martin
   2135 #Saint-Pierre
   } 
   
 ##################### 
 # technologie datas # 
 #####################    
 
 deactivate = { }
 blueprints = { 3710 3810 3130 3140 2900 } # 1939 submarine, 1938 Escorts & DD => units already in OOB; TP 1936 + heavy tanks 1937
 
 techapps = { 
 4010 4020 4030 4040 # Single Engined 1929, Int, Fighter, CAS 1930
 4050 # Single Engined 1936

 4290 4300 4310 4320 # double Engined 1929, tactical, naval, Escort brigade 1930
4330 4370 # Double Engined 1936, Transport 1937

 4570 # CAG 1930

 9010 9020 9030 # Aerial warfare, basic doctrines


 2800 2810 # Basic Armoured Car

 2630 2550 2560 2010 # Tanks

 2290 2300 # GW artillery
 
 17000 # 1936 rocket artillery/mortars

 2450 2460 # Early Static AA

 2510 # Basic AA

 1010 1020 # Early infantry 36'

 1190 1200 # Early cavalry 36'

 1110 # Early Mountain
 2400 # AT
 1310 # Engineers
 10110 # 1937 motorized Inf
 11750 # 1937 mech inf

 5010 # Agriculture
 5050 #Basic Machine Tools
 5080 5090 # Construction
 5190 5200 # Imp. oil conversion
 5310 5320 # Basic CT machine
 5470 5480 # Nukes labs

 6100 6110 6120 # Trench Warfare doctrine (land)

 #Naval doctrines
 8010 8070 8130 8180 8240 8370 8610 8660 8760

 #Naval Techs
# Escorts up to pre-WW2
3010	3040	3070	3100
3020	3050	3080	3110
3030 15250	3060	3090	3120
 
 #3070 # Escort 1939
 3350 3390 3430 3480 3510 15100 # Capital Design up to 1935
 3360 3440 3490	3520 # CA up to 1930
 3370 # AC (BC 0)
 3380 3410 3420	3470 3500 3530 3550 # BB up to 1936
 15090 16030 3190 3200 3210 # Prewar Carrier, CV + CVE 1930
 3700 15080 3760 # Prewar SS, SS 1930 & SS 1936
 3800 # Prewar TP
} 

 #############################
 # army datas by Lord Rommel # 
 #############################
 
landunit = {
	id = { type = 13500 id = 600 }
	name = "Région militaire de Paris"
	location = 55
	    division = { id = { type = 13500 id = 1 }   name = "Grand Quartier Général" type = hq model = 0 strength = 100 experience = 20 }
		division = { id = { type = 13500 id = 2 }   name = "2ème Division Légère Mécanique" type = mechanized model = 0 strength = 75 }
		division = { id = { type = 13500 id = 3 }   name = "1ère Division de Cavalerie" type = cavalry model = 0 strength = 75 }
		division = { id = { type = 13500 id = 4 }   name = "3ème Division de Cavalerie" type = cavalry model = 0 strength = 75 }
		division = { id = { type = 13500 id = 5 }   name = "10ème Division d'Infanterie" type = infantry model = 0 strength = 25 }
		division = { id = { type = 13500 id = 6 }   name = "41ème Division d'Infanterie" type = infantry model = 0 strength = 25 }
		division = { id = { type = 13500 id = 7 }   name = "71ème Division d'Infanterie" type = infantry model = 0 strength = 25 }
	}

landunit = {
	id = { type = 13500 id = 601 }
	name = "Région militaire de Lille"
	location = 52 #Lille
		division = { id = { type = 13500 id = 8 }   name = "1ère Div. d'Infanterie Motorisée" type = motorized model = 0 strength = 75 extra = armored_car }
		division = { id = { type = 13500 id = 9 }   name = "2ème Division d'Infanterie" type = infantry model = 0 strength = 25 }
		division = { id = { type = 13500 id = 10 }  name = "51ème Division d'Infanterie" type = infantry model = 0 strength = 25 }
	}

landunit = {
	id = { type = 13500 id = 602 }
	name = "Région militaire de Amiens"
	location = 50 #Amiens
		division = { id = { type = 13500 id = 11 } name = "3ème Div. d'Infanterie Motorisée" type = motorized model = 0 strength = 75 extra = armored_car }
		division = { id = { type = 13500 id = 12 } name = "4ème Division d'Infanterie" type = infantry model = 0 strength = 25 }
		division = { id = { type = 13500 id = 13 } name = "52ème Division d'Infanterie" type = infantry model = 0 strength = 25 }
	}

landunit = {
	id = { type = 13500 id = 603 }
	name = "Région militaire du Havre"
	location = 45 #Le Havre
		division = { id = { type = 13500 id = 14 } name = "6ème Division d'Infanterie" type = infantry model = 0 strength = 25 }
		division = { id = { type = 13500 id = 15 } name = "53ème Division d'Infanterie" type = infantry model = 0 strength = 25 }
	}

landunit = {
	id = { type = 13500 id = 606 }
	name = "Région militaire de Caen"
	location = 44 #Caen
		division = { id = { type = 13500 id = 16 } name = "5ème Div. d'Infanterie Motorisée" type = motorized model = 0 strength = 75 extra = armored_car }	
    }	
	
landunit = {
	id = { type = 13500 id = 607 }
	name = "Région militaire de Reims"
	location = 99 #Reims
		division = { id = { type = 13500 id = 17 } name = "1ère Division Légère Mécanique" type = mechanized model = 0 strength = 75 }
		division = { id = { type = 13500 id = 18 } name = "12ème Div. d'Infanterie Motorisée" type = motorized model = 0 strength = 75 extra = armored_car }
		division = { id = { type = 13500 id = 19 } name = "24ème Division d'Infanterie" type = infantry model = 0 strength = 25  }
		division = { id = { type = 13500 id = 20 } name = "62ème Division d'Infanterie" type = infantry model = 0 strength = 25  }
	}

landunit = {
	id = { type = 13500 id = 608 }
	name = "Région militaire de Metz"
	location = 104 #Metz
		division = { id = { type = 13500 id = 21 } name = "2ème Div. d'Infanterie Nord-Africaine" type = infantry model = 0 strength = 75  }
		division = { id = { type = 13500 id = 22 } name = "42ème Division d'Infanterie" type = infantry model = 0 strength = 25  }
		division = { id = { type = 13500 id = 23 } name = "55ème Division d'Infanterie" type = infantry model = 0 strength = 25  }
	}
	
landunit = {
	id = { type = 13500 id = 609 }
	name = "Région militaire de Strasbourg"
	location = 107 #Strasbourg
		division = { id = { type = 13500 id = 24 } name = "43ème Division d'Infanterie" type = infantry model = 0 strength = 25  }
		division = { id = { type = 13500 id = 25 } name = "60ème Division d'Infanterie" type = infantry model = 0 strength = 25  }
	}	
	
landunit = {
	id = { type = 13500 id = 610 }
	name = "Région militaire de Nancy"
	location = 106 #Nancy
		division = { id = { type = 13500 id = 26 } name = "2ème Division de Cavalerie" type = cavalry model = 0 strength = 75 }
	    division = { id = { type = 13500 id = 27 } name = "4ème Div. d'Infanterie Nord-Africaine" type = infantry model = 0 strength = 75  }
		division = { id = { type = 13500 id = 28 } name = "11ème Division d'Infanterie" type = infantry model = 0 strength = 25 }
		division = { id = { type = 13500 id = 29 } name = "70ème Division d'Infanterie" type = infantry model = 0 strength = 25  }
	}		
	
landunit = {
	id = { type = 13500 id = 611 }
	name = "Région militaire de Belfort"
	location = 97 #Belfort
		division = { id = { type = 13500 id = 30 } name = "13ème Division d'Infanterie" type = infantry model = 0 strength = 25  }
		division = { id = { type = 13500 id = 31 } name = "14ème Division d'Infanterie" type = infantry model = 0 strength = 25  }
		division = { id = { type = 13500 id = 32 } name = "47ème Division d'Infanterie" type = infantry model = 0 strength = 25  }
		division = { id = { type = 13500 id = 33 } name = "57ème Division d'Infanterie" type = infantry model = 0 strength = 25  }
	}	
	
landunit = {
	id = { type = 13500 id = 612 }
	name = "Région militaire de Verdun"
	location = 100 #Verdun
		division = { id = { type = 13500 id = 34 } name = "8ème Division d'Infanterie" type = infantry model = 0 strength = 75 }
		division = { id = { type = 13500 id = 35 } name = "76ème Division d'Infanterie" type = infantry model = 0 strength = 25 }
		division = { id = { type = 13500 id = 36 } name = "77ème Division d'Infanterie" type = infantry model = 0 strength = 25 }
		division = { id = { type = 13500 id = 37 } name = "128ème Division d'Infanterie" type = infantry model = 0 strength = 25 }
	}	

landunit = {
	id = { type = 13500 id = 613 }
	name = "Région militaire d'Orléans"
	location = 66 #Orleans
        division = { id = { type = 13500 id = 38 } name = "1ère Division légère" type = cavalry model = 1 strength = 75 extra = light_armor_brigade }
		division = { id = { type = 13500 id = 39 } name = "9ème Div. d'Infanterie Motorisée" type = motorized model = 0 strength = 25 extra = armored_car }
		division = { id = { type = 13500 id = 40 } name = "45ème Division d'Infanterie" type = infantry model = 0 strength = 25  }
	}		

landunit = {
	id = { type = 13500 id = 614 }
	name = "Région militaire du Mans"
	location = 58 #Le Mans
		division = { id = { type = 13500 id = 41 } name = "7ème Division d'Infanterie" type = infantry model = 0 strength = 25 }
		division = { id = { type = 13500 id = 42 } name = "19ème Division d'Infanterie" type = infantry model = 0 strength = 25 }
		division = { id = { type = 13500 id = 43 } name = "20ème Division d'Infanterie" type = infantry model = 0 strength = 25 }
		division = { id = { type = 13500 id = 44 } name = "54ème Division d'Infanterie" type = infantry model = 0 strength = 25 }
	}	

landunit = {
	id = { type = 13500 id = 615 }
	name = "Région militaire de Nantes"
	location = 57 #Nantes
		division = { id = { type = 13500 id = 45 } name = "21ème Division d'Infanterie" type = infantry model = 0 strength = 25 }
		division = { id = { type = 13500 id = 46 } name = "22ème Division d'Infanterie" type = infantry model = 0 strength = 25 }
		division = { id = { type = 13500 id = 47 } name = "61ème Division d'Infanterie" type = infantry model = 0 strength = 25 }
	}		

landunit = {
	id = { type = 13500 id = 616 }
	name = "Région militaire de Tours"
	location = 61 #Tours
	    division = { id = { type = 13500 id = 48 } name = "3ème Div. d'Infanterie Nord-Africaine" type = infantry model = 0 strength = 75  }
		division = { id = { type = 13500 id = 49 } name = "23ème Division d'Infanterie" type = infantry model = 0 strength = 25 }
		division = { id = { type = 13500 id = 50 } name = "18ème Division d'Infanterie" type = infantry model = 0 strength = 25 }
	}		
	
landunit = {
	id = { type = 13500 id = 617 }
	name = "École de cavalerie de Saumur"
	location = 61 #Tours
        division = { id = { type = 13500 id = 51 } name = "3ème Division légère" type = cavalry model = 1 strength = 75 extra = light_armor_brigade }
	    division = { id = { type = 13500 id = 52 } name = "5ème Division de Cavalerie" type = cavalry model = 0 strength = 75 }
	    division = { id = { type = 13500 id = 53 } name = "17ème Div. d'Infanterie Motorisée" type = motorized model = 0 strength = 25 extra = armored_car }
	}	
	
landunit = {
	id = { type = 13500 id = 618 }
	name = "Région militaire de Bordeaux"
	location = 68 #Bordeaux
		division = { id = { type = 13500 id = 54 } name = "1ère Division d'Infanterie Colonial" type = d_02 model = 0 strength = 75 }
		division = { id = { type = 13500 id = 55 } name = "35ème Division d'Infanterie" type = infantry model = 0 strength = 25 }
		division = { id = { type = 13500 id = 56 } name = "36ème Division d'Infanterie" type = infantry model = 0 strength = 25 }
	}	
	
landunit = {
	id = { type = 13500 id = 619 }
	name = "Région militaire de Toulouse"
	location = 77 #Toulouse
		#division = { id = { type = 13500 id = 57 } name = "4ème Division d'Infanterie Colonial" type = d_02 model = 0 strength = 75 }
		division = { id = { type = 13500 id = 58 } name = "67ème Division d'Infanterie" type = infantry model = 0 strength = 25 }	
	}
	
landunit = {
	id = { type = 13500 id = 620 }
	name = "Région militaire de Clermont-Ferrand"
	location = 71 #Clermont-Ferrand
		division = { id = { type = 13500 id = 59 } name = "25ème Div. d'Infanterie Motorisée" type = motorized model = 0 strength = 25 extra = armored_car }
		division = { id = { type = 13500 id = 60 } name = "26ème Division d'Infanterie" type = infantry model = 0 strength = 25 }
		division = { id = { type = 13500 id = 61 } name = "63ème Division d'Infanterie" type = infantry model = 0 strength = 25 }
	}	

landunit = {
	id = { type = 13500 id = 621 }
	name = "Région militaire de Montpellier"
	location = 82 #Montpellier
		division = { id = { type = 13500 id = 62 } name = "31ème Division d'Infanterie alpine" type = bergsjaeger model = 0 strength = 25 }
		division = { id = { type = 13500 id = 63 } name = "32ème Division d'Infanterie" type = infantry model = 0 strength = 25 }
		division = { id = { type = 13500 id = 64 } name = "66ème Division d'Infanterie" type = infantry model = 0 strength = 25 }
	}
	
landunit = {
	id = { type = 13500 id = 622 }
	name = "Région militaire de Marseille"
	location = 89 #Marseille
		division = { id = { type = 13500 id = 65 } name = "29ème Division d'Infanterie alpine" type = bergsjaeger model = 0 strength = 25 }
		division = { id = { type = 13500 id = 66 } name = "30ème Division d'Infanterie alpine" type = bergsjaeger model = 0 strength = 25 }
		division = { id = { type = 13500 id = 67 } name = "2ème Division d'Infanterie Colonial" type = d_02 model = 0 strength = 75 }
		division = { id = { type = 13500 id = 68 } name = "65ème Division d'Infanterie" type = infantry model = 0 strength = 25 }
	}	
	
landunit = {
	id = { type = 13500 id = 623 }
	name = "Région militaire de Grenoble"
	location = 90 #Grenoble
		division = { id = { type = 13500 id = 69 } name = "27ème Division d'Infanterie alpine" type = bergsjaeger model = 0 strength = 25 }
	}	

landunit = {
	id = { type = 13500 id = 624 }
	name = "Région militaire de Charmbery"
	location = 91 #Chambery
		division = { id = { type = 13500 id = 70 } name = "28ème Division d'Infanterie alpine" type = bergsjaeger model = 0 strength = 25 }
	}
	
landunit = {
	id = { type = 13500 id = 625 }
	name = "Région militaire de Lyon"
	location = 85 #Lyon
	    division = { id = { type = 13500 id = 71 } name = "6ème Division légère" type = cavalry model = 1 strength = 75 extra = light_armor_brigade }
	    division = { id = { type = 13500 id = 72 } name = "1ère Div. d'Infanterie Nord-Africaine" type = infantry model = 0 strength = 75  }
	    division = { id = { type = 13500 id = 73 } name = "64ème Division d'Infanterie alpine" type = bergsjaeger model = 0 strength = 25 }
	}	
	
landunit = {
	id = { type = 13500 id = 626 }
	name = "Région militaire de Dijon"
	location = 64 #Dijon
		division = { id = { type = 13500 id = 74 } name = "15ème Div. d'Infanterie Motorisée" type = motorized model = 0 strength = 25 extra = armored_car }
		division = { id = { type = 13500 id = 75 } name = "16ème Division d'Infanterie" type = infantry model = 0 strength = 25 }
		division = { id = { type = 13500 id = 76 } name = "58ème Division d'Infanterie" type = infantry model = 0 strength = 25 }
	}		
	
landunit = {
	id = { type = 13500 id = 627 }
	name = "Forteresse militaire de Maroc"
	location = 717 #Rabat
		division = { id = { type = 13500 id = 77 } name = "Division de Meknès" type = d_02 model = 0 strength = 85 }
	}

landunit = {
	id = { type = 13500 id = 628 }
	name = "Forteresse militaire d'Oran"
	location = 728 #Oran
		division = { id = { type = 13500 id = 78 } name = "Division d'Oran" type = d_02 model = 0 strength = 85 }
	}	
	
landunit = {
	id = { type = 13500 id = 629 }
	name = "Forteresse militaire d'Alger"
	location = 727 #Algiers
		division = { id = { type = 13500 id = 79 } name = "Division d'Alger" type = d_02 model = 0 strength = 85 }
	}	
	
landunit = {
	id = { type = 13500 id = 630 }
	name = "Forteresse militaire de Constantine"
	location = 734 #Constantine
		division = { id = { type = 13500 id = 80 } name = "Division de Constantine" type = d_02 model = 0 strength = 85 }
	}		
	
landunit = {
	id = { type = 13500 id = 631 }
	name = "Région militaire de Sénégal"
	location = 978 #Dakar
		division = { id = { type = 13500 id = 81 } name = "1ère Division Sénégalaise" type = d_02 model = 0 strength = 85 }
	}		
	
landunit = {
	id = { type = 13500 id = 632 }
	name = "Ière Corps d'Infanterie Colonial"
	location = 747 #Tunis
	    division = { id = { type = 13500 id = 89 }   name = "Quartier Général d'Afrique" type = hq model = 0 strength = 100 experience = 20 }
		division = { id = { type = 13500 id = 82 } name = "3ème Division d'Infanterie Colonial" type = d_02 model = 0 strength = 80 }
        division = { id = { type = 13500 id = 83 } name = "4ème Division d'Infanterie Colonial" type = d_02 model = 0 strength = 80 }
        division = { id = { type = 13500 id = 84 } name = "5ème Division d'Infanterie Colonial" type = d_02 model = 0 strength = 80 }
	}	
	
landunit = {
	id = { type = 13500 id = 633 }
	name = "Division légère d'Infanterie Colonial"
	location = 747 #Tunis
	    division = { id = { type = 13500 id = 85 } name = "8ème Div. légère d'Inf. Colonial" type = d_02 model = 0 strength = 85 extra = light_armor_brigade }
	}		
	
landunit = {
	id = { type = 13500 id = 634 }
	name = "IIère Corps d'Infanterie Colonial"
	location = 727 #Algiers
		division = { id = { type = 13500 id = 86 } name = "7ème Division d'Infanterie Colonial" type = d_02 model = 0 strength = 80 }
        division = { id = { type = 13500 id = 87 } name = "8ème Division d'Infanterie Colonial" type = d_02 model = 0 strength = 80 }
        division = { id = { type = 13500 id = 88 } name = "10ème Division d'Infanterie Colonial" type = d_02 model = 0 strength = 80 }
	}
	
landunit = {
	id = { type = 13500 id = 806 }
	name = "Région militaire du Levant"
	location = 1019 #Beirut
		division = { id = { type = 13500 id = 807 } name = "Groupe des forces mobiles du Levant" type = d_02 model = 0 strength = 25 }
	}	

landunit = {
	id = { type = 13500 id = 808 }
	name = "Région militaire d'Afrique-Équatoriale"
	location = 915 #Libreville
		division = { id = { type = 13500 id = 809 } name = "Tirailleurs sénégalais" type = d_02 model = 0 strength = 25 }
	}	
	
landunit = {
	id = { type = 13500 id = 800 }
	name = "L'armée de Madagascar"
	location = 1003
	    division = { id = { type = 13500 id = 801 } name = "Régiment Malgaches" type = militia model = 0 strength = 45 }
	}	

#Indochina	
	
landunit = {
	id = { type = 13500 id = 802 }
	name = "1ère Corps Indochine"
	location = 1395 #Hanoi
	    division = { id = { type = 13500 id = 803 } name = "Division du Tonkin" type = d_02 model = 0 strength = 45 }
	}	
	
landunit = {
	id = { type = 13500 id = 804 }
	name = "2ème Corps Indochine"
	location = 1399 #Saigon
	    division = { id = { type = 13500 id = 805 } name = "Div. de Cochinchine-Cambodge" type = d_02 model = 0 strength = 35 }
	}	
	
	
#######################################
# french navy
#######################################	

navalunit = {
	id = { type = 13500 id = 98 }
	name = "1ère Flotte de la France"
	location = 37 #Brest
	base = 37
		division = { id = { type = 13500 id = 99 } name = "Béarn" type = carrier model = 0 extra = cag brigade_model = 0 experience = 15 }
   		division = { id = { type = 13500 id = 400 } name = "Algérie" type = heavy_cruiser model = 5 experience = 15 }
		division = { id = { type = 13500 id = 126 } name = "Primauguet" type = light_cruiser model = 3 experience = 15  }
		division = { id = { type = 13500 id = 127 } name = "Duguay-Trouin" type = light_cruiser model = 3 experience = 15  }
		division = { id = { type = 13500 id = 129 } name = "Lamotte-Picquet" type = light_cruiser model = 3 experience = 15  }
		division = { id = { type = 13500 id = 131 } name = "La Galissonnière" type = light_cruiser model = 4 experience = 15  }
		division = { id = { type = 13500 id = 243 } name = "Bourrasque" type = destroyer model = 2 experience = 15 }
		division = { id = { type = 13500 id = 244 } name = "Cyclone" type = destroyer model = 2 experience = 15 }
		division = { id = { type = 13500 id = 245 } name = "Mistral" type = destroyer model = 2 experience = 15 }
		division = { id = { type = 13500 id = 471 } name = "Aigle" type = d_09 model = 3 experience = 15 }
		division = { id = { type = 13500 id = 472 } name = "Albatros" type = d_09 model = 3 experience = 15 }
		division = { id = { type = 13500 id = 473 } name = "Epervier" type = d_09 model = 3 experience = 15 }
	}

navalunit = {
	id = { type = 13500 id = 100 }
	name = "2ème Flotte de la France"
	location = 86 # Toulon
	base = 86
		division = { id = { type = 13500 id = 101 } name = "Courbet" type = battleship model = 1 experience = 15 }
		division = { id = { type = 13500 id = 103 } name = "Paris" type = battleship model = 1 experience = 15 }
		division = { id = { type = 13500 id = 118 } name = "Suffren" type = heavy_cruiser model = 4 experience = 15 }
		division = { id = { type = 13500 id = 116 } name = "Duquesne" type = heavy_cruiser model = 4 experience = 15 }
		division = { id = { type = 13500 id = 259 } name = "Pluton" type = light_cruiser model = 2 extra = naval_improved_hull_s experience = 15 }
		division = { id = { type = 13500 id = 133 } name = "Jeanne d'Arc" type = light_cruiser model = 2 experience = 15 }
		division = { id = { type = 13500 id = 139 } name = "Orage" type = destroyer model = 2 experience = 15 }
		division = { id = { type = 13500 id = 144 } name = "Ouragan" type = destroyer model = 2 experience = 15 }
		division = { id = { type = 13500 id = 246 } name = "Simoun" type = destroyer model = 2 experience = 15 }
		division = { id = { type = 13500 id = 477 } name = "Trombe" type = destroyer model = 2 experience = 15 }
		division = { id = { type = 13500 id = 478 } name = "Typhon" type = destroyer model = 2 experience = 15 }
		division = { id = { type = 13500 id = 479 } name = "Basque" type = destroyer model = 2 experience = 15 }	
		division = { id = { type = 13500 id = 448 } name = "Dauphin" type = submarine model = 1 experience = 5 }
		division = { id = { type = 13500 id = 449 } name = "Marsouin" type = submarine model = 1 experience = 5 }
		division = { id = { type = 13500 id = 450 } name = "Espadon" type = submarine model = 1 experience = 5 }
		division = { id = { type = 13500 id = 451 } name = "Morse" type = submarine model = 1 experience = 5 }
		division = { id = { type = 13500 id = 538 } name = "Le Gladiateur" type = d_09 model = 2 experience = 15 } # offensive netlayer
	}

navalunit = {
	id = { type = 13500 id = 104 }
	name = "3ème Flotte de la France"
	location = 727 #Algier
	base = 727
		division = { id = { type = 13500 id = 105 } name = "Ocean" type = battleship model = 1 strength = 30 experience = 15 } #Renamed Jean Bart 1937, bad condition 1936
		division = { id = { type = 13500 id = 109 } name = "Bretagne" type = battleship model = 2 extra = naval_anti_air_l experience = 15 }
		division = { id = { type = 13500 id = 206 } name = "Commandant Teste" type = escort_carrier model = 2 experience = 15 } # was in reconstruction at that time, but TRP doesn't offer these brigades for CVEs
		division = { id = { type = 13500 id = 120 } name = "Foch" type = heavy_cruiser model = 4 experience = 15 }
		division = { id = { type = 13500 id = 115 } name = "Tourville" type = heavy_cruiser model = 4 experience = 15 }
		division = { id = { type = 13500 id = 255 } name = "Gerfaut" type = d_09 model = 3 experience = 15 }
		division = { id = { type = 13500 id = 152 } name = "Milan" type = d_09 model = 3 experience = 15 }
		division = { id = { type = 13500 id = 157 } name = "Vautour" type = d_09 model = 3 experience = 15 }
		division = { id = { type = 13500 id = 242 } name = "Chacal" type = d_09 model = 3 experience = 15 }
		division = { id = { type = 13500 id = 468 } name = "Jaguar" type = d_09 model = 3 experience = 15 }
		division = { id = { type = 13500 id = 469 } name = "Léopard" type = d_09 model = 3 experience = 15 }
		division = { id = { type = 13500 id = 470 } name = "Lynx" type = d_09 model = 3 experience = 15 }
		division = { id = { type = 13500 id = 452 } name = "Narval" type = submarine model = 1 experience = 5 }
		division = { id = { type = 13500 id = 453 } name = "Phoque" type = submarine model = 1 experience = 5 }
		division = { id = { type = 13500 id = 454 } name = "Requin" type = submarine model = 1 experience = 5 }
		division = { id = { type = 13500 id = 455 } name = "Souffleur" type = submarine model = 1 experience = 5 }
	}

navalunit = {
	id = { type = 13500 id = 110 }
	name = "4ème Flotte de la France"
	location = 37 #Brest
	base = 37
		division = { id = { type = 13500 id = 111 } name = "Lorraine" type = battleship model = 2 experience = 15 }
		division = { id = { type = 13500 id = 113 } name = "Provence" type = battleship model = 2 extra1 = naval_anti_air_l extra2 = floatplane experience = 15 }
		division = { id = { type = 13500 id = 122 } name = "Colbert" type = heavy_cruiser model = 4 experience = 15 }
		division = { id = { type = 13500 id = 124 } name = "Dupleix" type = heavy_cruiser model = 4 experience = 15 }
		division = { id = { type = 13500 id = 137 } name = "Emile Bertin" type = light_cruiser model = 3 experience = 15 }
		division = { id = { type = 13500 id = 165 } name = "Sirocco" type =  destroyer model = 2 experience = 15 }
		division = { id = { type = 13500 id = 474 } name = "Tempete" type =  destroyer model = 2 experience = 15 }
		division = { id = { type = 13500 id = 475 } name = "Tornade" type =  destroyer model = 2 experience = 15 }
		division = { id = { type = 13500 id = 476 } name = "Tramontane" type =  destroyer model = 2 experience = 15 }				
		division = { id = { type = 13500 id = 494 } name = "Valmy" type = d_09 model = 3 experience = 15 }
		division = { id = { type = 13500 id = 495 } name = "Vauban" type = d_09 model = 3 experience = 15 }
		division = { id = { type = 13500 id = 496 } name = "Verdun" type = d_09 model = 3 experience = 15 }
		division = { id = { type = 13500 id = 456 } name = "Surcouf" type = d_08 model = 1 experience = 10 extra = floatplane }
		division = { id = { type = 13500 id = 457 } name = "Galatée" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 13500 id = 458 } name = "Naiade" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 13500 id = 459 } name = "Sirène" type = nuclear_submarine model = 1 experience = 5 }
	}

navalunit = {
	id = { type = 13500 id = 171 }
	name = "1ère Flotte de Soumarins"
	location = 86 # Toulon
	base = 86
		division = { id = { type = 13500 id = 247 } name = "Aréthuse" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 13500 id = 401 } name = "Calypso" type = nuclear_submarine model = 1 experience = 5 }
	}

navalunit = {
	id = { type = 13500 id = 181 }
	name = "2ème Flotte de Soumarins"
	location = 86 # Toulon
	base = 86
		division = { id = { type = 13500 id = 249 } name = "Argonaute" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 13500 id = 250 } name = "Atalante" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 13500 id = 251 } name = "La Sultane" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 13500 id = 182 } name = "La Vestale" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 13500 id = 187 } name = "Ariane" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 13500 id = 402 } name = "Circé" type = nuclear_submarine model = 1 experience = 5 }
	}

navalunit = {
	id = { type = 13500 id = 191 }
	name = "3ème Flotte de Soumarins"
	location = 727 #Algier
	base = 727
		division = { id = { type = 13500 id = 254 } name = "Danaé" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 13500 id = 252 } name = "Eurycide" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 13500 id = 403 } name = "Doris" type = nuclear_submarine model = 1 experience = 5 }
	}

navalunit = {
	id = { type = 13500 id = 410 }
	name = "4ème Flotte de Soumarins"
	location = 68 #Bordeaux
	base = 68
		division = { id = { type = 13500 id = 404 } name = "Thétis" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 13500 id = 405 } name = "Amazone" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 13500 id = 406 } name = "Amphitrite" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 13500 id = 407 } name = "Antiope" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 13500 id = 408 } name = "Diane" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 13500 id = 409 } name = "La Psyché" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 13500 id = 673 } name = "La Sibylle" type = nuclear_submarine model = 1 experience = 5 }
	}

navalunit = {
	id = { type = 13500 id = 486 }
	name = "1ère Flotille des Contre-Torpilleurs"
	location = 68 #Bordeaux
	base = 68
		division = { id = { type = 13500 id = 480 } name = "Bordelais" type = destroyer model = 2 experience = 15 }
		division = { id = { type = 13500 id = 481 } name = "Boulonnais" type = destroyer model = 2 experience = 15 }
		division = { id = { type = 13500 id = 482 } name = "Brestois" type = destroyer model = 2 experience = 15 }
		division = { id = { type = 13500 id = 483 } name = "Foudroyant" type = destroyer model = 2 experience = 15 }
		division = { id = { type = 13500 id = 484 } name = "Forbin" type = destroyer model = 2 experience = 15 }
		division = { id = { type = 13500 id = 485 } name = "Fougueux" type = destroyer model = 2 experience = 15 }
	}

navalunit = {
	id = { type = 13500 id = 487 }
	name = "2ème Flotille des Contre-Torpilleurs"
	location = 68 #Bordeaux
	base = 68
		division = { id = { type = 13500 id = 488 } name = "Panthere" type = d_09 model = 3 experience = 15 }
		division = { id = { type = 13500 id = 489 } name = "Tigre" type = d_09 model = 3 experience = 15 }
		division = { id = { type = 13500 id = 490 } name = "Mars" type = destroyer model = 2 experience = 15 }
		division = { id = { type = 13500 id = 491 } name = "Bison" type = d_09 model = 3 experience = 15 }
		division = { id = { type = 13500 id = 492 } name = "Guepard" type = d_09 model = 3 experience = 15 }
		division = { id = { type = 13500 id = 493 } name = "Lion" type = d_09 model = 3 experience = 15 }
	}		
		
navalunit = {
	id = { type = 13500 id = 411 }
	name = "6ème Flotte de Soumarins"
	location = 68 #Bordeaux
	base = 68
		division = { id = { type = 13500 id = 412 } name = "La Sybille" type = submarine model = 1 experience = 5 }
		division = { id = { type = 13500 id = 413 } name = "Méduse" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 13500 id = 414 } name = "Oréade" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 13500 id = 415 } name = "Orphée" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 13500 id = 416 } name = "L'Espoir" type = submarine model = 2 experience = 5 }
		division = { id = { type = 13500 id = 417 } name = "Le Centaure" type = submarine model = 2 experience = 5 }
	}

navalunit = {
	id = { type = 13500 id = 418 }
	name = "5ème Flotte de Soumarins"
	location = 718 #Casablanca
	base = 718
		division = { id = { type = 13500 id = 419 } name = "Le Glorieux" type = submarine model = 2 experience = 5 }
		division = { id = { type = 13500 id = 421 } name = "Le Héros" type = submarine model = 2 experience = 5 }
		division = { id = { type = 13500 id = 679 } name = "Phénix" type = submarine model = 2 experience = 5 }
		division = { id = { type = 13500 id = 447 } name = "Caiman" type = submarine model = 1 experience = 5 }
	}

navalunit = {
	id = { type = 13500 id = 425 }
	name = "7ème Flotte de Soumarins"
	location = 978 #Dakar
	base = 978
		division = { id = { type = 13500 id = 427 } name = "Achéron" type = submarine model = 2 experience = 5 }
		division = { id = { type = 13500 id = 428 } name = "Achille" type = submarine model = 2 experience = 5 }
		division = { id = { type = 13500 id = 446 } name = "Vengeur" type = submarine model = 2 experience = 5 }
	}

navalunit = {
	id = { type = 13500 id = 429 }
	name = "8ème Flotte de Soumarins"
	location = 1019 #Beirut
	base = 1019
		division = { id = { type = 13500 id = 430 } name = "Actéon" type = submarine model = 2 experience = 5 }
		division = { id = { type = 13500 id = 431 } name = "Ajax" type = submarine model = 2 experience = 5 }
		division = { id = { type = 13500 id = 432 } name = "Archimede" type = submarine model = 2 experience = 5 }
		division = { id = { type = 13500 id = 445 } name = "Redoutable" type = submarine model = 2 experience = 5 }
	}

navalunit = {
	id = { type = 13500 id = 433 }
	name = "9ème Flotte de Soumarins"
	location = 833 #Djibuti
	base = 833
		division = { id = { type = 13500 id = 434 } name = "Argo" type = submarine model = 2 experience = 5 }
		division = { id = { type = 13500 id = 435 } name = "Fresnel" type = submarine model = 2 experience = 5 }
		division = { id = { type = 13500 id = 436 } name = "Henri Poincaré" type = submarine model = 2 experience = 5 }
		division = { id = { type = 13500 id = 444 } name = "Protée" type = submarine model = 2 experience = 5 }
	}

navalunit = {
	id = { type = 13500 id = 437 }
	name = "10ème Flotte de Soumarins"
	location = 68 #Bordeaux
	base = 68
		division = { id = { type = 13500 id = 438 } name = "Monge" type = submarine model = 2 experience = 5 }
		division = { id = { type = 13500 id = 439 } name = "Pascal" type = submarine model = 2 experience = 5 }
		division = { id = { type = 13500 id = 440 } name = "Pasteur" type = submarine model = 2 experience = 5 }
		division = { id = { type = 13500 id = 441 } name = "Pégase" type = submarine model = 2 experience = 5 }
		division = { id = { type = 13500 id = 442 } name = "Persée" type = submarine model = 2 experience = 5 }
		division = { id = { type = 13500 id = 443 } name = "Poncelet" type = submarine model = 2 experience = 5 }
	}

navalunit = {
	id = { type = 13500 id = 460 }
	name = "11ème Flotte de Soumarins"
	location = 49 #Calais
	base = 43#Cherbourg
		division = { id = { type = 13500 id = 461 } name = "Diamant" type = nuclear_submarine model = 2 experience = 5 }
		division = { id = { type = 13500 id = 462 } name = "Nautilus" type = nuclear_submarine model = 2 experience = 5 }
		division = { id = { type = 13500 id = 463 } name = "Perlé" type = submarine model = 1 experience = 5 }
		division = { id = { type = 13500 id = 674 } name = "Nymphe" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 13500 id = 675 } name = "Ondine" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 13500 id = 676 } name = "Orion" type = nuclear_submarine model = 1 experience = 5 }
	}
	
navalunit = {
	id = { type = 13500 id = 510 }
	name = "4ème Flotille des Contre-Torpilleurs"
	location = 727 #Algeri
	base = 727
		division = { id = { type = 13500 id = 511 } name = "Cassard" type = d_09 model = 3 experience = 15 }
		division = { id = { type = 13500 id = 512 } name = "Chevalier Paul" type = d_09 model = 3 experience = 15 }
		division = { id = { type = 13500 id = 513 } name = "Kersaint" type = d_09 model = 3 experience = 15 }
		division = { id = { type = 13500 id = 514 } name = "Maillé Brézé" type = d_09 model = 3 experience = 15 }
		division = { id = { type = 13500 id = 515 } name = "Tartu" type = d_09 model = 3 experience = 15 }
		division = { id = { type = 13500 id = 516 } name = "Vauquelin" type = d_09 model = 3 experience = 15 }
	}

navalunit = {
	id = { type = 13500 id = 517 }
	name = "5ème Flotille des Contre-Torpilleurs"
	location = 978 #Dakar
	base = 978
		division = { id = { type = 13500 id = 518 } name = "Frondeur" type = destroyer model = 2 experience = 15 }
		division = { id = { type = 13500 id = 519 } name = "Adroit" type = destroyer model = 2 experience = 15 }
		division = { id = { type = 13500 id = 520 } name = "Alcyon" type = destroyer model = 2 experience = 15 }
	}

navalunit = {
	id = { type = 13500 id = 521 }
	name = "6ème Flotille des Contre-Torpilleurs"
	location = 1019 #Beirut
	base = 1019
		division = { id = { type = 13500 id = 522 } name = "Palme" type = destroyer model = 2 experience = 15 }
		division = { id = { type = 13500 id = 523 } name = "Railleuse" type = destroyer model = 2 experience = 15 }
		division = { id = { type = 13500 id = 524 } name = "Fortuné" type = destroyer model = 2 experience = 15 }
	}

navalunit = {
	id = { type = 13500 id = 464 }
	name = "12ème Flotte de Soumarins"
	location = 49#Calais
	base = 43#Cherbourg
		division = { id = { type = 13500 id = 465 } name = "Rubis" type = nuclear_submarine model = 2 experience = 5 }
		division = { id = { type = 13500 id = 466 } name = "Saphir" type = nuclear_submarine model = 2 experience = 5 }
		division = { id = { type = 13500 id = 467 } name = "Turquoise" type = nuclear_submarine model = 2 experience = 5 }
	}

navalunit = {
	id = { type = 13500 id = 198 }
	location = 1399 #Saigon
	base = 1399
	name = "Transport Expéditionnaire"
		division = { id = { type = 13500 id = 199 } name = "Marie José" type = transport model = 0 }
		division = { id = { type = 13500 id = 200 } name = "Mont Viso" type = transport model = 0 }
		division = { id = { type = 13500 id = 201 } name = "Saint Louis" type = transport model = 0 }
	}

navalunit = {
	id = { type = 13500 id = 202 }
	location = 89 #Marseille
	base = 89
	name = "Transport Génerale"
		division = { id = { type = 13500 id = 203 } name = "Sidi-Bel-Abbès" type = transport model = 0 }
		division = { id = { type = 13500 id = 204 } name = "Baoulé" type = transport model = 0 }
		division = { id = { type = 13500 id = 205 } name = "Capitaine Edmond Laborie" type = transport model = 0 }
		division = { id = { type = 13500 id = 500 } name = "Rouennais" type = transport model = 0 }
	}
	
navalunit = {
	id = { type = 13500 id = 207 }
	name = "7ème Flotille des Contre-Torpilleurs"
	location = 1399 #Saigon
	base = 1399
		division = { id = { type = 13500 id = 208 } name = "Bougainville" type = d_09 model = 2 experience = 15 } # large Avisos/Sloops
		division = { id = { type = 13500 id = 209 } name = "Amiral Charner" type = d_09 model = 2 experience = 15 }
		division = { id = { type = 13500 id = 210 } name = "Dumont d'Urville" type = d_09 model = 2 experience = 15 }
		division = { id = { type = 13500 id = 211 } name = "D'Entracasteaux" type = d_09 model = 2 experience = 15 }
		division = { id = { type = 13500 id = 212 } name = "Rigault de Genouilly" type = d_09 model = 2 experience = 15 }
		division = { id = { type = 13500 id = 213 } name = "D'Iberville" type = d_09 model = 2 experience = 15 }
		division = { id = { type = 13500 id = 214 } name = "Savorgnan de Brazza" type = d_09 model = 2 experience = 15 }
	}
	
navalunit = {
	id = { type = 13500 id = 526 }
	name = "1ère Flotille de la Réserve"
	location = 39 #Lorient
	base = 37 # Brest
		division = { id = { type = 13500 id = 539 } name = "Waldeck-Rousseau" type = battlecruiser model = 0 strength = 20 experience = 15 } # out of service June 14, 1936
		division = { id = { type = 13500 id = 527 } name = "Strassbourg II" type = light_cruiser model = 2 strength = 40 experience = 15 } # ex-german cruiser SMS Regensburg
		division = { id = { type = 13500 id = 528 } name = "Algérien" type = destroyer model = 1 strength = 20 experience = 15 } # out of service in 1936
		division = { id = { type = 13500 id = 529 } name = "Arabe" type = destroyer model = 1 strength = 20 experience = 15 } # out of service in 1936
		division = { id = { type = 13500 id = 530 } name = "Hova" type = destroyer model = 1 strength = 20 experience = 15 } # out of service in 1936
		division = { id = { type = 13500 id = 531 } name = "Kabyle" type = destroyer model = 1 strength = 20 experience = 15 } # out of service in 1936
		division = { id = { type = 13500 id = 532 } name = "Sakalave" type = destroyer model = 1 strength = 20 experience = 15 } # out of service in 1936
		division = { id = { type = 13500 id = 533 } name = "Sénégalais" type = destroyer model = 1 strength = 20 experience = 15 } # out of service in 1936
		division = { id = { type = 13500 id = 534 } name = "Tonkinois" type = destroyer model = 1 strength = 20 experience = 15 } # out of service in 1936
		division = { id = { type = 13500 id = 535 } name = "Enseigne Roux" type = destroyer model = 1 strength = 20 experience = 15 } # out of service in 1936
		division = { id = { type = 13500 id = 536 } name = "Mécanicien Principal Lestin" type = destroyer model = 1 strength = 20 experience = 15 } # out of service in 1936
		division = { id = { type = 13500 id = 537 } name = "Enseigne Gabolde" type = destroyer model = 1 strength = 60 experience = 15 } # out of service in 1938
	}
	

##############################################################################################
# Armée de l'air                                                                             #
# 1.Jan. 1936: 7 escadre de chasse, 1 escadre de chasse mixte, 6 escadre de bombardement     #
# 4 escadre colonial -> 0ne escarde was equipped with light transports                       #
# All 4 escadre colonial were disbanded in 1937 because of its old planes and the high cost  #
# of modernisation.                                                                          # 
##############################################################################################

airunit = {
	id = { type = 13500 id = 635 }
	name = "1ère Groupement de Bombardement"
	location = 99 #Reims
	base = 99
		division = { id = { type = 13500 id = 636 } name = "12ème Escadres de bombardement" strength = 40 type = tactical_bomber experience = 10 }
		division = { id = { type = 13500 id = 637 } name = "21ème Escadres de bombardement" strength = 40 type = tactical_bomber experience = 10 }
	}

airunit = {
	id = { type = 13500 id = 638 }
	name = "2ème Groupement de Bombardement"
	location = 66 #Orleans
	base = 66
		division = { id = { type = 13500 id = 639 } name = "15ème Escadres de bombardement" strength = 40 type = tactical_bomber experience = 10 }
		division = { id = { type = 13500 id = 640 } name = "22ème Escadres de bombardement" strength = 40 type = tactical_bomber experience = 10 }
	}

airunit = {
	id = { type = 13500 id = 641 }
	name = "3ème Groupement de Bombardement"
	location = 104 #Metz
	base = 104
		division = { id = { type = 13500 id = 642 } name = "11ème Escadres de bombardement" strength = 40 type = tactical_bomber experience = 10 }
	}
	
airunit = {
	id = { type = 13500 id = 643 }
	name = "Groupement de Bombardement d'Africa"
	location = 747 #Tunis
	base = 747
		division = { id = { type = 13500 id = 644 } name = "25ème Escadres de bombardement" strength = 25 type = tactical_bomber experience = 10 }		
	}

airunit = {
	id = { type = 13500 id = 645 }
	name = "1ère Groupement de Chasse"
    location = 55 #Paris
	base = 55
		division = { id = { type = 13500 id = 646 } name = "1ère Escadres de chasse" strength = 50 type = interceptor model = 0 experience = 10 }
	}

airunit = {
	id = { type = 13500 id = 647 }
	name = "2ème Groupement de Chasse"
    location = 61 #Tours
	base = 61
		division = { id = { type = 13500 id = 648 } name = "2ème Escadres de chasse" strength = 50 type = interceptor model = 0 experience = 10 }
	}	
	
airunit = {
	id = { type = 13500 id = 649 }
	name = "3ème Groupement de Chasse"
    location = 97 #Belfort/Dijon
	base = 97
		division = { id = { type = 13500 id = 650 } name = "3ème Escadres de chasse" strength = 50 type = interceptor model = 0 experience = 10 }
	    division = { id = { type = 13500 id = 651 } name = "7ème Escadres de chasse" strength = 50 type = interceptor model = 0 experience = 10 }
	}	
	
airunit = {
	id = { type = 13500 id = 652 }
	name = "4ème Groupement de Chasse"
    location = 99 #Reims
	base = 99
	    division = { id = { type = 13500 id = 653 } name = "4ème Escadres de chasse mixte" strength = 40 type = multi_role  model = 0 experience = 10 }
	    division = { id = { type = 13500 id = 655 } name = "6ème Escadres de chasse"       strength = 50 type = interceptor model = 0 experience = 10 }
	}	

airunit = {
	id = { type = 13500 id = 656 }
	name = "5ème Groupement de Chasse"
    location = 85 #Lyon
	base = 85
		division = { id = { type = 13500 id = 657 } name = "5ème Escadres de chasse" strength = 50 type = interceptor model = 0 experience = 10 }
		division = { id = { type = 13500 id = 654 } name = "8ème Escadres de chasse" strength = 50 type = interceptor model = 1 experience = 10 }
	}	
	
airunit = {
	id = { type = 13500 id = 658 }
	name = "6ème Groupement de Chasse"
    location = 89 #Marseille
	base = 89
		division = { id = { type = 13500 id = 659 } name = "5ème Escadres de chasse" strength = 50 type = interceptor model = 0 experience = 10 }
	}	
	
airunit = {
	id = { type = 13500 id = 660 }
	name = "Groupement de Chasse d'Algerie"
    location = 727 #Algier
	base = 727
		division = { id = { type = 13500 id = 661 } name = "1ère Escadres Algerie" strength = 25 type = interceptor model = 0 experience = 10 } #max_strength = 45
	}	
	
airunit = {
	id = { type = 13500 id = 662 }
	name = "Groupement de Chasse de Maroc"
    location = 718 #Casablanca
	base = 718
		division = { id = { type = 13500 id = 663 } name = "2ème Escadres Nord Maroc" strength = 25 type = interceptor model = 0 experience = 10 } #max_strength = 45
	    division = { id = { type = 13500 id = 664 } name = "3ème Escadres Sud Maroc"  strength = 40 type = transport_plane model = 0 experience = 10 } #max_strength = 45
	}		

airunit = {
	id = { type = 13500 id = 665 }
	name = "Groupement de Chasse de Tunisie"
    location = 747 #Tunis
	base = 747
		division = { id = { type = 13500 id = 666 } name = "4ème Escadres Tunisie" strength = 25 type = interceptor model = 0 experience = 10 } #max_strength = 45
	}	

# navy's last stand (decision) #
navaldivision = { dormant = yes id = { type = 13500 id = 540 }  name = "Diderot" type = battleship model = 0 strength = 40 } #training ship; scrapped march 17, 1937
navaldivision = { dormant = yes id = { type = 13500 id = 541 }  name = "Voltaire" type = battleship model = 0 strength = 40 } #training ship; scrapped march 17, 1937
	
# elite divisions #
landdivision = { dormant = yes id = { type = 13500 id = 1501 }  name = "Légion étrangère"              type = d_03 model = 2 extra = engineer brigade_model = 1 experience = 20 }
landdivision = { dormant = yes id = { type = 13500 id = 1531 }  name = "Sections d'éclaireurs-skieurs" type = d_07 model = 1 extra = engineer brigade_model = 1 experience = 75 strength = 30 } #~3500 soldiers

# frenchs mechanized army plans #
# plan a.) #
landdivision = { dormant = yes id = { type = 13500 id = 1510 }  name = "3ème Division Légère Mécanique" type = mechanized model = 0 strength = 100 experience = 20 }
landdivision = { dormant = yes id = { type = 13500 id = 1511 }  name = "4ème Division Légère Mécanique" type = mechanized model = 0 strength = 100 experience = 20 }
landdivision = { dormant = yes id = { type = 13500 id = 1512 }  name = "5ème Division Légère Mécanique" type = mechanized model = 0 strength = 100 experience = 20 }
landdivision = { dormant = yes id = { type = 13500 id = 1513 }  name = "6ème Division Légère Mécanique" type = mechanized model = 0 strength = 100 experience = 20 }
# plan b.)
landdivision = { dormant = yes id = { type = 13500 id = 1520 }  name = "3ème Division Légère Mécanique" type = mechanized model = 0 strength = 100 experience = 15 }
landdivision = { dormant = yes id = { type = 13500 id = 1521 }  name = "4ème Division Légère Mécanique" type = mechanized model = 0 strength = 100 experience = 15 }
#
landdivision = { dormant = yes id = { type = 13500 id = 1522 }  name = "1ère Division Légère de Cavalerie" type = mechanized model = 0 strength = 100 experience = 15 }
landdivision = { dormant = yes id = { type = 13500 id = 1523 }  name = "2ème Division Légère de Cavalerie" type = mechanized model = 0 strength = 100 experience = 15 }
landdivision = { dormant = yes id = { type = 13500 id = 1524 }  name = "3ème Division Légère de Cavalerie" type = mechanized model = 0 strength = 100 experience = 15 }
landdivision = { dormant = yes id = { type = 13500 id = 1525 }  name = "4ème Division Légère de Cavalerie" type = mechanized model = 0 strength = 100 experience = 15 }
landdivision = { dormant = yes id = { type = 13500 id = 1526 }  name = "5ème Division Légère de Cavalerie" type = mechanized model = 0 strength = 100 experience = 15 }
#
landdivision = { dormant = yes id = { type = 13500 id = 1527 }  name = "1ère Division Cuirassée de Réserve" type = armor model = 1 strength = 100 extra = super_heavy_armor brigade_model = 0 experience = 15 }
landdivision = { dormant = yes id = { type = 13500 id = 1528 }  name = "2ème Division Cuirassée de Réserve" type = armor model = 1 strength = 100 extra = super_heavy_armor brigade_model = 0 experience = 15 }
landdivision = { dormant = yes id = { type = 13500 id = 1529 }  name = "3ème Division Cuirassée de Réserve" type = armor model = 1 strength = 100 extra = super_heavy_armor brigade_model = 0 experience = 15 }
landdivision = { dormant = yes id = { type = 13500 id = 1530 }  name = "4ème Division Cuirassée de Réserve" type = armor model = 1 strength = 100 extra = super_heavy_armor brigade_model = 0 experience = 15 }

# polish army in france decision # (68ooo ~ 84ooo soldiers)
landdivision = { dormant = yes id = { type = 13500 id = 1502 }  name = "1. Dywizja Grenadierów"        type = infantry  model = 1 extra = artillery brigade_model = 3 }
landdivision = { dormant = yes id = { type = 13500 id = 1504 }  name = "2. Dywizja Strzelców Pieszych" type = infantry  model = 2 extra = artillery brigade_model = 0 }
landdivision = { dormant = yes id = { type = 13500 id = 1505 }  name = "3. Dywizja Piechoty"           type = d_02      model = 2 strength = 85 }
landdivision = { dormant = yes id = { type = 13500 id = 1506 }  name = "4. Dywizja Piechoty"           type = d_02      model = 2 strength = 85 }

#airdivision  = { dormant = yes id = { type = 13500 id = 1507 } name = "1ère Escadres polonais"        type = interceptor model = 2 }

# czech army in france
landdivision = { dormant = yes id = { type = 13500 id = 1508 }  name = "1ère Division tchécoslovaque" type = d_02 model = 2 }

##################################
# Naval units under construction
##################################

brigade_development = {
        id = { type = 13500 id = 1600 }
        name = "Floatplane 1930"
		cost = 0.02
        size = 15
        type = floatplane
		model = 0
        date  = {  year = 1940 }
		unitcost = yes
		}
		
brigade_development = {
        id = { type = 13500 id = 1601 }
        name = "Capital Improved Hull 1936"
		cost = 0.04
        size = 5
        type = naval_improved_hull_l
		model = 0
        date  = {  year = 1938 }
		unitcost = yes
        }

brigade_development = {
        id = { type = 13500 id = 1602 }
        name = "Improved Hull 1936"
		cost = 0.2
        size = 15
        type = naval_improved_hull_s
		model = 0
        date  = {  year = 1940 }
		unitcost = yes
        }
		
brigade_development = {
        id = { type = 13500 id = 1603 }
        name = "Improved Hull 1936"
		cost = 0.2
        size = 15
        type = naval_improved_hull_s
		model = 0
        date  = {  year = 1940 }
		unitcost = yes
        }
		
#brigade_development = {
#        id = { type = 13500 id = 1604 }
#        cost = 0.6
#        size = 25
#        type = artillery
#		model = 1
#        date  = {  year = 1940 }
#		unitcost = yes
#        }
#		
#brigade_development = {
#        id = { type = 13500 id = 1605 }
#        cost = 0.6
#        size = 25
#        type = artillery
#		model = 1
#        date  = {  year = 1940 }
#		unitcost = yes
#        }

division_development = {
	name = "Dunkerque"
	type = battleship
	model = 5
	cost = 0.6 #6
	new_model = no unitcost = yes
	id = { type = 13500 id = 300 }
	date = { year = 1937 month = april day = 0 }
	}

division_development = {
	name = "Strasbourg"
	type = battleship
	model = 5
	cost = 0.6 #6
	new_model = no unitcost = yes
	id = { type = 13500 id = 301 }
	date = { year = 1938 month = december day = 0 }
	}

division_development = {
	name = "Richelieu"
	type = battleship
	model = 9
	cost = 0.7 #7
	new_model = no unitcost = yes
	id = { type = 13500 id = 302 }
	date = { year = 1940 month = may day = 14 }
	}

division_development = {
	name = "Georges Leygues"
	type = light_cruiser
	model = 4
	cost = 0.2 #2
	new_model = no unitcost = yes
	id = { type = 13500 id = 303 }
	date = { year = 1937 month = november day = 14 }
	}

division_development = {
	name = "Gloire"
	type = light_cruiser
	model = 4
	cost = 0.2 #2
	new_model = no unitcost = yes
	id = { type = 13500 id = 304 }
	date = { year = 1937 month = november day = 14 }
	}

division_development = {
	name = "Jean de Vienne"
	type = light_cruiser
	model = 4
	cost = 0.2 #2
	new_model = no unitcost = yes
	id = { type = 13500 id = 305 }
	date = { year = 1937 month = february day = 9 }
	}

division_development = {
	name = "Marseillaise"
	type = light_cruiser
	model = 4
	cost = 0.2 #2
	new_model = no unitcost = yes
	id = { type = 13500 id = 306 }
	date = { year = 1937 month = october day = 9 }
	}

division_development = {
	name = "Montcalm"
	type = light_cruiser
	model = 4
	cost = 0.2 #2
	new_model = no unitcost = yes
	id = { type = 13500 id = 307 }
	date = { year = 1937 month = november day = 14 }
	}
division_development = {
	name = "L'Audacieux"
	type = d_09
	model = 4
	cost = 0.06 #0.6
	new_model = no unitcost = yes
	id = { type = 13500 id = 497 }
	date = { year = 1936 month = august day = 8 }
	}
division_development = {
	name = "Le Fantasque"
	type = d_09
	model = 4
	cost = 0.06 #0.6
	new_model = no unitcost = yes
	id = { type = 13500 id = 503 }
	date = { year = 1936 month = may day = 0 }
	}
division_development = {
	name = "Le Malin"
	type = d_09
	model = 4
	cost = 0.06 #0.6
	new_model = no unitcost = yes
	id = { type = 13500 id = 504 }
	date = { year = 1936 month = june day = 8 }
	}
division_development = {
	name = "Le Terrible"
	type = d_09
	model = 4
	cost = 0.06 #0.6
	new_model = no unitcost = yes
	id = { type = 13500 id = 505 }
	date = { year = 1936 month = may day = 0 }
	}
division_development = {
	name = "Le Triomphant"
	type = d_09
	model = 4
	cost = 0.06 #0.6
	new_model = no unitcost = yes
	id = { type = 13500 id = 508 }
	date = { year = 1936 month = may day = 25 }
	}
division_development = {
	name = "L'Indomptable"
	type = d_09
	model = 4
	cost = 0.06 #0.6
	new_model = no unitcost = yes
	id = { type = 13500 id = 502 }
	date = { year = 1936 month = june day = 8 }
	}
division_development = {
	name = "Mogador"
	type = d_09
	model = 5
	cost = 0.06 #0.6
	new_model = no unitcost = yes
	id = { type = 13500 id = 509 }
	date = { year = 1939 month = april day = 8 }
	}
division_development = {
	name = "Volta"
	type = d_09
	model = 5
	cost = 0.06 #0.6
	new_model = no unitcost = yes
	id = { type = 13500 id = 525 }
	date = { year = 1939 month = march day = 3 }
	}
division_development = {
	name = "Agosta"
	type = submarine
	model = 2
	cost = 0.04 #0.4
	new_model = no unitcost = yes
	id = { type = 13500 id = 172 }
	date = { year = 1937 month = february day = 0 }
	}
division_development = {
	name = "Bévéziers"
	type = submarine
	model = 2
	cost = 0.04 #0.4
	new_model = no unitcost = yes
	id = { type = 13500 id = 672 }
	date = { year = 1937 month = june day = 4 }
	}
division_development = {
	name = "Casabianca"
	type = submarine
	model = 2
	cost = 0.04 #0.4
	new_model = no unitcost = yes
	id = { type = 13500 id = 248 }
	date = { year = 1937 month = january day = 0 }
	}
division_development = {
	name = "Iris"
	type = nuclear_submarine
	model = 3
	cost = 0.04 #0.4
	new_model = no unitcost = yes
	id = { type = 13500 id = 420 }
	date = { year = 1936 month = september day = 15 }
	}
division_development = {
	name = "Junon"
	type = nuclear_submarine
	model = 3
	cost = 0.04 #0.4
	new_model = no unitcost = yes
	id = { type = 13500 id = 423 }
	date = { year = 1937 month = september day = 20 }
	}
division_development = {
	name = "Le Conquérant"
	type = submarine
	model = 2
	cost = 0.04 #0.4
	new_model = no unitcost = yes
	id = { type = 13500 id = 424 }
	date = { year = 1936 month = september day = 7 }
	}
division_development = {
	name = "Le Tonnant"
	type = submarine
	model = 2
	cost = 0.04 #0.4
	new_model = no unitcost = yes
	id = { type = 13500 id = 422 }
	date = { year = 1937 month = june day = 0 }
	}
division_development = {
	name = "Minerve"
	type = nuclear_submarine
	model = 3
	cost = 0.04 #0.4
	new_model = no unitcost = yes
	id = { type = 13500 id = 426 }
	date = { year = 1936 month = september day = 15 }
	}
division_development = {
	name = "Ouessant"
	type = submarine
	model = 2
	cost = 0.04 #0.4
	new_model = no unitcost = yes
	id = { type = 13500 id = 677 }
	date = { year = 1939 month = january day = 0 }
	}
division_development = {
	name = "Perle"
	type = nuclear_submarine
	model = 2
	cost = 0.04 #0.4
	new_model = no unitcost = yes
	id = { type = 13500 id = 678 }
	date = { year = 1937 month = march day = 0 }
	}
division_development = {
	name = "Sfax"
	type = submarine
	model = 2
	cost = 0.04 #0.4
	new_model = no unitcost = yes
	id = { type = 13500 id = 268 }
	date = { year = 1936 month = september day = 7 }
	}
division_development = {
	name = "Sidi Ferruch"
	type = submarine
	model = 2
	cost = 0.04 #0.4
	new_model = no unitcost = yes
	id = { type = 13500 id = 680 }
	date = { year = 1939 month = january day = 0 }
	}
division_development = {
	name = "Vénus"
	type = nuclear_submarine
	model = 3
	cost = 0.04 #0.4
	new_model = no unitcost = yes
	id = { type = 13500 id = 681 }
	date = { year = 1936 month = november day = 15 }
	}
}
 