###############################################
# global IC values removed from province.csv
# adapted to Darkest Hour by Kane, 15th May 2011
###############################################

province = { id = 1 ic = 1 }#Reykyavik
province = { id = 4 ic = 1 }#Stornoway
province = { id = 5 ic = 2 }#Scapa Flow
province = { id = 6 ic = 2 }#Inverness
province = { id = 7 ic = 3 }#Aberdeen
province = { id = 10 ic = 3 }#Dumfries
province = { id = 11 ic = 8 }#Glasgow
province = { id = 12 ic = 3 }#Edinburgh
province = { id = 13 ic = 9 }#Sunderland
province = { id = 14 ic = 4 }#Carlisle
province = { id = 15 ic = 2 }#Hull
province = { id = 16 ic = 2 }#Lincoln
province = { id = 18 ic = 6 }#Sheffield
province = { id = 17 ic = 17 }#Manchester
province = { id = 22 ic = 6 }#Cardiff
province = { id = 23 ic = 1 }#Akureyri
province = { id = 24 ic = 15 }#Birmingham
province = { id = 25 ic = 7 }#Norwich
province = { id = 29 ic = 17 }#London
province = { id = 26 ic = 6 }#Dover
province = { id = 27 ic = 6 }#Portsmouth
province = { id = 19 ic = 5 }#Bristol
province = { id = 23 ic = 4 }#Plymouth
province = { id = 31 ic = 1 }#Cork
province = { id = 32 ic = 1 }#Galway
province = { id = 36 ic = 5 }#Belfast
province = { id = 35 ic = 2 }#Londonderry
province = { id = 34 ic = 2 }#Dublin
province = { id = 38 ic = 5 }#Rennes
province = { id = 40 ic = 5 }#St.Nazaire
province = { id = 44 ic = 3 }#Caen
province = { id = 45 ic = 3 }#Le Havre
province = { id = 52 ic = 8 }#Lille
province = { id = 114 ic = 2 }#Bruges
province = { id = 125 ic = 3 }#Rotterdam
province = { id = 122 ic = 5 }#Amsterdam
province = { id = 121 ic = 1 }#Maastricht
province = { id = 118 ic = 2 }#Eindhoven
province = { id = 115 ic = 2 }#Antwerpen
province = { id = 116 ic = 10 }#Brussels
province = { id = 50 ic = 3 }#Amiens
province = { id = 56 ic = 3 }#Chateau Thierry
province = { id = 55 ic = 21 }#Paris
province = { id = 66 ic = 4 }#Orleans
province = { id = 142 ic = 5 }#Duesseldorf
province = { id = 145 ic = 10 }#Essen
province = { id = 108 ic = 6 }#Liege
province = { id = 109 ic = 5 }#Luxemburg
province = { id = 96 ic = 4 }#Longwy
province = { id = 107 ic = 3 }#Strassburg
province = { id = 127 ic = 8 }#Saarbrücken
province = { id = 131 ic = 8 }#Cologne
province = { id = 144 ic = 10 }#Ruhrgebiet
province = { id = 119 ic = 3 }#Arnhem
province = { id = 124 ic = 2 }#Groningen
province = { id = 147 ic = 3 }#Wilhelmshafen
province = { id = 141 ic = 10 }#Münster
province = { id = 137 ic = 4 }#Kassel
province = { id = 140 ic = 7 }#Fulda
province = { id = 146 ic = 8 }#Hannover
province = { id = 148 ic = 2 }#Bremen
province = { id = 154 ic = 6 }#Hamburg
province = { id = 152 ic = 3 }#Kiel
province = { id = 220 ic = 2 }#Aarhus
province = { id = 2152 ic = 3 }#Malmoe
province = { id = 2155 ic = 1 }#Kalmar
province = { id = 2154 ic = 2 }#Joenkoeping
province = { id = 2153 ic = 2 }#Gothenburg
province = { id = 2157 ic = 2 }#Linkoeping
province = { id = 2159 ic = 8 }#Stockholm
province = { id = 2161 ic = 2 }#Karlstad
province = { id = 484 ic = 2 }#Frederrikstad
province = { id = 483 ic = 5 }#Oslo
province = { id = 485 ic = 1 }#Kristiansand
province = { id = 488 ic = 1 }#Bergen
province = { id = 489 ic = 2 }#Hamar
province = { id = 2162 ic = 6 }#Gaevle
province = { id = 2165 ic = 2 }#Umea
province = { id = 493 ic = 1 }#Trondheim
province = { id = 520 ic = 1 }#Oulu
province = { id = 521 ic = 1 }#Vaasa
province = { id = 524 ic = 1 }#Turku
province = { id = 525 ic = 2 }#Helsinki
province = { id = 527 ic = 2 }#Tampere
province = { id = 528 ic = 1 }#Mikkeli
province = { id = 531 ic = 1 }#Viipuri
province = { id = 522 ic = 2 }#Kuopio
province = { id = 542 ic = 2 }#Archangelsk
province = { id = 658 ic = 2 }#Penza
province = { id = 663 ic = 2 }#Stalingrad
province = { id = 681 ic = 2 }#Kostroma
province = { id = 682 ic = 2 }#Ivanovo
province = { id = 680 ic = 5 }#Gorkij
province = { id = 548 ic = 2 }#Volodga
province = { id = 569 ic = 2 }#Kalinnin
province = { id = 572 ic = 18 }#Moscow
province = { id = 677 ic = 2 }#Yaroslavl
province = { id = 678 ic = 2 }#Vladimir
province = { id = 576 ic = 2 }#Kaluga
province = { id = 553 ic = 5 }#Leningrad
province = { id = 270 ic = 1 }#Tallinn
province = { id = 271 ic = 1 }#Parnu
province = { id = 264 ic = 2 }#Riga
province = { id = 265 ic = 1 }#Valmiera
province = { id = 566 ic = 2 }#Pskov
province = { id = 266 ic = 1 }#Daugavpils
province = { id = 269 ic = 1 }#Jelgava
province = { id = 268 ic = 1 }#Liepaja
province = { id = 261 ic = 1 }#Kleipeda
province = { id = 262 ic = 1 }#Kaunas
province = { id = 258 ic = 1 }#Wilno
province = { id = 251 ic = 2 }#Nowogrodek
province = { id = 599 ic = 3 }#Minsk
province = { id = 590 ic = 2 }#Vitebsk
province = { id = 589 ic = 2 }#Smolensk
province = { id = 600 ic = 2 }#Mogilev
province = { id = 595 ic = 1 }#Mozyr
province = { id = 611 ic = 2 }#Zhitomir
province = { id = 612 ic = 5 }#Vinnitsa
province = { id = 238 ic = 1 }#Stanislawow
province = { id = 303 ic = 1 }#Balti
province = { id = 626 ic = 3 }#Odessa
province = { id = 622 ic = 2 }#Nikolayev
province = { id = 627 ic = 3 }#Krivoy Rog
province = { id = 628 ic = 2 }#Kirovograd
province = { id = 618 ic = 2 }#Cherkasy
province = { id = 617 ic = 3 }#Kiev
province = { id = 607 ic = 2 }#Chernigov
province = { id = 604 ic = 2 }#Kursk
province = { id = 606 ic = 2 }#Sumy
province = { id = 629 ic = 2 }#Poltava
province = { id = 630 ic = 2 }#Zaporozhye
province = { id = 603 ic = 2 }#Belgorod
province = { id = 636 ic = 3 }#Kharkov
province = { id = 635 ic = 8 }#Stalino
province = { id = 641 ic = 2 }#Sevastopol
province = { id = 691 ic = 3 }#Krasnodar
province = { id = 644 ic = 3 }#Rostov-on-Don
province = { id = 601 ic = 2 }#Gomel
province = { id = 588 ic = 2 }#Bryansk
province = { id = 584 ic = 2 }#Tula
province = { id = 579 ic = 2 }#Ryazan
province = { id = 650 ic = 2 }#Tambov
province = { id = 652 ic = 2 }#Lipetsk
province = { id = 581 ic = 2 }#Oryol
province = { id = 654 ic = 3 }#Voronezh
province = { id = 217 ic = 1 }#Aalborg
province = { id = 219 ic = 1 }#Odense
province = { id = 294 ic = 7 }#Copenhagen
province = { id = 153 ic = 4 }#Rostock
province = { id = 169 ic = 6 }#Magdeburg
province = { id = 163 ic = 25 }#Berlin
province = { id = 158 ic = 5 }#Stettin
province = { id = 181 ic = 1 }#Danzig
province = { id = 183 ic = 1 }#Elbing
province = { id = 224 ic = 1 }#Poznan
province = { id = 170 ic = 6 }#Leipzig
province = { id = 173 ic = 8 }#Dresden
province = { id = 177 ic = 6 }#Nuremberg
province = { id = 174 ic = 2 }#Bayreuth
province = { id = 138 ic = 5 }#Frankfurt
province = { id = 139 ic = 2 }#Darmstadt
province = { id = 140 ic = 3 }#Schweinfurt
province = { id = 134 ic = 6 }#Stuttgart
province = { id = 136 ic = 2 }#Karlsruhe
province = { id = 95 ic = 1 }#Chaumont
province = { id = 97 ic = 4 }#Belfort
province = { id = 73 ic = 2 }#Limoges
province = { id = 69 ic = 4 }#La Rochelle
province = { id = 68 ic = 5 }#Bordeaux
province = { id = 442 ic = 1 }#Zaragoza
province = { id = 443 ic = 2 }#Bilbao
province = { id = 444 ic = 1 }#Oviedo
province = { id = 441 ic = 1 }#Coruna
province = { id = 481 ic = 1 }#Porto
province = { id = 476 ic = 2 }#Lissabon
province = { id = 479 ic = 1 }#Coimbra
province = { id = 448 ic = 2 }#Leon
province = { id = 460 ic = 3 }#Madrid
province = { id = 455 ic = 1 }#Guadalajara
province = { id = 458 ic = 1 }#Badajoz
province = { id = 480 ic = 1 }#Evora
province = { id = 478 ic = 1 }#Beja
province = { id = 474 ic = 3 }#Sevilla
province = { id = 463 ic = 1 }#Murcia
province = { id = 464 ic = 1 }#Valencia
province = { id = 461 ic = 1 }#Castellon de la Plana
province = { id = 440 ic = 2 }#Barcelona
province = { id = 77 ic = 5 }#Toulouse
province = { id = 71 ic = 3 }#Clermont-Ferrand
province = { id = 79 ic = 4 }#Beziers
province = { id = 89 ic = 4 }#Marseille
province = { id = 93 ic = 1 }#Avignon
province = { id = 94 ic = 2 }#Korsika
province = { id = 396 ic = 6 }#Genua+3
province = { id = 408 ic = 4 }#Parma+3
province = { id = 407 ic = 12 }#Mailand+3
province = { id = 393 ic = 4 }#Brescia+3
province = { id = 401 ic = 1 }#Trento
province = { id = 390 ic = 1 }#Chur
province = { id = 179 ic = 8 }#Munich
province = { id = 189 ic = 1 }#Innsbruck
province = { id = 400 ic = 7 }#Venice+3
province = { id = 404 ic = 2 }#Trieste
province = { id = 406 ic = 2 }#Pola
province = { id = 349 ic = 1 }#Ljubljana
province = { id = 352 ic = 2 }#Zagreb
province = { id = 350 ic = 1 }#Split
province = { id = 355 ic = 1 }#Sarajevo
province = { id = 356 ic = 1 }#Mostar
province = { id = 332 ic = 1 }#Cetinje
province = { id = 359 ic = 1 }#Tirana
province = { id = 362 ic = 1 }#Vlore
province = { id = 373 ic = 1 }#Corinthe
province = { id = 382 ic = 1 }#Irakleio
province = { id = 374 ic = 1 }#Chalcis
province = { id = 377 ic = 2 }#Athens
province = { id = 368 ic = 1 }#Larissa
province = { id = 1011 ic = 1 }#Haifa
province = { id = 409 ic = 1 }#Istanbul
province = { id = 365 ic = 1 }#Thessaloniki
province = { id = 366 ic = 1 }#Kozani
province = { id = 333 ic = 1 }#Skopje
province = { id = 329 ic = 1 }#Pristina
province = { id = 320 ic = 1 }#Gorna Dzumaya
province = { id = 321 ic = 1 }#Sofia
province = { id = 318 ic = 1 }#Vidin
province = { id = 323 ic = 1 }#Pleven
province = { id = 324 ic = 1 }#Plovdiv
province = { id = 326 ic = 1 }#Varna
province = { id = 310 ic = 1 }#Constanta
province = { id = 316 ic = 5 }#Bucharest
province = { id = 315 ic = 1 }#Craiova
province = { id = 291 ic = 1 }#Sibiu
province = { id = 288 ic = 1 }#Cluj
province = { id = 299 ic = 1 }#Bacau
province = { id = 293 ic = 1 }#Miercurea Ciuc
province = { id = 311 ic = 1 }#Ploesti
province = { id = 309 ic = 1 }#Braila
province = { id = 297 ic = 1 }#Iasi
province = { id = 304 ic = 1 }#Chisinau
province = { id = 306 ic = 1 }#Ismail
province = { id = 1077 ic = 1 }#Izmir
province = { id = 1057 ic = 1 }#Antalya
province = { id = 388 ic = 1 }#Nicosia
province = { id = 1059 ic = 1 }#Sivas
province = { id = 1075 ic = 1 }#Ankara
province = { id = 338 ic = 2 }#Belgrade
province = { id = 277 ic = 1 }#Pecs
province = { id = 284 ic = 4 }#Budapest
province = { id = 279 ic = 1 }#Gyor
province = { id = 190 ic = 2 }#Graz
province = { id = 191 ic = 1 }#Klagenfurt
province = { id = 192 ic = 1 }#Salzburg
province = { id = 195 ic = 5 }#Vienna
province = { id = 194 ic = 1 }#Hollabrunn
province = { id = 187 ic = 1 }#Linz
province = { id = 197 ic = 1 }#Znojmo
province = { id = 202 ic = 2 }#Ceske Budejovice
province = { id = 207 ic = 3 }#Prag
province = { id = 199 ic = 2 }#Plzen
province = { id = 205 ic = 2 }#Karlovy Vary
province = { id = 200 ic = 1 }#Liberec
province = { id = 167 ic = 12 }#Breslau
province = { id = 201 ic = 3 }#Ostrava
province = { id = 196 ic = 3 }#Brno
province = { id = 208 ic = 3 }#Bratislava
province = { id = 211 ic = 2 }#Banska Bystrica
province = { id = 235 ic = 2 }#Cracow
province = { id = 237 ic = 2 }#Tarnow
province = { id = 227 ic = 1 }#Czestochowa
province = { id = 164 ic = 4 }#Oppeln
province = { id = 223 ic = 2 }#Lodz
province = { id = 232 ic = 4 }#Warsaw
province = { id = 228 ic = 1 }#Siedlce
province = { id = 214 ic = 2 }#Presov
province = { id = 282 ic = 1 }#Miskolc
province = { id = 280 ic = 1 }#Szeged
province = { id = 341 ic = 1 }#Novi Sad
province = { id = 295 ic = 2 }#Resita
province = { id = 286 ic = 1 }#Arad
province = { id = 281 ic = 1 }#Debrecen
province = { id = 296 ic = 1 }#Oradea
province = { id = 242 ic = 1 }#Lwow
province = { id = 240 ic = 1 }#Tarnopol
province = { id = 249 ic = 1 }#Pinsk
province = { id = 254 ic = 1 }#Bialystok
province = { id = 184 ic = 3 }#Koenigsberg
province = { id = 182 ic = 1 }#Tilsit
province = { id = 263 ic = 1 }#Alytus
province = { id = 411 ic = 6 }#Bologna
province = { id = 410 ic = 3 }#Florenz
province = { id = 419 ic = 6 }#Rom
province = { id = 413 ic = 1 }#Livorno
province = { id = 414 ic = 1 }#Perugia
province = { id = 415 ic = 3 }#Pescara
province = { id = 420 ic = 1 }#Foggia
province = { id = 421 ic = 3 }#Neapel
province = { id = 427 ic = 1 }#Salerno
province = { id = 425 ic = 1 }#Reggio di Calabria
province = { id = 430 ic = 2 }#Palermo
province = { id = 85 ic = 8 }#Lyon
province = { id = 98 ic = 2 }#Pontarlier
province = { id = 391 ic = 3 }#Geneva
province = { id = 398 ic = 6 }#Turin
province = { id = 392 ic = 5 }#Bern
province = { id = 389 ic = 3 }#Zurich
province = { id = 434 ic = 1 }#Cagliari
province = { id = 2080 ic = 1 }#Managua
province = { id = 2081 ic = 1 }#San Jose
province = { id = 2089 ic = 1 }#Vancouver
province = { id = 2140 ic = 1 }#Fairbanks
province = { id = 2090 ic = 3 }#Victoria
province = { id = 244 ic = 2 }#Rowne
province = { id = 2138 ic = 1 }#Nain
province = { id = 2137 ic = 1 }#St. Johns
province = { id = 2134 ic = 3 }#Glace Bay
province = { id = 1784 ic = 5 }#Bangor
province = { id = 2118 ic = 1 }#Sherbrooke
province = { id = 2119 ic = 1 }#Montreal
province = { id = 2117 ic = 7 }#Quebec
province = { id = 2113 ic = 7 }#Pembroke
province = { id = 2111 ic = 3 }#Toronto
province = { id = 2109 ic = 1 }#Hamilton
province = { id = 2108 ic = 1 }#Ottawa
province = { id = 1790 ic = 3 }#Burlington
province = { id = 1785 ic = 3 }#Lewiston
province = { id = 1793 ic = 7 }#Albany
province = { id = 1789 ic = 10 }#Boston
province = { id = 1796 ic = 3 }#Providence
province = { id = 1788 ic = 18 }#Hartford
province = { id = 1795 ic = 29 }#New York
province = { id = 1797 ic = 27 }#Newark
province = { id = 1807 ic = 3 }#Cape Charles
province = { id = 1809 ic = 13 }#Washington DC
province = { id = 1808 ic = 9 }#Baltimore
province = { id = 1805 ic = 44 }#Philadelphia
province = { id = 1801 ic = 9 }#Harrisburg
province = { id = 1792 ic = 7 }#Syracuse
province = { id = 1806 ic = 9 }#Pittsburgh
province = { id = 1825 ic = 15 }#Cleveland
province = { id = 1845 ic = 17 }#Detroit
province = { id = 1842 ic = 7 }#Grand Rapids
province = { id = 1828 ic = 9 }#Indianapolis
province = { id = 1832 ic = 21 }#Chicago
province = { id = 1839 ic = 13 }#Milwaukee
province = { id = 1829 ic = 7 }#Peoria
province = { id = 1830 ic = 7 }#Decatur
province = { id = 1827 ic = 9 }#Evansville
province = { id = 1821 ic = 10 }#Columbus
province = { id = 1823 ic = 5 }#Cincinnati
province = { id = 1817 ic = 9 }#Beckley
province = { id = 1816 ic = 5 }#Charlottesville
province = { id = 1813 ic = 5 }#Richmond
province = { id = 1812 ic = 5 }#Norfolk
province = { id = 1961 ic = 5 }#Raleigh
province = { id = 1962 ic = 10 }#Charlotte
province = { id = 1819 ic = 13 }#Louisville
province = { id = 1943 ic = 4 }#Nashville
province = { id = 1942 ic = 1 }#Knoxville
province = { id = 1960 ic = 5 }#Charleston
province = { id = 1957 ic = 5 }#Columbia
province = { id = 1952 ic = 3 }#Jacksonville
province = { id = 1948 ic = 3 }#Tampa
province = { id = 1949 ic = 3 }#Orlando
province = { id = 1953 ic = 3 }#Miami
province = { id = 1776 ic = 2 }#San Cristobal de la Habana
province = { id = 1779 ic = 1 }#Santa Clara
province = { id = 1775 ic = 1 }#Camaguey
province = { id = 1777 ic = 1 }#Santiago de Cuba
province = { id = 2050 ic = 9 }#Buenos Aires
province = { id = 1959 ic = 7 }#Augusta
province = { id = 1955 ic = 7 }#Atlanta
province = { id = 1941 ic = 5 }#Chattanooga
province = { id = 1946 ic = 7 }#Birmingham,Al
province = { id = 1940 ic = 5 }#Memphis
province = { id = 1939 ic = 5 }#Jackson
province = { id = 1950 ic = 7 }#Pensacola
province = { id = 1951 ic = 3 }#Tallahassee
province = { id = 1944 ic = 5 }#Mobile
province = { id = 1932 ic = 5 }#Baton Rouge
province = { id = 1931 ic = 4 }#New Orleans
province = { id = 1934 ic = 1 }#Lafayette
province = { id = 1918 ic = 5 }#Little Rock
province = { id = 1917 ic = 5 }#Fort Smith
province = { id = 1833 ic = 10 }#St. Louis
province = { id = 1914 ic = 9 }#Kansas City
province = { id = 1837 ic = 5 }#Cedar Rapids
province = { id = 1846 ic = 2 }#Rochester
province = { id = 1838 ic = 7 }#Des Moines
province = { id = 1847 ic = 13 }#Minneapolis
province = { id = 1856 ic = 3 }#Bismarck
province = { id = 1908 ic = 5 }#Denver
province = { id = 1910 ic = 5 }#Wichita
province = { id = 1913 ic = 5 }#Oklahoma City
province = { id = 1924 ic = 11 }#Dallas
province = { id = 1928 ic = 11 }#Houston
province = { id = 1906 ic = 3 }#Santa Fe
province = { id = 1900 ic = 3 }#Phoenix
province = { id = 1896 ic = 3 }#Salt Lake City
province = { id = 1979 ic = 1 }#Hermosillo
province = { id = 1980 ic = 1 }#Culiacan Rosales
province = { id = 1976 ic = 1 }#Saltillo
province = { id = 1975 ic = 1 }#Monterrey
province = { id = 1922 ic = 7 }#Corpus Christi
province = { id = 1973 ic = 1 }#Leon de los Aldama
province = { id = 1982 ic = 2 }#Guadalajara
province = { id = 1974 ic = 6 }#Mexico City
province = { id = 1969 ic = 3 }#Puebla de Zaragoza
province = { id = 1972 ic = 1 }#Acapulco de Juarez
province = { id = 1968 ic = 1 }#Vera Cruz
province = { id = 1966 ic = 1 }#Merida
province = { id = 2088 ic = 1 }#Guatemala
province = { id = 2079 ic = 1 }#San Salvador
province = { id = 2085 ic = 1 }#Tegucigalpa
province = { id = 1886 ic = 7 }#San Diego
province = { id = 1887 ic = 11 }#Los Angeles
province = { id = 1891 ic = 2 }#Santa Barbara
province = { id = 1889 ic = 12 }#San Franzisco
province = { id = 1884 ic = 1 }#Santa Rosa
province = { id = 1863 ic = 3 }#Helena
province = { id = 1874 ic = 5 }#Seattle
province = { id = 1877 ic = 5 }#Tacoma
province = { id = 1878 ic = 5 }#Portland
province = { id = 1857 ic = 3 }#Sioux Falls
province = { id = 1860 ic = 7 }#Omaha
province = { id = 1912 ic = 10 }#Tulsa
province = { id = 1989 ic = 1 }#Barquisimeto
province = { id = 1990 ic = 1 }#Cucuta
province = { id = 1988 ic = 1 }#Maracaibo
province = { id = 1995 ic = 1 }#Maturin
province = { id = 1993 ic = 2 }#Caracas
province = { id = 1987 ic = 2 }#Medellin
province = { id = 2042 ic = 1 }#San Franzisco de Quito
province = { id = 1780 ic = 1 }#Trujillo
province = { id = 2011 ic = 1 }#Pucallpa
province = { id = 2015 ic = 1 }#Cuzco
province = { id = 2016 ic = 2 }#Lima
province = { id = 2017 ic = 1 }#Arequipa
province = { id = 2020 ic = 3 }#Nuestra Senora de la Paz
province = { id = 2064 ic = 1 }#La Santisima Trinidad
province = { id = 2046 ic = 1 }#Villa Hayes
province = { id = 2021 ic = 1 }#Sucre
province = { id = 2025 ic = 2 }#Antofagasta
province = { id = 2023 ic = 3 }#Santiago de Chile
province = { id = 2056 ic = 1 }#Resistencia
province = { id = 2057 ic = 1 }#Curitiba
province = { id = 2058 ic = 1 }#Porto Allegre
province = { id = 2052 ic = 1 }#Montevideo
province = { id = 2049 ic = 1 }#Corrientes
province = { id = 2055 ic = 1 }#Rosario
province = { id = 2053 ic = 3 }#Mar del Plata
province = { id = 2045 ic = 1 }#Falklands
province = { id = 2009 ic = 1 }#Florencia
province = { id = 2004 ic = 1 }#Maraba
province = { id = 2068 ic = 1 }#Belem
province = { id = 2072 ic = 1 }#Fortaleza
province = { id = 2071 ic = 2 }#Recife
province = { id = 2073 ic = 1 }#Salvador
province = { id = 2067 ic = 1 }#Goiania
province = { id = 2074 ic = 2 }#Vitoria
province = { id = 2075 ic = 2 }#Rio de Janeiro
province = { id = 2059 ic = 1 }#Sao Paulo
province = { id = 2076 ic = 1 }#Belo Horizonte
province = { id = 2078 ic = 1 }#Ciudad de Panama
province = { id = 1986 ic = 1 }#Baranquilla
province = { id = 1781 ic = 1 }#Port-au-Prince
province = { id = 1780 ic = 1 }#Ciudad Trujillo
province = { id = 1765 ic = 1 }#Puerto Rico
province = { id = 1768 ic = 1 }#Martinique
province = { id = 787 ic = 3 }#Cairo
province = { id = 792 ic = 1 }#El Fayum
province = { id = 789 ic = 1 }#Alexandria
province = { id = 747 ic = 2 }#Tunis
province = { id = 748 ic = 1 }#Bizerte
province = { id = 735 ic = 1 }#Bona
province = { id = 734 ic = 1 }#Constantine
province = { id = 727 ic = 1 }#Algiers
province = { id = 716 ic = 1 }#Nador
province = { id = 718 ic = 1 }#Casablanca
province = { id = 722 ic = 1 }#Marrakech
province = { id = 720 ic = 1 }#Agadir
province = { id = 978 ic = 1 }#Dakar
province = { id = 977 ic = 1 }#Tambacounda
province = { id = 967 ic = 1 }#KanKan
province = { id = 969 ic = 1 }#Monrovia
province = { id = 962 ic = 1 }#Abidjan
province = { id = 961 ic = 1 }#Bouake
province = { id = 944 ic = 1 }#Niamey
province = { id = 950 ic = 1 }#Lome
province = { id = 951 ic = 1 }#Cotonou
province = { id = 932 ic = 1 }#Ibadan
province = { id = 939 ic = 1 }#Kaduna
province = { id = 930 ic = 1 }#Port Harcourt
province = { id = 794 ic = 1 }#Asyut
province = { id = 811 ic = 1 }#El Qadarif
province = { id = 825 ic = 1 }#Addis Abeba
province = { id = 836 ic = 1 }#Mogadischu
province = { id = 843 ic = 1 }#Nakuru
province = { id = 851 ic = 1 }#Tabora
province = { id = 844 ic = 1 }#Kampala
province = { id = 810 ic = 1 }#Khartoum
province = { id = 908 ic = 1 }#Quesso
province = { id = 926 ic = 1 }#Bangui
province = { id = 920 ic = 1 }#Fort Lamy
province = { id = 859 ic = 1 }#Livingstone
province = { id = 888 ic = 1 }#Lubango
province = { id = 886 ic = 1 }#Tsumeb
province = { id = 870 ic = 1 }#Gaberones
province = { id = 878 ic = 1 }#Kimberley
province = { id = 880 ic = 1 }#Cape Town
province = { id = 881 ic = 2 }#Port Elizabeth
province = { id = 872 ic = 1 }#Durban
province = { id = 876 ic = 1 }#Johannesburg
province = { id = 873 ic = 3 }#Pretoria
province = { id = 885 ic = 1 }#Lourenco Marques
province = { id = 866 ic = 1 }#Bulawayo
province = { id = 898 ic = 2 }#Elisabethville
province = { id = 862 ic = 8 }#Chingola
province = { id = 854 ic = 1 }#Nampula
province = { id = 1001 ic = 1 }#Tananarive
province = { id = 850 ic = 1 }#Dar es Salaam
province = { id = 940 ic = 1 }#Kano
province = { id = 686 ic = 3 }#Kudymkar
province = { id = 1541 ic = 1 }#Okha
province = { id = 1544 ic = 1 }#Kushiro
province = { id = 1545 ic = 3 }#Saporro
province = { id = 1549 ic = 8 }#Sendai
province = { id = 1547 ic = 3 }#Akita
province = { id = 1551 ic = 4 }#Niigata
province = { id = 1548 ic = 2 }#Nagano
province = { id = 1552 ic = 13 }#Tokyo
province = { id = 1550 ic = 7 }#Yokohama
province = { id = 1557 ic = 4 }#Nagyoa
province = { id = 1546 ic = 2 }#Shizuoka
province = { id = 1556 ic = 5 }#Kanazawa
province = { id = 1553 ic = 10 }#Osaka
province = { id = 1558 ic = 5 }#Kyoto
province = { id = 1554 ic = 2 }#Hiroshima
province = { id = 1555 ic = 4 }#Kobe
province = { id = 1559 ic = 3 }#Matsyama
province = { id = 1560 ic = 6 }#Nagasaki
province = { id = 1561 ic = 5 }#Kagoshima
province = { id = 1230 ic = 3 }#Gwangju
province = { id = 1232 ic = 2 }#Busan
province = { id = 1231 ic = 2 }#Daegu
province = { id = 1233 ic = 1 }#Chuncheon
province = { id = 1228 ic = 3 }#Seoul
province = { id = 1221 ic = 2 }#Pyongyang
province = { id = 1219 ic = 1 }#Port Arthur
province = { id = 1247 ic = 1 }#Beiping
province = { id = 1238 ic = 1 }#Huhehaote
province = { id = 1330 ic = 1 }#Jinan
province = { id = 1334 ic = 1 }#Nantong
province = { id = 1340 ic = 1 }#Hefei
province = { id = 1252 ic = 1 }#Taiyuan
province = { id = 1324 ic = 1 }#Zhengzhou
province = { id = 1317 ic = 1 }#Wuhan
province = { id = 1337 ic = 1 }#Nanjing
province = { id = 1338 ic = 1 }#Shanghai
province = { id = 1345 ic = 1 }#Hangzhou
province = { id = 1358 ic = 1 }#Fuzhou
province = { id = 1352 ic = 1 }#Nanchang
province = { id = 1318 ic = 1 }#Huangshi
province = { id = 1308 ic = 1 }#Changsha
province = { id = 1378 ic = 1 }#Guilin
province = { id = 1380 ic = 1 }#Liuzhou
province = { id = 1383 ic = 1 }#Guilin
province = { id = 1258 ic = 1 }#Xi'an
province = { id = 1259 ic = 1 }#Yan'an #3
province = { id = 1255 ic = 1 }
province = { id = 1256 ic = 1 }
province = { id = 1264 ic = 1 }#Lanzhou
province = { id = 1299 ic = 3 }#Chongqing
province = { id = 1443 ic = 1 }#Dhubri
province = { id = 1445 ic = 2 }#Dhaka
province = { id = 1444 ic = 1 }#Khulna
province = { id = 1442 ic = 1 }#Imphal
province = { id = 1450 ic = 1 }#Cattagram
province = { id = 1406 ic = 2 }#Haka
province = { id = 1420 ic = 1 }#Akyab
province = { id = 1415 ic = 2 }#Rangoon
province = { id = 1404 ic = 1 }#Muang Xay
province = { id = 1390 ic = 1 }#Kunming #3
province = { id = 1385 ic = 1 }
province = { id = 1386 ic = 1 }
province = { id = 1369 ic = 1 }#Guangzhou
province = { id = 1371 ic = 1 }#Hong Kong
province = { id = 1379 ic = 2 }#Nanning
province = { id = 1361 ic = 1 }#Gaoxiong
province = { id = 1362 ic = 1 }#Taipei
province = { id = 1364 ic = 1 }#Hualian
province = { id = 1395 ic = 1 }#Hanoi
province = { id = 1426 ic = 1 }#Phitsanulok
province = { id = 1427 ic = 1 }#Khon Khaen
province = { id = 1397 ic = 1 }#Da Nang
province = { id = 1399 ic = 1 }#Saigon
province = { id = 1400 ic = 1 }#Phnom Phen
province = { id = 1422 ic = 1 }#Chon Buri
province = { id = 1423 ic = 1 }#Bangkok
province = { id = 1424 ic = 1 }#Nakhon Sawan
province = { id = 1434 ic = 1 }#Alor Setar
province = { id = 1436 ic = 1 }#Kuantan
province = { id = 1432 ic = 3 }#Singapore
province = { id = 1642 ic = 1 }#Medan
province = { id = 1636 ic = 1 }#Palembang
province = { id = 1297 ic = 1 }#Chengdu
province = { id = 1305 ic = 1 }#GuiYang
province = { id = 1190 ic = 2 }#Khabarovsk
province = { id = 1191 ic = 2 }#Vladivostok
province = { id = 1225 ic = 1 }#Cheongjin
province = { id = 1207 ic = 3 }#Jilin
province = { id = 1199 ic = 2 }#Harbin
province = { id = 1169 ic = 2 }#Chita
province = { id = 1208 ic = 2 }#Changchun
province = { id = 1226 ic = 1 }#Ganggye
province = { id = 1227 ic = 1 }#Hamheung
province = { id = 1217 ic = 1 }#Anshun
province = { id = 1218 ic = 1 }#Panjin
province = { id = 1124 ic = 2 }#Ulaabaatar #was 1
province = { id = 1162 ic = 2 }#Irkutsk
province = { id = 1119 ic = 1 }#Kyzyl #was 8
province = { id = 504 ic = 2 }#Alma-Ata
province = { id = 1109 ic = 2 }#Chimkent
province = { id = 1103 ic = 5 }#Tashkent
province = { id = 1107 ic = 2 }#Frunze
province = { id = 1281 ic = 1 }#Urumqi
province = { id = 1283 ic = 1 }#Ge'ermu
province = { id = 1289 ic = 1 }#Lhasa
province = { id = 1456 ic = 1 }#Punakha
province = { id = 1447 ic = 1 }#Calcutta
province = { id = 1471 ic = 1 }#Bhubanesbar
province = { id = 1476 ic = 1 }#Ranchi
province = { id = 1465 ic = 1 }#Patna
province = { id = 1518 ic = 1 }#Ahmedabad
province = { id = 1481 ic = 1 }#Indhur
province = { id = 1524 ic = 1 }#Jaypur
province = { id = 1461 ic = 2 }#Lucknow
province = { id = 1462 ic = 1 }#Muzaffarpur
province = { id = 1457 ic = 1 }#Kathmandu
province = { id = 1540 ic = 1 }#Srinagar
province = { id = 1530 ic = 1 }#Lahore
province = { id = 1531 ic = 1 }#Ludhiana
province = { id = 1463 ic = 2 }#Chandighar
province = { id = 1532 ic = 1 }#Nawabshah
province = { id = 1529 ic = 1 }#Quetta
province = { id = 1105 ic = 2 }#Dushanbe
province = { id = 2171 ic = 1 }#Kabul
province = { id = 1099 ic = 2 }#Samarkand
province = { id = 1097 ic = 2 }#Ashkhabat
province = { id = 1093 ic = 1 }#Zahedan
province = { id = 1095 ic = 1 }#Birjand
province = { id = 1092 ic = 1 }#Mashad
province = { id = 1085 ic = 1 }#Tehran
province = { id = 1517 ic = 1 }#Bombay
province = { id = 1514 ic = 1 }#Nasik
province = { id = 1487 ic = 2 }#Hyderabad
province = { id = 1500 ic = 1 }#Madras
province = { id = 1502 ic = 2 }#Bangalore
province = { id = 1512 ic = 1 }#Kolhapur
province = { id = 1497 ic = 1 }#Cochin
province = { id = 1504 ic = 1 }#Madurai
province = { id = 1144 ic = 3 }#Kemerovo
province = { id = 1140 ic = 3 }#Barnaul
province = { id = 1142 ic = 3 }#Novosibirsk
province = { id = 1138 ic = 2 }#Omsk
province = { id = 503 ic = 2 }#Karaganda
province = { id = 1156 ic = 2 }#Krasnoyarsk
province = { id = 1131 ic = 3 }#Ufa
province = { id = 1134 ic = 2 }#Orenburg
province = { id = 1151 ic = 5 }#Sverdlovsk
province = { id = 1132 ic = 3 }#Chelyabinsk
province = { id = 1137 ic = 2 }#Kurgan
province = { id = 1136 ic = 2 }#Tyumen
province = { id = 1646 ic = 1 }#Tjilatjap
province = { id = 1650 ic = 1 }#Semarang
province = { id = 1653 ic = 1 }#Soerabaja
province = { id = 1620 ic = 1 }#Halmahera
province = { id = 1690 ic = 1 }#Perth
province = { id = 1704 ic = 1 }#Brisbane
province = { id = 1703 ic = 1 }#Newcastle
province = { id = 1705 ic = 5 }#Sydney
province = { id = 1707 ic = 6 }#Canberra
province = { id = 1708 ic = 5 }#Melbourne
province = { id = 1712 ic = 1 }#Adelaide
province = { id = 1565 ic = 2 }#Manila
province = { id = 1567 ic = 1 }#Baguio
province = { id = 1568 ic = 1 }#Legazpi
province = { id = 1576 ic = 1 }#Panay
province = { id = 1574 ic = 1 }#Bacolod
province = { id = 1687 ic = 1 }#Funafuti
province = { id = 685 ic = 2 }#Syktyvkar
province = { id = 675 ic = 2 }#Cheboksary
province = { id = 670 ic = 2 }#Saransk
province = { id = 656 ic = 2 }#Ulyanovsk
province = { id = 672 ic = 3 }#Kazan
province = { id = 671 ic = 2 }#Izhevsk
province = { id = 684 ic = 2 }#Kirov
province = { id = 1019 ic = 1 }#Beirut
province = { id = 1008 ic = 1 }#Tel Aviv
province = { id = 1045 ic = 1 }#Riyadh
province = { id = 1050 ic = 1 }#Sanaa
province = { id = 1052 ic = 1 }#Mascate
province = { id = 667 ic = 3 }#Tolyatti
province = { id = 669 ic = 3 }#Saratov
province = { id = 698 ic = 2 }#Voroshilovsk
province = { id = 702 ic = 2 }#Grozny
province = { id = 709 ic = 3 }#Tblisi
province = { id = 1061 ic = 1 }#Maltya
province = { id = 711 ic = 2 }#Yerevan
province = { id = 704 ic = 2 }#Makhachkala
province = { id = 1014 ic = 1 }#Deir es Zor
province = { id = 1034 ic = 1 }#Baghdad
province = { id = 1720 ic = 2 }#Auckland
province = { id = 1721 ic = 8 }#Wellington
province = { id = 1723 ic = 1 }#Dunedin
province = { id = 713 ic = 3 }#Baku