#converted DH, March 6th 2011, Kane
province = { id = 1219 anti_air = 2 air_base = { size = 7 current_size = 7 } naval_base = { size = 5 current_size = 5 }} #Port Arthur
province = { id = 1552 anti_air = 2 air_base = { size = 10 current_size = 10 } naval_base = { size = 10	current_size = 10 }}#Tokyo
province = { id = 1554 anti_air = 2 air_base = { size = 10 current_size = 10 } naval_base = { size = 10	current_size = 10 }}#Hiroshima
province = { id = 1547 anti_air = 2 air_base = { size = 10 current_size = 10 } naval_base = { size = 10	current_size = 10 }}#Akita
province = { id = 1559 anti_air = 2 air_base = { size = 10 current_size = 10 } naval_base = { size = 10	current_size = 10 }}#Matsuyama
province = { id = 1560 anti_air = 2 air_base = { size = 10 current_size = 10 } naval_base = { size = 10	current_size = 10 }}#Nagasaki
province = { id = 1556 anti_air = 2 air_base = { size = 10 current_size = 10 } naval_base = { size = 10	current_size = 10 }}#Kanazawa
province = { id = 1553 anti_air = 2 air_base = { size = 10 current_size = 10 } naval_base = { size = 10	current_size = 10 }}#Osaka
province = { id = 1557 anti_air = 2 air_base = { size = 10 current_size = 10 } naval_base = { size = 10	current_size = 10 }}#Nagoya
province = { id = 1232 anti_air = 2 air_base = { size = 10 current_size = 10 } naval_base = { size = 10	current_size = 10 }}#Busan
province = { id = 1361 anti_air = 4 air_base = { size = 8 current_size = 8 } naval_base = { size = 10 current_size = 10 }}#Gaoxiong
province = { id = 1563 anti_air = 2 air_base = { size = 6 current_size = 6 } naval_base = { size = 6 current_size = 6 }}#Okinawa South
province = { id = 1667 air_base = { size = 10 current_size = 10 } naval_base = { size = 10 current_size = 10 } } #Truk #coastalfort = 3 #anti_air = 5
province = { id = 1675 naval_base = { size = 1 current_size = 1 }}#Eniwetok #anti_air = 5
province = { id = 1676 air_base = { size = 3 current_size = 3 } naval_base = { size = 1 current_size = 1 }}#Kwajalein #anti_air = 5
province = { id = 1226 anti_air = 2 air_base = { size = 4 current_size = 4 }}#Ganggye
province = { id = 1677 naval_base = { size = 1 current_size = 1 } } #Majuro
province = { id = 1681 air_base = { size = 2 current_size = 2 } }#Wotje
province = { id = 1669 naval_base = { size = 1 current_size = 1 }}#Yap
province = { id = 1670 air_base = { size = 2 current_size = 2 } naval_base = { size = 1 current_size = 1 } }#Peleliu #coastalfort = 1 
province = { id = 1685 air_base = { size = 2 current_size = 2 } naval_base = { size = 4 current_size = 4 } }#Saipan  #coastalfort = 3
province = { id = 1672 air_base = { size = 1 current_size = 1 }}#Minami Torishima
province = { id = 1663 air_base = { size = 2 current_size = 2 }}#Motoyama

#Anti Aircraft Batteries
#province = { id = 1549 anti_air = 2 } #Sendai
#province = { id = 1662 anti_air = 2 } #Cichi Jima
#province = { id = 1686 anti_air = 3 } #Pagan
#province = { id = 1669 anti_air = 3 } #Yap
#province = { id = 1677 anti_air = 3 } #Majuro

#Supply Pools
province = { id = 1542  oilpool = 1 supplypool = 10 } #Toyohara
#province = { id = 1174  oilpool = 1 supplypool = 10 } #Sakhalin-entfällt
province = { id = 1665  oilpool = 1 supplypool = 10 } #Ponape
province = { id = 1666  oilpool = 1 supplypool = 10 } #Kusaie
province = { id = 1685  oilpool = 1 supplypool = 10 } #Saipan
province = { id = 1686  oilpool = 1 supplypool = 10 } #Pagan
province = { id = 1684  oilpool = 1 supplypool = 10 } #Rota
province = { id = 1669  oilpool = 1 supplypool = 10 } #Yap
province = { id = 1670  oilpool = 1 supplypool = 10 } #Peleliu(Palau)
#province = { id = 1604  oilpool = 1 supplypool = 10 } #Woleai-entfällt
province = { id = 1671  oilpool = 1 supplypool = 10 } #Kloulklubek(Ngulu)
#province = { id = 1618  oilpool = 1 supplypool = 10 } #Ulithi-entfällt
province = { id = 1668  oilpool = 1 supplypool = 10 } #Woleai
#province = { id = 1616  oilpool = 1 supplypool = 10 } #Pulusuk-entfällt
#province = { id = 1615  oilpool = 1 supplypool = 10 } #Ulul-entfällt
province = { id = 1667  oilpool = 100 supplypool = 100 } #Truk
#province = { id = 1612  oilpool = 1 supplypool = 10 } #Satawan-entfällt
province = { id = 1674  oilpool = 1 supplypool = 10 } #Bikini
province = { id = 1675  oilpool = 100 supplypool = 100 } #Eniwetok
province = { id = 1681  oilpool = 1 supplypool = 10 } #Wotje
#province = { id = 1603  oilpool = 1 supplypool = 10 } #Moleap-entfällt
province = { id = 1677  oilpool = 1 supplypool = 10 } #Majuro
#province = { id = 1606  oilpool = 1 supplypool = 10 } #Mili-entfällt
#province = { id = 1607  oilpool = 1 supplypool = 10 } #Jaluit-entfällt
province = { id = 1676  oilpool = 100 supplypool = 100 } #Kwajalein
province = { id = 1362  oilpool = 100 supplypool = 100 } #Taipei
province = { id = 1672  oilpool = 1 supplypool = 10 } #Minami Torishima
province = { id = 1563  oilpool = 100 supplypool = 100 } #Okinawa South
province = { id = 1562  oilpool = 1 supplypool = 10 } #Amami
#province = { id = 1194  oilpool = 1 supplypool = 10 } #Jeju-entfällt
province = { id = 1543  oilpool = 1 supplypool = 10 } #Shana
province = { id = 1662  oilpool = 1 supplypool = 10 } #Chichi Jima
province = { id = 1661  oilpool = 1 supplypool = 10 } #Iwo Jima

country = {
	tag = JAP
	belligerence = 5
	capital = 1552 #Tokyo
		
	ai_settings	= { flags = { convoy_gift_on_release = yes } }
	policy = {
        date = { year = 0 month = january day = 0 }
        democratic = 5
        political_left = 3
        freedom = 3
        free_market = 3
        professional_army = 3
        defense_lobby = 8
        interventionism = 8
    }
    allowed_divisions = { 
        infantry = yes 
        cavalry = yes 
	} 

	diplomacy = {
relation = { tag = BEL value = -25 }
relation = { tag = CGX value = -75 }
relation = { tag = CHC value = -200 }
relation = { tag = CHI value = -100 }
relation = { tag = CHL value = 20 }
relation = { tag = CSX value = -75 }
relation = { tag = CXB value = -75 }
relation = { tag = CYN value = -75 }
relation = { tag = ENG value = -25 }
relation = { tag = ETH value = 35 }
relation = { tag = FIN value = 20 }
relation = { tag = FRA value = -20 }
relation = { tag = GER value = 20 }
relation = { tag = HOL value = -50 }
relation = { tag = MAN value = 200 access = yes }
#relation = { tag = MEN value = 200 access = yes }
relation = { tag = U00 value = 200 access = yes } # Kwantung Army
relation = { tag = PHI value = 0 }
relation = { tag = SIA value = 75 }
relation = { tag = SOV value = -10 }
relation = { tag = USA value = 15 } 
relation = { tag = U03 value = 70 access = yes } # Hebei
		}		

  SpyInfo                = { country = "JAP" NumberOfSpies = 9 }

	manpower = 175

	# Resource Reserves
	energy	=		1000 
	metal	= 		1000	
	rare_materials =	500	
	oil =			3083	
	supplies =		13330 # 3000 units transferred to KWA
	money = 		100

    dormant_teams = { 1941 1942 }
	dormant_ministers = { 5166 5217 5216 5165 5215 5218 5219 5220 5221 }
	dormant_leaders = { # KWA
						101000	#	Abe N.
						101003	#	Amakasu
						101006	#	Amamiya
						101007	#	[lw] Anami
						101009	#	Akashiba
						101011	#	Doi
						101012	#	Arisue S.
						101014	#	[od] Asaka
						101015	#	[od] Fujita Sh.
						101018	#	[pl] Hayashi Y.
						101019	#	Fujita Su.
						101021	#	Doihara
						101022	#	[fb] Ando Rin.
						101023	#	[fb] Fujie
						101026	#	Fukui
						101027	#	Hirabayashi
						101031	#	Fujimuro
						101032	#	Goto
						101033	#	[od] Takahashi
						101034	#	[od,fb] Hata
						101036	#	[lw] Hayashi K.
						101037	#	[lw,fb] Tanaka R.
						101038	#	[od] Higashikuni
						101039	#	Higuchi
						101040	#	Hirata
						101041	#	Sakai K.
						101043	#	[dd] Honda M.
						101045	#	[lw,dd] Inoue
						101046	#	[od] Hasunuma
						101050	#	[pl] Hoshino
						101053	#	[od] Sakuma
						101054	#	[od] Ishida M.
						101057	#	[fb] Ihara
						101058	#	Imai T.
						101060	#	[lw,od] Iida Sa.
						101062	#	Ishiguro T.
						101063	#	[od,pl] Nishihara
						101064	#	[od,tr] Ishiwara
						101067	#	Isogai
						101070	#	[lw] Itagaki
						101071	#	Imai K.
						101073	#	Ishiguro I.
						101074	#	Kajima
						101077	#	[od,og] Kanin Kotohito
						101079	#	[od] Kasahara
						101081	#	[od] Kataoka
						101082	#	[lw] Katsuki
						101084	#	[lw,od] Ishimoto
						101085	#	Kawagishi
						101087	#	Iwamatsu
						101088	#	[fb] Machijiri
						101089	#	Katayama S.
						101090	#	[lw] Fuse
						101091	#	[lw] Kashiwa
						101092	#	Kim Suk-won
						101095	#	Kayashima
						101099	#	Kunisaki
						101100	#	Yokoyama T.
						101101	#	[lw] Koiso
						101103	#	Komatsubara
						101104	#	Kondo
						101106	#	[dd] Okabe
						101107	#	[od] Tajima H.
						101116	#	[od,og] Matsui I.
						101117	#	[od,og] Minami
						101121	#	[od] Mori T.
						101127	#	Tsutsumi
						101128	#	[dd] Nakajima K.
						101129	#	[lw] Nashioka
						101131	#	Uchida
						101133	#	[lw] Kamada
						101134	#	[od] Nishio
						101136	#	Sonobe
						101137	#	Ogisu
						101138	#	Hatori
						101140	#	[en] Kusaba
						101141	#	[pl] Okada T.
						101142	#	Nakamura J.
						101146	#	Shidei
						101152	#	Sato  Ke.
						101154	#	Sasaki T.
						101155	#	Nakamura M.
						101157	#	Nozoe
						101158	#	[en] Matsui M.
						101160	#	[en,fb] Shimomura
						101163	#	[lw,dd] Sugiyama
						101164	#	Sawaki
						101165	#	[fb] Sumida
						101170	#	[dd] Tada
						101172	#	Takumi
						101176	#	Tani
						101177	#	Tashiro
						101178	#	Kashii
						101181	#	[od] Motoizumi
						101182	#	[og] Ushijima  S.
						101183	#	[od] Honda T.
						101185	#	[lw] Yasui
						101190	#	[fb] Uchiyama
						101191	#	[od,og] Ueda
						101192	#	[lw] Umezu
						101193	#	Murakami
						101194	#	[od] Naito
						101197	#	[lw] Nakajima T.
						101200	#	[od] Yamada O.
						101201	#	Yamaguchi
						101202	#	Yamaoka
						101204	#	[lw] Yamamoto
						101206	#	[lw] Saeki
						101207	#	[od] Yanagawa
						101211	#	Nakamura K.
						101212	#	[lw] Yokoyama I.
						101213	#	Nemoto
						101215	#	Sakai N.
						101216	#	Yoshioka
						101217	#	Obata T.
						101218	#	[od] Okamura
						101220	#	Ono
						101221	#	Onodera
						101222	#	[lw] Saito  Ya.
						101224	#	[fb] Sawada
						101226	#	[lw] Shibayama
						101227	#	Shinozuka
						101228	#	Sogawa
						101229	#	Suematsu
						101230	#	[od] Suetaka
						101231	#	Suzuki  Shigeyasu
						101232	#	Suzuki  T.
						101234	#	Takamori
						101236	#	Tatekawa
						101237	#	Tatsumi
						101239	#	Tomita
						101240	#	[lw,od] Tsukada O.
						101241	#	[od] Usami
						101242	#	[en] Ushijima  Mitsune
						101245	#	[fb,og] Yamamuro
						101247	#	Yoneyama
						101248	#	Yoshida M.
						101249	#	[od,pl] Yoshida S.
						101250	#	Yoshimoto
						101251	#	Ushiroku
						101253	#	[od] Wada Y.
						101256	#	Suzuki Y.
						101257	#	Obata N.
						101263	#	[pl] Hara
						101264	#	[lw] Hashimoto
						101265	#	Furusho
						101267	#	[dd,og] Nishi
						101270	#	Yoshizawa
						101271	#	Kano
						101272	#	Kato
						101273	#	[lw] Shimokawa
						101309	#	[tb] Itahana
						101383	#	Niimi
						101499	#	Tanimoto
						101550	#	[od] Mori Sh.
						101551	#	Mori Su.
						101552	#	Ouchi
						101554	#	Shimomoto
						101556	#	Takehara
						101557	#	[en] Wada K.
						101558	#	[pl] Yasuoka
						101559	#	[lw] Ikeda R.
						101560	#	Banzai
						101561	#	Ishida K.
						101563	#	Matsumoto
						101564	#	Sakata
						101572	#	Ikagura
						101575	#	Kinoshita I.
						101579	#	[pl] Hosomi
						101600	#	Hongo
						101609	#	Hongo
						}

	transports = 800 # + 175 in kwantung, 975 in total
	escorts = 70 # + 11 in Kwantung; 81 in total

   nationalprovinces      = 
{  
	1543 #Shana
	1544 #Kushiro=>Asahikawa
	1545 #Sapporo
	1549 #Sendai
	1551 #Niigata
	1550 #Yokohama
	1556 #Kanazawa
	1552 #Tokyo
	1557 #Nagoya
	1558 #Kyoto
	1553 #Osaka
	1554 #Hiroshima
	1559 #Matsuyama=>Shikoku
	1560 #Nagasaki=>Fukuoka
	1561 #Kagoshima
	1662 #Chichi Jima=>Bonin Island
	1661 #Iwo Jima
	1663 #Motoyama
	1664 #Mount Suribashi
	1562 #Amami
	1563 #Okinawa South
	1564 #Okinawa North
	1672 #Minami Torichima
	1555 #Kobe
	1542 #Toyohara
    1541 #Okha
    1547 #Akita
	1548 #Nagano
	1546 #Shizuoka
# South Korea
	1228 #Seoul
	1229 #Daeejon
	1233 #Chuncheon
	1232 #Busan
	1231 #Daegu
	1230 #Gwangju
# North Korea
	1223 #Wonsan
	1221 #Pyongyang
	1222 #Sariwon
	1226 #Ganggye
	1227 #Hamheyung
	1224 #Sinuiju
	1225 #Cheongijn
	
# Port Arthur
	1219

} 
   ownedprovinces         = {  
1543 1544 1545 1549 1551 1550 1556 1552 1557 1558 1553 1554 1559 1560 1561 1662 1661 1663 1664 1562 1563 1564 1672 1686 1685 1684  
#Carolines
	1670 #Peleliu
	1671 #Kloulklubek
	1665 #Ponape
	1669 #Yap
	1668 #Woleai
	1667 #Truk
	1666 #Kusaie
	1674 #Bikini
	1675 #Eniwetok
	1676 #Kwajalein
	1677 #Majuro
	1681 #Wotje
	1542 1555 1547 1548 1546 
# Taiwan		 
	1361 #Gaoxiong#
	1362 #Taipei
	1363 #Tauizhong
	1364  #Hualian
# Port Arthur
	1219
} 
  
   controlledprovinces    = {  
1543 1544 1545 1549 1551 1550 1556 1552 1557 1558 1553 1554 1559 1560 1561 1662 1661 1663 1664 1562 1563 1564 1672 1686 1685 1684 1668 1670 1671 1665 1669 1667 1666 1674 1675 1676 1677 1681 1364 
1542 1555 1361  
1547 1548 1546 1362 
# Sakhalin 
 1363
# Port Arthur
 1219
}

claimedprovinces = {
1676 # Marshall Islands
1677 # Marshall Islands
1669 # Carolines
1671 # Carolines
1668 # Carolines
1667 # Carolines
1665 # Ponape
1674 # Bikini
1675 # Eniwetok
1666 # Kosrae
1670 # Palau
1681 # Wotje
1684 # Mariane Islands
1685 # Mariane Islands
1686 # Mariane Islands
1683 # Guam
1361 # Taiwan
1362 # Taiwan
1363 # Taiwan
1364 # Taiwan
}

	deactivate = {  }

	techapps = {
# JAP 1936 techs
#######################

#####################
# Aircraft techs
#####################
4010 4020 4030 4040 # Single Engined 1929, Int, fgt, CAS 1930
4050 # Single Engined 1936

4290 4300 4310 4320 # double Engined 1929, tactical, naval, escort brigade 1930
4330 # double Engined 1396

4570 # CAG 1930

9010 9020 9030 # Aerial warfare, basic doctrines
9120 		# Airsuperiority off.

#############################

2800 2810 # Basic Armoured Car

2550 2630 # Tanks

2290 2300 # GW artillery

2450 # Early Static AA

17000 # 1936 rocket artillery/mortars

2460 2510 # Basic AA

1010 1020 # Early infantry
1190 1200 # Early cavalry

1310 # Engineers

2400 #AT

5010 # Agriculture (basic)
5080 5090  # Construction 
5190 # Basic Oil Refining
5310 5320 5350 # Encryption
5470 # Nukes

6400 6410 6420 # Light Infantry

#Naval doctrines
8010 8070 8130 8660 8300 8370 8710 8760 8810

#Naval Techs
# Escorts up to pre-WW2
3010	3040	3070	3100
3020	3050	3080	3110
3030 15250	3060	3090	3120

3350 3390 3430 3480 3510 15100 # Capital Design up to 1935
3360 3440 3490 3520 3540 # CA up to 1936
3370 3400 3450 3460 # BC up to 1918
3380 3410 3420 3470 3500 3530 3550 # BB up to 1936
15090 16030 3190 3200 3210 # Prewar Carrier, CV and CVE 1930
3220 3230 3240 # Carrier 1936, CV 1937, CVE 1937
3700 15080 3760 # Prewar SS, SS 1930 & SS 1936
3800 3810 # prewar and 1936 TP
3850 # torpedoes 36
#3900 # ASW 1936
}
blueprints = { 1150 3250 3260 4360 2010 } # reflects Shokaku ( CV )
inventions = { 8022 } # Heavy BB

#####################################################
#Japanese groundforces by Lord Rommel - 2.2.2012
#####################################################
#18 Infanterie-Divisionen + Imperial Gurads
#China Garrison Army mit 5771 Mann (IST 1936)
#IJA Cavalry Group mit 3 Brigaden (1.,3. und 4.)
#Inner Mongolian Army mit 8 Kav-Divs (20.000 Mann)
#Taiwan Army of Japan mit 2 Brigaden (1935)
#Special Naval Landing Forces mit unbekannter Stärke 1936
#
#KWA: 11 IJA Divs
#2,4,6,7,8,9,10,11,14,19 und 20
#
#####################################################
#IJA - Imperial Japanese Army
#####################################################

landunit = {
	id = { type = 13016 id = 1 }
	name = "Tobugun" # Tokyo District
	location = 1552  
	    division = { id = { type = 13016 id = 2 } name = "IJA Daihon'ei" type = hq model = 0 } 
		division = { id = { type = 13016 id = 3 } name = "Konoe Shidan"  type = d_03 model = 1 extra = artillery brigade_model = 2 experience = 35 } 		
	}

landunit = {
	id = { type = 13016 id = 4 }
	name = "1 Hoheishidan" # Tokyo District
	location = 1552  
		division = { id = { type = 13016 id = 5 } name = "1 Ryodan" type = d_02 model = 1 extra = artillery           brigade_model = 1 experience = 20 } 
		division = { id = { type = 13016 id = 6 } name = "2 Ryodan" type = d_02 model = 1 extra = light_armor_brigade brigade_model = 1 experience = 20 }	
	}	
	
landunit = {
	id = { type = 13016 id = 7 }
	name = "14 Hoheishidan" # Utsunomiya
	location =   1549
		division = { id = { type = 13016 id = 8 } name = "27 Ryodan" type = d_02 model = 1 experience = 20 } 
		division = { id = { type = 13016 id = 9 } name = "28 Ryodan" type = d_02 model = 1 experience = 20 }	
	}		

landunit = {
	id = { type = 13016 id = 10 }
	name = "3 Hoheishidan" # Nagoya
	location =   1557
		division = { id = { type = 13016 id = 11 } name = "5 Ryodan"  type = d_02 model = 1 extra = artillery   brigade_model = 1 experience = 20 } 
		division = { id = { type = 13016 id = 12 } name = "29 Ryodan" type = d_02 model = 1 extra = armored_car brigade_model = 0 experience = 20 }	
	}			
	
landunit = {
	id = { type = 13016 id = 13 }
	name = "4 Hoheishidan" # Osaka
	location =   1553
		division = { id = { type = 13016 id = 14 } name = "7 Ryodan"  type = d_02 model = 1 experience = 20 } 
		division = { id = { type = 13016 id = 15 } name = "32 Ryodan" type = d_02 model = 1 experience = 20 }	
	}		
	
landunit = {
	id = { type = 13016 id = 16 }
	name = "10 Hoheishidan" # Himeji 
	location =   1555
		division = { id = { type = 13016 id = 17 } name = "8 Ryodan"  type = d_02 model = 1 experience = 20 } 
		division = { id = { type = 13016 id = 18 } name = "33 Ryodan" type = d_02 model = 1 experience = 20 }	
	}			
	
landunit = {
	id = { type = 13016 id = 19 }
	name = "16 Hoheishidan" # Kyoto
	location =   1558
		division = { id = { type = 13016 id = 20 } name = "18 Ryodan" type = d_02 model = 1 experience = 20 } 
		division = { id = { type = 13016 id = 21 } name = "19 Ryodan" type = d_02 model = 1 experience = 20 }	
	}			
	
landunit = {
	id = { type = 13016 id = 22 }
	name = "11 Hoheishidan" # Zentsuji
	location =   1559
		division = { id = { type = 13016 id = 23 } name = "10 Ryodan" type = d_02 model = 1 experience = 20 } 
		division = { id = { type = 13016 id = 24 } name = "22 Ryodan" type = d_02 model = 1 experience = 20 }	
	}	
	
landunit = {
	id = { type = 13016 id = 25 }
	name = "12 Hoheishidan" # Kokura
	location =   1560
		division = { id = { type = 13016 id = 26 } name = "12 Ryodan" type = d_02 model = 1 extra = artillery           brigade_model = 1 experience = 20 } 
		division = { id = { type = 13016 id = 27 } name = "24 Ryodan" type = d_02 model = 1 extra = light_armor_brigade brigade_model = 1 experience = 20 }	
	}	
	
#############################################		
#############################################	
	
landunit = {
	id = { type = 13016 id = 30 }
	name = "Taiwan gun" # Taiwan
	location = 1362 
		division = { id = { type = 13016 id = 31 } name = "Forumosa Ryodan" type = d_02 model = 1 strength = 30 }
	}		
	
landunit = {
	id = { type = 13016 id = 32 }
	name = "Saka gun" # Sakhalin
	location = 1542 
		division = { id = { type = 13016 id = 33 } name = "Karafuto Ryodan" type = d_02 model = 1 strength = 30 }
	}		
	
#########################################################
# Island defence forces                                 #
#########################################################

landdivision = { dormant = yes  id = { type = 13016 id = 661 } name = "Ponape Bobitai"      type = garrison model = 1 strength = 25 }
landdivision = { dormant = yes  id = { type = 13016 id = 674 } name = "Eniwetok Bobitai"    type = garrison model = 1 strength = 25 }
landdivision = { dormant = yes  id = { type = 13016 id = 678 } name = "Kwajalein Bobitai"   type = garrison model = 1 strength = 25 }
landdivision = { dormant = yes  id = { type = 13016 id = 680 } name = "Saipan Bobitai"      type = garrison model = 1 strength = 25 }
landdivision = { dormant = yes  id = { type = 13016 id = 684 } name = "Peleliu Keibitai"    type = garrison model = 1 strength = 25 }
landdivision = { dormant = yes  id = { type = 13016 id = 690 } name = "Truk Bobitai"        type = garrison model = 1 strength = 25 }
landdivision = { dormant = yes  id = { type = 13016 id = 691 } name = "Wotje Bobitai"       type = garrison model = 1 strength = 25 }

#########################################################
# old ships used for training duties etc.               #
# => 'final stand' decision								#
#########################################################	
	
navaldivision = { dormant = yes id = { type = 13016 id = 1618 }  name = "Asama" type = battlecruiser model = 0 strength = 25 } # damaged by fire in 1935, floating battery
navaldivision = { dormant = yes id = { type = 13016 id = 1619 }  name = "Tokiwa" type = battlecruiser model = 0 strength = 75 } # rebuilt as large minelayer
navaldivision = { dormant = yes id = { type = 13016 id = 1620 }  name = "Azuma" type = battlecruiser model = 0 strength = 75 } # stationary training ship
navaldivision = { dormant = yes id = { type = 13016 id = 1621 }  name = "Mikasa" type = battleship model = 0 strength = 75 } # museum ship

#########################################################
# Chinese Ships                                         #
#########################################################	

navaldivision = { dormant = yes id = { type = 13016 id = 1622 }  name = "Ioshima"   type = d_09 model = 2 }
navaldivision = { dormant = yes id = { type = 13016 id = 1623 }  name = "Yasoshima" type = d_09 model = 2 } 

#########################################################
# Type A Elite                                          #
# 1.,8.,10.,11.,12.,15.,19.,20.,23.,24.,25.,28.,51.,57. #
#########################################################

#landdivision = { dormant = yes id = { type = 13016 id = 50 }  name = "15 Hoheishidan" type = d_03 model = 1 extra = light_armor_brigade brigade_model = 3 experience = 10 }
#landdivision = { dormant = yes id = { type = 13016 id = 51 }  name = "23 Hoheishidan" type = d_03 model = 1 extra = light_armor_brigade brigade_model = 3 experience = 10 }
#landdivision = { dormant = yes id = { type = 13016 id = 52 }  name = "24 Hoheishidan" type = d_03 model = 2 extra = light_armor_brigade brigade_model = 4 experience = 10 }
#landdivision = { dormant = yes id = { type = 13016 id = 53 }  name = "25 Hoheishidan" type = d_03 model = 2 extra = light_armor_brigade brigade_model = 5 experience = 10 }
#landdivision = { dormant = yes id = { type = 13016 id = 54 }  name = "28 Hoheishidan" type = d_03 model = 2 extra = light_armor_brigade brigade_model = 5 experience = 10 }
#landdivision = { dormant = yes id = { type = 13016 id = 55 }  name = "51 Hoheishidan" type = d_03 model = 2 extra = light_armor_brigade brigade_model = 5 experience = 10 }
#landdivision = { dormant = yes id = { type = 13016 id = 56 }  name = "57 Hoheishidan" type = d_03 model = 2 extra = light_armor_brigade brigade_model = 5 experience = 10 }
	
#####################################################
#IJN - Imperial Japanese Navy - Groundforces        #
#####################################################

landunit = {
	id = { type = 13016 id = 70 }
	name = "Kure Kaigun Tokubetsu Rikusentai" # Kure - Special Naval Landing Forces
	location = 1554 #
		division = { id = { type = 13016 id = 71 } name = "Kure Rikusentai" type = marine model = 0 strength = 10 }
	}	
	
landunit = {
	id = { type = 13016 id = 72 }
	name = "Yokosuka Kaigun Tokubetsu Rikusentai" # Yokosuka - Special Naval Landing Forces
	location = 1552 #
		division = { id = { type = 13016 id = 73 } name = "Yokosuka Rikusentai" type = marine model = 0 strength = 10 }
	}	

landunit = {
	id = { type = 13016 id = 74 }
	name = "Sasebo Kaigun Tokubetsu Rikusentai" # Sasebo - Special Naval Landing Forces
	location = 1560 #
		division = { id = { type = 13016 id = 75 } name = "Sasebo Rikusentai" type = marine model = 0 strength = 10 }
	}	

landunit = {
	id = { type = 13016 id = 76 }
	name = "Maizuru Kaigun Tokubetsu Rikusentai" # Maizuru - Special Naval Landing Forces
	location = 1558 #
		division = { id = { type = 13016 id = 77 } name = "Maizuru Rikusentai" type = marine model = 0 strength = 10 }
	}

landunit = {
	id = { type = 13016 id = 78 }
	name = "Shanghai Kaigun Tokubetsu Rikusentai" # Shanghai - Special Naval Landing Forces
	location = 1552 #
		division = { id = { type = 13016 id = 79 } name = "Shanghai Rikusentai" type = marine model = 0 strength = 25 }
	}		
	
#####################################
# costal garrisons for AI by Studti #
#####################################

# 1561 Kagoshima
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451100 } name = "1 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451101 } name = "2 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451102 } name = "3 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	
# 1560 Nagasaki
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451103 } name = "4 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451104 } name = "5 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451105 } name = "6 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	
# 1554 Hiroshima
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451106 } name = "7 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451107 } name = "8 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451108 } name = "9 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	
# 1559 Matsuyama
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451109 } name = "10 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451110 } name = "11 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451111 } name = "12 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	
# 1555 Kobe
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451112 } name = "13 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451113 } name = "14 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451114 } name = "15 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	
# 1553 Osaka
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451115 } name = "16 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451116 } name = "17 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451117 } name = "18 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	
# 1558 Kyoto
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451118 } name = "19 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451119 } name = "20 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451120 } name = "21 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	
# 1556 Kanazawa
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451121 } name = "22 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451122 } name = "23 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451123 } name = "24 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	
# 1557 Nagoya
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451124 } name = "25 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451125 } name = "26 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451126 } name = "27 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	
# 1550 Yokohama
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451127 } name = "28 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451128 } name = "29 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451129 } name = "30 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	
# 1552 Tokyo
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451130 } name = "31 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451131 } name = "32 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451132 } name = "33 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	
# 1549 Sendai
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451133 } name = "34 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451134 } name = "35 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451135 } name = "36 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	
# 1551 Niigata
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451136 } name = "37 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451137 } name = "38 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451138 } name = "39 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	
# 1547 Akita
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451139 } name = "40 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451140 } name = "41 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451141 } name = "42 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	
# 1545 Sapporo
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451142 } name = "43 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451143 } name = "44 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451144 } name = "45 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	
# 1544 Kushiro
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451145 } name = "46 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451146 } name = "47 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451147 } name = "48 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	
#####################################
# Korea garrisons for AI by Studti  #
#####################################

# 1217 Anshan
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451148 } name = "49 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451149 } name = "50 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	
# 1219 Port Arthur
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451150 } name = "51 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	
# 1221 Pyeongyang
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451151 } name = "52 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451152 } name = "53 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	
# 1228 Seoul
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451153 } name = "54 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451154 } name = "55 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	
# 1232 Busan
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451155 } name = "56 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451156 } name = "57 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	
# 1223 Wonsan
	landdivision = { dormant = yes locked = yes id = { type = 13016 id = 451157 } name = "58 Kaigan o surutameni-ka" type = garrison model = 2 strength = 100 extra = anti_air brigade_model = 3 }
	
#####################################################
#IJAAF - Imperial japanese army air force           #
#####################################################
# by Aser                                           #
# 4 Fighter wings                                   #
# 2 ground attack wings                             #
# 4 bomber wings                                    #
#####################################################

airunit = {
    id = { type = 13016 id = 100 }
    name = "I Kokugun"
    location = 1552 #
    base = 1552 
		division = { id = { type = 13016 id = 110 } name = "1 Zerosen no Hikodan"          strength = 60 type = interceptor     model = 0 experience = 10 }
		division = { id = { type = 13016 id = 117 } name = "3 Keibakugekiki no Hikodan"    strength = 80 type = tactical_bomber model = 0 experience = 10 }		
        division = { id = { type = 13016 id = 115 } name = "1 Sentougakugekiki no Hikodan" strength = 80 type = cas             model = 0 experience = 10 }
    }
	
airunit = {
    id = { type = 13016 id = 101 }
    name = "II Kokugun"
    location = 1553 
    base = 1553 
	    division = { id = { type = 13016 id = 111 } name = "2 Zerosen no Hikodan"          strength = 60 type = interceptor model = 0 experience = 10 }
		division = { id = { type = 13016 id = 114 } name = "2 Sentougakugekiki no Hikodan" strength = 80 type = cas         model = 0 experience = 10 }
    }
	
airunit = {
    id = { type = 13016 id = 102 }
    name = "III Kokugun"
    location = 1554 
    base = 1554 
		division = { id = { type = 13016 id = 112 } name = "3 Zerosen no Hikodan"       strength = 60 type = interceptor     model = 0 experience = 10 }
		division = { id = { type = 13016 id = 113 } name = "4 Zerosen no Hikodan"       strength = 60 type = interceptor     model = 0 experience = 10 }
		division = { id = { type = 13016 id = 116 } name = "1 Keibakugekiki no Hikodan" strength = 80 type = tactical_bomber model = 0 experience = 10 }		
		division = { id = { type = 13016 id = 118 } name = "2 Keibakugekiki no Hikodan" strength = 80 type = tactical_bomber model = 0 experience = 10 }
		division = { id = { type = 13016 id = 119 } name = "4 Keibakugekiki no Hikodan" strength = 80 type = tactical_bomber model = 0 experience = 10 }
    }

#####################################################
#IJNAS - Imperial japanese navy air service         #
#####################################################
# by Aser                                           #
# 3 Fighter wings                                   #
# 2 naval bomber wings                              #
# + carrier groups (carrier attchment)              #
#####################################################

airunit = {
    id = { type = 13016 id = 200 }
    name = "Kure Koku Kantai"
    location = 1554 
    base = 1554 
		division = { id = { type = 13016 id = 210 } name = "3 Zerosen no Kokutai" strength = 80 type = d_01 model = 1 experience = 10 }
		division = { id = { type = 13016 id = 213 } name = "1 Kaigunkugekiki no Kokutai" strength = 80 type = naval_bomber model = 0 experience = 10 }
	}		
				
airunit = {
    id = { type = 13016 id = 202 }
    name = "Yokosuka Koku Kantai"
    location = 1552 
    base = 1552 	
	    division = { id = { type = 13016 id = 211 } name = "2 Zerosen no Kokutai" strength = 80 type = d_01 model = 1 experience = 10 }
	}
	
airunit = {
    id = { type = 13016 id = 201 }
    name = "Sasebo Koku Kantai"
    location = 1560 
    base = 1560 
        division = { id = { type = 13016 id = 212 } name = "1 Zerosen no Kokutai" strength = 80 type = d_01 model = 1 experience = 10 }
		division = { id = { type = 13016 id = 214 } name = "2 Kaigunkugekiki no Kokutai" strength = 80 type = naval_bomber model = 0 experience = 10 }
    }
	
##################################################
# Imperial japanese navy 
##################################################

#naval decisions:
navaldivision = { dormant = yes id = { type = 13016 id = 1073 }  name = "Zuiho" type = light_carrier model = 4 extra = light_cag brigade_model = 1 experience = 20 }
navaldivision = { dormant = yes id = { type = 13016 id = 1074 }  name = "Shoho" type = light_carrier model = 4 extra = light_cag brigade_model = 2 experience = 20 }
navaldivision = { dormant = yes id = { type = 13016 id = 1075 }  name = "Ryuho" type = light_carrier model = 3 extra = light_cag brigade_model = 2 experience = 20 }
	
	
navalunit = {
	id = { type = 13016 id = 1001 }
	name = "Nihon Kaigun"
	location = 1552 #Tokyo
	base = 1552 #Tokyo
		division = { id = { type = 13016 id = 1004 } name = "Haruna" type = battlecruiser model = 6 extra = floatplane experience = 20 } # 1935 refitted
		division = { id = { type = 13016 id = 1797 } name = "Hiei" type = battlecruiser model = 2 experience = 20 } # 1937-1940 (!) refitted
		division = { id = { type = 13016 id = 1398 } name = "Kongo" type = battlecruiser model = 2 extra = floatplane experience = 20 div_upgr_progress = 0.4 } # refitted 01.06.35 until 08.01.37
		division = { id = { type = 13016 id = 1399 } name = "Kirishima" type = battlecruiser model = 2 extra = floatplane experience = 20 div_upgr_progress = 0.75 } # refitted 18.11.34 until 08.06.36
	}

navalunit = {
	id = { type = 13016 id = 1005 }
	name = "1. Kaigun"
	location = 1552 #Tokyo
	base = 1552 #Tokyo
		division = { id = { type = 13016 id = 1007 } name = "Fuso" type = battleship model = 2 experience = 20 }
		division = { id = { type = 13016 id = 1008 } name = "Yamashiro" type = battleship model = 7 experience = 20 }
		division = { id = { type = 13016 id = 1303 } name = "Hyuga" type = battleship model = 2 experience = 20 div_upgr_progress = 0.75 } #reconstruction until september 3 1936
		division = { id = { type = 13016 id = 1302 } name = "Ise" type = battleship model = 2 experience = 20 div_upgr_progress = 0.3 } #reconstruction until march 27 1937	
	}

navalunit = {
	id = { type = 13016 id = 1009 }
	name = "2. Kaigun"
	location = 1554 #Hiroshima
	base = 1554 #Hiroshima
		division = { id = { type = 13016 id = 1012 } name = "Nagato" type = battleship model = 3 experience = 20 div_upgr_progress = 0.95 } #
	}

navalunit = { # was drydocked until September 30, 1936
	id = { type = 13016 id = 1013 }
	name = "3. Kaigun"
	location = 1554 #Hiroshima
	base = 1554 #Hiroshima
		division = { id = { type = 13016 id = 1014 } name = "Mutsu" type = battleship model = 3 experience = 20 div_upgr_progress = 0.7 } #
	}

navalunit = {
	id = { type = 13016 id = 1015 }
	name = "4. Kaigun"
	location = 1552 #Tokyo
	base = 1552 #Tokyo
		division = { id = { type = 13016 id = 1016 } name = "Tatsuta" type = light_cruiser model = 2 experience = 20 }
		division = { id = { type = 13016 id = 1017 } name = "Hirado" type = light_cruiser model = 1 experience = 20 }
		division = { id = { type = 13016 id = 1018 } name = "Yahagi" type = light_cruiser model = 1 experience = 20 }
		division = { id = { type = 13016 id = 1019 } name = "Kuma" type = light_cruiser model = 3 experience = 20 }
		division = { id = { type = 13016 id = 1020 } name = "Tama" type = light_cruiser model = 3 experience = 20 }
	}

navalunit = {
	id = { type = 13016 id = 1021 }
	name = "5. Kaigun"
	location = 1554 #Hiroshima
	base = 1554 #Hiroshima
		division = { id = { type = 13016 id = 1022 } name = "Furutaka" type = heavy_cruiser model = 3 extra1 = naval_anti_air_s extra2 = naval_torpedoes_s extra3 = floatplane experience = 20 }
		division = { id = { type = 13016 id = 1023 } name = "Kitakami" type = light_cruiser model = 3 experience = 20 }
		division = { id = { type = 13016 id = 1024 } name = "Kiso" type = light_cruiser model = 3 experience = 20 }
		division = { id = { type = 13016 id = 1025 } name = "Oi" type = light_cruiser model = 3 experience = 20 }
		division = { id = { type = 13016 id = 1026 } name = "Nagara" type = light_cruiser model = 3 experience = 20 }
		division = { id = { type = 13016 id = 1028 } name = "Tenryu" type = light_cruiser model = 2 experience = 20 }
	}

navalunit = {
	id = { type = 13016 id = 1029 }
	name = "6. Kaigun"
	location = 1552 #Tokyo
	base = 1552 #Tokyo
		division = { id = { type = 13016 id = 1030 } name = "Natori" type = light_cruiser model = 3 experience = 20 }
		division = { id = { type = 13016 id = 1031 } name = "Kinu" type = light_cruiser model = 3 experience = 20 }
		division = { id = { type = 13016 id = 1032 } name = "Yura" type = light_cruiser model = 3 experience = 20 }
	}

navalunit = {
	id = { type = 13016 id = 1034 }
	name = "7. Kaigun"
	location = 1559 #Matsuyama
	base = 1559 #Matsuyama
		division = { id = { type = 13016 id = 1035 } name = "Yubari" type = light_cruiser model = 3 experience = 20 }
		division = { id = { type = 13016 id = 1036 } name = "Isuzu" type = light_cruiser model = 3 experience = 20 }
		division = { id = { type = 13016 id = 1037 } name = "Sendai" type = light_cruiser model = 3 experience = 20 }
		division = { id = { type = 13016 id = 1038 } name = "Abukuma" type = light_cruiser model = 3 experience = 20 }
		division = { id = { type = 13016 id = 1039 } name = "Jintsu" type = light_cruiser model = 3 experience = 20 }
	}

navalunit = {
	id = { type = 13016 id = 1040 }
	name = "8. Kaigun"
	location = 1552 #Tokyo
	base = 1552 #Tokyo
		division = { id = { type = 13016 id = 1041 } name = "Kako" type = heavy_cruiser model = 3 extra1 = naval_anti_air_s extra2 = naval_torpedoes_s extra3 = floatplane experience = 20 }
		division = { id = { type = 13016 id = 1042 } name = "Aoba" type = heavy_cruiser model = 4 experience = 20 }
		division = { id = { type = 13016 id = 1043 } name = "Kinugasa" type = heavy_cruiser model = 4 experience = 20 }
		division = { id = { type = 13016 id = 1044 } name = "Nachi" type = heavy_cruiser model = 5 experience = 20 }
		division = { id = { type = 13016 id = 1045 } name = "Haguro" type = heavy_cruiser model = 5 experience = 20 }
		division = { id = { type = 13016 id = 1046 } name = "Naka" type = light_cruiser model = 3 experience = 20 }
	}

navalunit = {
	id = { type = 13016 id = 1047 }
	name = "9. Kaigun"
	location = 1552 #Tokyo
	base = 1552 #Tokyo
		division = { id = { type = 13016 id = 1048 } name = "Myoko" type = heavy_cruiser model = 5 experience = 20 }
		division = { id = { type = 13016 id = 1049 } name = "Ashigara" type = heavy_cruiser model = 5 experience = 20 }
		division = { id = { type = 13016 id = 1050 } name = "Atago" type = heavy_cruiser model = 5 experience = 20 }
		division = { id = { type = 13016 id = 1051 } name = "Takao" type = heavy_cruiser model = 5 experience = 20 }
		division = { id = { type = 13016 id = 1052 } name = "Chokai" type = heavy_cruiser model = 5 experience = 20 }
	}

navalunit = {
	id = { type = 13016 id = 1053 }
	name = "10. Kaigun"
	location = 1559 #Matsuyama
	base = 1559 #Matsuyama
		division = { id = { type = 13016 id = 1054 } name = "Maya" type = heavy_cruiser model = 5 experience = 20 }
		division = { id = { type = 13016 id = 1055 } name = "Mikuma" type = light_cruiser model = 4 experience = 20 }
		division = { id = { type = 13016 id = 1056 } name = "Mogami" type = light_cruiser model = 4 experience = 20 }
	}
	
navalunit = {
	id = { type = 13016 id = 1124 }
	name = "11. Kaigun"
	location = 1559 #Matsuyama
	base = 1559 #Matsuyama
#		division = { id = { type = 13016 id = 1125 } name = "Asama" type = battlecruiser model = 0 extra = naval_anti_air_l strength = 20 experience = 20 }
		division = { id = { type = 13016 id = 1126 } name = "Yakumo" type = battlecruiser model = 0 strength = 20 experience = 20 }
		division = { id = { type = 13016 id = 1127 } name = "Izumo" type = battlecruiser model = 0 strength = 20 experience = 20 }
		division = { id = { type = 13016 id = 1128 } name = "Iwate" type = battlecruiser model = 0 strength = 20 experience = 20 }
		division = { id = { type = 13016 id = 1131 } name = "Kasuga" type = battlecruiser model = 0 strength = 20 experience = 20 }
		division = { id = { type = 13016 id = 1201 } name = "Tsushima" type = light_cruiser model = 0 strength = 20 experience = 20 }
		division = { id = { type = 13016 id = 1132 } name = "Yodo" type = d_09 model = 0 strength = 50 experience = 20 }
		division = { id = { type = 13016 id = 1138 } name = "Amatsukaze" type = destroyer model = 1 strength = 20 experience = 20 }
		division = { id = { type = 13016 id = 1139 } name = "Hamakaze" type = destroyer model = 1 strength = 20 experience = 20 }
		division = { id = { type = 13016 id = 1140 } name = "Isokaze" type = destroyer model = 1 strength = 20 experience = 20 }
		division = { id = { type = 13016 id = 1071 } name = "Tokitsukaze" type = destroyer model = 1 strength = 20 experience = 20 }
	}

navalunit = {
	id = { type = 13016 id = 1061 }
	name = "13. Kaigun"
	location = 1552 #Tokyo
	base = 1552 #Tokyo
		division = { id = { type = 13016 id = 1062 } name = "Kaga" type = carrier model = 0 extra = cag brigade_model = 0 experience = 20 }
	}

navalunit = {
	id = { type = 13016 id = 1063 }
	name = "14. Kaigun"
	location = 1554 #Hiroshima
	base = 1554 #Hiroshima
		division = { id = { type = 13016 id = 1064 } name = "Hosho" type = light_carrier model = 1 extra = light_cag strength = 75 experience = 20 } #in dock for repairs until April 36
		division = { id = { type = 13016 id = 1199 } name = "Ryujo" type = light_carrier model = 2 extra = light_cag experience = 20 }
		division = { id = { type = 13016 id = 1060 } name = "Notoro" type = escort_carrier model = 0 experience = 20 }
		division = { id = { type = 13016 id = 1072 } name = "Kamoi" type = escort_carrier model = 1 experience = 20 }
		division = { id = { type = 13016 id = 1142 } name = "Fumizuki" type = destroyer model = 2 experience = 20 }
		division = { id = { type = 13016 id = 1143 } name = "Kikuzuki" type = destroyer model = 2 experience = 20 }
		division = { id = { type = 13016 id = 1144 } name = "Mikazuki" type = destroyer model = 2 experience = 20 }
		division = { id = { type = 13016 id = 1145 } name = "Minatsuki" type = destroyer model = 2 experience = 20 }
		division = { id = { type = 13016 id = 1146 } name = "Mochizuki" type = destroyer model = 2 experience = 20 }
		division = { id = { type = 13016 id = 1147 } name = "Nagatsuki" type = destroyer model = 2 experience = 20 }
		division = { id = { type = 13016 id = 1148 } name = "Satsuki" type = destroyer model = 2 experience = 20 }
		division = { id = { type = 13016 id = 1149 } name = "Yuzuki" type = destroyer model = 2 experience = 20 }
		division = { id = { type = 13016 id = 1150 } name = "Kawakaze" type = destroyer model = 1 experience = 20 }
	}

navalunit = {
	id = { type = 13016 id = 1065 }
	name = "15. Kaigun"
	location = 1553 #Osaka
	base = 1553 #Osaka
		division = { id = { type = 13016 id = 1066 } name = "Kashi" type = destroyer model = 1 experience = 20 }
		division = { id = { type = 13016 id = 1067 } name = "Hinoki" type = destroyer model = 1 experience = 20 }
		division = { id = { type = 13016 id = 1068 } name = "Yanagi" type = destroyer model = 1 experience = 20 }
		division = { id = { type = 13016 id = 1141 } name = "Momo" type = destroyer model = 1 experience = 20 }
		division = { id = { type = 13016 id = 1069 } name = "Enoki" type = destroyer model = 1 experience = 20 }
		division = { id = { type = 13016 id = 1070 } name = "Nara" type = destroyer model = 1 experience = 20 }
		division = { id = { type = 13016 id = 1800 } name = "Kashino" type = transport model = 0 experience = 20 }
		division = { id = { type = 13016 id = 1801 } name = "Mamiya" type = transport model = 0 experience = 20 }
		division = { id = { type = 13016 id = 1802 } name = "Nozaki" type = transport model = 1 experience = 20 }
		division = { id = { type = 13016 id = 1803 } name = "Kinesaki" type = transport model = 1 experience = 20 }
		division = { id = { type = 13016 id = 1804 } name = "Kurasaki" type = transport model = 1 experience = 20 }
		division = { id = { type = 13016 id = 1805 } name = "Settsu" type = transport model = 0 experience = 20 }
		division = { id = { type = 13016 id = 1501 } name = "Urakaze" type = destroyer model = 1 experience = 20 }
		division = { id = { type = 13016 id = 1503 } name = "Minekaze" type = destroyer model = 2 experience = 20 }
		division = { id = { type = 13016 id = 1504 } name = "Sawakaze" type = destroyer model = 2 experience = 20 }
		division = { id = { type = 13016 id = 1505 } name = "Okikaze" type = destroyer model = 2 experience = 20 }
		division = { id = { type = 13016 id = 1506 } name = "Hakaze" type = destroyer model = 2 experience = 20 }
		division = { id = { type = 13016 id = 1507 } name = "Yakaze " type = destroyer model = 2 experience = 20 }
		division = { id = { type = 13016 id = 1508 } name = "Nadakaze" type = destroyer model = 2 experience = 20 }
	}

navalunit = {
	id = { type = 13016 id = 1078 }
	name = "16. Kaigun"
	location = 1553 #Osaka
	base = 1553 #Osaka
		division = { id = { type = 13016 id = 1079 } name = "Shimakaze" type = destroyer model = 2 experience = 20 }
		division = { id = { type = 13016 id = 1080 } name = "Akikaze" type = destroyer model = 2 experience = 20 }
		division = { id = { type = 13016 id = 1081 } name = "Shiokaze" type = destroyer model = 2 experience = 20 }
		division = { id = { type = 13016 id = 1082 } name = "Yukaze" type = destroyer model = 2 experience = 20 }
		division = { id = { type = 13016 id = 1083 } name = "Hokaze" type = destroyer model = 2 experience = 20 }
		division = { id = { type = 13016 id = 1084 } name = "Tachikaze" type = destroyer model = 2 experience = 20 }
		division = { id = { type = 13016 id = 1085 } name = "Nokaze" type = destroyer model = 2 experience = 20 }
		division = { id = { type = 13016 id = 1086 } name = "Namikaze" type = destroyer model = 2 experience = 20 }
		division = { id = { type = 13016 id = 1087 } name = "Numakaze" type = destroyer model = 2 experience = 20 }
		division = { id = { type = 13016 id = 1088 } name = "Kaya" type = destroyer model = 1 experience = 20 }
		division = { id = { type = 13016 id = 1509 } name = "Nire" type = destroyer model = 1 experience = 20 }
		division = { id = { type = 13016 id = 1510 } name = "Nashi" type = destroyer model = 1 experience = 20 }
		division = { id = { type = 13016 id = 1511 } name = "Take" type = destroyer model = 1 experience = 20 }
		division = { id = { type = 13016 id = 1512 } name = "Kaki" type = destroyer model = 1 experience = 20 }
		division = { id = { type = 13016 id = 1513 } name = "Kuri" type = destroyer model = 1 experience = 20 }
		division = { id = { type = 13016 id = 1514 } name = "Tsuga" type = destroyer model = 1 experience = 20 }
		division = { id = { type = 13016 id = 1515 } name = "Fuji" type = destroyer model = 1 experience = 20 }
		division = { id = { type = 13016 id = 1516 } name = "Kiku" type = destroyer model = 1 experience = 20 }
		division = { id = { type = 13016 id = 1517 } name = "Aoi" type = destroyer model = 1 experience = 20 }
		division = { id = { type = 13016 id = 1518 } name = "Hagi" type = destroyer model = 1 experience = 20 }
		division = { id = { type = 13016 id = 1519 } name = "Susuki" type = destroyer model = 1 experience = 20 }
		division = { id = { type = 13016 id = 1520 } name = "Ashi" type = destroyer model = 1 experience = 20 }
		division = { id = { type = 13016 id = 1521 } name = "Tsuta" type = destroyer model = 1 experience = 20 }
		division = { id = { type = 13016 id = 1522 } name = "Hasu" type = destroyer model = 1 experience = 20 }
		division = { id = { type = 13016 id = 1523 } name = "Hishi" type = destroyer model = 1 experience = 20 }
		division = { id = { type = 13016 id = 1524 } name = "Sumire" type = destroyer model = 1 experience = 20 }
	}

navalunit = {
	name = "18. Kaigun"
	id = { type = 13016 id = 1089 }
	location = 1552 #Tokyo
	base = 1552 #Tokyo
		division = { id = { type = 13016 id = 1090 } name = "Yomogi" type = destroyer model = 1 experience = 20 }
		division = { id = { type = 13016 id = 1091 } name = "Tade" type = destroyer model = 1 experience = 20 }
		division = { id = { type = 13016 id = 1092 } name = "Wakatake" type = destroyer model = 1 experience = 20 }
		division = { id = { type = 13016 id = 1525 } name = "Kuretake" type = destroyer model = 1 experience = 20 }
		division = { id = { type = 13016 id = 1526 } name = "Sanae" type = destroyer model = 1 experience = 20 }
		division = { id = { type = 13016 id = 1527 } name = "Asagao" type = destroyer model = 1 experience = 20 }
		division = { id = { type = 13016 id = 1528 } name = "Yugao" type = destroyer model = 1 experience = 20 }
		division = { id = { type = 13016 id = 1529 } name = "Fuyo" type = destroyer model = 1 experience = 20 }
		division = { id = { type = 13016 id = 1530 } name = "Karukaya" type = destroyer model = 1 experience = 20 }
		division = { id = { type = 13016 id = 1565 } name = "Usugumo" type = d_09 model = 3 experience = 20 }
		division = { id = { type = 13016 id = 1566 } name = "Shirakumo" type = d_09 model = 3 experience = 20 }
		division = { id = { type = 13016 id = 1567 } name = "Isonami" type = d_09 model = 3 experience = 20 }
		division = { id = { type = 13016 id = 1568 } name = "Shirayuki" type = d_09 model = 3 experience = 20 }
		division = { id = { type = 13016 id = 1569 } name = "Hatsuyuki" type = d_09 model = 3 experience = 20 }
		division = { id = { type = 13016 id = 1570 } name = "Miyuki" type = d_09 model = 3 experience = 20 }
		division = { id = { type = 13016 id = 1571 } name = "Murakumo" type = d_09 model = 3 experience = 20 }
		division = { id = { type = 13016 id = 1572 } name = "Uranami" type = d_09 model = 3 experience = 20 }
		division = { id = { type = 13016 id = 1573 } name = "Shikinami" type = d_09 model = 3 experience = 20 }
	}
	
navalunit = {
	name = "19. Kaigun"
	id = { type = 13016 id = 1097 }
	location = 1552 #Tokyo
	base = 1552 #Tokyo
		division = { id = { type = 13016 id = 1098 } name = "Kamikaze" type = destroyer model = 2 experience = 20 }
		division = { id = { type = 13016 id = 1099 } name = "Asakaze" type = destroyer model = 2 experience = 20 }
		division = { id = { type = 13016 id = 1100 } name = "Harukaze" type = destroyer model = 2 experience = 20 }
		division = { id = { type = 13016 id = 1532 } name = "Matsukaze" type = destroyer model = 2 experience = 20 }
		division = { id = { type = 13016 id = 1533 } name = "Hatakaze" type = destroyer model = 2 experience = 20 }
		division = { id = { type = 13016 id = 1534 } name = "Oite" type = destroyer model = 2 experience = 20 }
		division = { id = { type = 13016 id = 1535 } name = "Hayate" type = destroyer model = 2 experience = 20 }
		division = { id = { type = 13016 id = 1536 } name = "Asanagi" type = destroyer model = 2 experience = 20 }
		division = { id = { type = 13016 id = 1537 } name = "Yunagi" type = destroyer model = 2 experience = 20 }
		division = { id = { type = 13016 id = 1559 } name = "Mutsuki" type = destroyer model = 2 experience = 20 }
		division = { id = { type = 13016 id = 1560 } name = "Kisaragi" type = destroyer model = 2 experience = 20 }
		division = { id = { type = 13016 id = 1561 } name = "Yayoi" type = destroyer model = 2 experience = 20 }
		division = { id = { type = 13016 id = 1562 } name = "Uzuki" type = destroyer model = 2 experience = 20 }
		division = { id = { type = 13016 id = 1563 } name = "Fubuki" type = d_09 model = 3 experience = 20 }
		division = { id = { type = 13016 id = 1564 } name = "Shinonome" type = d_09 model = 3 experience = 20 }
		division = { id = { type = 13016 id = 1137 } name = "Shirakumo" type = d_09 model = 3 experience = 20 }
}

navalunit = {
	name = "20. Kaigun"
	id = { type = 13016 id = 1105 }
	location = 1554 #Hiroshima
	base = 1554 #Hiroshima
		division = { id = { type = 13016 id = 1106 } name = "Manshu" type = transport model = 0 }
		division = { id = { type = 13016 id = 1107 } name = "Hayasui" type = transport model = 0 }
		division = { id = { type = 13016 id = 1108 } name = "Kamoi" type = transport model = 0 }
		division = { id = { type = 13016 id = 1109 } name = "Ondo" type = transport model = 0 }
	}

navalunit = {
	id = { type = 13016 id = 1574 }
	name = "24. Kaigun"
	location = 1554 #Hiroshima
	base = 1554 #Hiroshima
		division = { id = { type = 13016 id = 1575 } name = "Ayanami" type = d_09 model = 3 experience = 20 }
		division = { id = { type = 13016 id = 1576 } name = "Asagiri" type = d_09 model = 3 experience = 20 }
		division = { id = { type = 13016 id = 1577 } name = "Sagiri" type = d_09 model = 3 experience = 20 }
		division = { id = { type = 13016 id = 1578 } name = "Yugiri" type = d_09 model = 3 experience = 20 }
		division = { id = { type = 13016 id = 1579 } name = "Amagiri" type = d_09 model = 3 experience = 20 }
		division = { id = { type = 13016 id = 1580 } name = "Oboro" type = d_09 model = 3 experience = 20 }
		division = { id = { type = 13016 id = 1581 } name = "Akebono" type = d_09 model = 3 experience = 20 }
		division = { id = { type = 13016 id = 1820 } name = "Sazanami" type = d_09 model = 3 experience = 20 }
		division = { id = { type = 13016 id = 1583 } name = "Ushio" type = d_09 model = 3 experience = 20 }
		division = { id = { type = 13016 id = 1584 } name = "Akatsuki" type = d_09 model = 3 experience = 20 }
		division = { id = { type = 13016 id = 1585 } name = "Hibiki" type = d_09 model = 3 experience = 20 }
		division = { id = { type = 13016 id = 1586 } name = "Ikazuchi" type = d_09 model = 3 experience = 20 }
		division = { id = { type = 13016 id = 1587 } name = "Inazuma" type = d_09 model = 3 experience = 20 }
		division = { id = { type = 13016 id = 1136 } name = "Isonami" type = d_09 model = 3 experience = 20 }
		division = { id = { type = 13016 id = 1588 } name = "Hatsuharu" type = destroyer model = 2 experience = 20 }
		division = { id = { type = 13016 id = 1589 } name = "Nenohi" type = destroyer model = 2 experience = 20 }
		division = { id = { type = 13016 id = 1590 } name = "Hatsushimo" type = destroyer model = 2 experience = 20 }
		division = { id = { type = 13016 id = 1591 } name = "Wakaba" type = destroyer model = 2 experience = 20 }
		division = { id = { type = 13016 id = 1592 } name = "Yugure" type = destroyer model = 2 experience = 20 }
		division = { id = { type = 13016 id = 1593 } name = "Ariake" type = destroyer model = 2 experience = 20 }

	}

navalunit = {
	id = { type = 13016 id = 1110 }
	name = "21. Kaigun"
	location = 1552 #Tokyo
	base = 1552 #Tokyo
		division = { id = { type = 13016 id = 1111 } name = "I-51" type = d_08 model = 0 experience = 5 }
		division = { id = { type = 13016 id = 1112 } name = "I-52" type = d_08 model = 0 experience = 5 }
		division = { id = { type = 13016 id = 1538 } name = "I-53" type = d_08 model = 0 experience = 5 }
		division = { id = { type = 13016 id = 1539 } name = "I-54" type = d_08 model = 0 experience = 5 }
		division = { id = { type = 13016 id = 1540 } name = "I-55" type = d_08 model = 0 experience = 5 }
		division = { id = { type = 13016 id = 1541 } name = "I-56" type = d_08 model = 0 experience = 5 }
	}

navalunit = {
	id = { type = 13016 id = 1113 }
	name = "22. Kaigun"
	location = 1554 #Hiroshima
	base = 1554 #Hiroshima
		division = { id = { type = 13016 id = 1114 } name = "I-57" type = d_08 model = 0 experience = 5 }
		division = { id = { type = 13016 id = 1152 } name = "I-58" type = d_08 model = 0 experience = 5 }
		division = { id = { type = 13016 id = 1115 } name = "I-59" type = d_08 model = 0 experience = 5 }
		division = { id = { type = 13016 id = 1542 } name = "I-60" type = d_08 model = 0 experience = 5 }
		division = { id = { type = 13016 id = 1544 } name = "I-61" type = d_08 model = 0 experience = 5 }
		division = { id = { type = 13016 id = 1545 } name = "I-62" type = d_08 model = 0 experience = 5 }
		division = { id = { type = 13016 id = 1543 } name = "I-63" type = d_08 model = 0 experience = 5 }
		division = { id = { type = 13016 id = 1600 } name = "I-6"  type = d_08 model = 1 experience = 5 extra = floatplane }
		division = { id = { type = 13016 id = 1603 } name = "I-21" type = submarine model = 1 experience = 5 }
		division = { id = { type = 13016 id = 1604 } name = "I-22" type = submarine model = 1 experience = 5 }
		division = { id = { type = 13016 id = 1605 } name = "I-23" type = submarine model = 1 experience = 5 }
		division = { id = { type = 13016 id = 1151 } name = "I-24" type = submarine model = 1 experience = 5 }
	}

navalunit = {
	id = { type = 13016 id = 1606 }
	name = "25. Kaigun"
	location = 1554 #Hiroshima
	base = 1554 #Hiroshima
		division = { id = { type = 13016 id = 1155 } name = "RO-17" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 13016 id = 1156 } name = "RO-18" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 13016 id = 1157 } name = "RO-19" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 13016 id = 1158 } name = "RO-25" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 13016 id = 1159 } name = "RO-26" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 13016 id = 1160 } name = "RO-27" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 13016 id = 1161 } name = "RO-28" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 13016 id = 1162 } name = "RO-29" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 13016 id = 1163 } name = "RO-30" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 13016 id = 1164 } name = "RO-31" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 13016 id = 1165 } name = "RO-32" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 13016 id = 1607 } name = "RO-33" type = nuclear_submarine model = 2 experience = 5 }
		division = { id = { type = 13016 id = 1166 } name = "RO-51" type = submarine model = 0 experience = 5 }
		division = { id = { type = 13016 id = 1167 } name = "RO-53" type = submarine model = 0 experience = 5 }
		division = { id = { type = 13016 id = 1168 } name = "RO-54" type = submarine model = 0 experience = 5 }
		division = { id = { type = 13016 id = 1169 } name = "RO-55" type = submarine model = 0 experience = 5 }
		division = { id = { type = 13016 id = 1170 } name = "RO-56" type = submarine model = 0 experience = 5 }
		division = { id = { type = 13016 id = 1171 } name = "RO-57" type = submarine model = 0 experience = 5 }
		division = { id = { type = 13016 id = 1172 } name = "RO-58" type = submarine model = 0 experience = 5 }
		division = { id = { type = 13016 id = 1173 } name = "RO-59" type = submarine model = 0 experience = 5 }
		division = { id = { type = 13016 id = 1609 } name = "RO-60" type = submarine model = 0 experience = 5 }
		division = { id = { type = 13016 id = 1610 } name = "RO-61" type = submarine model = 0 experience = 5 }
		division = { id = { type = 13016 id = 1611 } name = "RO-62" type = submarine model = 0 experience = 5 }
		division = { id = { type = 13016 id = 1612 } name = "RO-63" type = submarine model = 0 experience = 5 }
		division = { id = { type = 13016 id = 1613 } name = "RO-64" type = submarine model = 0 experience = 5 }
		division = { id = { type = 13016 id = 1614 } name = "RO-65" type = submarine model = 0 experience = 5 }
		division = { id = { type = 13016 id = 1615 } name = "RO-66" type = submarine model = 0 experience = 5 }
		division = { id = { type = 13016 id = 1616 } name = "RO-67" type = submarine model = 0 experience = 5 }
		division = { id = { type = 13016 id = 1617 } name = "RO-68" type = submarine model = 0 experience = 5 }
	}

navalunit = {
	id = { type = 13016 id = 1116 }
	name = "23. Kaigun"
	location = 1560 # Nagasaki
	base = 1560 # Nagasaki
		division = { id = { type = 13016 id = 1117 } name = "I-64" type = d_08 model = 0 experience = 5 }
		division = { id = { type = 13016 id = 1118 } name = "I-65" type = submarine model = 2 experience = 5 }
		division = { id = { type = 13016 id = 1119 } name = "I-66" type = submarine model = 2 experience = 5 }
		division = { id = { type = 13016 id = 1120 } name = "I-67" type = submarine model = 2 experience = 5 }
		division = { id = { type = 13016 id = 1546 } name = "I-68" type = submarine model = 2 experience = 5 }
		division = { id = { type = 13016 id = 1547 } name = "I-69" type = submarine model = 2 experience = 5 }
		division = { id = { type = 13016 id = 1548 } name = "I-70" type = submarine model = 2 experience = 5 }
		division = { id = { type = 13016 id = 1549 } name = "I-71" type = d_08 model = 0 experience = 5 }
		division = { id = { type = 13016 id = 1552 } name = "I-1" type = d_08 model = 1 experience = 5 }
		division = { id = { type = 13016 id = 1553 } name = "I-2" type = d_08 model = 1 experience = 5 }
		division = { id = { type = 13016 id = 1554 } name = "I-3" type = d_08 model = 1 experience = 5 }
		division = { id = { type = 13016 id = 1555 } name = "I-4" type = d_08 model = 1 experience = 5 }
		division = { id = { type = 13016 id = 1556 } name = "I-5" type = d_08 model = 1 experience = 5 extra = floatplane }
		}

#### Under division_development


convoy_development = {
        id = { type = 13016 id = 1400 }
        cost = 0.1
        size = 99
        type = transports
        date  = {  year = 1964 }
		unitcost = yes
        }
		
#brigade_development = {
#        id = { type = 13016 id = 1401 }
#        cost = 0.5
#        size = 10
#        type = anti_air
#		model = 0
#        date  = {  year = 1937 }
#		unitcost = yes
#        }
		
brigade_development = {
        id = { type = 13016 id = 1402 }
        name = "Torpedoes 1936"
		cost = 0.05
        size = 20
        type = naval_torpedoes_s
		model = 0
        date  = {  year = 1941 }
		unitcost = yes
        }
		
brigade_development = {
        id = { type = 13016 id = 1403 }
        name = "Torpedoes 1936"
		cost = 0.05
        size = 20
        type = naval_torpedoes_s
		model = 0
        date  = {  year = 1941 }
		unitcost = yes
        }
		
brigade_development = {
        id = { type = 13016 id = 1404 }
        name = "Torpedoes 1936"
		cost = 0.05
        size = 20
        type = naval_torpedoes_s
		model = 0
        date  = {  year = 1941 }
		unitcost = yes
        }
		
brigade_development = {
        id = { type = 13016 id = 1405 }
        name = "Torpedoes 1936"
		cost = 0.05
        size = 20
        type = naval_torpedoes_s
		model = 0
        date  = {  year = 1941 }
		unitcost = yes
        }
		
brigade_development = {
        id = { type = 13016 id = 1406 }
        name = "Torpedoes 1936"
		cost = 0.05
        size = 20
        type = naval_torpedoes_s
		model = 0
        date  = {  year = 1941 }
		unitcost = yes
        }
		
brigade_development = {
        id = { type = 13016 id = 1407 }
        name = "Torpedoes 1936"
		cost = 0.05
        size = 20
        type = naval_torpedoes_s
		model = 0
        date  = {  year = 1941 }
		unitcost = yes
        }
		
brigade_development = {
        id = { type = 13016 id = 1408 }
        name = "Floatplane 1930"
		cost = 0.02
        size = 20
        type = floatplane
		model = 0
        date  = {  year = 1940 }
		unitcost = yes
        }
		
brigade_development = {
        id = { type = 13016 id = 1409 }
        name = "Capital Improved Hull 1936"
		cost = 0.04
        size = 10
        type = naval_improved_hull_l
		model = 0
        date  = {  year = 1941 }
		unitcost = yes
        }
		
brigade_development = {
        id = { type = 13016 id = 1410 }
        name = "Improved Hull 1936"
		cost = 0.2
        size = 10
        type = naval_improved_hull_s
		model = 0
        date  = {  year = 1939 }
		unitcost = yes
        }

division_development = {  #Reconstruction of the Akagi; price to be fixed later in OOB rework
	name = "Akagi"
	type = carrier
	extra = cag
	model = 0
	cost = 0.5 #5
	new_model = no 
	unitcost = yes
	id = { type = 13016 id = 1102 }
	date = { year = 1938 month = august day = 29 }
	}

division_development = {
	name = "Soryu"
	type = carrier
	extra = cag
	model = 1
	cost = 0.4 #4
	new_model = no 
	unitcost = yes
	id = { type = 13016 id = 1104 }
	date = { year = 1937 month = december day = 28 }
	}

division_development = {  
	name = "Chitose"
	type = escort_carrier
	model = 3
	cost = 0.25 #2.5
	new_model = no 
	unitcost = yes
	id = { type = 13016 id = 1058 }
	date = { year = 1936 month = november day = 28 }
	}
	
division_development = {  
	name = "Chiyoda"
	type = escort_carrier
	model = 3
	cost = 0.25 #2.5
	new_model = no 
	unitcost = yes
	id = { type = 13016 id = 1059 }
	date = { year = 1938 month = july day = 25 }
	}

division_development = {
	name = "Chikuma"
	type = heavy_cruiser
	model = 7
	cost = 0.2 #2
	new_model = no 
	unitcost = yes
	id = { type = 13016 id = 1129 }
	date = { year = 1939 month = may day = 19 }
	}
	
division_development = {
	name = "Tone"
	type = heavy_cruiser
	model = 7
	cost = 0.2 #2
	new_model = no 
	unitcost = yes
	id = { type = 13016 id = 1130 }
	date = { year = 1938 month = november day = 19 }
	}

division_development = {
	name = "Suzuya"
	type = light_cruiser
	model = 4
	cost = 0.2 #2
	new_model = no 
	unitcost = yes
	id = { type = 13016 id = 1122 }
	date = { year = 1937 month = october day = 29 }
	}

division_development = {
	name = "Kumano"
	type = light_cruiser
	model = 4
	cost = 0.2 #2
	new_model = no 
	unitcost = yes
	id = { type = 13016 id = 1123 }
	date = { year = 1937 month = october day = 29 }
	}

##### Destroyers #####

division_development = {
	name = "Shiratsuyu"
	type = destroyer
	model = 3
	cost = 0.06 #0.6
	new_model = no 
	unitcost = yes
	id = { type = 13016 id = 1740 }
	date = { year = 1936 month = august day = 20 }
	}

division_development = {
	name = "Shigure"
	type = destroyer
	model = 3
	cost = 0.06 #0.6
	new_model = no 
	unitcost = yes
	id = { type = 13016 id = 1793 }
	date = { year = 1936 month = september day = 7 }
	}

division_development = {  # reduced cost due to time
	name = "Murasame"
	type = destroyer
	model = 3
	cost = 0.06 #0.6
	new_model = no 
	unitcost = yes
	id = { type = 13016 id = 1795 }
	date = { year = 1937 month = january day = 7 }
	}

division_development = {
	name = "Yudachi"
	type = destroyer
	model = 3
	cost = 0.06 #0.6
	new_model = no 
	unitcost = yes
	id = { type = 13016 id = 1796 }
	date = { year = 1937 month = january day = 7 }
	}

division_development = {
	name = "Samidare"
	type = destroyer
	model = 3
	cost = 0.06 #0.6
	new_model = no 
	unitcost = yes
	id = { type = 13016 id = 1294 }
	date = { year = 1937 month = january day = 29 }
	}

division_development = {  # reduced cost due to time
	name = "Kawakaze"
	type = destroyer
	model = 3
	cost = 0.06 #0.6
	new_model = no 
	unitcost = yes
	id = { type = 13016 id = 1291 }
	date = { year = 1937 month = april day = 29 }
	}

division_development = {  # reduced cost due to time
	name = "Umikaze"
	type = destroyer
	model = 3
	cost = 0.06 #0.6
	new_model = no 
	unitcost = yes
	id = { type = 13016 id = 1290 }
	date = { year = 1937 month = may day = 29 }
	}

division_development = {
	name = "Yamakaze"
	type = destroyer
	model = 3
	cost = 0.06 #0.6
	new_model = no 
	unitcost = yes
	id = { type = 13016 id = 1121 }
	date = { year = 1937 month = june day = 29 }
	}

division_development = {
	name = "Harusame"
	type = destroyer
	model = 3
	cost = 0.06 #0.6
	new_model = no 
	unitcost = yes
	id = { type = 13016 id = 1293 }
	date = { year = 1937 month = august day = 26 }
	}

division_development = { # reduced cost due to time
	name = "Suzukaze"
	type = destroyer
	model = 3
	cost = 0.06 #0.6
	new_model = no 
	unitcost = yes
	id = { type = 13016 id = 1289 }
	date = { year = 1937 month = august day = 29 }
	}
	
division_development = { # reduced cost due to time
	name = "Arashio"
	type = destroyer
	model = 3
	cost = 0.06 #0.6
	new_model = no 
	unitcost = yes
	id = { type = 13016 id = 1133 }
	date = { year = 1937 month = december day = 29 }
	}
	
division_development = { # reduced cost due to time
	name = "Asahio"
	type = destroyer
	model = 3
	cost = 0.06 #0.6
	new_model = no 
	unitcost = yes
	id = { type = 13016 id = 1134 }
	date = { year = 1937 month = august day = 29 }
	}
	
division_development = { # reduced cost due to time
	name = "Michishio"
	type = destroyer
	model = 3
	cost = 0.06 #0.6
	new_model = no 
	unitcost = yes
	id = { type = 13016 id = 1135 }
	date = { year = 1937 month = october day = 29 }
	}

division_development = { 
	name = "I-7"
	type = d_08
	extra = floatplane
	model = 1
	cost = 0.05 #0.5
	new_model = no 
	unitcost = yes
	id = { type = 13016 id = 1601 }
	date = { year = 1937 month = march day = 29 }
	}
	
division_development = { 
	name = "I-8"
	type = d_08
	extra = floatplane
	model = 1
	cost = 0.05 #0.5
	new_model = no 
	unitcost = yes
	id = { type = 13016 id = 1602 }
	date = { year = 1938 month = december day = 4 }
	}

division_development = { 
	name = "I-72"
	type = d_08
	model = 0
	cost = 0.05 #0.5
	new_model = no 
	unitcost = yes
	id = { type = 13016 id = 1550 }
	date = { year = 1937 month = january day = 6 }
	}
	
division_development = { 
	name = "I-73"
	type = d_08
	model = 0
	cost = 0.05 #0.5
	new_model = no 
	unitcost = yes
	id = { type = 13016 id = 1551 }
	date = { year = 1937 month = january day = 6 }
	}
	
division_development = { 
	name = "I-74"
	type = d_08
	model = 0
	cost = 0.05 #0.5
	new_model = no 
	unitcost = yes
	id = { type = 13016 id = 1153 }
	date = { year = 1938 month = august day = 14 }
	}
	
division_development = { 
	name = "I-75"
	type = d_08
	model = 0
	cost = 0.05 #0.5
	new_model = no 
	unitcost = yes
	id = { type = 13016 id = 1154 }
	date = { year = 1938 month = december day = 17 }
	}
	
division_development = { 
	name = "RO-34"
	type = nuclear_submarine
	model = 2
	cost = 0.04 #0.4
	new_model = no 
	unitcost = yes
	id = { type = 13016 id = 1608 }
	date = { year = 1937 month = may day = 29 }
	}
	
} # End File
