#####################
# Country main data #
#####################

province = { id = 535 anti_air = 2 naval_base = { size = 7 current_size = 7 } air_base = { size = 4 current_size = 4 }} #Murmansk
province = { id = 542 anti_air = 2 naval_base = { size = 3 current_size = 3 } air_base = { size = 4	current_size = 4 }} #Archangelsk
province = { id = 553 anti_air = 2 naval_base = { size = 10	current_size = 10 }	air_base = { size = 10 current_size = 10 }} #Leningrad
province = { id = 599 anti_air = 2 air_base = {	size = 10 current_size = 10 }} #Minsk
province = { id = 636 anti_air = 2 air_base = {	size = 4 current_size = 4 }} #Kharkov
province = { id = 641 anti_air = 3 naval_base = { size = 10 current_size = 10 }	air_base = { size = 6 current_size = 6 }} #Sevastopol
province = { id = 708 anti_air = 2 naval_base = { size = 3 current_size = 3 } air_base = { size = 4 current_size = 4 }} #Batum/ Kutaisi
province = { id = 713 air_base = { size = 4 current_size = 4 }} #Baku
province = { id = 1174 air_base = { size = 2 current_size = 2 }} #Kuybshevka-Vostochnaya
province = { id = 1148 air_base = { size = 2 current_size = 2 }} #Tomsk
province = { id = 664 air_base = { size = 2 current_size = 2 }} #Naberezhnye Chelny
province = { id = 706 anti_air = 2 air_base = { size = 4 current_size = 4 }} #Astrakhan
province = { id = 666 air_base = { size = 3 current_size = 3 }} #Engels
province = { id = 601 air_base = { size = 2	current_size = 2 }} #Gomel
province = { id = 1191 anti_air = 2 naval_base = { size = 10 current_size = 10 } air_base = { size = 10	current_size = 10 }} #Vladivostok
province = { id = 1541 anti_air = 2 naval_base = { size = 3	current_size = 3 }} #Oha
province = { id = 1186 anti_air = 2 naval_base = { size = 1	current_size = 1 } air_base = {	size = 1 current_size = 1 }} #Okhotsk
province = { id = 1187 air_base = { size = 1 current_size = 1 }} #Komsomolsk-na-Amure
province = { id = 1179 air_base = { size = 1 current_size = 1 }} #Yakutsk
province = { id = 1157 air_base = { size = 1 current_size = 1 }} #Kansk
province = { id = 1138 air_base = { size = 1 current_size = 1 }} #Omsk
province = { id = 1132 air_base = { size = 1 current_size = 1 }} #Chelyabinsk
province = { id = 663 air_base = { size = 8 current_size = 8 }} #Stalingrad
province = { id = 680 air_base = { size = 4	current_size = 4 }} #Gorkij
province = { id = 617 air_base = { size = 8	current_size = 8 }} #Kiev
province = { id = 589 air_base = { size = 8	current_size = 8 }} #Smolensk
province = { id = 566 air_base = { size = 6	current_size = 6 }} #Pskov
province = { id = 572 air_base = { size = 10	current_size = 10 }} #Moscow
province = { id = 581 air_base = { size = 5	current_size = 5 }} #Orel
province = { id = 560 air_base = { size = 5	current_size = 5 }} #Novgorod
province = { id = 1162 air_base = { size = 5 current_size = 5 }} #Irkutsk
province = { id = 630 air_base = { size = 2 current_size = 2 }} #Zaporozhye
province = { id = 604 air_base = { size = 5 current_size = 5 }} #Kursk
province = { id = 569 air_base = { size = 2 current_size = 2 }} #Kalinin
province = { id = 626 air_base = { size = 2 current_size = 2 } naval_base = { size = 1 current_size = 1 } } #Odessa
province = { id = 622 naval_base = { size = 1 current_size = 1 } } #Nikolayiv

#Forts
province = { id = 553	landfort = 5 coastalfort = 5 anti_air = 4 }#Leningrad
province = { id = 572	landfort = 5 anti_air = 4 }#Moscow
province = { id = 663	landfort = 5 anti_air = 3 }#Stalingrad
province = { id = 641	landfort = 3 coastalfort = 5 }#Sevestapol
province = { id = 638	landfort = 3 }#Simferopol
province = { id = 1191	landfort = 1 coastalfort = 3 }#Vladivostok

#Stalin Line
province = { id = 626	landfort = 2 anti_air = 1 }#Odessa
province = { id = 621	landfort = 2 anti_air = 1 }#Tiraspol
province = { id = 619	landfort = 2 }#Mogilev Podolsky
province = { id = 618	landfort = 2 }#Kamenets Podolsky
province = { id = 614	landfort = 2 anti_air = 1 }#Proskurov
province = { id = 597	landfort = 2 anti_air = 1 }#Luban
province = { id = 596	landfort = 2 }#Slutsk
province = { id = 599	landfort = 2 anti_air = 1 }#Minsk
province = { id = 592	landfort = 2 }#Borisov
province = { id = 593	landfort = 2 anti_air = 1 }#Polotsk
province = { id = 564	landfort = 2 anti_air = 1 }#Opochka
province = { id = 566	landfort = 2 anti_air = 1 }#Pskov
province = { id = 550	landfort = 2 anti_air = 1 }#Kingisepp
province = { id = 612	landfort = 2 anti_air = 1 }#Vinnitsa

#Anti Aircraft Batteries
province = { id = 560 anti_air = 1 } #Novgorod
province = { id = 535 anti_air = 2 } #Murmansk
province = { id = 542 anti_air = 2 } #Archangelsk
province = { id = 590 anti_air = 2 } #Vitebsk
province = { id = 589 anti_air = 3 } #Smolensk
province = { id = 599 anti_air = 3 } #Minsk
province = { id = 600 anti_air = 2 } #Mogiljov
province = { id = 588 anti_air = 2 } #Bryansk
province = { id = 576 anti_air = 1 } #Kaluga
province = { id = 594 anti_air = 1 } #Bobrujsk
province = { id = 607 anti_air = 2 } #Chernigov
province = { id = 617 anti_air = 3 } #Kiev
province = { id = 626 anti_air = 3 } #Odessa
province = { id = 630 anti_air = 2 } #Zaporozhye
province = { id = 641 anti_air = 3 } #Sevastopol
province = { id = 636 anti_air = 1 } #Kharkov
province = { id = 644 anti_air = 2 } #Rostov
province = { id = 654 anti_air = 1 } #Voronezh
province = { id = 678 anti_air = 2 } #Vladimir
province = { id = 680 anti_air = 2 } #Nizjnij Novgorod -> hieß Gorky während des Krieges
province = { id = 708 anti_air = 1 } #Batumi/Kutaisi
province = { id = 711 anti_air = 1 } #Yerevan
province = { id = 713 anti_air = 3 } #Baku
province = { id = 668 anti_air = 3 } #Kujbysjev
province = { id = 1134 anti_air = 3 } #Magnitogorsk (Teil von Orenburg)
province = { id = 1191 anti_air = 3 } #Vladivostok

country = {
 tag = SOV

 regular_id = RUS
	intrinsic_gov_type = leninist

	capital = 572

	ai_settings	= { flags = { convoy_gift_on_release = yes } }
	policy = {
		date = { year = 0 month = january day = 0 }
		democratic = 1
		political_left = 10
		freedom = 1
		free_market = 1
		professional_army = 3
		defense_lobby = 6
		interventionism = 4
	}
	
	#headofgovernment       = {  type = 9 id = 4094 } # just here for testing purposes
	
    allowed_divisions = { 
        infantry = yes 
        cavalry = yes 
        bergsjaeger = yes
        motorized = yes
	} 
	
	dormant_leaders = { 10523 10524 } #polish generals in ussr

	#inventions = { 2700061 2700063 2700065 2700066 }
		
	# Resource Reserves
	energy	= 1000 
	metal	= 1000		
	rare_materials = 500	
	oil = 2500	
	supplies = 5000
	money = 30
	
	peacetime_ic_mod = 0.8
	industrial_modifier = 0.85 # Purges +0.05, Molotov-Ribbentrop-pact +0.05, Great Patriotic War +0.05
	manpower = 50
	dissent = 0
	
nationalprovinces = {  
    1191 #Vladivostok
	1193 #Nakhodka
	1192 #Semyonovka
	1196 #Nikolsk-Ussurysky
	1195 #Tetyukhe
	1190 #Khabarovsk
	1187 #Komsomolsk-on-Amur
	1188 #Elban
	1175 #Birobidzhan
	1174 #Kuybyshevka-Vostochnaya
	1541 #Oha
	1189 #Nikolayevsk-on-Amur
	1176 #Blagoveshchensk
	1180 #Verkhoyansk
	1181 #Magadan
	1182 #Anadyr
	1183 #Palana
	1184 #Petropavlovsk-Kamchatsky
	1194 #Lesozavodsk
	1179 #Yakutsk
	1178 #Nezametny
	1168 #Borzya
	1177 #Nyurba
	1169 #Chita
	1164 #Ust-Kut
	1163 #Bodaybo
	1162 #Irkutsk
	1167 #Ulan-Ude
	1166 #Cheremkhovo
	1186 #Okhotsk
    1165 #Bratsk
	1150 #Ostyako-Vogulsk
	1154 #Surgut
	507 #Ust-Kamenogorosk
	505 #Sar
    498 #Pavlodar
    1153 #Uray
	1152 #Salekhard
	1145 #Stalinsk
	1146 #Oyrot-Tura
	1147 #Abakan
	1158 #Minusinsk
	1156 #Krasnoyarsk
    1157 #Kansk
	1144 #Kemerovo
	1143 #Biysk
	1129 #Vorkuta
	1142 #Novosibirsk
	1140 #Barnaul
	1148 #Tomsk
	685 #Syktyvkar
	1155 #Norilsk
	544 #Kichmensky Gorodok
	546 #Molotovsk
	545 #Velsk
	568 #Solnechnogorsk
	615 #Uman
	625 #Ochakov
	564 #Opochka
	621 #Tiraspol
	588 #Bryansk
	584 #Tula
	500 #Balkhash
	1138 #Omsk
	1139 #Tara
	583 #Efremov
	1136 #Tyumen
	1135 #Tobolsk
	1111 #Fyodorovka
	1110 #Kzyl-Orda
	504 #Alma-Ata
	1112 #Novokazalinsk
	1102 #Nakus
	1101 #Zheleznodorozhny
	1118 #Shevchenko
	502 #Akmolinsk
	501 #Kokchetav
	1151 #Sverdlovsk
	1130 #Berezniki
	1137 #Kurgan
	598 #Rechytsa
	1132 #Chelyabinsk
	1131 #Ufa
	1133 #Orsk
	1115 #Kustanay
	1116 #Derzhavinsk
	503 #Karaganda
	1117 #Chelkar
	1114 #Aktyubinsk
	1113 #Uralsk
	690 #Sterlitamak
	699 #Elista
	632 #Dnepropetrovsk
	592 #Borisov
	687 #Perm
	689 #Solikamsk
	688 #Ukhta
	542 #Arkhangelsk
	686 #Kudymkar
	681 #Kostroma
	543 #Totma
	547 #Kirllov
	538 #Segezha
	539 #Petrozavodsk
	537 #Kem
	536 #Kandalaksha
	534 #Kola
	535 #Murmansk
	706 #Astrakhan
	702 #Grozny
	704 #Makhachkala
	703 #Vladikavkaz
	709 #Tbilisi
	708 #Kutaisi
	710 #Sukhumi
	701 #Nalchik
	696 #Cherkessk
	695 #Sochi
	694 #Novorossiysk
	691 #Krasnodar
	692 #Salsk
	697 #Volgodonsk
	698 #Voroshilovsk
	700 #Khasavyurt
	645 #Konstantinovsk
	659 #Kalach-on-Don
	662 #Kotelnikovo
	661 #Kamyshin
	660 #Volzhsky
	666 #Engel's
	639 #Dzhankoy
	1134 #Orenburg
	665 #Volsk
	669 #Saratov
	658 #Penza
	668 #Kuybyshev
	637 #Yevpatoria
	641 #Sevastopol
	640 #Kerch
	670 #Saransk
	667 #Tolyatti
	675 #Cheboksary
	674 #Zelenodolsk
	672 #Kazan
	664 #Naberezhnye Chelny
	671 #Izhevsk
	673 #Yoshkar-Ola
	684 #Kirov
	663 #Stalingrad
	693 #Maykop
	618 #Kamenets-Podolsky
	655 #Uryupinsk
	642 #Surovikino
	651 #Borisoglebsk
	650 #Tambov
	656 #Ulyanovsk
	638 #Simferopol
	578 #Sasovo
	683 #Arzamas
	682 #Ivanovo
	679 #Murom
	571 #Orekhovo-Zuyevo
	680 #Gorky
	678 #Vladimir
	677 #Yaroslavl
	676 #Rybinsk
	548 #Vologda
	556 #Vytegra
	554 #Kinry
	569 #Kalinini
	572 #Moscow #########
	570 #Zagorsk
	585 #Kozelsk
	574 #Vyazma
	540 #Kestenga
	541 #Belomorsk
	559 #Borovichi
	561 #Staraya Russa
	551 #Krasnogvardeysk
	557 #Tikhvin
	549 #Luga
	553 #Leningrad
	550 #Kingisepp
	552 #Gdov
	560 #Novgorod
	566 #Pskov
	599 #Minsk
	595 #Mozyr
	616 #Novograd-Volynsky
	611 #Zhitomir
	612 #Vinnitsa
	619 #Mogilev-Podolsky
	620 #Balta
	626 #Odessa
	622 #Nikolayev
	624 #Kherson
	623 #Melitopol
	627 #Kirvoy Rog
	628 #Kirovograd
	613 #Cherkasy
	617 #Kiev
	608 #Nezhin
	609 #Korosten
	600 #Mogilev
	596 #Slutsk
	607 #Chernigov
	597 #Luban
	601 #Gomel
	586 #Roslavl
	581 #Oryol
	587 #Klintsy
	582 #Livny
	579 #Ryazan
	657 #Balashov
	654 #Voronezh
	604 #Kursk
	580 #Yelets
	630 #Zaporozhye
	631 #Mariupol
	634 #Voroshilovgrad
	636 #Kharkov
	603 #Belgorod
	602 #Zheleznogorsk
	647 #Stary Oskol
	646 #Alexeyevka
	644 #Rostov-on-Don
	643 #Morozovsk
	614 #Proskurov
	633 #Kupyansk
	649 #Kamensk-Shakhtinsky
	653 #Pavlovsk
	648 #Rossosh
	1097 #Ashkhabad
	1098 #Merv
	1105 #Stalinabad
	1104 #Khorugh
	1099 #Samarkand
	1103 #Tashkent
	1106 #Osh
	1109 #Chimkent
	1108 #Dzambul
	1107 #Frunze
	567 #Serpukhov
	573 #Velikiye Luki
	565 #Dno
	590 #Vitebsk
	591 #Orsha
	589 #Smolensk
	594 #Bobruisk
	605 #Konotop
	629 #Poltava
	577 #Nelidovo
	562 #Kirishi
	558 #Rzhev
	563 #Torzhok
	707 #Tshinvali
	1185 #Sovetskaya Gavan
	506 #Taldy-Kurgan
	1100 #Bukhara
	711 #Yerevan
	712 #Stepanakert
	713 #Baku
	1149 #Asino
	1141 #Barabinsk
	499 #Ekibastuz
	593 #Polotsk
	714 #Nakhchivan
	576 #Kaluga
	555 #Cherepovets
	705 #Nazran
	1126 #Kungur
	1127 #Pervouralsk
	1128 #Nizhny Tagil
	1069 #Tayshet
	1070 #Kachug
	1161 #Kalakan
	1170 #Never
	1171 #Ekimchan
	575 #Safonovo
	606 #Sumy
	635 #Stalino
	652 #Lipetsk
	610 #Kremenchug
#Claims on Japan
	1542 #Toyohara
    } 
	
ownedprovinces = {  
    1191 #Vladivostok
	1193 #Nakhodka
	1192 #Semyonovka
	1196 #Nikolsk-Ussurysky
	1195 #Tetyukhe
	1190 #Khabarovsk
	1187 #Komsomolsk-on-Amur
	1188 #Elban
	1175 #Birobidzhan
	1174 #Kuybyshevka-Vostochnaya
	1541 #Oha
	1189 #Nikolayevsk-on-Amur
	1176 #Blagoveshchensk
	1180 #Verkhoyansk
	1181 #Magadan
	1182 #Anadyr
	1183 #Palana
	1184 #Petropavlovsk-Kamchatsky
	1194 #Lesozavodsk
	1179 #Yakutsk
	1178 #Nezametny
	1168 #Borzya
	1177 #Nyurba
	1169 #Chita
	1164 #Ust-Kut
	1163 #Bodaybo
	1162 #Irkutsk
	1167 #Ulan-Ude
	1166 #Cheremkhovo
	1186 #Okhotsk
    1165 #Bratsk
	1150 #Ostyako-Vogulsk
	1154 #Surgut
	507 #Ust-Kamenogorosk
	505 #Sar
    498 #Pavlodar
    1153 #Uray
	1152 #Salekhard
	1145 #Stalinsk
	1146 #Oyrot-Tura
	1147 #Abakan
	1158 #Minusinsk
	1156 #Krasnoyarsk
    1157 #Kansk
	1144 #Kemerovo
	1143 #Biysk
	1129 #Vorkuta
	1142 #Novosibirsk
	1140 #Barnaul
	1148 #Tomsk
	685 #Syktyvkar
	1155 #Norilsk
	544 #Kichmensky Gorodok
	546 #Molotovsk
	545 #Velsk
	568 #Solnechnogorsk
	615 #Uman
	625 #Ochakov
	564 #Opochka
	621 #Tiraspol
	588 #Bryansk
	584 #Tula
	500 #Balkhash
	1138 #Omsk
	1139 #Tara
	583 #Efremov
	1136 #Tyumen
	1135 #Tobolsk
	1111 #Fyodorovka
	1110 #Kzyl-Orda
	504 #Alma-Ata
	1112 #Novokazalinsk
	1102 #Nakus
	1101 #Zheleznodorozhny
	1118 #Shevchenko
	502 #Akmolinsk
	501 #Kokchetav
	1151 #Sverdlovsk
	1130 #Berezniki
	1137 #Kurgan
	598 #Rechytsa
	1132 #Chelyabinsk
	1131 #Ufa
	1133 #Orsk
	1115 #Kustanay
	1116 #Derzhavinsk
	503 #Karaganda
	1117 #Chelkar
	1114 #Aktyubinsk
	1113 #Uralsk
	690 #Sterlitamak
	699 #Elista
	632 #Dnepropetrovsk
	592 #Borisov
	687 #Perm
	689 #Solikamsk
	688 #Ukhta
	542 #Arkhangelsk
	686 #Kudymkar
	681 #Kostroma
	543 #Totma
	547 #Kirllov
	538 #Segezha
	539 #Petrozavodsk
	537 #Kem
	536 #Kandalaksha
	534 #Kola
	535 #Murmansk
	706 #Astrakhan
	702 #Grozny
	704 #Makhachkala
	703 #Vladikavkaz
	709 #Tbilisi
	708 #Kutaisi
	710 #Sukhumi
	701 #Nalchik
	696 #Cherkessk
	695 #Sochi
	694 #Novorossiysk
	691 #Krasnodar
	692 #Salsk
	697 #Volgodonsk
	698 #Voroshilovsk
	700 #Khasavyurt
	645 #Konstantinovsk
	659 #Kalach-on-Don
	662 #Kotelnikovo
	661 #Kamyshin
	660 #Volzhsky
	666 #Engel's
	639 #Dzhankoy
	1134 #Orenburg
	665 #Volsk
	669 #Saratov
	658 #Penza
	668 #Kuybyshev
	637 #Yevpatoria
	641 #Sevastopol
	640 #Kerch
	670 #Saransk
	667 #Tolyatti
	675 #Cheboksary
	674 #Zelenodolsk
	672 #Kazan
	664 #Naberezhnye Chelny
	671 #Izhevsk
	673 #Yoshkar-Ola
	684 #Kirov
	663 #Stalingrad
	693 #Maykop
	618 #Kamenets-Podolsky
	655 #Uryupinsk
	642 #Surovikino
	651 #Borisoglebsk
	650 #Tambov
	656 #Ulyanovsk
	638 #Simferopol
	578 #Sasovo
	683 #Arzamas
	682 #Ivanovo
	679 #Murom
	571 #Orekhovo-Zuyevo
	680 #Gorky
	678 #Vladimir
	677 #Yaroslavl
	676 #Rybinsk
	548 #Vologda
	556 #Vytegra
	554 #Kinry
	569 #Kalinini
	572 #Moscow #########
	570 #Zagorsk
	585 #Kozelsk
	574 #Vyazma
	540 #Kestenga
	541 #Belomorsk
	559 #Borovichi
	561 #Staraya Russa
	551 #Krasnogvardeysk
	557 #Tikhvin
	549 #Luga
	553 #Leningrad
	550 #Kingisepp
	552 #Gdov
	560 #Novgorod
	566 #Pskov
	599 #Minsk
	595 #Mozyr
	616 #Novograd-Volynsky
	611 #Zhitomir
	612 #Vinnitsa
	619 #Mogilev-Podolsky
	620 #Balta
	626 #Odessa
	622 #Nikolayev
	624 #Kherson
	623 #Melitopol
	627 #Kirvoy Rog
	628 #Kirovograd
	613 #Cherkasy
	617 #Kiev
	608 #Nezhin
	609 #Korosten
	600 #Mogilev
	596 #Slutsk
	607 #Chernigov
	597 #Luban
	601 #Gomel
	586 #Roslavl
	581 #Oryol
	587 #Klintsy
	582 #Livny
	579 #Ryazan
	657 #Balashov
	654 #Voronezh
	604 #Kursk
	580 #Yelets
	630 #Zaporozhye
	631 #Mariupol
	634 #Voroshilovgrad
	636 #Kharkov
	603 #Belgorod
	602 #Zheleznogorsk
	647 #Stary Oskol
	646 #Alexeyevka
	644 #Rostov-on-Don
	643 #Morozovsk
	614 #Proskurov
	633 #Kupyansk
	649 #Kamensk-Shakhtinsky
	653 #Pavlovsk
	648 #Rossosh
	1097 #Ashkhabad
	1098 #Merv
	1105 #Stalinabad
	1104 #Khorugh
	1099 #Samarkand
	1103 #Tashkent
	1106 #Osh
	1109 #Chimkent
	1108 #Dzambul
	1107 #Frunze
	567 #Serpukhov
	573 #Velikiye Luki
	565 #Dno
	590 #Vitebsk
	591 #Orsha
	589 #Smolensk
	594 #Bobruisk
	605 #Konotop
	629 #Poltava
	577 #Nelidovo
	562 #Kirishi
	558 #Rzhev
	563 #Torzhok
	707 #Tshinvali
	1185 #Sovetskaya Gavan
	506 #Taldy-Kurgan
	1100 #Bukhara
	711 #Yerevan
	712 #Stepanakert
	713 #Baku
	1149 #Asino
	1141 #Barabinsk
	499 #Ekibastuz
	593 #Polotsk
	714 #Nakhchivan
	576 #Kaluga
	555 #Cherepovets
	705 #Nazran
	1126 #Kungur
	1127 #Pervouralsk
	1128 #Nizhny Tagil
	1069 #Tayshet
	1070 #Kachug
	1161 #Kalakan
	1170 #Never
	1171 #Ekimchan
	575 #Safonovo
	606 #Sumy
	635 #Stalino
	652 #Lipetsk
	610 #Kremenchug
	} 
	
   controlledprovinces  = { 
    1191 #Vladivostok#
	1193 #Nakhodka#
	1192 #Semyonovka#
	1196 #Nikolsk-Ussurysky#
	1195 #Tetyukhe#
	1190 #Khabarovsk#
	1187 #Komsomolsk-on-Amur#
	1188 #Elban#
	1175 #Birobidzhan#
	1174 #Kuybyshevka-Vostochnaya#
	1541 #Okha#
	1189 #Nikolayevsk-on-Amur#
	1176 #Blagoveshchensk#
	1180 #Verkhoyansk#
	1181 #Magadan#
	1182 #Anadyr#
	1183 #Palana#
	1184 #Petropavlovsk#
	1194 #Lesozavodsk#
	1179 #Yakutsk#
	1178 #Nezametny#
	1168 #Borzya#
	1177 #Nyurba#
	1169 #Chita#
	1164 #Ust-Kut#
	1163 #Bodaybo#
	1162 #Irkutsk#
	1167 #Ulan-Ude#
	1166 #Cheremkhovo#
	1186 #Okhotsk#
    1165 #Bratsk#
	1150 #Ostyako-Vogulsk#
	1154 #Surgut#
	507 #Ust-Kamenogorosk#
	505 #Sar#
    498 #Pavlodar#
    1153 #Uray#
	1152 #Salekhard#
	1145 #Kusnezk#
	1146 #Oyrot-Tura#
	1147 #Abakan#
	1158 #Minusinsk#
	1156 #Krasnoyarsk#
        1157 #Kansk#
	1144 #Kemerovo#
	1143 #Biysk#
	1129 #Vorkuta#
	1142 #Novosibirsk#
	1140 #Barnaul#
	1148 #Tomsk#
	685 #Syktyvkar#
	1155 #Norilsk#
	544 #Kichmensky Gorodok#
	546 #Molotovsk#
	545 #Velsk#
	568 #Solnechnogorsk#
	615 #Uman#
	625 #Ochakov#
	564 #Opochka#
	621 #Tiraspol#
	588 #Bryansk#
	584 #Tula#
	500 #Balkhash#
	1138 #Omsk#
	1139 #Tara#
	583 #Efremov#
	1136 #Tyumen#
	1135 #Tobolsk#
	1111 #Fyodorovka#
	1110 #Kzyla-Orda#
	504 #Alma-Ata#
	1112 #Novokazalinsk#
	1102 #Nakus#
	1101 #Zheleznodorozhny#
	1118 #Fort Alexandrovsky#
	502 #Akmolinsk#
	501 #Kokchetav#
	1151 #Sverdlovsk#
	1130 #Berezniki#
	1137 #Kurgan#
	598 #Rechytsa#
	1132 #Chelyabinsk#
	1131 #Ufa#
	1133 #Orsk#
	1115 #Kustanay#
	1116 #Derzhavinsk#
	503 #Karaganda#
	1117 #Chelkar#
	1114 #Aktyubinsk#
	1113 #Uralsk#
	690 #Sterlitamak#
	699 #Elista#
	632 #Dnepropetrovsk#
	592 #Borisov#
	687 #Perm#
	689 #Solikamsk#
	688 #Ukhta#
	542 #Arkhangelsk#
	686 #Kudymkar#
	681 #Kostroma#
	543 #Totma#
	547 #Kirillov#
	538 #Segezha#
	539 #Petrozavodsk#
	537 #Kem#
	536 #Kandalaksha#
	534 #Kola#
	535 #Murmansk#
	706 #Astrakhan#
	702 #Grozny#
	704 #Makhachkala#
	703 #Vladikavkaz#
	709 #Tbilisi#
	708 #Kutaisi#
	710 #Sukhumi#
	701 #Nalchik#
	696 #Cherkessk#
	695 #Sochi#
	694 #Novorossiysk#
	691 #Krasnodar#
	692 #Salsk#
	697 #Volgodonsk#
	698 #Voroshilovsk#
	700 #Khasavyurt#
	645 #Konstantinovsk#
	659 #Kalach-on-Don#
	662 #Kotelnikovo#
	661 #Kamyshin#
	660 #Volzhsky#
	666 #Engel's#
	639 #Dzhankoy#
	1134 #Orenburg#
	665 #Volsk#
	669 #Saratov#
	658 #Penza#
	668 #Kuybyshev#
	637 #Yevpatoria#
	641 #Sevastopol#
	640 #Kerch#
	670 #Saransk#
	667 #Tolyatti#
	675 #Cheboksary#
	674 #Zelenodolsk#
	672 #Kazan#
	664 #Naberezhnye Chelny#
	671 #Izhevsk#
	673 #Yoshkar-Ola#
	684 #Kirov#
	663 #Stalingrad#
	693 #Maykop#
	618 #Kamenets-Podolsky#
	655 #Uryupinsk#
	642 #Surovikino#
	651 #Borisoglebsk#
	650 #Tambov#
	656 #Ulyanovsk#
	638 #Simferopol#
	578 #Sasovo#
	683 #Arzamas#
	682 #Ivanovo#
	679 #Murom#
	571 #Orekhovo-Zuyevo#
	680 #Gorky#
	678 #Vladimir#
	677 #Yaroslavl#
	676 #Rybinsk#
	548 #Vologda#
	556 #Vytegra#
	554 #Kinry#
	569 #Kalinin#
	572 #Moscow #########
	570 #Zagorsk#
	585 #Kozelsk#
	574 #Vyazma#
	540 #Kestenga#
	541 #Belomorsk#
	559 #Borovichi#
	561 #Staraya Russa#
	551 #Krasnogvardeysk#
	557 #Tikhvin#
	549 #Luga#
	553 #Leningrad#
	550 #Kingisepp#
	552 #Gdov#
	560 #Novgorod#
	566 #Pskov#
	599 #Minsk#
	595 #Mozyr#
	616 #Novograd-Volynsky#
	611 #Zhitomir#
	612 #Vinnitsa#
	619 #Mogilev-Podolsky#
	620 #Balta#
	626 #Odessa#
	622 #Nikolayev#
	624 #Kherson#
	623 #Melitopol#
	627 #Kirvoy Rog#
	628 #Kirovograd#
	613 #Cherkasy#
	617 #Kiev#
	608 #Nezhin#
	609 #Korosten#
	600 #Mogilev#
	596 #Slutsk#
	607 #Chernigov#
	597 #Luban#
	601 #Gomel#
	586 #Roslavl#
	581 #Oryol#
	587 #Klintsy#
	582 #Livny#
	579 #Ryazan#
	657 #Balashov#
	654 #Voronezh#
	604 #Kursk#
	580 #Yelets#
	630 #Zaporozhye#
	631 #Mariupol#
	634 #Voroshilovgrad#
	636 #Kharkov#
	603 #Belgorod#
	602 #Zheleznogorsk#
	647 #Stary Oskol#
	646 #Ostrogozhsk#
	644 #Rostov-on-Don#
	643 #Morozovsk#
	614 #Proskurov#
	633 #Kupyansk#
	649 #Kamensk-Shakhtinsky#
	653 #Pavlovsk#
	648 #Rossosh#
	1097 #Ashkhabad#
	1098 #Merv#
	1105 #Stalinabad#
	1104 #Khorugh#
	1099 #Samarkand#
	1103 #Tashkent#
	1106 #Osh#
	1109 #Chimkent#
	1108 #Dzambul#
	1107 #Frunze#
	567 #Serpukhov#
	573 #Velikiye Luki#
	565 #Dno#
	590 #Vitebsk#
	591 #Orsha#
	589 #Smolensk#
	594 #Bobruisk#
	605 #Konotop#
	629 #Poltava#
	577 #Nelidovo#
	562 #Kirishi#
	558 #Rzhev#
	563 #Torzhok#
	707 #Tshinvali#
	1185 #Sovetskaya Gavan#
	506 #Taldy-Kurgan#
	1100 #Bukhara#
	711 #Yerevan#
	712 #Stepanakert#
	713 #Baku#
	1149 #Asino#
	1141 #Barabinsk#
	499 #Ekibastuz#
	593 #Polotsk#
	714 #Nakhchivan#
	576 #Kaluga#
	555 #Cherepovets#
	705 #Nazran#
	1126 #Kungur#
	1127 #Pervouralsk#
	1128 #Nizhny Tagil#
	1069 #Tayshet#
	1070 #Kachug#
	1161 #Kalakan#
	1170 #Never#
	1171 #Ekimchan#
	575 #Safonovo#
	606 #Sumy#
	635 #Stalino#
	652 #Lipetsk#
	610 #Kremenchug

}

diplomacy = {
relation = { tag = AFG value = 0 guaranteed = { day = 16 month = may year = 1935 } }
relation = { tag = BRA value = -50 }
relation = { tag = BUL value = 15 guaranteed = { day = 16 month = may year = 1935 } }
relation = { tag = CZE value = 100 }
relation = { tag = ENG value = -25 }
relation = { tag = EST value = -30 guaranteed = { day = 16 month = may year = 1935 } }
relation = { tag = FIN value = 0 }
relation = { tag = FRA value = 100 guaranteed = { day = 7 month = january year = 1935 } }
relation = { tag = GER value = 0 }
relation = { tag = GRE value = 15 }
relation = { tag = IRE value = 0 }
relation = { tag = LAT value = -30 guaranteed = { day = 16 month = may year = 1935 } }
relation = { tag = LIT value = -30 guaranteed = { day = 16 month = may year = 1935 } }
relation = { tag = MON value = 150 guaranteed = { day = 29 month = december year = 1935 } }
relation = { tag = PER value = -20 guaranteed = { day = 16 month = may year = 1935 } }
relation = { tag = POL value = -50 }
relation = { tag = ROM value = 0 }
relation = { tag = SAU value = 0 }
relation = { tag = SIK value = 125 }
relation = { tag = SPR value = 75 }
relation = { tag = TAN value = 200 guaranteed = { day = 16 month = may year = 1935 } access = yes }
relation = { tag = TUR value = 100 guaranteed = { day = 29 month = december year = 1935 } }
relation = { tag = URU value = -100 }
relation = { tag = USA value = 35 }
relation = { tag = SCH value = 0 guaranteed = { day = 16 month = may year = 1935 } }
}

  SpyInfo  = { country = "SOV" NumberOfSpies = 8 }
  deactivate = { }
  dormant_teams = { 3744 }

#####################
# technology   data #
##################### 
  
techapps = {
####################
# Aircraft techs
####################
4010 4020 4030 4040 4050 # Single Engined 1929, Int, CAS 1930, Single Engined 1936

4290 4300 4310 4320 # double Engined 1929, tactical, naval, escort brigade 1930

4520 4530 # str. B.

9010 9020 9030 # Aerial warfare, basic doctrines
9600	# Early Airborne Experience

#############################
# Armor and artillery 1936
#############################

2550 2560 2570 2630 2640 2650
2010 2020 2800 2810 2290 2300 2450
2900 # heavy tank 37
2510 # basic AA brigade
17000 # 1936 rocket artillery/mortars
12000 # StuG Doctrine

############################
#Industry, electronics, atomic, rocket 1936
############################

5010 # Modern Agriculture
5080 5090 # Construction (up to the forts)
5190 # Basic oil conversion

############################
#Infantry 1936
############################

1010 1110 1190 
10110
1020 1200 1210 
11750 # 1937 mech inf
1310 # Engineers
#6210 6300
6600 6610 # Land Doctrins Human Wave
2400 #AT

############################
#Naval doctrines 
############################
8070 8240 8370 8610 8660

############################
#Naval Techs
############################
3010	3040	3070 # Escorts up to Washington
3020	3050	3080 # DD up to Washington
3030 15250	3060 # CL up to WW1

3350 3390 3430 3480 # Capital Design up to 1925
3360 3440 3490 # CA up to 1925
3370 3400 3450 3460 # BC up to 1918
3380 3410 3420 3470 # BB up to 1918
7550 # WW1 Monitor
3700 15080 3760 # Prewar SS, SS 1930 & SS 1936
3800 # Prewar TP

15090 # WW1 escort carrier
}

blueprints = { 1070 1150 4370 4080 11720 } #spg artillery
inventions = { 8023 } # Monitor

#################################
# red army oob
# by Lord Rommel - basing on datas by p'dox user Nick3210
# oob for 1.1.36
#################################

#moscow military district

landunit = {
 	id = { type = 10848 id = 1 }
 	name = "5. mekhanizirovannyi Korpus"
 	location = 572
        division = { id = { type = 10848 id = 2 } name = "13. mekhanizirovannyi Brigadu" strength = 90 type = armor model = 0 extra = sp_artillery brigade_model = 0 }
		division = { id = { type = 10848 id = 3 } name = "14. mekhanizirovannyi Brigadu" strength = 90 type = armor model = 0 extra = sp_artillery brigade_model = 0 }
		division = { id = { type = 10848 id = 4 } name = "20. mekhanizirovannyi Brigadu" strength = 85 type = armor model = 0 extra = super_heavy_armor brigade_model = 0 }
    }

landunit = {
 	id = { type = 10848 id = 5 }
 	name = "2. Strelkovyi Korpus"
 	location = 572 #moscow
	    division = { id = { type = 10848 id = 6 } name = "STAVKA" type = hq model = 0 }	
	    division = { id = { type = 10848 id = 7 } name = "Moskovskaya Proletarskiy Strelk.Div." strength = 100 type = infantry   model = 1 extra = artillery brigade_model = 2 experience = 25 }
		division = { id = { type = 10848 id = 8 } name = "Dzerzhinskogo Diviziya"               strength = 100 type = mechanized model = 0 experience = 15 } 
		division = { id = { type = 10848 id = 9 } name = "14. Strelkovaya Diviziya"             strength = 60  type = infantry   model = 0 extra = light_armor_brigade brigade_model = 2}
		division = { id = { type = 10848 id = 10 } name = "84. Strelkovaya Diviziya"            strength = 60  type = infantry   model = 0 extra = rocket_artillery brigade_model = 0 }
	}	
	
landunit = {
 	id = { type = 10848 id = 11 }
 	name = "10. Strelkovyi Korpus"
 	location = 604 #kursk
		division = { id = { type = 10848 id = 12 } name = "6. Strelkovaya Diviziya"  strength = 60 type = infantry model = 0 extra = light_armor_brigade brigade_model = 2 }
		division = { id = { type = 10848 id = 13 } name = "49. Strelkovaya Diviziya" strength = 60 type = infantry model = 0 extra = artillery brigade_model = 1 }
		division = { id = { type = 10848 id = 14 } name = "55. Strelkovaya Diviziya" strength = 60 type = infantry model = 0 extra = artillery brigade_model = 1 }
	}		
	
landunit = {
 	id = { type = 10848 id = 15 }
 	name = "3. Strelkovyi Korpus"
 	location = 581 #orel
		division = { id = { type = 10848 id = 16 } name = "17. Strelkovaya Diviziya" strength = 60 type = infantry model = 0 extra = light_armor_brigade brigade_model = 2 }
		division = { id = { type = 10848 id = 17 } name = "19. Strelkovaya Diviziya" strength = 60 type = infantry model = 0 extra = rocket_artillery brigade_model = 0 }
	}	
	
#leningrad military district

landunit = {
 	id = { type = 10848 id = 18 }
 	name = "7. mekhanizirovannyi Korpus"
 	location = 553 
		division = { id = { type = 10848 id = 19 } name = "1. mekhanizirovannyi Brigadu"  strength = 90 type = armor model = 0 extra = sp_artillery brigade_model = 0 }
		division = { id = { type = 10848 id = 20 } name = "19. mekhanizirovannyi Brigadu" strength = 90 type = armor model = 0 extra = sp_artillery brigade_model = 0 }
		division = { id = { type = 10848 id = 21 } name = "31. mekhanizirovannyi Brigadu" strength = 85 type = armor model = 0 extra = super_heavy_armor brigade_model = 0 }
	}
	
landunit = {
 	id = { type = 10848 id = 22 }
 	name = "Leningradskii Aviatsionnyyu Brigadu"
 	location = 553 
		division = { id = { type = 10848 id = 23 } name = "3. Aviatsionnyyu Brigadu" strength = 15 type = paratrooper model = 0 }
	}

landunit = {
 	id = { type = 10848 id = 24 }
 	name = "19. Strelkovyi Korpus"
 	location = 553 #leningrad
	    division = { id = { type = 10848 id = 25 } name = "Severnyi Front" type = hq model = 0 }
		division = { id = { type = 10848 id = 26 } name = "4. Turkestanskaya Strelk.Div."  strength = 60 type = infantry model = 0 extra = light_armor_brigade brigade_model = 2 }
		division = { id = { type = 10848 id = 27 } name = "18. Strelkovaya Diviziya"       strength = 60 type = infantry model = 0 extra = rocket_artillery brigade_model = 0 }
		division = { id = { type = 10848 id = 28 } name = "20. Strelkovaya Diviziya"       strength = 60 type = infantry model = 0 extra = artillery brigade_model = 1 }
	}		
	
landunit = {
 	id = { type = 10848 id = 29 }
 	name = "1. Strelkovyi Korpus"
 	location = 552 #pskov
		division = { id = { type = 10848 id = 30 } name = "16. Strelkovaya Diviziya" strength = 60 type = infantry model = 0 extra = light_armor_brigade brigade_model = 2 }
		division = { id = { type = 10848 id = 31 } name = "56. Strelkovaya Diviziya" strength = 60 type = infantry model = 0 extra = artillery brigade_model = 1 }
	}
	
#murmansk military district	

landunit = {
 	id = { type = 10848 id = 32 }
 	name = "Severnyy Korpus"
 	location = 535 #murmansk
		division = { id = { type = 10848 id = 33 } name = "10. Strelkovaya Diviziya" strength = 45 type = infantry model = 0 extra = rocket_artillery brigade_model = 0 }
	}
	
#minsk military district	

landunit = {
 	id = { type = 10848 id = 34 }
 	name = "Smolenskii Aviatsionnyyu Brigadu"
 	location = 589 
		division = { id = { type = 10848 id = 35 } name = "47. Aviatsionnyyu Brigadu" strength = 15 type = paratrooper model = 0 }
	}

landunit = {
 	id = { type = 10848 id = 36 }
 	name = "4. Strelkovyi Korpus"
 	location = 566 #pskov
		division = { id = { type = 10848 id = 37 } name = "2. Strelkovaya Diviziya"  strength = 60 type = infantry model = 0 extra = light_armor_brigade brigade_model = 2 }
		division = { id = { type = 10848 id = 38 } name = "4. Strelkovaya Diviziya"  strength = 60 type = infantry model = 0 extra = artillery brigade_model = 1 }
	}		
	
landunit = {
 	id = { type = 10848 id = 39 }
 	name = "16. Strelkovyi Korpus"
 	location = 591 #orsha
		division = { id = { type = 10848 id = 40 } name = "33. Strelkovaya Diviziya" strength = 60 type = infantry model = 0 extra = light_armor_brigade brigade_model = 2 }
		division = { id = { type = 10848 id = 41 } name = "43. Strelkovaya Diviziya" strength = 60 type = infantry model = 0 extra = artillery brigade_model = 1 }
	}	
	
landunit = {
 	id = { type = 10848 id = 42 }
 	name = "11. Strelkovyi Korpus"
 	location = 599 #minsk
	    division = { id = { type = 10848 id = 43 } name = "Tsentral'nyi Front" type = hq model = 0 }
	    division = { id = { type = 10848 id = 44 } name = "8. Strelkovaya Diviziya"  strength = 60 type = infantry model = 0 extra = light_armor_brigade brigade_model = 2 }
		division = { id = { type = 10848 id = 45 } name = "27. Strelkovaya Diviziya" strength = 60 type = infantry model = 0 extra = rocket_artillery brigade_model = 0 }
		division = { id = { type = 10848 id = 46 } name = "37. Strelkovaya Diviziya" strength = 60 type = infantry model = 0 extra = artillery brigade_model = 1 }
	}	
	
landunit = {
 	id = { type = 10848 id = 47 }
 	name = "5. Strelkovyi Korpus"
 	location = 594 #bobruisk
		division = { id = { type = 10848 id = 48 } name = "5. Strelkovaya Diviziya"  strength = 60 type = infantry model = 0 extra = light_armor_brigade brigade_model = 2 }
		division = { id = { type = 10848 id = 49 } name = "29. Strelkovaya Diviziya" strength = 60 type = infantry model = 0 extra = artillery brigade_model = 1 }
	}	
	
landunit = {
 	id = { type = 10848 id = 167 }
 	name = "20. Strelkovyi Korpus"
 	location = 599 #smolensk
	    division = { id = { type = 10848 id = 168 } name = "48. Strelkovaya Diviziya" strength = 60 type = infantry model = 0 extra = light_armor_brigade brigade_model = 2 }
		division = { id = { type = 10848 id = 169 } name = "64. Strelkovaya Diviziya" strength = 60 type = infantry model = 0 extra = artillery brigade_model = 1 }
		division = { id = { type = 10848 id = 170 } name = "81. Strelkovaya Diviziya" strength = 60 type = infantry model = 0 extra = artillery brigade_model = 1 }
	}		
	
#kiev military district

landunit = {
 	id = { type = 10848 id = 50 }
 	name = "Kievskiy Front"
 	location = 617 
        division = { id = { type = 10848 id = 51 } name = "Yuzhnyi Front" type = hq model = 0 }
    }
		
landunit = {
 	id = { type = 10848 id = 52 }
 	name = "Kievskii Aviatsionnyyu Brigadu"
 	location = 617 
		division = { id = { type = 10848 id = 53 } name = "13. Aviatsionnyyu Brigadu" strength = 15 type = paratrooper model = 0 }
	}
	
landunit = {
 	id = { type = 10848 id = 54 }
 	name = "45. mekhanizirovannyi Korpus"
 	location = 617 
        division = { id = { type = 10848 id = 55 } name = "12. mekhanizirovannyi Brigadu"  strength = 90 type = armor model = 0 extra = sp_artillery brigade_model = 0 }
		division = { id = { type = 10848 id = 56 } name = "133. mekhanizirovannyi Brigadu" strength = 90 type = armor model = 0 extra = sp_artillery brigade_model = 0 }
		division = { id = { type = 10848 id = 57 } name = "134. mekhanizirovannyi Brigadu" strength = 85 type = armor model = 0 extra = super_heavy_armor brigade_model = 0 }
    }

landunit = {
 	id = { type = 10848 id = 58 }
 	name = "15. Strelkovyi Korpus"
 	location = 609 #korosten
		division = { id = { type = 10848 id = 59 } name = "2. Kavkazskaya Strel.Div."  strength = 60 type = infantry model = 0 extra = light_armor_brigade brigade_model = 2 }
		division = { id = { type = 10848 id = 60 } name = "7. Strelkovaya Diviziya"    strength = 60 type = infantry model = 0 extra = rocket_artillery brigade_model = 0 }
		division = { id = { type = 10848 id = 61 } name = "46. Strelkovaya Diviziya"   strength = 60 type = infantry model = 0 extra = artillery brigade_model = 1 }
		division = { id = { type = 10848 id = 62 } name = "58. Strelkovaya Diviziya"   strength = 60 type = infantry model = 0 extra = artillery brigade_model = 1 }
	}		
	
landunit = {
 	id = { type = 10848 id = 63 }
 	name = "8. Strelkovyi Korpus"
 	location = 611 #zhitomir
	    division = { id = { type = 10848 id = 64 } name = "2. Turkestanskaya Strelk.Div."  strength = 60 type = infantry model = 0 extra = light_armor_brigade brigade_model = 2 }
		division = { id = { type = 10848 id = 65 } name = "44. Strelkovaya Diviziya"       strength = 60 type = infantry model = 0 extra = artillery brigade_model = 1 }
		division = { id = { type = 10848 id = 66 } name = "100. Strelkovaya Diviziya"      strength = 60 type = infantry model = 0 extra = artillery brigade_model = 1 }
	}	
	
landunit = {
 	id = { type = 10848 id = 67 }
 	name = "17. Strelkovyi Korpus"
 	location = 612 #winniza
	    division = { id = { type = 10848 id = 68 } name = "24. Strelkovaya Diviziya" strength = 60 type = infantry model = 0 extra = light_armor_brigade brigade_model = 2 }
		division = { id = { type = 10848 id = 69 } name = "96. Strelkovaya Diviziya" strength = 60 type = infantry model = 0 extra = artillery brigade_model = 1 }
		division = { id = { type = 10848 id = 70 } name = "99. Strelkovaya Diviziya" strength = 60 type = infantry model = 0 extra = artillery brigade_model = 1 }
	}	
	
landunit = {
 	id = { type = 10848 id = 71 }
 	name = "7. Strelkovyi Korpus"
 	location = 632 #dneperpetrovsk
		division = { id = { type = 10848 id = 72 } name = "23. Strelkovaya Diviziya" strength = 60 type = infantry model = 0 extra = light_armor_brigade brigade_model = 2 }
		division = { id = { type = 10848 id = 73 } name = "25. Strelkovaya Diviziya" strength = 60 type = infantry model = 0 extra = artillery brigade_model = 1 }
		division = { id = { type = 10848 id = 74 } name = "30. Strelkovaya Diviziya" strength = 60 type = infantry model = 0 extra = artillery brigade_model = 1 }
		division = { id = { type = 10848 id = 75 } name = "75. Strelkovaya Diviziya" strength = 60 type = infantry model = 0 extra = artillery brigade_model = 1 }
	}

landunit = {
 	id = { type = 10848 id = 76 }
 	name = "6. Strelkovyi Korpus"
 	location = 626 #odessa
		division = { id = { type = 10848 id = 77 } name = "15. Strelkovaya Diviziya" strength = 60 type = infantry model = 0 extra = light_armor_brigade brigade_model = 2 }
		division = { id = { type = 10848 id = 78 } name = "51. Strelkovaya Diviziya" strength = 60 type = infantry model = 0 extra = rocket_artillery brigade_model = 0 }
		division = { id = { type = 10848 id = 79 } name = "91. Strelkovaya Diviziya" strength = 60 type = infantry model = 0 extra = artillery brigade_model = 1 }
	}	

landunit = {
 	id = { type = 10848 id = 80 }
 	name = "14. Strelkovyi Korpus"
 	location = 641 #sevastopol
		division = { id = { type = 10848 id = 81 } name = "3. Strelkovaya Diviziya"  strength = 60 type = infantry model = 0 extra = light_armor_brigade brigade_model = 2 }
		division = { id = { type = 10848 id = 82 } name = "41. Strelkovaya Diviziya" strength = 60 type = infantry model = 0 extra = artillery brigade_model = 1 }
        division = { id = { type = 10848 id = 83 } name = "80. Strelkovaya Diviziya" strength = 60 type = infantry model = 0 extra = artillery brigade_model = 1 }
	}		
	
# north caucasus military district

landunit = {
 	id = { type = 10848 id = 84 }
 	name = "9. Strelkovyi Korpus"
 	location = 691 #krasnodar
		division = { id = { type = 10848 id = 85 } name = "9. Strelkovaya Diviziya"  strength = 60 type = infantry model = 0 extra = light_armor_brigade brigade_model = 2 }
		division = { id = { type = 10848 id = 86 } name = "22. Strelkovaya Diviziya" strength = 60 type = infantry model = 0 extra = rocket_artillery brigade_model = 0 }
		division = { id = { type = 10848 id = 87 } name = "74. Strelkovaya Diviziya" strength = 60 type = infantry model = 0 extra = artillery brigade_model = 1 }
	}	
	
landunit = {
 	id = { type = 10848 id = 88 }
 	name = "Sever Kavkazskiy VO"
 	location = 708 #tuapse
		division = { id = { type = 10848 id = 89 } name = "28. Gornostrelkovaya Diviziya" strength = 50 type = bergsjaeger model = 0 extra = artillery brigade_model = 1 }
	}	
	
landunit = {
 	id = { type = 10848 id = 90 }
 	name = "Dagestanskiy Korpus"
 	location = 704 #makhachkaia
		division = { id = { type = 10848 id = 91 } name = "13. Strelkovaya Diviziya"  strength = 60 type = infantry model = 0 extra = artillery brigade_model = 1 }
	}	
	
# stalingrad military district

landunit = {
 	id = { type = 10848 id = 92 }
 	name = "12. Strelkovyi Korpus"
 	location = 663 #stalingrad
	    division = { id = { type = 10848 id = 93 } name = "Kavkazskii Front" type = hq model = 0 }
		division = { id = { type = 10848 id = 94 } name = "31. Strelkovaya Diviziya"  strength = 60 type = infantry model = 0 extra = light_armor_brigade brigade_model = 2 }
	}	
	
landunit = {
 	id = { type = 10848 id = 95 }
 	name = "13. Strelkovyi Korpus"
 	location = 668 #kuybyshew
		division = { id = { type = 10848 id = 96 } name = "1. Strelkovaya Diviziya"   strength = 60 type = infantry model = 0 extra = light_armor_brigade brigade_model = 2 }
		division = { id = { type = 10848 id = 97 } name = "70. Strelkovaya Diviziya"  strength = 60 type = infantry model = 0 extra = rocket_artillery brigade_model = 0 }
	}	
	
landunit = {
 	id = { type = 10848 id = 98 }
 	name = "Privolzhskiy Korpus"
 	location = 669 #saratov
		division = { id = { type = 10848 id = 99 } name = "53. Strelkovaya Diviziya"  strength = 60 type = infantry model = 0 extra = artillery brigade_model = 1 }
	}	
	
landunit = {
 	id = { type = 10848 id = 100 }
 	name = "Penzenskiy Korpus"
 	location = 658 #pensa
		division = { id = { type = 10848 id = 101 } name = "61. Strelkovaya Diviziya"  strength = 60 type = infantry model = 0 extra = artillery brigade_model = 1 }
	}	
	
landunit = {
 	id = { type = 10848 id = 102 }
 	name = "Tyumenskiy Korpus"
 	location = 1138 #tyumen
		division = { id = { type = 10848 id = 103 } name = "65. Strelkovaya Diviziya"  strength = 60 type = infantry model = 0 extra = artillery brigade_model = 1 }
	}	
	
landunit = {
 	id = { type = 10848 id = 104 }
 	name = "Permskiy Korpus"
 	location = 687 #molotov
		division = { id = { type = 10848 id = 105 } name = "82. Strelkovaya Diviziya"  strength = 60 type = infantry model = 0 extra = artillery brigade_model = 1 }
	}	
	
landunit = {
 	id = { type = 10848 id = 106 }
 	name = "Chelnabinskiy Korpus"
 	location = 1132 #Chelnabinsk
		division = { id = { type = 10848 id = 107 } name = "85. Strelkovaya Diviziya"  strength = 60 type = infantry model = 0 extra = artillery brigade_model = 1 }
	}	
	
# turmenistan military district

landunit = {
 	id = { type = 10848 id = 108 }
 	name = "1. Turkestanskaya Korpus"
 	location = 1097 #ashgabat
	    division = { id = { type = 10848 id = 109 } name = "Aziya Front" type = hq model = 0 }
		division = { id = { type = 10848 id = 110 } name = "1. Turkestanskaya Gorno.Strelk.Div." strength = 50 type = bergsjaeger model = 0 extra = artillery brigade_model = 1 }
	}
	
landunit = {
 	id = { type = 10848 id = 111 }
 	name = "3. Turkestanskaya Korpus"
 	location = 1098 #chardzhou
		division = { id = { type = 10848 id = 112 } name = "3. Turkestanskaya Gorno.Strelk.Div." strength = 50 type = bergsjaeger model = 0 extra = artillery brigade_model = 1 }
	}
	
# sibiria military district

landunit = {
 	id = { type = 10848 id = 113 }
 	name = "Sibirskiy VO"
 	location = 1138 #omsk
		division = { id = { type = 10848 id = 114 } name = "71. Strelkovaya Diviziya"  strength = 60 type = infantry model = 0 extra = rocket_artillery brigade_model = 0 }
		division = { id = { type = 10848 id = 115 } name = "73. Strelkovaya Diviziya"  strength = 60 type = infantry model = 0 extra = artillery brigade_model = 1 }
	}	
	
landunit = {
 	id = { type = 10848 id = 116 }
 	name = "Tomskiy Korpus"
 	location = 1148 #tomsk
		division = { id = { type = 10848 id = 117 } name = "78. Strelkovaya Diviziya"  strength = 60 type = infantry model = 0 extra = artillery brigade_model = 1 }
	}	
	
# caucasian military district

landunit = {
 	id = { type = 10848 id = 118 }
 	name = "1. Kavkazskiy Korpus"
 	location = 703 #batum
		division = { id = { type = 10848 id = 119 } name = "1. Kavkazskaya Gorno.Strelk.Div." strength = 50 type = bergsjaeger model = 0 extra = rocket_artillery brigade_model = 0 }
	}
	
landunit = {
 	id = { type = 10848 id = 120 }
 	name = "3. Kavkazskiy Korpus"
 	location = 705 #kirovabad
		division = { id = { type = 10848 id = 121 } name = "3. Kavkazskaya Gorno.Strelk.Div." strength = 50 type = bergsjaeger model = 0 extra = artillery brigade_model = 1 }
	}
	
landunit = {
 	id = { type = 10848 id = 123 }
 	name = "Gruzinskiy Korpus"
 	location = 709 #tblisit
	    division = { id = { type = 10848 id = 124 } name = "1. Gruzinskaya Gorno.Strelk.Div." strength = 50 type = bergsjaeger model = 0 extra = artillery brigade_model = 1 }
	    division = { id = { type = 10848 id = 125 } name = "2. Gruzinskaya Strelk.Div."       strength = 60 type = infantry    model = 0 extra = artillery brigade_model = 1 }
	}
	
landunit = {
 	id = { type = 10848 id = 126 }
 	name = "Azerbaydzhanskiy Korpus"
 	location = 713 #baku
		division = { id = { type = 10848 id = 127 } name = "Azerbaydzhanskaya Gorno.Strelk.Div." strength = 50 type = bergsjaeger model = 0 extra = artillery brigade_model = 1 }
	}
	
landunit = {
 	id = { type = 10848 id = 128 }
 	name = "Armyanskiy Korpus"
 	location = 711 #chardzhou
		division = { id = { type = 10848 id = 129 } name = "Armyanskaya Gorno.Strelk.Div." strength = 50 type = bergsjaeger model = 0 extra = artillery brigade_model = 1 }
	}
	
# far eastern military district

landunit = {
 	id = { type = 10848 id = 130 }
 	name = "11. mekhanizirovannyi Korpus"
 	location = 1168 #Kamenets-Podolsky
        division = { id = { type = 10848 id = 131 } name = "3. mekhanizirovannyi Brigadu"  strength = 90 type = armor model = 0 extra = sp_artillery brigade_model = 0 }
		division = { id = { type = 10848 id = 132 } name = "16. mekhanizirovannyi Brigadu" strength = 90 type = armor model = 0 extra = sp_artillery brigade_model = 0 }
		division = { id = { type = 10848 id = 133 } name = "21. mekhanizirovannyi Brigadu" strength = 90 type = armor model = 0 extra = super_heavy_armor brigade_model = 0 }
    }
	
landunit = {
 	id = { type = 10848 id = 134 }
 	name = "Dal'niy Vostok Aviatsionnyyu Korpus"
 	location = 1174
		division = { id = { type = 10848 id = 135 } name = "1./2./5. Aviatsionnyyu Polk" strength = 15 type = paratrooper model = 0 }
	}

landunit = {
 	id = { type = 10848 id = 136 }
 	name = "Tetyukhe Korpus"
 	location = 1195 #tetyukhe
		division = { id = { type = 10848 id = 137 } name = "1. tikhii Strelk.Div."  strength = 60 type = infantry model = 0 extra = rocket_artillery brigade_model = 0 }
	}	
	
landunit = {
 	id = { type = 10848 id = 138 }
 	name = "Amurskiy Korpus"
 	location = 1175 #blagovoshchensk
		division = { id = { type = 10848 id = 139 } name = "12. Strelkovaya Diviziya"  strength = 60 type = infantry model = 0 extra = artillery brigade_model = 1 }
	}	
	
landunit = {
 	id = { type = 10848 id = 140 }
 	name = "Spassk Dalnyy Korpus"
 	location = 1194 #spassk-dal
		division = { id = { type = 10848 id = 141 } name = "21. Strelkovaya Diviziya"  strength = 60 type = infantry model = 0 extra = artillery brigade_model = 1 }
	}	
	
landunit = {
 	id = { type = 10848 id = 142 }
 	name = "Iman Korpus"
 	location = 1196 #Iman
		division = { id = { type = 10848 id = 143 } name = "26. Strelkovaya Diviziya"  strength = 60 type = infantry model = 0 extra = artillery brigade_model = 1 }
	}	
	
landunit = {
 	id = { type = 10848 id = 145 }
 	name = "18. Strelkovyi Korpus"
 	location = 1191 #vladivostok
	    division = { id = { type = 10848 id = 146 } name = "Man'chzhurii Front" type = hq model = 0 }
		division = { id = { type = 10848 id = 147 } name = "32. Strelkovaya Diviziya"  strength = 75 type = infantry model = 0 extra = light_armor_brigade brigade_model = 2 }
		division = { id = { type = 10848 id = 148 } name = "40. Strelkovaya Diviziya"  strength = 75 type = infantry model = 0 extra = artillery brigade_model = 1 }
	}	
	
landunit = {
 	id = { type = 10848 id = 149 }
 	name = "Dalnevostochnyy VO"
 	location = 1176 #komsomolskna
		division = { id = { type = 10848 id = 150 } name = "34. Strelkovaya Diviziya"  strength = 60 type = infantry model = 0 extra = artillery brigade_model = 1 }
	}	
	
landunit = {
 	id = { type = 10848 id = 151 }
 	name = "Chita Korpus"
 	location = 1169 #chita
		division = { id = { type = 10848 id = 152 } name = "35. Strelkovaya Diviziya"  strength = 60 type = infantry model = 0 extra = artillery brigade_model = 1 }
	}	
	
landunit = {
 	id = { type = 10848 id = 153 }
 	name = "Zabaykalskiy VO"
 	location = 1168 #borzya
		division = { id = { type = 10848 id = 154 } name = "36. Strelkovaya Diviziya"  strength = 60 type = infantry model = 0 extra = artillery brigade_model = 1 }
		division = { id = { type = 10848 id = 155 } name = "57. Strelkovaya Diviziya"  strength = 60 type = infantry model = 0 extra = artillery brigade_model = 1 }
	}	
	
landunit = {
 	id = { type = 10848 id = 156 }
 	name = "Krasnjyarskiy Korpus"
 	location = 1167 #Krasnoyarsk
		division = { id = { type = 10848 id = 157 } name = "94. Strelkovaya Diviziya"  strength = 60 type = infantry model = 0 extra = artillery brigade_model = 1 }
	}	
	
landunit = {
 	id = { type = 10848 id = 158 }
 	name = "Kolhznyy Korpus"
 	location = 1190 #khabarovsk
		division = { id = { type = 10848 id = 159 } name = "1. Kolkhoz Diviziya"  strength = 20 type = d_02 model = 0 extra = artillery brigade_model = 1 }
		division = { id = { type = 10848 id = 160 } name = "2. Kolkhoz Diviziya"  strength = 20 type = d_02 model = 0 extra = artillery brigade_model = 1 }
		division = { id = { type = 10848 id = 161 } name = "3. Kolkhoz Diviziya"  strength = 20 type = d_02 model = 0 extra = artillery brigade_model = 1 }
	}	
	
#Ids 1 - 170 in use	
	
######################
# red army cavalry
######################

landunit = { 
	id = { type = 12077 id = 618 } 
	name = "3. Kavaleriyskii Korpus" 
	location = 599
 		division = { id = { type = 10848 id = 619 } name = "7. Kavaleriyskaya Diviziya"  strength = 44 type = cavalry model = 1 extra = light_armor_brigade brigade_model = 2 }   
		division = { id = { type = 10848 id = 620 } name = "11. Kavaleriyskaya Diviziya" strength = 44 type = cavalry model = 1 extra = light_armor_brigade brigade_model = 2 }
		division = { id = { type = 10848 id = 621 } name = "24. Kavaleriyskaya Diviziya" strength = 44 type = cavalry model = 1 extra = light_armor_brigade brigade_model = 2 }
		division = { id = { type = 10848 id = 622 } name = "27. Kavaleriyskaya Diviziya" strength = 44 type = cavalry model = 1 extra = light_armor_brigade brigade_model = 2 }
	}

landunit = { 
	id = { type = 12077 id = 623 } 
	name = "4. Kavaleriyskii Korpus" 
	location = 711 
		division = { id = { type = 10848 id = 624 } name = "10. Kavaleriyskaya Diviziya" strength = 44 type = cavalry model = 1 extra = light_armor_brigade brigade_model = 2 }
		division = { id = { type = 10848 id = 625 } name = "12. Kavaleriyskaya Diviziya" strength = 44 type = cavalry model = 1 extra = light_armor_brigade brigade_model = 2 }
	}
	
landunit = { 
	id = { type = 12077 id = 610 } 
	name = "2. Kavaleriyskii Korpus" 
	location = 611
 		division = { id = { type = 10848 id = 611 } name = "3. Kavaleriyskaya Diviziya"  strength = 44 type = cavalry model = 1 extra = light_armor_brigade brigade_model = 2 }   
		division = { id = { type = 10848 id = 612 } name = "5. Kavaleriyskaya Diviziya"  strength = 44 type = cavalry model = 1 extra = light_armor_brigade brigade_model = 2 }
		division = { id = { type = 10848 id = 613 } name = "14. Kavaleriyskaya Diviziya" strength = 44 type = cavalry model = 1 extra = light_armor_brigade brigade_model = 2 }
	}		
	
landunit = { 
	id = { type = 12077 id = 614 } 
	name = "7. Kavaleriyskii Korpus" 
	location = 610
		division = { id = { type = 10848 id = 615 } name = "23. Kavaleriyskaya Diviziya" strength = 44 type = cavalry model = 1 extra = light_armor_brigade brigade_model = 2 }
		division = { id = { type = 10848 id = 616 } name = "26. Kavaleriyskaya Diviziya" strength = 44 type = cavalry model = 1 extra = light_armor_brigade brigade_model = 2 }
		division = { id = { type = 10848 id = 617 } name = "28. Kavaleriyskaya Diviziya" strength = 44 type = cavalry model = 1 extra = light_armor_brigade brigade_model = 2 }
	}
	
landunit = { 
	id = { type = 12077 id = 606 } 
	name = "1. Kavaleriyskii Korpus" 
	location = 614 #Proskurovo
 		division = { id = { type = 10848 id = 607 } name = "1. Kavaleriyskaya Diviziya" strength = 44 type = cavalry model = 1 extra = light_armor_brigade brigade_model = 2 }   
		division = { id = { type = 10848 id = 608 } name = "2. Kavaleriyskaya Diviziya" strength = 44 type = cavalry model = 1 extra = light_armor_brigade brigade_model = 2 }
		division = { id = { type = 10848 id = 609 } name = "9. Kavaleriyskaya Diviziya" strength = 44 type = cavalry model = 1 extra = light_armor_brigade brigade_model = 2 }
	}
	
landunit = { 
	id = { type = 12077 id = 604 } 
	name = "6. Kavaleriyskii Korpus" 
	location = 601
	    division = { id = { type = 10848 id = 672 } name = "6. Kavaleriyskaya Diviziya"   strength = 44 type = cavalry model = 1 extra = light_armor_brigade brigade_model = 2 }  
 		division = { id = { type = 10848 id = 605 } name = "29. Kavaleriyskaya Diviziya"  strength = 44 type = cavalry model = 1 extra = light_armor_brigade brigade_model = 2 }   
	}	
	
landunit = { 
	id = { type = 12077 id = 600 } 
	name = "5. Kavaleriyskii Korpus" 
	location = 566
		division = { id = { type = 10848 id = 601 } name = "16. Kavaleriyskaya Diviziya" strength = 44 type = cavalry model = 1 extra = light_armor_brigade brigade_model = 2 }
		division = { id = { type = 10848 id = 602 } name = "25. Kavaleriyskaya Diviziya" strength = 44 type = cavalry model = 1 extra = light_armor_brigade brigade_model = 2 }
		division = { id = { type = 10848 id = 603 } name = "30. Kavaleriyskaya Diviziya" strength = 44 type = cavalry model = 1 extra = light_armor_brigade brigade_model = 2 }
	}
	
####

landunit = { 
	id = { type = 12077 id = 670 } 
	name = "4. Kavaleriyskaya Diviziya" 
	location = 594
 		division = { id = { type = 10848 id = 671 } name = "4. Kavaleriyskaya Diviziya"  strength = 44 type = cavalry model = 1 extra = light_armor_brigade brigade_model = 2 }   
	}
	
landunit = { 
	id = { type = 12077 id = 673 } 
	name = "8. Kavaleriyskaya Diviziya" 
	location = 698
      	division = { id = { type = 12077 id = 674 } name = "8. Kavaleriyskaya Diviziya" strength = 44 type = cavalry model = 1 extra = light_armor_brigade brigade_model = 2 } 
	} 

landunit = { 
	id = { type = 12077 id = 675 } 
	name = "13. Kavaleriyskaya Diviziya" 
	location = 1162
      	division = { id = { type = 12077 id = 676 } name = "13. Kavaleriyskaya Diviziya" strength = 44 type = cavalry model = 1 extra = light_armor_brigade brigade_model = 2 } 
	} 
	
landunit = { 
	id = { type = 12077 id = 677 } 
	name = "15. Kavaleriyskaya Diviziya" 
	location = 1168
      	division = { id = { type = 12077 id = 678 } name = "15. Kavaleriyskaya Diviziya" strength = 44 type = cavalry model = 1 extra = light_armor_brigade brigade_model = 2 } 
	} 
	
landunit = { 
	id = { type = 12077 id = 679 } 
	name = "17. Kavaleriyskaya Diviziya" 
	location = 709
      	division = { id = { type = 12077 id = 680 } name = "17. Kavaleriyskaya Diviziya" strength = 44 type = cavalry model = 1 extra = light_armor_brigade brigade_model = 2 } 
	} 

####Mountain cavalry

landunit = { 
	id = { type = 12077 id = 700 } 
	name = "18. Kavaleriyskaya Diviziya" 
	location = 1098
      	division = { id = { type = 12077 id = 701 } name = "4. Turkestanskaya Kav.Div." strength = 25 type = cavalry model = 1 extra = light_armor_brigade brigade_model = 2 } 
	} 

landunit = { 
	id = { type = 12077 id = 702 } 
	name = "19. Kavaleriyskaya Diviziya" 
	location = 1099
      	division = { id = { type = 12077 id = 703 } name = "6. Uzbekskaya Kav.Div." strength = 25 type = cavalry model = 1 extra = light_armor_brigade brigade_model = 2 } 
	} 
	
landunit = { 
	id = { type = 12077 id = 704 } 
	name = "20. Kavaleriyskaya Diviziya" 
	location = 1105
      	division = { id = { type = 12077 id = 705 } name = "7. Turkestanskaya Kav.Div." strength = 25 type = cavalry model = 1 extra = light_armor_brigade brigade_model = 2 } 
	} 
	
landunit = { 
	id = { type = 12077 id = 706 } 
	name = "21. Kavaleriyskaya Diviziya" 
	location = 1106
      	division = { id = { type = 12077 id = 707 } name = "8. Turkestanskaya Kav.Div." strength = 25 type = cavalry model = 1 extra = light_armor_brigade brigade_model = 2 } 
	} 
	
landunit = { 
	id = { type = 12077 id = 708 } 
	name = "22. Kavaleriyskaya Diviziya" 
	location = 705
      	division = { id = { type = 12077 id = 709 } name = "1. Kolhoznaya Kav.Div." strength = 25 type = cavalry model = 1 extra = light_armor_brigade brigade_model = 2 } 
	} 
	
##############################################################################################
# Red Army Navy Naval Base troops
##############################################################################################

#Murmansk	
landunit = { 
	id = { type = 12077 id = 300 }
	name = "Murmanskaya Strelk. Bda." 
	location = 535 
	    division = { id = { type = 10848 id = 301 } name = "Krasnyi Flot Murmanskaya VMB"     strength = 25 type = marine model = 0 }      
    }
	
#Leningrad
landunit = { 
	id = { type = 12077 id = 302 }
	name = "Garnizon Krondshtadskoy VMB" 
	location = 553 
	    division = { id = { type = 10848 id = 303 } name = "Krasnyi Flot Krondshtadskoy VMB"  strength = 25 type = marine model = 0 }      
    }
	
#Sevastopol
landunit = { 
	id = { type = 12077 id = 304 }
	name = "Garnizon Sevastopolskoy VMB" 
	location = 641 
	    division = { id = { type = 10848 id = 305 } name = "Krasnyi Flot Sevastopolskoy VMB"  strength = 25 type = marine model = 0 }      
    }	
	
#Vladivostok
landunit = { 
	id = { type = 12077 id = 306 }
	name = "Garnizon Vladivistokskoy VMB" 
	location = 1191 
	    division = { id = { type = 10848 id = 307 } name = "Krasnyi Flot Vladivistokskoy VMB" strength = 25 type = marine model = 0 }      
    }	
	
##############################################################################################
# Red Army fortifed postions (Ukreplennya Raiony) of the Stalinline
##############################################################################################

#Kingisepp
landunit = { 
	id = { type = 12077 id = 308 }
	name = "Garnizon Kingisepp" 
	location = 550 
	    division = { id = { type = 10848 id = 309 } name = "Ukreplennya Raiony Kingisepp" strength = 10 type = garrison model = 0 extra = anti_air }      
    }
	
#Pskov
landunit = { 
	id = { type = 12077 id = 310 }
	name = "Garnizon Pskov" 
	location = 566 
	    division = { id = { type = 10848 id = 311 } name = "Ukreplennya Raiony Pskov"     strength = 10 type = garrison model = 0 extra = anti_air }      
    }
	
#Opochka
landunit = { 
	id = { type = 12077 id = 312 }
	name = "Garnizon Opochka" 
	location = 564 
	    division = { id = { type = 10848 id = 313 } name = "Ukreplennya Raiony Opochka"   strength = 10 type = garrison model = 0 extra = anti_air }      
    }
	
#Polotsk
landunit = { 
	id = { type = 12077 id = 314 }
	name = "Garnizon Polotsk" 
	location = 593 
	    division = { id = { type = 10848 id = 315 } name = "Ukreplennya Raiony Polotsk"   strength = 10 type = garrison model = 0 extra = anti_air }      
    }
	
#Minsk
landunit = { 
	id = { type = 12077 id = 316 }
	name = "Garnizon Minsk" 
	location = 599 
	    division = { id = { type = 10848 id = 317 } name = "Ukreplennya Raiony Minsk"     strength = 10 type = garrison model = 0 extra = anti_air }      
    } 
	
#Luban
landunit = { 
	id = { type = 12077 id = 318 }
	name = "Garnizon Luban" 
	location = 597 
	    division = { id = { type = 10848 id = 319 } name = "Ukreplennya Raiony Luban"     strength = 10 type = garrison model = 0 extra = anti_air }      
    }
	
#Proskurov
landunit = { 
	id = { type = 12077 id = 320 }
	name = "Garnizon Proskurov" 
	location = 614 
	    division = { id = { type = 10848 id = 321 } name = "Ukreplennya Raiony Proskurov" strength = 10 type = garrison model = 0 extra = anti_air }      
    }
	
#Vinnitsa
landunit = { 
	id = { type = 12077 id = 322 }
	name = "Garnizon Vinnitsa" 
	location = 612 
	    division = { id = { type = 10848 id = 323 } name = "Ukreplennya Raiony Vinnitsa"  strength = 10 type = garrison model = 0 extra = anti_air }      
    }
	
#Tiraspol
landunit = { 
	id = { type = 12077 id = 324 }
	name = "Garnizon Tiraspol" 
	location = 621 
	    division = { id = { type = 10848 id = 325 } name = "Ukreplennya Raiony Tiraspol"  strength = 10 type = garrison model = 0 extra = anti_air }      
    }
	
#Kiew
landunit = { 
	id = { type = 12077 id = 326 }
	name = "Garnizon Kiev" 
	location = 617 
	    division = { id = { type = 10848 id = 327 } name = "Ukreplennya Raiony Kiev"      strength = 10 type = garrison model = 0 extra = anti_air }      
    }
	
################################################# 
# 
# 	Red Army Airforce
# 
#################################################
# by Lord Rommel - basing on datas by p'dox user Nick3210
# oob for 1.1.36
#################################################

airunit = {
 	id = { type = 10848 id = 400 }
 	name = "Leningrad I. AD"
 	location = 553 #Leningrad
	base = 553
    division = { id = { type = 10848 id = 401 } name = "1. Bombardirovochnaya Brigada" strength = 70  type = tactical_bomber  model = 0 experience = 5 extra = escort }
	division = { id = { type = 10848 id = 402 } name = "8. Bombardirovochnaya Brigada" strength = 70  type = tactical_bomber  model = 0 experience = 5 extra = escort }
    division = { id = { type = 10848 id = 404 } name = "12. Shturmovaya Brigada"       strength = 80  type = cas              model = 1 experience = 5 }
	division = { id = { type = 10848 id = 461 } name = "13. Shturmovaya Brigada"       strength = 80  type = cas              model = 1 experience = 5 }
	division = { id = { type = 10848 id = 405 } name = "3. Transportnaya Brigada"      strength = 50  type = transport_plane  model = 0 }
 	}

airunit = {
 	id = { type = 10848 id = 406 }
 	name = "Riga II. AD"
 	location = 566 #Pskov
	base = 566
    division = { id = { type = 10848 id = 407 } name = "2. Bombardirovochnaya Brigada" strength = 70  type = tactical_bomber  model = 0 experience = 5 extra = escort }
	division = { id = { type = 10848 id = 408 } name = "3. Bombardirovochnaya Brigada" strength = 70  type = tactical_bomber  model = 0 experience = 5 extra = escort }
	division = { id = { type = 10848 id = 409 } name = "1. Shturmovaya Brigada"        strength = 80  type = cas              model = 1 experience = 5 }
	division = { id = { type = 10848 id = 410 } name = "9. Shturmovaya Brigada"        strength = 80  type = cas              model = 1 experience = 5 }
	division = { id = { type = 10848 id = 411 } name = "7. Istrebitel'naya Brigada"    strength = 80  type = multi_role       model = 0 experience = 5 }
 	}

airunit = {
 	id = { type = 10848 id = 412 }
 	name = "Minsk III. AD"
 	location = 599 #Minsk
	base = 599
    division = { id = { type = 10848 id = 413 } name = "4. Bombardirovochnaya Brigada" strength = 70  type = tactical_bomber  model = 0 experience = 5 extra = escort }
	division = { id = { type = 10848 id = 414 } name = "7. Bombardirovochnaya Brigada" strength = 70  type = tactical_bomber  model = 0 experience = 5 extra = escort }
	division = { id = { type = 10848 id = 415 } name = "6. Shturmovaya Brigada"        strength = 80  type = cas              model = 1 experience = 5 }
	division = { id = { type = 10848 id = 416 } name = "8. Shturmovaya Brigada"        strength = 80  type = cas              model = 1 experience = 5 }
	division = { id = { type = 10848 id = 417 } name = "2. Transportnaya Brigada"     strength = 50  type = transport_plane  model = 0 }
 	}

airunit = {
 	id = { type = 10848 id = 418 }
 	name = "Kiev IV. AD"
 	location = 617 #Kiev
	base = 617
    division = { id = { type = 10848 id = 419 } name = "6. Bombardirovochnaya Brigada"  strength = 70  type = tactical_bomber  model = 0 experience = 5 extra = escort }
	division = { id = { type = 10848 id = 420 } name = "10. Bombardirovochnaya Brigada" strength = 70  type = tactical_bomber  model = 0 experience = 5 extra = escort }
	division = { id = { type = 10848 id = 421 } name = "7. Shturmovaya Brigada"         strength = 80  type = cas              model = 1 experience = 5 }
	division = { id = { type = 10848 id = 422 } name = "23. Shturmovaya Brigada"        strength = 80  type = cas              model = 1 experience = 5 }
	division = { id = { type = 10848 id = 423 } name = "1. Transportnaya Brigada"       strength = 50  type = transport_plane  model = 0 }
 	}

airunit = {
 	id = { type = 10848 id = 424 }
 	name = "Odessa V. AD"
 	location = 626 #Odessa
	base = 626
    division = { id = { type = 10848 id = 425 } name = "5. Bombardirovochnaya Brigada" strength = 70  type = tactical_bomber  model = 0 experience = 5 extra = escort }
	division = { id = { type = 10848 id = 426 } name = "9. Bombardirovochnaya Brigada" strength = 70  type = tactical_bomber  model = 0 experience = 5 extra = escort }
	division = { id = { type = 10848 id = 427 } name = "4. Shturmovaya Brigada"        strength = 80  type = cas              model = 1 experience = 5 }
	division = { id = { type = 10848 id = 428 } name = "10. Shturmovaya Brigada"       strength = 80  type = cas              model = 1 experience = 5 }
	division = { id = { type = 10848 id = 429 } name = "6. Istrebitel'naya Brigada"    strength = 80  type = multi_role       model = 0 experience = 5 }
 	}

airunit = {
 	id = { type = 10848 id = 430 }
 	name = "Mockba VI. AD"
 	location = 572 #Moskau
	base = 572
    division = { id = { type = 10848 id = 431 } name = "3. Shturmovaya Brigada"     strength = 70  type = cas              model = 1 experience = 5 }
	division = { id = { type = 10848 id = 432 } name = "11. Shturmovaya Brigada"    strength = 80  type = cas              model = 0 experience = 5 }
	division = { id = { type = 10848 id = 433 } name = "14. Shturmovaya Brigada"    strength = 80  type = cas              model = 0 experience = 5 }
	division = { id = { type = 10848 id = 434 } name = "19. Shturmovaya Brigada"    strength = 80  type = cas              model = 0 experience = 5 }
	division = { id = { type = 10848 id = 435 } name = "3. Istrebitel'naya Brigada" strength = 80  type = multi_role       model = 0 experience = 5 }
 	}

airunit = {
 	id = { type = 10848 id = 436 }
 	name = "Transbaikal VII. AD"			 
 	location = 1157 #Kansk
	base = 1157
    division = { id = { type = 10848 id = 437 } name = "15. Shturmovaya Brigada"    strength = 70  type = cas              model = 1 experience = 5 }
	division = { id = { type = 10848 id = 438 } name = "17. Shturmovaya Brigada"    strength = 80  type = cas              model = 0 experience = 5 }
	division = { id = { type = 10848 id = 439 } name = "22. Shturmovaya Brigada"    strength = 80  type = cas              model = 0 experience = 5 }
	division = { id = { type = 10848 id = 440 } name = "24. Shturmovaya Brigada"    strength = 80  type = cas              model = 0 experience = 5 }
	division = { id = { type = 10848 id = 441 } name = "5. Istrebitel'naya Brigada" strength = 80  type = multi_role       model = 0 experience = 5 }
 	}

airunit = {
 	id = { type = 10848 id = 442 }
 	name = "Kharkov VIII. AD"
 	location = 636 #Kharkov
	base = 636
    division = { id = { type = 10848 id = 443 } name = "16. Shturmovaya Brigada"    strength = 80  type = cas              model = 0 experience = 5 }
	division = { id = { type = 10848 id = 444 } name = "18. Shturmovaya Brigada"    strength = 80  type = cas              model = 0 experience = 5 }
	division = { id = { type = 10848 id = 445 } name = "20. Shturmovaya Brigada"    strength = 80  type = cas              model = 0 experience = 5 }
	division = { id = { type = 10848 id = 446 } name = "21. Shturmovaya Brigada"    strength = 80  type = cas              model = 0 experience = 5 }
	division = { id = { type = 10848 id = 447 } name = "4. Istrebitel'naya Brigada" strength = 80  type = multi_role       model = 0 experience = 5 }
	}
	
airunit = {
 	id = { type = 10848 id = 448 }
 	name = "Vladivostok IX. AD"
 	location = 1191 #Vladivostok
	base = 1191
    division = { id = { type = 10848 id = 449 } name = "2. Shturmovaya Brigada"     strength = 80  type = cas              model = 0 experience = 5 }
    division = { id = { type = 10848 id = 450 } name = "5. Shturmovaya Brigada"     strength = 80  type = cas              model = 0 experience = 5 }
	division = { id = { type = 10848 id = 451 } name = "1. Istrebitel'naya Brigada" strength = 80  type = interceptor      model = 0 experience = 5 }
	division = { id = { type = 10848 id = 452 } name = "2. Istrebitel'naya Brigada" strength = 80  type = interceptor      model = 0 experience = 5 }
    }
 	
airunit = {
 	id = { type = 10848 id = 453 }
 	name = "STAVKA Strategic Reserves"
 	location = 589 #smolensk
	base = 589
    division = { id = { type = 10848 id = 454 } name = "1. Tyazhelaya Bomb. Brigada" strength = 50  type = strategic_bomber model = 1 experience = 5 }
	division = { id = { type = 10848 id = 455 } name = "2. Tyazhelaya Bomb. Brigada" strength = 50  type = strategic_bomber model = 1 experience = 5 }
 	}
	
airunit = {
 	id = { type = 10848 id = 456 }
 	name = "Archangelsk X. AD"
 	location = 542 #Archangelsk
	base = 542
    division = { id = { type = 10848 id = 457 } name = "8. Istrebitel'naya Brigada" strength = 80  type = interceptor      model = 0 experience = 5 }
	division = { id = { type = 10848 id = 458 } name = "1. Torpednaya Brigada"      strength = 50  type = naval_bomber     model = 0 experience = 5 }
 	}
	
airunit = {
 	id = { type = 10848 id = 489 }
 	name = "Vozdushno-desantnoy Korpus"
 	location = 1174 #Far East
	base = 1174
    division = { id = { type = 10848 id = 460 } name = "4. Transportnaya Brigada" strength = 45  type = transport_plane  model = 0 }
    }

#IDs 400 - 461 in use.
	
############################################################################################
#
#   Red army navy
#
############################################################################################

navalunit = {
 id = { type = 10848 id = 1561 }
 name = "Arkangels Flote"
 location = 542 #Arkangels
 base = 542
 	 division = { id = { type = 10848 id = 1200 } name = "Artyom" type = destroyer model = 1 experience = 5 }
 	 division = { id = { type = 10848 id = 1555 } name = "Rykov" type = destroyer model = 1 experience = 5 } # renamed Valerian Kuybyshev in 1937
 	 division = { id = { type = 10848 id = 1554 } name = "Volodarsky" type = destroyer model = 1 experience = 5 }
 }

navalunit = {
	id = { type = 10848 id = 5113 }
	name = "Arskoje Flote"
	location = 535 #Murmansk
 	base = 535
 	 division = { id = { type = 10848 id = 1254 } name = "D 4" type = submarine model = 1 experience = 5 }
 	 division = { id = { type = 10848 id = 1255 } name = "L 1" type = submarine model = 1 experience = 5 }
 	 division = { id = { type = 10848 id = 1203 } name = "L 2" type = submarine model = 1 experience = 5 }
	 division = { id = { type = 10848 id = 1605 } name = "L 55" type = submarine model = 0 experience = 5 }	 
 	 division = { id = { type = 10848 id = 1202 } name = "A 1" type = nuclear_submarine model = 0 experience = 5 }
 	 division = { id = { type = 10848 id = 1253 } name = "A 2" type = nuclear_submarine model = 0 experience = 5 }	 	 
 	 division = { id = { type = 10848 id = 1518 } name = "M 8" type = nuclear_submarine model = 0 experience = 5 }
 	 division = { id = { type = 10848 id = 1519 } name = "M 7" type = nuclear_submarine model = 0 experience = 5 }
 	 division = { id = { type = 10848 id = 1520 } name = "M 6" type = nuclear_submarine model = 0 experience = 5 }
 	 division = { id = { type = 10848 id = 1521 } name = "M 4" type = nuclear_submarine model = 0 experience = 5 }
 	 division = { id = { type = 10848 id = 1522 } name = "M 5" type = nuclear_submarine model = 0 experience = 5 }
	 division = { id = { type = 10848 id = 1568 } name = "M 13" type = nuclear_submarine model = 0 experience = 5 }
 	 division = { id = { type = 10848 id = 1569 } name = "M 14" type = nuclear_submarine model = 0 experience = 5 }
 	 division = { id = { type = 10848 id = 1570 } name = "M 15" type = nuclear_submarine model = 0 experience = 5 }
	 division = { id = { type = 10848 id = 1571 } name = "M 16" type = nuclear_submarine model = 0 experience = 5 } 
	 division = { id = { type = 10848 id = 1614 } name = "M 51" type = nuclear_submarine model = 0 experience = 5 }
	 division = { id = { type = 10848 id = 1615 } name = "M 52" type = nuclear_submarine model = 0 experience = 5 }
	 division = { id = { type = 10848 id = 1616 } name = "M 53" type = nuclear_submarine model = 0 experience = 5 }
	 division = { id = { type = 10848 id = 1620 } name = "M 71" type = nuclear_submarine model = 0 experience = 5 }
	 division = { id = { type = 10848 id = 1621 } name = "M 72" type = nuclear_submarine model = 0 experience = 5 }
	 division = { id = { type = 10848 id = 1622 } name = "M 73" type = nuclear_submarine model = 0 experience = 5 }
	 division = { id = { type = 10848 id = 1623 } name = "M 74" type = nuclear_submarine model = 0 experience = 5 }
	 division = { id = { type = 10848 id = 1624 } name = "M 75" type = nuclear_submarine model = 0 experience = 5 }
	 division = { id = { type = 10848 id = 1625 } name = "M 76" type = nuclear_submarine model = 0 experience = 5 }
 }

navalunit = {
	id = { type = 10848 id = 5114 }
	name = "CCCP Baltijskoje Flote"
	location = 553 #Leningrad
	base = 553
 	 division = { id = { type = 10848 id = 1204 } name = "Marat" type = battleship model = 1 experience = 5 }
 	 division = { id = { type = 10848 id = 1205 } name = "Oktyabrskaya Revoluciya" type = battleship model = 1 extra = naval_improved_hull_l experience = 5 }
	 division = { id = { type = 10848 id = 1727 } name = "Aurora" type = light_cruiser model = 0 experience = 5 }
 	 division = { id = { type = 10848 id = 1553 } name = "Stalin" type = destroyer model = 1 experience = 5 }
 	 division = { id = { type = 10848 id = 1552 } name = "Uritsky" type = destroyer model = 1 experience = 5 }
	 division = { id = { type = 10848 id = 1710 } name = "Frunze" type = destroyer model = 1 experience = 5 }
	 division = { id = { type = 10848 id = 1711 } name = "Petrovskiy" type = destroyer model = 1 experience = 5 } # renamed Zhelezniakov in 1939
	 }
	 
navalunit = {
	id = { type = 10848 id = 5117 }
	name = "CCCP Baltijskoje Flote Podlodok"
	location = 553 #Leningrad
	base = 553
	 division = { id = { type = 10848 id = 1523 } name = "P 1" type = submarine model = 2 experience = 5 }
 	 division = { id = { type = 10848 id = 1524 } name = "P 2" type = submarine model = 2 experience = 5 }
 	 division = { id = { type = 10848 id = 1525 } name = "P 3" type = submarine model = 2 experience = 5 } 
 	 division = { id = { type = 10848 id = 1209 } name = "D 5" type = submarine model = 1 experience = 5 }
 	 division = { id = { type = 10848 id = 1210 } name = "D 6" type = submarine model = 1 experience = 5 }
 	 division = { id = { type = 10848 id = 1211 } name = "L 3" type = submarine model = 1 experience = 5 }
 	 division = { id = { type = 10848 id = 1212 } name = "L 4" type = submarine model = 1 experience = 5 }
	 division = { id = { type = 10848 id = 1257 } name = "L 5" type = submarine model = 1 experience = 5 }
 	 division = { id = { type = 10848 id = 1258 } name = "L 6" type = submarine model = 1 experience = 5 }
 	 division = { id = { type = 10848 id = 1208 } name = "A 3" type = nuclear_submarine model = 0 experience = 5 }	 
 	 division = { id = { type = 10848 id = 1256 } name = "A 4" type = nuclear_submarine model = 0 experience = 5 }
	 division = { id = { type = 10848 id = 1600 } name = "A 5" type = nuclear_submarine model = 0 experience = 5 }
	 division = { id = { type = 10848 id = 1601 } name = "Komissar" type = submarine model = 0 experience = 5 }
	 division = { id = { type = 10848 id = 1602 } name = "Kommunar" type = submarine model = 0 strength = 20 experience = 5 } #out of service 1936
	 division = { id = { type = 10848 id = 1603 } name = "Krasoarmeets" type = submarine model = 0 strength = 20 experience = 5 } #out of service 1936
	 division = { id = { type = 10848 id = 1604 } name = "Volk" type = submarine model = 0 strength = 20 experience = 5 } #out of service 1936
 	 division = { id = { type = 10848 id = 1515 } name = "M 1" type = nuclear_submarine model = 0 experience = 5 }
 	 division = { id = { type = 10848 id = 1516 } name = "M 2" type = nuclear_submarine model = 0 experience = 5 }
 	 division = { id = { type = 10848 id = 1517 } name = "M 3" type = nuclear_submarine model = 0 experience = 5 }
	 division = { id = { type = 10848 id = 1685 } name = "SC 301" type = nuclear_submarine model = 1 experience = 5 }
	 division = { id = { type = 10848 id = 1686 } name = "SC 302" type = nuclear_submarine model = 1 experience = 5 }
	 division = { id = { type = 10848 id = 1687 } name = "SC 303" type = nuclear_submarine model = 1 experience = 5 }
	 division = { id = { type = 10848 id = 1688 } name = "SC 304" type = nuclear_submarine model = 1 experience = 5 }
	 division = { id = { type = 10848 id = 1689 } name = "SC 305" type = nuclear_submarine model = 1 experience = 5 }
	 division = { id = { type = 10848 id = 1690 } name = "SC 306" type = nuclear_submarine model = 1 experience = 5 }
	 division = { id = { type = 10848 id = 1691 } name = "SC 307" type = nuclear_submarine model = 1 experience = 5 }
	 division = { id = { type = 10848 id = 1692 } name = "SC 308" type = nuclear_submarine model = 1 experience = 5 }
	 }

navalunit = {
	id = { type = 10848 id = 5115 }
	name = "Cernoje Flote"
	location = 641 #Sevastopol
	base = 641
 	  division = { id = { type = 10848 id = 1234 } name = "Parishskaya Kommuna" type = battleship model = 1 extra = naval_improved_hull_l experience = 5 } #being rebuilt until January 1938; not put into build queue so that the ship will stay in Black Sea
 	  division = { id = { type = 10848 id = 1217 } name = "Krasni Kavkaz" type = heavy_cruiser model = 3 experience = 5 }
 	  division = { id = { type = 10848 id = 1214 } name = "Profintern" type = light_cruiser model = 2 experience = 5 }
 	  division = { id = { type = 10848 id = 1216 } name = "Chervonaya Ukraina" type = light_cruiser model = 2 experience = 5 }	  
 	  division = { id = { type = 10848 id = 1215 } name = "Komintern" type = light_cruiser model = 0 experience = 5 } # former name Pamiat Merkuriya
 	  division = { id = { type = 10848 id = 1218 } name = "Dzerjinsky" type = destroyer model = 1 experience = 5 }
 	  division = { id = { type = 10848 id = 1550 } name = "Nezamojnik " type = destroyer model = 1 experience = 5 }
 	  division = { id = { type = 10848 id = 1551 } name = "Shaumian" type = destroyer model = 1 experience = 5 }
	  division = { id = { type = 10848 id = 1506 } name = "Engels" type = destroyer model = 1 experience = 5 }
 	  division = { id = { type = 10848 id = 1549 } name = "Lenin" type = destroyer model = 1 experience = 5 }
 	  division = { id = { type = 10848 id = 1548 } name = "Karl Marx" type = destroyer model = 1 experience = 5 } 
	  division = { id = { type = 10848 id = 1712 } name = "Krasnoye Znamya" type = d_09 model = 0 experience = 5 } # big gunboat
	}
	
	navalunit = {
	id = { type = 10848 id = 1560 }
	name = "Batumi Flote"
 	location = 708 #Batumi
 	base = 708
		division = { id = { type = 10848 id = 1526 } name = "S 1" type = submarine model = 2 experience = 5 }
		division = { id = { type = 10848 id = 1527 } name = "S 2" type = submarine model = 2 experience = 5 }
		division = { id = { type = 10848 id = 1528 } name = "S 3" type = submarine model = 2 experience = 5 }
		division = { id = { type = 10848 id = 1530 } name = "S 5" type = submarine model = 2 experience = 5 }
		division = { id = { type = 10848 id = 1531 } name = "S 6" type = submarine model = 2 experience = 5 }
		division = { id = { type = 10848 id = 1223 } name = "D 1" type = submarine model = 1 experience = 5 }
		division = { id = { type = 10848 id = 1259 } name = "L 7" type = submarine model = 1 experience = 5 }
		division = { id = { type = 10848 id = 1260 } name = "L 8" type = submarine model = 1 experience = 5 }
		division = { id = { type = 10848 id = 1507 } name = "L 18" type = submarine model = 1 experience = 5 }
		division = { id = { type = 10848 id = 1508 } name = "L 19" type = submarine model = 1 experience = 5 }
		division = { id = { type = 10848 id = 1670 } name = "SC 201" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 10848 id = 1671 } name = "SC 202" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 10848 id = 1672 } name = "SC 203" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 10848 id = 1673 } name = "SC 204" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 10848 id = 1563 } name = "M 9" type = nuclear_submarine model = 0 experience = 5 }
 	 	division = { id = { type = 10848 id = 1564 } name = "M 10" type = nuclear_submarine model = 0 experience = 5 }
 	 	division = { id = { type = 10848 id = 1565 } name = "M 11" type = nuclear_submarine model = 0 experience = 5 }
 	 	division = { id = { type = 10848 id = 1566 } name = "M 12" type = nuclear_submarine model = 0 experience = 5 } 
		division = { id = { type = 10848 id = 1606 } name = "M 21" type = nuclear_submarine model = 0 experience = 5 }
		division = { id = { type = 10848 id = 1607 } name = "M 22" type = nuclear_submarine model = 0 experience = 5 }
		division = { id = { type = 10848 id = 1608 } name = "M 23" type = nuclear_submarine model = 0 experience = 5 }
		division = { id = { type = 10848 id = 1609 } name = "M 24" type = nuclear_submarine model = 0 experience = 5 }
		division = { id = { type = 10848 id = 1610 } name = "M 25" type = nuclear_submarine model = 0 experience = 5 }
		division = { id = { type = 10848 id = 1611 } name = "M 26" type = nuclear_submarine model = 0 experience = 5 }
		division = { id = { type = 10848 id = 1612 } name = "M 27" type = nuclear_submarine model = 0 experience = 5 }
		division = { id = { type = 10848 id = 1613 } name = "M 28" type = nuclear_submarine model = 0 experience = 5 }
		division = { id = { type = 10848 id = 1631 } name = "M 82" type = nuclear_submarine model = 0 experience = 5 }
		division = { id = { type = 10848 id = 1632 } name = "M 83" type = nuclear_submarine model = 0 experience = 5 }
		division = { id = { type = 10848 id = 1633 } name = "M 84" type = nuclear_submarine model = 0 experience = 5 }
		division = { id = { type = 10848 id = 1634 } name = "M 85" type = nuclear_submarine model = 0 experience = 5 }
		division = { id = { type = 10848 id = 1635 } name = "M 86" type = nuclear_submarine model = 0 experience = 5 }
	}

navalunit = {
	id = { type = 10848 id = 5116 }
	name = "Beringovo Flote"
	location = 1191 #Vladivostok
	base = 1191
		division = { id = { type = 10848 id = 1558 } name = "Yakov Sverdlov" type = destroyer model = 1 experience = 5 }
 		division = { id = { type = 10848 id = 1557 } name = "Voykov" type = destroyer model = 1 experience = 5 }
 		division = { id = { type = 10848 id = 1547 } name = "Kalinin" type = destroyer model = 1 experience = 5 }
 	 	division = { id = { type = 10848 id = 1546 } name = "Karl Liebknecht" type = destroyer model = 1 experience = 5 }
		division = { id = { type = 10848 id = 1232 } name = "Mayakovsky" type = transport }
	}	
	
	navalunit = {
	id = { type = 10848 id = 5118 }
	name = "Beringovo Flote Podlodok"
	location = 1191 #Vladivostok
	base = 1191
 		division = { id = { type = 10848 id = 1226 } name = "D 2" type = submarine model = 1 experience = 5 }
 	 	division = { id = { type = 10848 id = 1227 } name = "L 10" type = submarine model = 1 experience = 5 }
 	 	division = { id = { type = 10848 id = 1228 } name = "L 9" type = submarine model = 1 experience = 5 }
 	 	division = { id = { type = 10848 id = 1231 } name = "D 3" type = submarine model = 1 experience = 5 }
 	 	division = { id = { type = 10848 id = 1262 } name = "L 11" type = submarine model = 1 experience = 5 }
 	 	division = { id = { type = 10848 id = 1501 } name = "L 12" type = submarine model = 1 experience = 5 }
 	 	division = { id = { type = 10848 id = 1502 } name = "L 13" type = submarine model = 1 experience = 5 }
 	 	division = { id = { type = 10848 id = 1503 } name = "L 14" type = submarine model = 1 experience = 5 }
 	 	division = { id = { type = 10848 id = 1504 } name = "L 15" type = submarine model = 1 experience = 5 }
 	 	division = { id = { type = 10848 id = 1505 } name = "L 16" type = submarine model = 1 experience = 5 }
		division = { id = { type = 10848 id = 1636 } name = "SC 101" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 10848 id = 1637 } name = "SC 102" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 10848 id = 1638 } name = "SC 103" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 10848 id = 1639 } name = "SC 104" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 10848 id = 1640 } name = "SC 105" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 10848 id = 1641 } name = "SC 106" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 10848 id = 1642 } name = "SC 107" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 10848 id = 1643 } name = "SC 108" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 10848 id = 1644 } name = "SC 109" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 10848 id = 1645 } name = "SC 110" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 10848 id = 1646 } name = "SC 111" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 10848 id = 1647 } name = "SC 112" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 10848 id = 1648 } name = "SC 113" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 10848 id = 1649 } name = "SC 114" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 10848 id = 1650 } name = "SC 115" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 10848 id = 1651 } name = "SC 116" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 10848 id = 1652 } name = "SC 117" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 10848 id = 1653 } name = "SC 118" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 10848 id = 1654 } name = "SC 119" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 10848 id = 1655 } name = "SC 120" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 10848 id = 1656 } name = "SC 121" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 10848 id = 1657 } name = "SC 122" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 10848 id = 1658 } name = "SC 123" type = nuclear_submarine model = 1 experience = 5 }
		division = { id = { type = 10848 id = 1659 } name = "SC 124" type = nuclear_submarine model = 1 experience = 5 }
	}
	
#brigade_development = {
#        id = { type = 10848 id = 1400 }
#        cost = 0.25
#        size = 10
#        type = engineer
#		model = 0
#        date  = {  year = 1938 }
#		unitcost = yes
#        }	
	
	division_development = {
	name = "Kirov"
	type = heavy_cruiser
	model = 4
	cost = 0.2 #2
	new_model = no unitcost = yes
	id = { type = 10848 id = 1728 }
	date = { year = 1938 month = september day = 25 }
	}
	
	division_development = {
	name = "Voroshilov"
	type = heavy_cruiser
	model = 4
	cost = 0.2 #2
	new_model = no unitcost = yes
	id = { type = 10848 id = 1729 }
	date = { year = 1940 month = june day = 19 }
	}

 	division_development = {
	name = "Baku"
	type = d_09
	model = 3
	cost = 0.04 #0.4
	new_model = no unitcost = yes
	id = { type = 10848 id = 1713 }
	date = { year = 1938 month = july day = 26 }
	}
	
	 	division_development = {
	name = "Kharkov"
	type = d_09
	model = 3
	cost = 0.04 #0.4
	new_model = no unitcost = yes
	id = { type = 10848 id = 1714 }
	date = { year = 1938 month = november day = 18 }
	}
	
	 	division_development = {
	name = "Leningrad"
	type = d_09
	model = 3
	cost = 0.04 #0.4
	new_model = no unitcost = yes
	id = { type = 10848 id = 1715 }
	date = { year = 1936 month = december day = 4 }
	}
	
	 	division_development = {
	name = "Minsk"
	type = d_09
	model = 3
	cost = 0.04 #0.4
	new_model = no unitcost = yes
	id = { type = 10848 id = 1716 }
	date = { year = 1939 month = february day = 4 }
	}
	
	 	division_development = {
	name = "Moskva"
	type = d_09
	model = 3
	cost = 0.04 #0.4
	new_model = no unitcost = yes
	id = { type = 10848 id = 1717 }
	date = { year = 1938 month = august day = 9 }
	}
 
  	division_development = {
	name = "Tbilisi"
	type = d_09
	model = 3
	cost = 0.04 #0.4
	new_model = no unitcost = yes
	id = { type = 10848 id = 1718 }
	date = { year = 1940 month = december day = 10 }
	}
	
	 	division_development = {
	name = "Opytnyy"
	type = destroyer
	model = 2
	cost = 0.04 #0.4
	new_model = no unitcost = yes
	id = { type = 10848 id = 1719 }
	date = { year = 1941 month = september day = 0 }
	}
	
	 	division_development = {
	name = "Bodryy"
	type = destroyer
	model = 2
	cost = 0.04 #0.4
	new_model = no unitcost = yes
	id = { type = 10848 id = 1720 }
	date = { year = 1938 month = november day = 0 }
	}
	
	 	division_development = {
	name = "Groznyy"
	type = destroyer
	model = 2
	cost = 0.04 #0.4
	new_model = no unitcost = yes
	id = { type = 10848 id = 1721 }
	date = { year = 1938 month = december day = 0 }
	}
	
	 	division_development = {
	name = "Gnevnyy"
	type = destroyer
	model = 2
	cost = 0.04 #0.4
	new_model = no unitcost = yes
	id = { type = 10848 id = 1722 }
	date = { year = 1938 month = december day = 0 }
	}
	
	 	division_development = {
	name = "Boykiy"
	type = destroyer
	model = 2
	cost = 0.04 #0.4
	new_model = no unitcost = yes
	id = { type = 10848 id = 1723 }
	date = { year = 1939 month = march day = 0 }
	}
	
	 	division_development = {
	name = "Reshitelnyy"
	type = destroyer
	model = 2
	cost = 0.04 #0.4
	new_model = no unitcost = yes
	id = { type = 10848 id = 1724 }
	date = { year = 1939 month = july day = 0 }
	}
	
	 	division_development = {
	name = "Ryanyy"
	type = destroyer
	model = 2
	cost = 0.04 #0.4
	new_model = no unitcost = yes
	id = { type = 10848 id = 1725 }
	date = { year = 1939 month = august day = 0 }
	}
	
	 	division_development = {
	name = "Rezvyy"
	type = destroyer
	model = 2
	cost = 0.04 #0.4
	new_model = no unitcost = yes
	id = { type = 10848 id = 1726 }
	date = { year = 1940 month = january day = 0 }
	}
 
 
 
 

	 division_development = {
	name = "M 17"
	type = nuclear_submarine
	model = 0
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 8501 }
	date = { year = 1936 month = february day = 0 }
	}

	 division_development = {
	name = "M 18"
	type = nuclear_submarine
	model = 0
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 8502 }
	date = { year = 1936 month = march day = 0 }
	}

	 division_development = {
	name = "M 19"
	type = nuclear_submarine
	model = 0
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 8503 }
	date = { year = 1936 month = february day = 21 }
	}

	 division_development = {
	name = "M 20"
	type = nuclear_submarine
	model = 0
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 8504 }
	date = { year = 1936 month = march day = 17 }
	}
	
		 division_development = {
	name = "M 54"
	type = nuclear_submarine
	model = 0
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1617 }
	date = { year = 1936 month = october day = 13 }
	}

	 division_development = {
	name = "M 55"
	type = nuclear_submarine
	model = 0
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1618 }
	date = { year = 1936 month = october day = 16 }
	}

	 division_development = {
	name = "M 56"
	type = nuclear_submarine
	model = 0
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1619 }
	date = { year = 1936 month = october day = 18 }
	}
	
	 division_development = {
	name = "M 77"
	type = nuclear_submarine
	model = 0
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1626 }
	date = { year = 1936 month = june day = 24 }
	}

	 division_development = {
	name = "M 78"
	type = nuclear_submarine
	model = 0
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1627 }
	date = { year = 1936 month = june day = 24 }
	}
	
		 division_development = {
	name = "M 79"
	type = nuclear_submarine
	model = 0
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1628 }
	date = { year = 1936 month = october day = 9 }
	}

	 division_development = {
	name = "M 80"
	type = nuclear_submarine
	model = 0
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1629 }
	date = { year = 1936 month = july day = 21 }
	}

	 division_development = {
	name = "M 81"
	type = nuclear_submarine
	model = 0
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1630 }
	date = { year = 1936 month = july day = 21 }
	}
	
		 division_development = {
	name = "SC 125"
	type = nuclear_submarine
	model = 1
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1660 }
	date = { year = 1936 month = may day = 14 }
	}
	
			 division_development = {
	name = "SC 126"
	type = nuclear_submarine
	model = 1
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1661 }
	date = { year = 1936 month = october day = 16 }
	}
	
				 division_development = {
	name = "SC 127"
	type = nuclear_submarine
	model = 1
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1662 }
	date = { year = 1936 month = october day = 16 }
	}
	
				 division_development = {
	name = "SC 128"
	type = nuclear_submarine
	model = 1
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1663 }
	date = { year = 1936 month = october day = 29 }
	}
	
				 division_development = {
	name = "SC 129"
	type = nuclear_submarine
	model = 1
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1664 }
	date = { year = 1936 month = october day = 29 }
	}
		
				 division_development = {
	name = "SC 130"
	type = nuclear_submarine
	model = 1
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1665 }
	date = { year = 1936 month = december day = 10 }
	}
		
				 division_development = {
	name = "SC 131"
	type = nuclear_submarine
	model = 1
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1666 }
	date = { year = 1936 month = december day = 10 }
	}
		
				 division_development = {
	name = "SC 132"
	type = nuclear_submarine
	model = 1
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1667 }
	date = { year = 1936 month = december day = 10 }
	}
	
					 division_development = {
	name = "SC 133"
	type = nuclear_submarine
	model = 1
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1668 }
	date = { year = 1936 month = november day = 18 }
	}
	
					 division_development = {
	name = "SC 134"
	type = nuclear_submarine
	model = 1
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1669 }
	date = { year = 1936 month = december day = 26 }
	}
	
					 division_development = {
	name = "SC 205"
	type = nuclear_submarine
	model = 1
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1674 }
	date = { year = 1936 month = november day = 16 }
	}
		
					 division_development = {
	name = "SC 206"
	type = nuclear_submarine
	model = 1
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1675 }
	date = { year = 1936 month = august day = 13 }
	}
		
					 division_development = {
	name = "SC 207"
	type = nuclear_submarine
	model = 1
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1676 }
	date = { year = 1936 month = november day = 16 }
	}
		
					 division_development = {
	name = "SC 208"
	type = nuclear_submarine
	model = 1
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1677 }
	date = { year = 1937 month = march day = 8 }
	}
		
					 division_development = {
	name = "SC 209"
	type = nuclear_submarine
	model = 1
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1678 }
	date = { year = 1936 month = december day = 29 }
	}
	
		
					 division_development = {
	name = "SC 210"
	type = nuclear_submarine
	model = 1
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1679 }
	date = { year = 1936 month = december day = 29 }
	}
	
		
					 division_development = {
	name = "SC 211"
	type = nuclear_submarine
	model = 1
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1680 }
	date = { year = 1938 month = may day = 4 }
	}
	
		
					 division_development = {
	name = "SC 212"
	type = nuclear_submarine
	model = 1
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1681 }
	date = { year = 1938 month = october day = 29 }
	}
	
		
					 division_development = {
	name = "SC 213"
	type = nuclear_submarine
	model = 1
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1682 }
	date = { year = 1938 month = october day = 29 }
	}
	
		
					 division_development = {
	name = "SC 214"
	type = nuclear_submarine
	model = 1
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1683 }
	date = { year = 1939 month = march day = 3 }
	}

		
					 division_development = {
	name = "SC 215"
	type = nuclear_submarine
	model = 1
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1684 }
	date = { year = 1938 month = august day = 29 }
	}
	
					 division_development = {
	name = "SC 309"
	type = nuclear_submarine
	model = 1
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1693 }
	date = { year = 1936 month = august day = 19 }
	}
		
					 division_development = {
	name = "SC 310"
	type = nuclear_submarine
	model = 1
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1694 }
	date = { year = 1936 month = august day = 19 }
	}
		
					 division_development = {
	name = "SC 311"
	type = nuclear_submarine
	model = 1
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1695 }
	date = { year = 1936 month = august day = 20 }
	}
		
					 division_development = {
	name = "SC 317"
	type = nuclear_submarine
	model = 1
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1696 }
	date = { year = 1936 month = september day = 28 }
	}
		
					 division_development = {
	name = "SC 318"
	type = nuclear_submarine
	model = 1
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1697 }
	date = { year = 1936 month = august day = 11 }
	}
		
					 division_development = {
	name = "SC 319"
	type = nuclear_submarine
	model = 1
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1698 }
	date = { year = 1936 month = november day = 28 }
	}
		
					 division_development = {
	name = "SC 320"
	type = nuclear_submarine
	model = 1
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1699 }
	date = { year = 1936 month = november day = 28 }
	}
		
					 division_development = {
	name = "SC 322"
	type = nuclear_submarine
	model = 1
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1700 }
	date = { year = 1936 month = november day = 3 }
	}
		
					 division_development = {
	name = "SC 323"
	type = nuclear_submarine
	model = 1
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1701 }
	date = { year = 1936 month = november day = 3 }
	}
		
					 division_development = {
	name = "SC 324"
	type = nuclear_submarine
	model = 1
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1702 }
	date = { year = 1936 month = october day = 29 }
	}
	
						 division_development = {
	name = "SC 401"
	type = nuclear_submarine
	model = 1
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1703 }
	date = { year = 1936 month = july day = 22 }
	}
	
						 division_development = {
	name = "SC 402"
	type = nuclear_submarine
	model = 1
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1704 }
	date = { year = 1936 month = september day = 28 }
	}
	
						 division_development = {
	name = "SC 403"
	type = nuclear_submarine
	model = 1
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1705 }
	date = { year = 1936 month = september day = 25 }
	}	
	
						 division_development = {
	name = "SC 404"
	type = nuclear_submarine
	model = 1
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1706 }
	date = { year = 1936 month = september day = 25 }
	}
	
						 division_development = {
	name = "SC 421"
	type = nuclear_submarine
	model = 1
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1707 }
	date = { year = 1936 month = december day = 4 }
	}
	
						 division_development = {
	name = "SC 422"
	type = nuclear_submarine
	model = 1
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1708 }
	date = { year = 1936 month = december day = 3 }
	}
	
						 division_development = {
	name = "SC 424"
	type = nuclear_submarine
	model = 1
	cost = 0.03 #0.3
	new_model = no unitcost = yes
	id = { type = 10848 id = 1709 }
	date = { year = 1936 month = july day = 16 }
	}
	
transports = 225
escorts = 44

#############################################################################################
# dormant ships
#############################################################################################

navaldivision = { dormant = yes id = { type = 10848 id = 1730 } name = "Frunze"	type = battleship model = 1 strength = 45 } # damaged by fire in 1919, partly repaired 1925 - 1926 (46,5% according to sources), work finally stopped in 1935
navaldivision = { dormant = yes id = { type = 10848 id = 1731 } name = "Volia"	type = battleship model = 1 strength = 25 } # rushed out of dock in 1918, captured by White Forces and moved to Brest (France) in 1919, broken up for scrap in 1936

#############################################################################################
# dormant Guard divisions
#############################################################################################

landdivision = { dormant = yes id = { type = 10848 id = 800 } name = "1. Gvard. Spetsial'nyy Strel. Korpus" strength = 100 type = d_03 model = 2  experience = 15 extra = b_01 brigade_model = 1 }
landdivision = { dormant = yes id = { type = 10848 id = 801 } name = "1. Gvardiya Strelkovyi Korpus"  strength = 100 type = d_03 model = 2 experience = 15 extra = artillery brigade_model = 4 }
landdivision = { dormant = yes id = { type = 10848 id = 802 } name = "2. Gvardiya Strelkovyi Korpus"  strength = 100 type = d_03 model = 2 experience = 15 extra = artillery brigade_model = 4 }
landdivision = { dormant = yes id = { type = 10848 id = 803 } name = "3. Gvardiya Strelkovyi Korpus"  strength = 100 type = d_03 model = 2 experience = 15 extra = artillery brigade_model = 4 }
landdivision = { dormant = yes id = { type = 10848 id = 804 } name = "4. Gvardiya Strelkovyi Korpus"  strength = 100 type = d_03 model = 3 experience = 15 extra = anti_tank brigade_model = 2 }
landdivision = { dormant = yes id = { type = 10848 id = 805 } name = "5. Gvardiya Strelkovyi Korpus"  strength = 100 type = d_03 model = 3 experience = 15 extra = artillery brigade_model = 4 } #1942
landdivision = { dormant = yes id = { type = 10848 id = 806 } name = "6. Gvardiya Strelkovyi Korpus"  strength = 100 type = d_03 model = 3 experience = 15 extra = anti_tank brigade_model = 2 }
landdivision = { dormant = yes id = { type = 10848 id = 807 } name = "7. Gvardiya Strelkovyi Korpus"  strength = 100 type = d_03 model = 3 experience = 15 extra = anti_tank brigade_model = 2 }
landdivision = { dormant = yes id = { type = 10848 id = 808 } name = "8. Gvardiya Strelkovyi Korpus"  strength = 100 type = d_03 model = 3 experience = 15 extra = anti_tank brigade_model = 2 }
landdivision = { dormant = yes id = { type = 10848 id = 809 } name = "9. Gvardiya Strelkovyi Korpus"  strength = 100 type = d_03 model = 3 experience = 15 extra = anti_tank brigade_model = 2 }
landdivision = { dormant = yes id = { type = 10848 id = 810 } name = "10. Gvardiya Strelkovyi Korpus" strength = 100 type = d_03 model = 3 experience = 15 extra = rocket_artillery brigade_model = 4 }
landdivision = { dormant = yes id = { type = 10848 id = 811 } name = "11. Gvardiya Strelkovyi Korpus" strength = 100 type = d_03 model = 3 experience = 15 extra = artillery brigade_model = 4 }
landdivision = { dormant = yes id = { type = 10848 id = 812 } name = "12. Gvardiya Strelkovyi Korpus" strength = 100 type = d_03 model = 3 experience = 15 extra = artillery brigade_model = 4 }
landdivision = { dormant = yes id = { type = 10848 id = 813 } name = "13. Gvardiya Strelkovyi Korpus" strength = 100 type = d_03 model = 3 experience = 15 extra = artillery brigade_model = 4 }
landdivision = { dormant = yes id = { type = 10848 id = 814 } name = "14. Gvardiya Strelkovyi Korpus" strength = 100 type = d_03 model = 3 experience = 15 extra = artillery brigade_model = 4 }
landdivision = { dormant = yes id = { type = 10848 id = 815 } name = "15. Gvardiya Strelkovyi Korpus" strength = 100 type = d_03 model = 3 experience = 15 extra = anti_tank brigade_model = 2 }
landdivision = { dormant = yes id = { type = 10848 id = 816 } name = "16. Gvardiya Strelkovyi Korpus" strength = 100 type = d_03 model = 3 experience = 15 extra = anti_tank brigade_model = 2 }
landdivision = { dormant = yes id = { type = 10848 id = 817 } name = "17. Gvardiya Strelkovyi Korpus" strength = 100 type = d_03 model = 3 experience = 15 extra = anti_tank brigade_model = 2 }
landdivision = { dormant = yes id = { type = 10848 id = 818 } name = "18. Gvardiya Strelkovyi Korpus" strength = 100 type = d_03 model = 3 experience = 15 extra = anti_tank brigade_model = 3 } #1943
landdivision = { dormant = yes id = { type = 10848 id = 819 } name = "19. Gvardiya Strelkovyi Korpus" strength = 100 type = d_03 model = 3 experience = 15 extra = anti_tank brigade_model = 3 }
landdivision = { dormant = yes id = { type = 10848 id = 820 } name = "20. Gvardiya Strelkovyi Korpus" strength = 100 type = d_03 model = 3 experience = 15 extra = anti_tank brigade_model = 3 }
landdivision = { dormant = yes id = { type = 10848 id = 821 } name = "21. Gvardiya Strelkovyi Korpus" strength = 100 type = d_03 model = 3 experience = 15 extra = anti_tank brigade_model = 3 }
landdivision = { dormant = yes id = { type = 10848 id = 822 } name = "22. Gvardiya Strelkovyi Korpus" strength = 100 type = d_03 model = 3 experience = 15 extra = anti_tank brigade_model = 3 }
landdivision = { dormant = yes id = { type = 10848 id = 823 } name = "23. Gvardiya Strelkovyi Korpus" strength = 100 type = d_03 model = 3 experience = 15 extra = anti_tank brigade_model = 3 }
landdivision = { dormant = yes id = { type = 10848 id = 824 } name = "24. Gvardiya Strelkovyi Korpus" strength = 100 type = d_03 model = 3 experience = 15 extra = artillery brigade_model = 5 }
landdivision = { dormant = yes id = { type = 10848 id = 825 } name = "25. Gvardiya Strelkovyi Korpus" strength = 100 type = d_03 model = 3 experience = 15 extra = artillery brigade_model = 5 }
landdivision = { dormant = yes id = { type = 10848 id = 826 } name = "26. Gvardiya Strelkovyi Korpus" strength = 100 type = d_03 model = 3 experience = 15 extra = anti_tank brigade_model = 3 }
landdivision = { dormant = yes id = { type = 10848 id = 827 } name = "27. Gvardiya Strelkovyi Korpus" strength = 100 type = d_03 model = 3 experience = 15 extra = anti_tank brigade_model = 3 }
landdivision = { dormant = yes id = { type = 10848 id = 828 } name = "28. Gvardiya Strelkovyi Korpus" strength = 100 type = d_03 model = 3 experience = 15 extra = anti_tank brigade_model = 3 }
landdivision = { dormant = yes id = { type = 10848 id = 829 } name = "29. Gvardiya Strelkovyi Korpus" strength = 100 type = d_03 model = 3 experience = 15 extra = anti_tank brigade_model = 3 }
landdivision = { dormant = yes id = { type = 10848 id = 830 } name = "30. Gvardiya Strelkovyi Korpus" strength = 100 type = d_03 model = 3 experience = 15 extra = artillery brigade_model = 5 }
landdivision = { dormant = yes id = { type = 10848 id = 831 } name = "31. Gvardiya Strelkovyi Korpus" strength = 100 type = d_03 model = 3 experience = 15 extra = artillery brigade_model = 5 }
landdivision = { dormant = yes id = { type = 10848 id = 832 } name = "32. Gvardiya Strelkovyi Korpus" strength = 100 type = d_03 model = 3 experience = 15 extra = anti_tank brigade_model = 3 }
landdivision = { dormant = yes id = { type = 10848 id = 833 } name = "33. Gvardiya Strelkovyi Korpus" strength = 100 type = d_03 model = 3 experience = 15 extra = anti_tank brigade_model = 3 }
landdivision = { dormant = yes id = { type = 10848 id = 834 } name = "34. Gvardiya Strelkovyi Korpus" strength = 100 type = d_03 model = 3 experience = 15 extra = anti_tank brigade_model = 3 }
landdivision = { dormant = yes id = { type = 10848 id = 835 } name = "35. Gvardiya Strelkovyi Korpus" strength = 100 type = d_03 model = 3 experience = 15 extra = anti_tank brigade_model = 3 }
landdivision = { dormant = yes id = { type = 10848 id = 836 } name = "36. Gvardiya Strelkovyi Korpus" strength = 100 type = d_03 model = 3 experience = 15 extra = anti_tank brigade_model = 3 }
landdivision = { dormant = yes id = { type = 10848 id = 837 } name = "37. Gvardiya Strelkovyi Korpus" strength = 100 type = d_03 model = 4 experience = 15 extra = artillery brigade_model = 5 } #1944
landdivision = { dormant = yes id = { type = 10848 id = 838 } name = "38. Gvardiya Strelkovyi Korpus" strength = 100 type = d_03 model = 4 experience = 15 extra = artillery brigade_model = 5 }
landdivision = { dormant = yes id = { type = 10848 id = 839 } name = "39. Gvardiya Strelkovyi Korpus" strength = 100 type = d_03 model = 4 experience = 15 extra = artillery brigade_model = 5 }
landdivision = { dormant = yes id = { type = 10848 id = 840 } name = "40. Gvardiya Strelkovyi Korpus" strength = 100 type = d_03 model = 4 experience = 15 extra = rocket_artillery brigade_model = 6 }
landdivision = { dormant = yes id = { type = 10848 id = 841 } name = "41. Gvardiya Strelkovyi Korpus" strength = 100 type = d_03 model = 4 experience = 15 extra = artillery brigade_model = 5 }

landdivision = { dormant = yes id = { type = 10848 id = 842 } name = "1. Gvardiya Kavaleriyskii Korpus" strength = 100 type = d_04 model = 4 experience = 25 extra = light_armor_brigade brigade_model = 6 }
landdivision = { dormant = yes id = { type = 10848 id = 843 } name = "2. Gvardiya Kavaleriyskii Korpus" strength = 100 type = d_04 model = 4 experience = 25 extra = light_armor_brigade brigade_model = 7 }
landdivision = { dormant = yes id = { type = 10848 id = 844 } name = "3. Gvardiya Kavaleriyskii Korpus" strength = 100 type = d_04 model = 4 experience = 25 extra = light_armor_brigade brigade_model = 6 }
landdivision = { dormant = yes id = { type = 10848 id = 845 } name = "4. Gvardiya Kavaleriyskii Korpus" strength = 100 type = d_04 model = 4 experience = 25 extra = light_armor_brigade brigade_model = 7 }
landdivision = { dormant = yes id = { type = 10848 id = 846 } name = "5. Gvardiya Kavaleriyskii Korpus" strength = 100 type = d_04 model = 4 experience = 25 extra = light_armor_brigade brigade_model = 7 }
landdivision = { dormant = yes id = { type = 10848 id = 847 } name = "6. Gvardiya Kavaleriyskii Korpus" strength = 100 type = d_04 model = 5 experience = 25 extra = light_armor_brigade brigade_model = 7 }
landdivision = { dormant = yes id = { type = 10848 id = 848 } name = "7. Gvardiya Kavaleriyskii Korpus" strength = 100 type = d_04 model = 5 experience = 25 extra = light_armor_brigade brigade_model = 7 }

landdivision = { dormant = yes id = { type = 10848 id = 849 } name = "1. Gvardiya Mekhanizirovannyi Korpus" strength = 100 type = d_06 model = 1 experience = 25 extra = sp_rct_artillery  brigade_model = 0 }  
landdivision = { dormant = yes id = { type = 10848 id = 850 } name = "2. Gvardiya Mekhanizirovannyi Korpus" strength = 100 type = d_06 model = 1 experience = 25 extra = sp_rct_artillery  brigade_model = 0 } 
landdivision = { dormant = yes id = { type = 10848 id = 851 } name = "3. Gvardiya Mekhanizirovannyi Korpus" strength = 100 type = d_06 model = 1 experience = 25 extra = super_heavy_armor brigade_model = 2 }
landdivision = { dormant = yes id = { type = 10848 id = 852 } name = "4. Gvardiya Mekhanizirovannyi Korpus" strength = 100 type = d_06 model = 2 experience = 25 extra = tank_destroyer	   brigade_model = 4 }
landdivision = { dormant = yes id = { type = 10848 id = 853 } name = "5. Gvardiya Mekhanizirovannyi Korpus" strength = 100 type = d_06 model = 2 experience = 25 extra = tank_destroyer	   brigade_model = 4 }
landdivision = { dormant = yes id = { type = 10848 id = 854 } name = "6. Gvardiya Mekhanizirovannyi Korpus" strength = 100 type = d_06 model = 2 experience = 25 extra = tank_destroyer	   brigade_model = 4 }
landdivision = { dormant = yes id = { type = 10848 id = 855 } name = "7. Gvardiya Mekhanizirovannyi Korpus" strength = 100 type = d_06 model = 2 experience = 25 extra = tank_destroyer	   brigade_model = 4 }
landdivision = { dormant = yes id = { type = 10848 id = 856 } name = "8. Gvardiya Mekhanizirovannyi Korpus" strength = 100 type = d_06 model = 2 experience = 25 extra = tank_destroyer	   brigade_model = 4 }
landdivision = { dormant = yes id = { type = 10848 id = 857 } name = "9. Gvardiya Mekhanizirovannyi Korpus" strength = 100 type = d_06 model = 2 experience = 25 extra = super_heavy_armor brigade_model = 3 }

landdivision = { dormant = yes id = { type = 10848 id = 858 } name = "1. Gvardiya Tankovyy Korpus"  strength = 100 type = light_armor model = 4 experience = 25 extra = sp_rct_artillery  brigade_model = 1 }
landdivision = { dormant = yes id = { type = 10848 id = 859 } name = "2. Gvardiya Tankovyy Korpus"  strength = 100 type = light_armor model = 4 experience = 25 extra = super_heavy_armor brigade_model = 3 }
landdivision = { dormant = yes id = { type = 10848 id = 860 } name = "3. Gvardiya Tankovyy Korpus"  strength = 100 type = light_armor model = 4 experience = 25 extra = super_heavy_armor brigade_model = 3 }
landdivision = { dormant = yes id = { type = 10848 id = 861 } name = "4. Gvardiya Tankovyy Korpus"  strength = 100 type = light_armor model = 4 experience = 25 extra = sp_rct_artillery  brigade_model = 1 }
landdivision = { dormant = yes id = { type = 10848 id = 862 } name = "5. Gvardiya Tankovyy Korpus"  strength = 100 type = light_armor model = 4 experience = 25 extra = super_heavy_armor brigade_model = 3 }
landdivision = { dormant = yes id = { type = 10848 id = 863 } name = "6. Gvardiya Tankovyy Korpus"  strength = 100 type = light_armor model = 4 experience = 25 extra = super_heavy_armor brigade_model = 3 }
landdivision = { dormant = yes id = { type = 10848 id = 864 } name = "7. Gvardiya Tankovyy Korpus"  strength = 100 type = light_armor model = 4 experience = 25 extra = super_heavy_armor brigade_model = 3 }
landdivision = { dormant = yes id = { type = 10848 id = 865 } name = "8. Gvardiya Tankovyy Korpus"  strength = 100 type = light_armor model = 4 experience = 25 extra = super_heavy_armor brigade_model = 3 }
landdivision = { dormant = yes id = { type = 10848 id = 866 } name = "9. Gvardiya Tankovyy Korpus"  strength = 100 type = light_armor model = 5 experience = 25 extra = sp_rct_artillery  brigade_model = 1 }
landdivision = { dormant = yes id = { type = 10848 id = 867 } name = "10. Gvardiya Tankovyy Korpus" strength = 100 type = light_armor model = 4 experience = 25 extra = super_heavy_armor brigade_model = 3 }
landdivision = { dormant = yes id = { type = 10848 id = 868 } name = "11. Gvardiya Tankovyy Korpus" strength = 100 type = light_armor model = 4 experience = 25 extra = super_heavy_armor brigade_model = 3 }
landdivision = { dormant = yes id = { type = 10848 id = 869 } name = "12. Gvardiya Tankovyy Korpus" strength = 100 type = light_armor model = 5 experience = 25 extra = sp_rct_artillery  brigade_model = 1 }

###############

landdivision = { dormant = yes id = { type = 10848 id = 701 } name = "1. Gvardiya Strelkovaya Div." strength = 80 type = d_03 model = 2 extra = artillery brigade_model = 4 }
landdivision = { dormant = yes id = { type = 10848 id = 702 } name = "2. Gvardiya Strelkovaya Div." strength = 80 type = d_03 model = 2 extra = rocket_artillery brigade_model = 1 } 
landdivision = { dormant = yes id = { type = 10848 id = 703 } name = "39. Gvardiya Strelkovaya Div." strength = 80 type = d_03 model = 2 extra = artillery brigade_model = 4 } 
landdivision = { dormant = yes id = { type = 10848 id = 704 } name = "4. Gvardiya Strelkovaya Div." strength = 80 type = d_03 model = 2 extra = light_armor_brigade brigade_model = 6 }
landdivision = { dormant = yes id = { type = 10848 id = 705 } name = "52. motorizovannyy Gvard. Strel. Div." strength = 80 type = d_05 model = 1 extra = sp_artillery brigade_model = 1 }
landdivision = { dormant = yes id = { type = 10848 id = 706 } name = "6. Gvardiya Strelkovaya Div." strength = 80 type = d_03 model = 2 extra = artillery brigade_model = 4 }
landdivision = { dormant = yes id = { type = 10848 id = 707 } name = "7. Gvardiya Strelkovaya Div." strength = 80 type = d_03 model = 2 extra = artillery brigade_model = 4 }
landdivision = { dormant = yes id = { type = 10848 id = 708 } name = "89. Gvardiya Strelkovaya Div." strength = 80 type = d_03 model = 2 extra = artillery brigade_model = 4 } 
landdivision = { dormant = yes id = { type = 10848 id = 709 } name = "9. Gvardiya Strelkovaya Div." strength = 80 type = d_03 model = 2 extra = rocket_artillery brigade_model = 1 } 
landdivision = { dormant = yes id = { type = 10848 id = 710 } name = "10. Gvardiya Strelkovaya Div." strength = 80 type = d_03 model = 2 extra = light_armor_brigade brigade_model = 6 } 
landdivision = { dormant = yes id = { type = 10848 id = 711 } name = "11. Gvardiya Strelkovaya Div." strength = 80 type = d_03 model = 2 extra = artillery brigade_model = 4 } 
landdivision = { dormant = yes id = { type = 10848 id = 712 } name = "12. Gvardiya Strelkovaya Div." strength = 80 type = d_03 model = 2 extra = light_armor_brigade brigade_model = 6 } 
landdivision = { dormant = yes id = { type = 10848 id = 713 } name = "13. Gvardiya Strelkovaya Div." strength = 80 type = d_03 model = 2 extra = artillery brigade_model = 4 } 
landdivision = { dormant = yes id = { type = 10848 id = 714 } name = "14. Gvardiya Strelkovaya Div." strength = 80 type = d_03 model = 2 extra = light_armor_brigade brigade_model = 6 }
landdivision = { dormant = yes id = { type = 10848 id = 715 } name = "15. Gvardiya Strelkovaya Div." strength = 80 type = d_03 model = 2 extra = artillery brigade_model = 4 }
landdivision = { dormant = yes id = { type = 10848 id = 716 } name = "16. Gvardiya Strelkovaya Div." strength = 80 type = d_03 model = 2 extra = light_armor_brigade brigade_model = 6 } 
landdivision = { dormant = yes id = { type = 10848 id = 717 } name = "17. Gvardiya Strelkovaya Div." strength = 80 type = d_03 model = 2 extra = artillery brigade_model = 4 } 
landdivision = { dormant = yes id = { type = 10848 id = 718 } name = "18. Gvardiya Strelkovaya Div." strength = 80 type = d_03 model = 3 extra = light_armor_brigade brigade_model = 6 } 
landdivision = { dormant = yes id = { type = 10848 id = 719 } name = "19. Gvardiya Strelkovaya Div." strength = 80 type = d_03 model = 3 extra = rocket_artillery brigade_model = 1 } 
landdivision = { dormant = yes id = { type = 10848 id = 720 } name = "20. Gvardiya Strelkovaya Div." strength = 80 type = d_03 model = 3 extra = rocket_artillery brigade_model = 1 } 
landdivision = { dormant = yes id = { type = 10848 id = 721 } name = "21. Gvardiya Strelkovaya Div." strength = 80 type = d_03 model = 3 extra = light_armor_brigade brigade_model = 6 } 
landdivision = { dormant = yes id = { type = 10848 id = 722 } name = "22. Gvardiya Strelkovaya Div." strength = 80 type = d_03 model = 3 extra = rocket_artillery brigade_model = 1 } 
landdivision = { dormant = yes id = { type = 10848 id = 723 } name = "23. Gvardiya Strelkovaya Div." strength = 80 type = d_03 model = 3 extra = artillery brigade_model = 4 } 
landdivision = { dormant = yes id = { type = 10848 id = 724 } name = "24. Gvardiya Strelkovaya Div." strength = 80 type = d_03 model = 3 extra = light_armor_brigade brigade_model = 6 } 
landdivision = { dormant = yes id = { type = 10848 id = 725 } name = "25. Gvardiya Strelkovaya Div." strength = 80 type = d_03 model = 3 extra = artillery brigade_model = 4 } 
landdivision = { dormant = yes id = { type = 10848 id = 726 } name = "26. Gvardiya Strelkovaya Div." strength = 80 type = d_03 model = 3 extra = light_armor_brigade brigade_model = 6 } 
landdivision = { dormant = yes id = { type = 10848 id = 727 } name = "27. Gvardiya Strelkovaya Div." strength = 80 type = d_03 model = 3 extra = artillery brigade_model = 4 } 
landdivision = { dormant = yes id = { type = 10848 id = 728 } name = "28. Gvardiya Strelkovaya Div." strength = 80 type = d_03 model = 3 extra = light_armor_brigade brigade_model = 6 } 
landdivision = { dormant = yes id = { type = 10848 id = 729 } name = "29. Gvardiya Strelkovaya Div." strength = 80 type = d_03 model = 3 extra = light_armor_brigade brigade_model = 6 }
landdivision = { dormant = yes id = { type = 10848 id = 730 } name = "30. Gvardiya Strelkovaya Div." strength = 80 type = d_03 model = 3 extra = artillery brigade_model = 4 } 
landdivision = { dormant = yes id = { type = 10848 id = 731 } name = "31. Gvardiya Strelkovaya Div." strength = 80 type = d_03 model = 3 extra = light_armor_brigade brigade_model = 6 } 
landdivision = { dormant = yes id = { type = 10848 id = 732 } name = "1. Gvardiya Tankovogo Korpus" strength = 80 type = light_armor model = 3 extra = sp_artillery brigade_model = 1 } 
landdivision = { dormant = yes id = { type = 10848 id = 733 } name = "2. Gvardiya Tankovogo Korpus" strength = 80 type = light_armor model = 4 extra = sp_rct_artillery brigade_model = 1 } 
landdivision = { dormant = yes id = { type = 10848 id = 734 } name = "3. Gvardiya Tankovogo Korpus" strength = 80 type = light_armor model = 4 extra = sp_rct_artillery brigade_model = 1 } 
landdivision = { dormant = yes id = { type = 10848 id = 735 } name = "4. Gvardiya Tankovogo Korpus" strength = 80 type = light_armor model = 4 extra = sp_artillery brigade_model = 1 }
landdivision = { dormant = yes id = { type = 10848 id = 736 } name = "1. Bortovoy Gvardiya Korpus" strength = 80 type = paratrooper model = 1 } 
landdivision = { dormant = yes id = { type = 10848 id = 737 } name = "2. Bortovoy Gvardiya Korpus" strength = 80 type = paratrooper model = 2 } 
landdivision = { dormant = yes id = { type = 10848 id = 738 } name = "3. Bortovoy Gvardiya Korpus" strength = 80 type = paratrooper model = 3 }
landdivision = { dormant = yes id = { type = 10848 id = 739 } name = "5. Gvardiya Tankovogo Korpus" strength = 80 type = light_armor model = 4 extra = sp_rct_artillery brigade_model = 1 } 
landdivision = { dormant = yes id = { type = 10848 id = 740 } name = "10. Gvard. Dobrovol'tsy Tanko. Korp." strength = 80 type = light_armor model = 4 extra = sp_artillery brigade_model = 1 }

#landdivision = { dormant = yes id = { type = 10848 id = 739 } name = "32th Infantry Guards" strength = type = d_07 model = } #
#landdivision = { dormant = yes id = { type = 10848 id = 740 } name = "5th Armour Guards" strength = type = d_06 model = } #
#landdivision = { dormant = yes id = { type = 10848 id = 741 } name = "33th Infantry Guards" strength = type = d_03 model = } #
#landdivision = { dormant = yes id = { type = 10848 id = 742 } name = "6th Armour Guards" strength = type = d_03 model = } #
#landdivision = { dormant = yes id = { type = 10848 id = 743 } name = "34th Infantry Guards" strength = type = d_03 model = } #
#landdivision = { dormant = yes id = { type = 10848 id = 744 } name = "1st Mountain Guards" strength = type = d_07 model = } #
#landdivision = { dormant = yes id = { type = 10848 id = 745 } name = "2nd Mountain Guards" strength = type = d_07 model = } #

# polish army in USSR - ID 222008-11 #
#1st polish army in ussr (Pierwsza Armia Wojska Polskiego)
landdivision = { dormant = yes id = { type = 10848 id = 775 } name = "1 Polska Dywizja Piechoty"     type = d_02        model = 3 extra = artillery brigade_model = 4 }
landdivision = { dormant = yes id = { type = 10848 id = 776 } name = "2 Warszawska Dywizja Piechoty" type = d_02        model = 3 extra = anti_tank brigade_model = 1 }
landdivision = { dormant = yes id = { type = 10848 id = 777 } name = "3 Polska Dywizja Piechoty"     type = d_02        model = 3 extra = artillery brigade_model = 5 }
landdivision = { dormant = yes id = { type = 10848 id = 778 } name = "4 Polska Dywizja Piechoty"     type = d_02        model = 3 extra = anti_air  brigade_model = 3 }
landdivision = { dormant = yes id = { type = 10848 id = 779 } name = "4 Polska Dywizja Piechoty"     type = d_02        model = 3 extra = engineer  brigade_model = 2 }
landdivision = { dormant = yes id = { type = 10848 id = 780 } name = "1 Brygada Pancerna/Kawaleria"  type = mechanized  model = 2 extra = engineer  brigade_model = 2 strength = 50 }

#2nd polish army in ussr (Druga Armia Wojska Polskiego)
landdivision = { dormant = yes id = { type = 10848 id = 781 } name = "5 Polska Dywizja Piechoty"     type = d_02        model = 3 extra = artillery brigade_model = 4 }
landdivision = { dormant = yes id = { type = 10848 id = 782 } name = "7 Polska Dywizja Piechoty"     type = d_02        model = 3 extra = anti_tank brigade_model = 1 }
landdivision = { dormant = yes id = { type = 10848 id = 783 } name = "8 Polska Dywizja Piechoty"     type = d_02        model = 3 extra = artillery brigade_model = 5 }
landdivision = { dormant = yes id = { type = 10848 id = 784 } name = "9 Polska Dywizja Piechoty"     type = d_02        model = 3 extra = anti_air  brigade_model = 3 }
landdivision = { dormant = yes id = { type = 10848 id = 785 } name = "10 Polska Dywizja Piechoty"    type = d_02        model = 3 extra = anti_tank brigade_model = 1 }
landdivision = { dormant = yes id = { type = 10848 id = 786 } name = "1 Korpus Pancerny"             type = armor       model = 5 extra = super_heavy_armor brigade_model = 4 }
landdivision = { dormant = yes id = { type = 10848 id = 787 } name = "16 Brygada Pancerna"           type = armor       model = 4 strength = 25 }

#polish Armia Krajowa - Warszawski Korpus Armii Krajowej
landdivision = { dormant = yes id = { type = 10848 id = 788 } name = "11 Dyw. Pie. im. Romualda Traugutta" type = d_02 model = 3 }
landdivision = { dormant = yes id = { type = 10848 id = 789 } name = "12 Dyw. Pie. im. Macieja Rataja"     type = d_02 model = 3 }
landdivision = { dormant = yes id = { type = 10848 id = 790 } name = "28 Dyw. Pie. im. Stefana Okrzei"     type = d_02 model = 3 }

#Czech Army in USSR
landdivision = { dormant = yes id = { type = 10848 id = 791 } name = "1. ceskoslovensky armádní sbor" type = infantry model = 4 extra = light_armor_brigade brigade_model = 9 strength = 80 }

#############################################################################################
# dormant & locked garrisons for defense of fortified positions by AI #
#############################################################################################

#Leningrad
landdivision = { dormant = yes locked = yes id = { type = 10848 id = 756 } name = "Leninskaya PMD"		type = garrison model = 2 extra = anti_air brigade_model = 3 }
landdivision = { dormant = yes locked = yes id = { type = 10848 id = 757 } name = "Smolninskaya PMD"	type = garrison model = 2 extra = anti_air brigade_model = 3 }
landdivision = { dormant = yes locked = yes id = { type = 10848 id = 758 } name = "Oktiabrskaya2 PMD"	type = garrison model = 2 extra = anti_air brigade_model = 3 }
landdivision = { dormant = yes locked = yes id = { type = 10848 id = 759 } name = "Smolninskaya4 PMD"	type = garrison model = 2 extra = anti_air brigade_model = 3 }
landdivision = { dormant = yes locked = yes id = { type = 10848 id = 760 } name = "Oktiabrskaya3 PMD"	type = garrison model = 2 extra = anti_air brigade_model = 3 }

#Sevastopol
landdivision = { dormant = yes locked = yes id = { type = 10848 id = 761 } name = "1. Sevastopol PMD"	type = garrison model = 2 extra = anti_air brigade_model = 3 }
landdivision = { dormant = yes locked = yes id = { type = 10848 id = 762 } name = "2. Sevastopol PMD"	type = garrison model = 2 extra = anti_air brigade_model = 3 }
landdivision = { dormant = yes locked = yes id = { type = 10848 id = 763 } name = "3. Sevastopol PMD"	type = garrison model = 2 extra = anti_air brigade_model = 3 }

#Stalingrad
landdivision = { dormant = yes locked = yes id = { type = 10848 id = 764 } name = "1. Stalingrad PMD"	type = garrison model = 2 extra = anti_air brigade_model = 3 }
landdivision = { dormant = yes locked = yes id = { type = 10848 id = 765 } name = "2. Stalingrad PMD"	type = garrison model = 2 extra = anti_air brigade_model = 3 }
landdivision = { dormant = yes locked = yes id = { type = 10848 id = 766 } name = "3. Stalingrad PMD"	type = garrison model = 2 extra = anti_air brigade_model = 3 }
landdivision = { dormant = yes locked = yes id = { type = 10848 id = 767 } name = "4. Stalingrad PMD"	type = garrison model = 2 extra = anti_air brigade_model = 3 }

#Rostov
landdivision = { dormant = yes locked = yes id = { type = 10848 id = 768 } name = "1. Rostov PMD"	type = garrison model = 2 extra = anti_air brigade_model = 3 }
landdivision = { dormant = yes locked = yes id = { type = 10848 id = 769 } name = "2. Rostov PMD"	type = garrison model = 2 extra = anti_air brigade_model = 3 }
landdivision = { dormant = yes locked = yes id = { type = 10848 id = 770 } name = "3. Rostov PMD"	type = garrison model = 2 extra = anti_air brigade_model = 3 }
landdivision = { dormant = yes locked = yes id = { type = 10848 id = 771 } name = "4. Rostov PMD"	type = garrison model = 2 extra = anti_air brigade_model = 3 }

#Murmansk
landdivision = { dormant = yes locked = yes id = { type = 10848 id = 772 } name = "1. Murmansk PMD"	type = garrison model = 2 extra = anti_air brigade_model = 3 }
landdivision = { dormant = yes locked = yes id = { type = 10848 id = 773 } name = "2. Murmansk PMD"	type = garrison model = 2 extra = anti_air brigade_model = 3 }

}
