   ##############################   
   # Country definition for USA #   
   ##############################   
      
province = { id = 1778 anti_air = 1 air_base = { size = 4 current_size = 4 } naval_base = { size = 8 current_size = 8 }} # Guantanamo
province = { id = 2142 anti_air = 1 air_base = { size = 4 current_size = 4 } naval_base = { size = 4 current_size = 4 }} # Anchorage
province = { id = 1789 anti_air = 3 air_base = { size = 10 current_size = 10 } naval_base = { size = 10 current_size = 10 }} # Boston
province = { id = 1795 anti_air = 4 air_base = { size = 10 current_size = 10 } naval_base = { size = 10 current_size = 10 }} # New York
province = { id = 1809 anti_air = 4 air_base = { size = 10 current_size = 10 } naval_base = { size = 10 current_size = 10 }} # Washington D.C.
province = { id = 1812 anti_air = 4 air_base = { size = 10 current_size = 10 } naval_base = { size = 10 current_size = 10 }} # Norfolk
province = { id = 1953 anti_air = 1 air_base = { size = 10 current_size = 10 } naval_base = { size = 10 current_size = 10 }} # Miami
province = { id = 1922 anti_air = 1 air_base = { size = 6 current_size = 6 } naval_base = { size = 8 current_size = 8 }} # Corpus Christi
province = { id = 1886 anti_air = 1 air_base = { size = 10 current_size = 10 } naval_base = { size = 10 current_size = 10 }} # San Diego
province = { id = 1887 anti_air = 3 air_base = { size = 4 current_size = 4 } naval_base = { size = 8 current_size = 8 }} # Los Angeles
province = { id = 1889 anti_air = 3 air_base = { size = 10 current_size = 10 } naval_base = { size = 10 current_size = 10 }} # San Francisco
province = { id = 1874 anti_air = 1 air_base = { size = 10 current_size = 10 } naval_base = { size = 10 current_size = 10 }} # Seattle
province = { id = 889 anti_air = 3 air_base = { size = 4 current_size = 4 } naval_base = { size = 4 current_size = 4 } supplypool = 100 oilpool = 50 } # Colon
province = { id = 1683 anti_air = 3 air_base = { size = 4 current_size = 4 } naval_base = { size = 4 current_size = 4 } supplypool = 100 oilpool = 50 } # Guam
province = { id = 1673 anti_air = 3 air_base = { size = 4 current_size = 4 } naval_base = { size = 4 current_size = 4 } supplypool = 100 oilpool = 50 } # Wake Island
province = { id = 1734 anti_air = 3 air_base = { size = 10 current_size = 10 } naval_base = { size = 10 current_size = 10 } supplypool = 1000 oilpool = 500 } #Pearl Harbour
province = { id = 2174 anti_air = 1 air_base = { size = 2 current_size = 2 } naval_base = { size = 1 current_size = 1 }} #Attu Island
Province = { id = 1792 anti_air = 1 air_base = { size = 4 current_size = 4 }} # Plattsburgh
province = { id = 1806 anti_air = 1 air_base = { size = 4 current_size = 4 }} # Pittsburgh
province = { id = 1845 anti_air = 1 air_base = { size = 4 current_size = 4 }} # Detroit
province = { id = 1832 anti_air = 3 air_base = { size = 10 current_size = 10 }} # Chicago
province = { id = 1839 anti_air = 1 air_base = { size = 4 current_size = 4 }} # Milwaukee
Province = { id = 1962 anti_air = 1 air_base = { size = 4 current_size = 4 }} # Charlotte
province = { id = 1820 anti_air = 1 air_base = { size = 4 current_size = 4 }} # Louisville
province = { id = 1960 anti_air = 1 air_base = { size = 4 current_size = 4 }} # Charleston
Province = { id = 1952 anti_air = 1 air_base = { size = 4 current_size = 4 }} # Jacksonville
province = { id = 1878 anti_air = 1 air_base = { size = 4 current_size = 4 }} # Portland
province = { id = 1859 anti_air = 1 air_base = { size = 4 current_size = 4 }} # Omaha
province = { id = 1913 anti_air = 1 air_base = { size = 4 current_size = 4 }} # Tulsa
province = { id = 1955 anti_air = 1 air_base = { size = 4 current_size = 4 }} # Atlanta
Province = { id = 1940 anti_air = 1 air_base = { size = 4 current_size = 4 }} # Memphis
Province = { id = 1944 anti_air = 1 air_base = { size = 4 current_size = 4 }} # Biloxi
province = { id = 1915 anti_air = 1 air_base = { size = 4 current_size = 4 }} # Little Rock
province = { id = 1833 anti_air = 1 air_base = { size = 4 current_size = 4 }} # St. Louis
province = { id = 1846 anti_air = 1 air_base = { size = 4 current_size = 4 }} # Minneapolis
province = { id = 1855 anti_air = 1 air_base = { size = 4 current_size = 4 }} # Bismarck
province = { id = 1908 anti_air = 1 air_base = { size = 4 current_size = 4 }} # Denver
Province = { id = 1911 anti_air = 1 air_base = { size = 4 current_size = 4 }} # Oklahoma City
province = { id = 1928 anti_air = 1 air_base = { size = 4 current_size = 4 }} # Houston
Province = { id = 1906 anti_air = 1 air_base = { size = 4 current_size = 4 }} # Santa Fe
province = { id = 1901 anti_air = 1 air_base = { size = 4 current_size = 4 }} # Phoenix
province = { id = 1896 anti_air = 1 air_base = { size = 10 current_size = 10 }} # Salt Lake City
province = { id = 1787 anti_air = 1 air_base = { size = 4 current_size = 4 }} # Concord
province = { id = 1888 anti_air = 1 air_base = { size = 4 current_size = 4 }} # Sacramento
province = { id = 1805 anti_air = 2 naval_base = { size = 2 current_size = 2 }} # Philadelphia
province = { id = 2141 supplypool = 1000 } # Juneau
province = { id = 1765 supplypool = 50 } # Puerto Rico
province = { id = 1747 air_base = { size = 1 current_size = 1 } supplypool = 50 } # Palmyra
province = { id = 1739 air_base = { size = 1 current_size = 1 } supplypool = 100 } # Midway Island
province = { id = 1738 air_base = { size = 1 current_size = 1 } supplypool = 1 } # Johnson Island
province = { id = 1733 naval_base = { size = 1 current_size = 1 } supplypool = 1 } # Pago Pago, Naval Base Tutuila
   
   #####################   
   # Country main data #   
   #####################   
      
country = 
{ 
	tag = USA   
	capital = 1809  
	peacetime_ic_mod = 0.13
	industrial_modifier = 0.8000
	manpower = 20
	
	# Resource Reserves   
	energy	=		1000 
	metal	= 		1000
	rare_materials = 	500	
	oil =			500	
	supplies =		500
	money = 		100

	transports = 		1600
	escorts = 		164

     	diplomacy = {  
      relation = { tag = ARG value = 75 }
      relation = { tag = AST value = 125 }
      relation = { tag = BEL value = 75 }
      relation = { tag = BOL value = 85 }
      relation = { tag = BRA value = 120 }
      relation = { tag = CAN value = 175 }
      relation = { tag = CHL value = 100 }
      relation = { tag = COL value = 75 }
      relation = { tag = COS value = 100 }
      relation = { tag = CUB value = 200 access = yes }
      relation = { tag = DEN value = 75 }
      relation = { tag = DOM value = 125 }
      relation = { tag = ECU value = 75 }
      relation = { tag = ENG value = 150 }
      relation = { tag = FIN value = 90 }
      relation = { tag = FRA value = 65 }
      relation = { tag = GER value = -10 }
      relation = { tag = GUA value = 125 }
      relation = { tag = HAI value = 100 }
      relation = { tag = HOL value = 70 }
      relation = { tag = HON value = 100 }
      relation = { tag = IRE value = 75 }
      relation = { tag = IRQ value = 120 }
      relation = { tag = JAP value = 15 }
      relation = { tag = LIB value = 200 access = yes }
      relation = { tag = MAN value = 0 }
      #relation = { tag = MEN value = 0 }
      relation = { tag = MEX value = 125 }
      relation = { tag = NEP value = 100 }
      relation = { tag = NIC value = 100 }
      relation = { tag = NOR value = 75 }
      relation = { tag = NZL value = 125 }
      relation = { tag = OMN value = 100 }
      relation = { tag = PAN value = 175 }
      relation = { tag = PAR value = 75 }
      relation = { tag = PHI value = 200 access = yes }
      relation = { tag = PRU value = 75 }
      relation = { tag = SAF value = 125 }
      relation = { tag = SAL value = 100 }
      relation = { tag = SOV value = 35 }
      relation = { tag = SCH value = 0 guaranteed = { day = 29 month = december year = 1935 } }
      relation = { tag = SWE value = 75 }
      relation = { tag = URU value = 100 }
      relation = { tag = VEN value = 125 }
      relation = { tag = YEM value = 100 }	 
      }   
     SpyInfo                = {  country = "USA" NumberOfSpies = 11  }  

	ai_settings	= { flags = { convoy_gift_on_release = yes } }
	policy =  
	{  date = { year = 0 month = january day = 0  }  
     	democratic        = 10 
      	political_left    = 6  
      	freedom           = 10  
      	free_market       = 10  
      	professional_army = 10  
      	defense_lobby     = 5  
      	interventionism   = 1  
	}
	
	headofstate = { type = 9 id = 6001 }
	headofgovernment = { type = 9 id = 6002 }
	foreignminister = { type = 9 id = 6003 }
	armamentminister = { type = 9 id = 6077 }
	ministerofsecurity = { type = 9 id = 6005 }
	ministerofintelligence = { type = 9 id = 6006 }
	chiefofstaff = { type = 9 id = 6007 }
	chiefofarmy = { type = 9 id = 6008 }
	chiefofnavy = { type = 9 id = 6009 }
	chiefofair = { type = 9 id = 6010 }
	
	dormant_teams = { 147 145 } #ranger team
    dormant_ministers = { 6259 }

    nationalprovinces      = { 
	1786 #Presque Isle=>Greenville#
	1784 #Bangor=>Portland#
	1787 #Concord#
	1785 #Lewiston=>Manchester#
	1790 #Burlington=>Montpelier/Bennington#
	1794 #Watertown=>Watertown/Plattsburgh#
	1844 #Flint#
	1843 #Marquette#
	1849 #Duluth#
	1854 #Grand Forks=>Moorehead
	1852 #Minot#=>Fargo(split)
	1853 #Fort Peck#
	1864 #Great Falls=>GreatFalls/Dodson(merge)#
	1865 #Missoula#
	1861 #Coeur d'Alene=>Lewiston#
	1875 #Wenatchee=>Spokane(split)#
	1874 #Seattle#
	1877 #Tacoma#
	1873 #Yakima=>Richland#
	1872 #Spokane#
	1876 #Walla Walla=>Blue Mountains#
	1871 #Boise#
	1863 #Helena=>Anaconda#
	1862 #Bozeman=>Butte#
	1867 #Glendive=>Billings#
	1856 #Bismarck#
	1855 #Fargo#
	1847 #Minneapolis#
	1850 #Saint Paul=>Duluth#
	1848 #Superior=>Greenbay#
	1840 #Eau Claire#
	1841 #Greenbay#
	1842 #Grand Rapids#
	1845 #Detroit#
	1791 #Buffalo#
	1792 #Syracuse#
	1793 #Albany#
	1788 #Hartford#
	1789 #Boston#
	1796 #Providence=>Boston(split)#
	1799 #Newburgh=>New York(split)#
	1800 #Binghampton=>Syracuse#
	1797 #Newark#
	1804 #Scranton#
	1795 #New York#
	1803 #Williamsport=>Altoona(split)#
	1801 #Harrisburg#
	1805 #Philadelphia#
	1807 #Cape Charles=>Dover#
	1809 #Washington#
	1808 #Baltimore#
	1802 #Altoona#
	1798 #Warren=>Pittsburgh#
	1824 #Erie=>Cleveland#
	1825 #Cleveland#
	1821 #Columbus#
	1806 #Pittsburgh#
	1810 #Clarksburg#
	1814 #Arlington=>Charlottesville(split)#
	1813 #Richmond#
	1812 #Norfolk#
	1815 #Danville=>Roanoke#
	1816 #Charlottesville#
	1818 #Roanoke#
	1817 #Beckley=>Charleston(split)#
	1811 #Huntington=>Charleston(split)#
	1822 #Toledo=>Cleveland#
	1823 #Cincinnati=>Columbus#
	1820 #Lexington#
	1819 #Louisville#
	1827 #Evansville#
	1828 #Indianapolis#
	1826 #Fort Wayne#
	1832 #Chicago#
	1839 #Milwaukee#
	1829 #Peoria#
	1830 #Decatur#
	1831 #Belleville#
	1833 #Saint Louis#
 	1835 #Saint Chalres#
	1837 #Cedar Rapids#
	1846 #Rochester=>Cedar Rapids(split)#
	1838 #Des Moines#
	1834 #Saint Joseph=>Des Moines(split)#
	1836 #Springfield#
	1912 #Tulsa#
	1914 #Kansas City#
	1859 #Lincoln=>Kansas City(split)#
	1860 #Omaha#
	1857 #Sioux Falls#
	1851 #Miles City#
	1858 #Rapid City#
	1908 #Denver#
	1910 #Wichita#
	1909 #Colorado Springs=>Pueblo#
	1907 #Cheyenne=>Aspen#
	1866 #Casper#
	1868 #Billings#
	1898 #Rock Springs#
	1897 #Grand Junction#
	1899 #Saint George#
	1896 #Salt Lake City#
	1869 #Idaho Falls#
	1870 #Rexburg#
	1881 #Twin Falls#
	1894 #Elko#
	1893 #Las Vegas#
	1895 #Reno#
	1880 #Klamath Falls#
	1882 #Bend#
	1878 #Portland#
	1879 #Eugene#
	1890 #Eureka#
	1884 #Santa Rosa=>San Franzisco#
	1885 #Redding#
	1888 #Sacramento#
	1889 #San Francisco#
	1891 #Santa Barbara#
	1883 #Fresno#
	1887 #Los Angeles#
	1886 #San Diego#
	1892 #San Bernardino#
	1901 #Tucson=>Yuma#
	1900 #Phoenix#
	1902 #Flagstaff=>Tucson
	1904 #Albuquerque#
	1906 #Santa Fe# 
	1905 #Roswell#
	1903 #Carlsbad#
	1923 #El Paso#
	1927 #Abilene#
	1920 #Lubbock#
	1921 #Amarillo#
	1913 #Oklahoma City#
	1911 #Lawton#
	1924 #Dallas#
	1925 #Austin#
	1926 #San Antonio #
	1922 #Corpus Christi#
	1928 #Houston#
	1919 #Tyler#
	1916 #Ardmore#
	1917 #Fort Smith#
	1918 #Little Rock#
	1930 #Shreveport=>Alexandria#
	1932 #Baton Rouge#
	1934 #Lafayette#
	1929 #Monroe#
	1933 #Pine Bluff#
	1915 #Jonesboro#
	1938 #Vicksburg#
	1937 #Natchez#
	1931 #New Orleans#
	1944 #Mobile#
	1939 #Jackson#
	1935 #Tupelo#
	1940 #Memphis#
	1943 #Nashville#
	1941 #Chattanooga#
	1946 #Birmingham Al#
	1950 #Pensacola#
	1947 #Montgomery#
	1945 #Gadsden#
	1942 #Knoxville=>Nashville(split)#
	1964 #Asheville#
	1955 #Atlanta#
	1959 #Augusta#
	1954 #Macon#
	1951 #Tallahassee#
	1948 #Tampa#
	1936 #Tuscaloosa
    	1953 #Miami#
	1949 #Orlando#
	1952 #Jacksonville#
	1956 #Savannah#
	1960 #Charleston#
	1958 #Greenville=>Columbia(split)#
	1957 #Columbia#
	1962 #Charlotte#
	1963 #Wilmington#
	1961 #Raleigh#
#Alaska#
	2141 #Juneau#
	2147 #Valdez=>Anchorage(split)#
	2140 #Fairbanks#
	2142 #Anchorage#
	2146 #Tanana=>Fairbanks(split)#
    	2145 #Nome#
	2144 #Bethel=>Anchorage(split)#
	2139 #Dillingham=>Anchorage(split)#
	2143 #Chignik=>Anchorage(split)#
	2150 #Adak=>Amchitka/Kiska/Andreanof#
	2151 #Dutch Habor=>Unimak/Unalaska/Umnak/Yunaska#
	2174 #Attu Island#
#Islands#	 
	1683 #Guam#
	1673 #Wake#
	1751 #Mayerton#
	1733 #Pago Pago#
	1745 #Jarvis Island#
	1747 #Palmyra#
	1738 #Johnston#
	1739 #Midway#
	1765 #Puerto Rico#
#Hawaii#
	1735 #Kauai#
	1734 #Pearl Harbor#
	1737 #Maui#
	1736 #Hawaii#
#Panama canal#
	889 #Balboa#
#Guantanamo
  	1778 #Guantanamo Bay Naval Base#
                              }  


    ownedprovinces         = {  
    1786 #Presque Isle
	1784 #Bangor
	1787 #Concord 
	1785 #Lewiston
	1790 #Burlington
	1794 #Watertown
	1844 #Flint
	1843 #Marquette
	1849 #Duluth
	1854 #Grand Forks
	1852 #Minot
	1853 #Fort Peck
	1864 #Great Falls
	1865 #Missoula
	1861 #Coeur d'Alene
	1875 #Wenatchee
	1874 #Seattle
	1877 #Tacoma
	1873 #Yakima 
	1872 #Spokane
	1876 #Walla Walla
	1871 #Boise
	1863 #Helena
	1862 #Bozeman
	1867 #Glendive
	1856 #Bismarck
	1855 #Fargo
	1847 #Minneapolis
	1850 #Saint Paul
	1848 #Superior
	1840 #Eau Claire
	1841 #Greenbay
	1842 #Grand Rapids
	1845 #Detroit
	1791 #Buffalo
	1792 #Syracuse
	1793 #Albany
	1788 #Hartford
	1789 #Boston
	1796 #Providence
	1799 #Newburgh
	1800 #Binghampton
	1797 #Newark
	1804 #Scranton
	1795 #New York
	1803 #Williamsport
	1801 #Harrisburg
	1805 #Philadelphia
	1807 #Cape Charles 
	1809 #Washington 
	1808 #Baltimore
	1802 #Altoona
	1798 #Warren
	1824 #Erie
	1825 #Cleveland
	1821 #Columbus
	1806 #Pittsburgh
	1810 #Clakrsburg
	1814 #Arlington
	1813 #Richmond
	1812 #Norfolk
	1815 #Danville
	1816 #Charlottesville
	1818 #Roanoke
	1817 #Beckley
	1811 #Huntington
	1822 #Toledo
	1823 #Cincinnati
	1820 #Lexington
	1819 #Louisville
	1827 #Evansville
	1828 #Indianapolis 
	1826 #Fort Wayne
	1832 #Chicago
	1839 #Milwaukee
	1829 #Peoria 
	1830 #Decatur
	1831 #Belleville
	1833 #Saint Louis
    1835 #Saint Chalres
	1837 #Cedar Rapids
	1846 #Rochester
	1838 #Des Moines
	1834 #Saint Joseph
	1836 #Springfield 
	1912 #Tulsa
	1914 #Kansas City
	1859 #Lincoln
	1860 #Omaha
	1857 #Sioux Falls
	1851 #Miles City
	1858 #Rapid City
	1908 #Denver
	1910 #Wichita
	1909 #Colorado Springs
	1907 #Cheyenne
	1866 #Casper
	1868 #Billings
	1898 #Rock Springs
	1897 #Grand Junction
	1899 #Saint George
	1896 #Salt Lake City
	1869 #Idaho Falls
	1870 #Rexburg
	1881 #Twin Falls
	1894 #Elko
	1893 #Las Vegas
	1895 #Reno
	1880 #Klamath Falls
	1882 #Bend
	1878 #Portland
	1879 #Eugene
	1890 #Eureka
	1884 #Santa Rosa
	1885 #Redding
	1888 #Sacramento
	1889 #San Francisco
	1891 #Santa Barbara
	1883 #Fresno
	1887 #Los Angeles
	1886 #San Diego
	1892 #San Bernardino
	1901 #Tucson
	1900 #Phoenix 
	1902 #Flagstaff
	1904 #Albuquerque
	1906 #Santa Fe 
	1905 #Roswell
	1903 #Carlsbad
	1923 #El Paso
	1927 #Abilene
	1920 #Lubbock
	1921 #Amarillo
	1913 #Oklahoma City
	1911 #Lawton
	1924 #Dallas
	1925 #Austin
	1926 #San Antonio 
	1922 #Corpus Christi
	1928 #Houston
	1919 #Tyler
	1916 #Ardmore
	1917 #Fort Smith
	1918 #Little Rock
	1930 #Shreveport
	1932 #Baton Rouge
	1934 #Lafayette
	1929 #Monroe
	1933 #Pine Bluff
	1915 #Jonesboro 
	1938 #Vicksburg
	1937 #Natchez
	1931 #New Orleans
	1944 #Mobile
	1939 #Jackson
	1935 #Tupelo
	1940 #Memphis
	1943 #Nashville
	1941 #Chattanooga
	1946 #Birmingham Al
	1950 #Pensacola
	1947 #Montgomery
	1945 #Gadsden
	1942 #Knoxville
	1964 #Asheville
	1955 #Atlanta
	1959 #Augusta
	1954 #Macon
	1951 #Tallahassee 
	1948 #Tampa 
	1936 #Tuscaloosa
    1953 #Miami  
	1949 #Orlando
	1952 #Jacksonville 
	1956 #Savannah
	1960 #Charleston
	1958 #Greenville
	1957 #Columbia 
	1962 #Charlotte
	1963 #Wilmington
	1961 #Raleigh
	#Alaska#
	2141 #Juneau
	2147 #Valdez
	2140 #Fairbanks
	2142 #Anchorage
	2146 #Tanana
    2145 #Nome
	2144 #Bethel
	2139 #Dillingham
	2143 #Chignik
	2150 #Unalaska
	2151 #Dutch Habor
	2174 #Attu Island
	#Islands#	 
	1683 #Guam
	1673 #Wake
	1751 #Mayerton
	1733 #Pago Pago
	1745 #Jarvis Island
	1747 #Palmyra
	1738 #Johnston
	1739 #Midway
	1765 #Puerto Rico
	#Hawaii#
	1735 #Kauai
	1734 #Pearl Harbor
	1737 #Maui
	1736 #Hawaii
	#Panama canal#
	889 #Balboa
	#Guantanamo
    1778 #Guantanamo Bay Naval Base  
                              }  


    controlledprovinces    = {  
	1786 #Presque Isle
	1784 #Bangor
	1787 #Concord 
	1785 #Lewiston
	1790 #Burlington
	1794 #Watertown
	1844 #Flint
	1843 #Marquette
	1849 #Duluth
	1854 #Grand Forks
	1852 #Minot
	1853 #Fort Peck
	1864 #Great Falls
	1865 #Missoula
	1861 #Coeur d'Alene
	1875 #Wenatchee
	1874 #Seattle
	1877 #Tacoma
	1873 #Yakima 
	1872 #Spokane
	1876 #Walla Walla
	1871 #Boise
	1863 #Helena
	1862 #Bozeman
	1867 #Glendive
	1856 #Bismarck
	1855 #Fargo
	1847 #Minneapolis
	1850 #Saint Paul
	1848 #Superior
	1840 #Eau Claire
	1841 #Greenbay
	1842 #Grand Rapids
	1845 #Detroit
	1791 #Buffalo
	1792 #Syracuse
	1793 #Albany
	1788 #Hartford
	1789 #Boston
	1796 #Providence
	1799 #Newburgh
	1800 #Binghampton
	1797 #Newark
	1804 #Scranton
	1795 #New York
	1803 #Williamsport
	1801 #Harrisburg
	1805 #Philadelphia
	1807 #Cape Charles 
	1809 #Washington 
	1808 #Baltimore
	1802 #Altoona
	1798 #Warren
	1824 #Erie
	1825 #Cleveland
	1821 #Columbus
	1806 #Pittsburgh
	1810 #Clakrsburg
	1814 #Arlington
	1813 #Richmond
	1812 #Norfolk
	1815 #Danville
	1816 #Charlottesville
	1818 #Roanoke
	1817 #Beckley
	1811 #Huntington
	1822 #Toledo
	1823 #Cincinnati
	1820 #Lexington
	1819 #Louisville
	1827 #Evansville
	1828 #Indianapolis 
	1826 #Fort Wayne
	1832 #Chicago
	1839 #Milwaukee
	1829 #Peoria 
	1830 #Decatur
	1831 #Belleville
	1833 #Saint Louis
    1835 #Saint Chalres
	1837 #Cedar Rapids
	1846 #Rochester
	1838 #Des Moines
	1834 #Saint Joseph
	1836 #Springfield 
	1912 #Tulsa
	1914 #Kansas City
	1859 #Lincoln
	1860 #Omaha
	1857 #Sioux Falls
	1851 #Miles City
	1858 #Rapid City
	1908 #Denver
	1910 #Wichita
	1909 #Colorado Springs
	1907 #Cheyenne
	1866 #Casper
	1868 #Billings
	1898 #Rock Springs
	1897 #Grand Junction
	1899 #Saint George
	1896 #Salt Lake City
	1869 #Idaho Falls
	1870 #Rexburg
	1881 #Twin Falls
	1894 #Elko
	1893 #Las Vegas
	1895 #Reno
	1880 #Klamath Falls
	1882 #Bend
	1878 #Portland
	1879 #Eugene
	1890 #Eureka
	1884 #Santa Rosa
	1885 #Redding
	1888 #Sacramento
	1889 #San Francisco
	1891 #Santa Barbara
	1883 #Fresno
	1887 #Los Angeles
	1886 #San Diego
	1892 #San Bernardino
	1901 #Tucson
	1900 #Phoenix 
	1902 #Flagstaff
	1904 #Albuquerque
	1906 #Santa Fe 
	1905 #Roswell
	1903 #Carlsbad
	1923 #El Paso
	1927 #Abilene
	1920 #Lubbock
	1921 #Amarillo
	1913 #Oklahoma City
	1911 #Lawton
	1924 #Dallas
	1925 #Austin
	1926 #San Antonio 
	1922 #Corpus Christi
	1928 #Houston
	1919 #Tyler
	1916 #Ardmore
	1917 #Fort Smith
	1918 #Little Rock
	1930 #Shreveport
	1932 #Baton Rouge
	1934 #Lafayette
	1929 #Monroe
	1933 #Pine Bluff
	1915 #Jonesboro 
	1938 #Vicksburg
	1937 #Natchez
	1931 #New Orleans
	1944 #Mobile
	1939 #Jackson
	1935 #Tupelo
	1940 #Memphis
	1943 #Nashville
	1941 #Chattanooga
	1946 #Birmingham Al
	1950 #Pensacola
	1947 #Montgomery
	1945 #Gadsden
	1942 #Knoxville
	1964 #Asheville
	1955 #Atlanta
	1959 #Augusta
	1954 #Macon
	1951 #Tallahassee 
	1948 #Tampa 
	1936 #Tuscaloosa
    1953 #Miami  
	1949 #Orlando
	1952 #Jacksonville 
	1956 #Savannah
	1960 #Charleston
	1958 #Greenville
	1957 #Columbia 
	1962 #Charlotte
	1963 #Wilmington
	1961 #Raleigh
	#Alaska#
	2141 #Juneau
	2147 #Valdez
	2140 #Fairbanks
	2142 #Anchorage
	2146 #Tanana
    2145 #Nome
	2144 #Bethel
	2139 #Dillingham
	2143 #Chignik
	2150 #Unalaska
	2151 #Dutch Habor
	2174 #Attu Island
	#Islands#	 
	1683 #Guam
	1673 #Wake
	1751 #Mayerton
	1733 #Pago Pago
	1745 #Jarvis Island
	1747 #Palmyra
	1738 #Johnston
	1739 #Midway
	1765 #Puerto Rico
	#Hawaii#
	1735 #Kauai
	1734 #Pearl Harbor
	1737 #Maui
	1736 #Hawaii
	#Panama canal#
	889 #Balboa
	#Guantanamo
    1778 #Guantanamo Bay Naval Base
	}  
     

 

 
  #####################   
   # technology   data #   
   #####################  
   
    deactivate = { }
	blueprints = { 3810 4060 } # TP 1936, Interceptors 1937 (OOB)
	inventions = { 8023 } # Monitor
   
    techapps              
	= {  
       ############################
       4010 4020 4030 4040 # Single Engined 1929, Int, Fighter, CAS 1930
       4050 # Single Engined 1936

       4290 4300 4310 4320 # Double Engined 1929, tactical, naval, escort brigade 1930
       4330 4370 # Double Engined 1936, Transport 1937

       4570 # CAG 1930
       4520 # Strategic 1930

       9010 9020 9030 # Aerial warfare, basic doctrines

       #############################

       2800 2810 # Basic Armoured Car

       2290 2300 # GW artillery

       2450 2460 # Early Static AA

       2510 # Basic AA
	   
	   17000 # 1936 rocket artillery/mortars

       1010 # Early infantry

       1150 1110 # Marines, Mountains

       1190 1200 # Early Cavalry

       1310 # Rear Area Supply Dumps (allows for SR)

       5010 # Agriculture
       5050 5060 # Improved Machine Tools
       5080 5090 # Construction Engineering
       5310 5320 # Basic CT machine
       5470 5480 # Nukes labs

       6010 6020 # Superior firepower (land)

       #Naval doctrines
       8010 8070 8130 8180 8240 8610 8660 8710 8760

       #Naval Techs
		# Escorts up to pre-WW2
		3010	3040	3070	3100
		3020	3050	3080	3110
		3030 15250	3060	3090	3120
		
		3350 3390 3430 3480 3510 15100 # Capital Design up to 1935
		3360 3440 3490 3520 3540 # CA up to 1936
		3370 3400 3450 3460 # BC up to 1918
		3380 3410 3420 3470 3500 3530 3550 # BB up to 1936
		7550 # WW1 Monitor
       15090 16030 3190 3200 3210 # Prewar Carrier, CV and CVE 1930
       3220 3230 # Carrier 1936, CV 1937
       3700 15080 3760 # Prewar SS, SS 1930 & SS 1936
       3800 # Prewar TP
       3850 # Torpedoes 36
	   3900 # ASW 1936
	   
	   5190 5200
	   
	   2010 2550 2630 # tanks
	   
      } 

#####################################################
# US Army
#####################################################	  
# by Lord Rommel - 2.2.2012
# Stand: 3 InfDivs, 2 KavDivs, 1 PzDiv, 
# + "National Guard" Kavallerie-Divisionen
# + Hawaii Division und Phillippine Divisionen
# + US Marines
#####################################################	
      
landunit = {
	location = 1809 #Washington
	name = "United States Army"
 	id = { type = 14800 id = 50 }
		division = { id = { type = 14800 id = 51 } name = "US Army HQ" type = hq model = 0 experience = 25 }
	}  
	  
landunit = {
	location = 1797 #Newark
	name = "1st US Army Corps"
 	id = { type = 14800 id = 1 }
		division = { id = { type = 14800 id = 2 } name = "1st 'Big Red One' Division" type = infantry model = 0 experience = 15 }
	}

landunit = {
	location = 1809 #Washington
	name = "2nd US Army Corps"
 	id = { type = 14800 id = 3 }
		division = { id = { type = 14800 id = 4 } name = "2nd 'Indianhead' Division" type = infantry model = 0 experience = 15 extra = rocket_artillery brigade_model = 0 }
	}

landunit = {
	location = 1887 #Los Angeles
	name = "3rd US Army Corps"
 	id = { type = 14800 id = 5 }
		division = { id = { type = 14800 id = 6 } name = "3rd 'Rock of the Marne' Division" type = infantry model = 0 experience = 15 }
	}

landunit = {
	location = 1908 #Denver
	name = "United States Cavalry"
	id = { type = 14800 id = 7 }
		division = { id = { type = 14800 id = 8 } name = "1st Cavalry 'The 1st Team' Div."    type = cavalry model = 0 strength = 50 experience = 15 } #1st Cavalry Division
		division = { id = { type = 14800 id = 9 } name = "2nd Cavalry Division"               type = cavalry model = 0 strength = 50 experience = 15 }
		division = { id = { type = 14800 id = 10 } name = "1st Armored 'Old Ironsides' Div."  type = armor   model = 0 strength = 5  experience = 20 }
	}
	
landunit = {
	location = 1734 #Hawaii
	name = "Hawaii Force"
	id = { type = 14800 id = 11 }
		division = { id = { type = 14800 id = 12 } name = "Hawaiian Division" type = infantry model = 0 experience = 15 }
	}

landunit = {
	location = 1565 #Manila
	name = "Phillippine Force"
	locked   = yes
	id = { type = 14800 id = 13 }
		division = { id = { type = 14800 id = 14 } name = "Phillippine Division" type = d_02 model = 0 experience = 35 extra = artillery }
	}
	
#####################################################
# US Army build up programm ID 3182116 - 3182118
#####################################################	
	
landdivision = { dormant = yes id = { type = 14800 id = 80 } name = "5th 'Red Diamond' Division"         type = infantry    model = 2 }
landdivision = { dormant = yes id = { type = 14800 id = 81 } name = "6th 'Red Star' Division"            type = infantry    model = 2 }
landdivision = { dormant = yes id = { type = 14800 id = 82 } name = "4th 'Ivy' Division"                 type = infantry    model = 2 }
landdivision = { dormant = yes id = { type = 14800 id = 83 } name = "7th 'Bayonet!' Division"            type = infantry    model = 2 }
landdivision = { dormant = yes id = { type = 14800 id = 84 } name = "8th 'Pathfinder' Division"          type = infantry    model = 2 }
landdivision = { dormant = yes id = { type = 14800 id = 85 } name = "9th 'Varsity' Division"             type = infantry    model = 2 }
landdivision = { dormant = yes id = { type = 14800 id = 86 } name = "2nd Armored 'Hell on Wheels' Div."  type = light_armor model = 2 extra = super_heavy_armor brigade_model = 1 }
landdivision = { dormant = yes id = { type = 14800 id = 87 } name = "3rd Armored 'Spearhead' Div."       type = light_armor model = 2 extra = super_heavy_armor brigade_model = 1 }
landdivision = { dormant = yes id = { type = 14800 id = 88 } name = "4th Armored 'Breakthrough' Div."    type = armor       model = 2 } 
landdivision = { dormant = yes id = { type = 14800 id = 89 } name = "5th Armored 'Victory' Div."         type = armor       model = 2 } 

landdivision = { dormant = yes id = { type = 14800 id = 90 } name = "1st Special Service Force"          type = d_07        model = 2 strength = 10 } #1200 soldiers
landdivision = { dormant = yes id = { type = 14800 id = 91 } name = "1st US Army Rangers"                type = d_07        model = 2 strength = 25 } #3000 soldiers
	
landdivision = { dormant = yes id = { type = 14800 id = 92 } name = "USAFFE Command"                     type = hq          model = 1 }
landdivision = { dormant = yes id = { type = 14800 id = 93 } name = "Americal Division"	                 type = infantry    model = 2 extra = light_armor_brigade brigade_model = 5 }
landdivision = { dormant = yes id = { type = 14800 id = 95 } name = "Poppy Force"                        type = garrison    model = 2 extra = anti_air brigade_model = 3 }
landdivision = { dormant = yes id = { type = 14800 id = 94 } name = "New Hebrides Defense Force"	     type = militia     model = 2 strength = 25 }

landdivision = { dormant = yes id = { type = 14800 id = 96 } name = "2nd USMC Raider Battalion"	         type = garrison    model = 2 strength = 10 }
landdivision = { dormant = yes id = { type = 14800 id = 97 } name = "24th 'Victory' Division"	         type = infantry    model = 2 strength = 50 }
landdivision = { dormant = yes id = { type = 14800 id = 98 } name = "25th 'Tropic Lightning' Division"	 type = infantry    model = 2 strength = 50 }
		
#####################################################
# National Guard
#####################################################	
#
# Alle Divisionen wurden in den 1920 als nationale #
# Reserve formiert. Sie nahmen zum letzten mal 1940 #
# an einem Armeemanöver teil. Danach wurden sie #
# aufgelöst und verteilt. Meistens bestanden sie nur #
# auf dem Papier mit reginalen Kleinverbänden (Polizei- #
# Reiterstaffeln und solche Aufgaben und Formationen). #
#
#####################################################

landunit = {
	location = 1809 #Washington
	name = "United States National Guard Cavalry"
	id = { type = 14800 id = 15 }
	    division = { id = { type = 14800 id = 16 } name = "3rd Cavalry Division"  type = cavalry model = 0 strength = 5 }
		division = { id = { type = 14800 id = 17 } name = "21st Cavalry Division" type = cavalry model = 0 strength = 5 }
		division = { id = { type = 14800 id = 18 } name = "22nd Cavalry Division" type = cavalry model = 0 strength = 5 }
		division = { id = { type = 14800 id = 19 } name = "23rd Cavalry Division" type = cavalry model = 0 strength = 5 }
		division = { id = { type = 14800 id = 20 } name = "24th Cavalry Division" type = cavalry model = 0 strength = 5 }
		division = { id = { type = 14800 id = 21 } name = "61st Cavalry Division" type = cavalry model = 0 strength = 5 }
		division = { id = { type = 14800 id = 22 } name = "62nd Cavalry Division" type = cavalry model = 0 strength = 5 }
		division = { id = { type = 14800 id = 23 } name = "63rd Cavalry Division" type = cavalry model = 0 strength = 5 }
		division = { id = { type = 14800 id = 24 } name = "64th Cavalry Division" type = cavalry model = 0 strength = 5 }
		division = { id = { type = 14800 id = 25 } name = "65th Cavalry Division" type = cavalry model = 0 strength = 5 }
		division = { id = { type = 14800 id = 26 } name = "66th Cavalry Division" type = cavalry model = 0 strength = 5 }
    }
	
#####################################################
# USMC
# Aktive Regimenter: 5th (1st Div), 6th (2nd Div), 10th (2nd Div), 
# 12th unklar
#####################################################
	
landunit = {
	location = 1809 #Washington
	name = "Camp Quantico"
	id = { type = 14800 id = 60 }
	    division = { id = { type = 14800 id = 61 } name = "1st Marine 'The Old Breed' Div."  type = marine model = 0 strength = 15 experience = 20 }	
    }
	
landunit = {
	location = 1734 #Hawaii
	name = "Fleet Marine Force"
	id = { type = 14800 id = 62 }
	    division = { id = { type = 14800 id = 63 } name = "2nd Marine 'Follow Me' Division"  type = marine model = 0 strength = 30 experience = 20 }	
    }
	
#####################################################
# US Airforce
#####################################################		
		
airunit = {
	location = 1886 #San Diego
	base = 1886 #San Diego
	id = { type = 14800 id = 27 }
	name = "1st USAAF Fighter Group"
		division = { id = { type = 14800 id = 28 } name = "1st USAAF Fighter Wing" type = interceptor model = 1 experience = 10 }
	}

airunit = {
	location = 1874 #Seattle
	base = 1874 #Seattle
	id = { type = 14800 id = 29 }
	name = "2nd USAAF Bombardment Group"
		division = { id = { type = 14800 id = 30 } name = "2nd USAAF Strategic Bomb. Wing" type = strategic_bomber model = 0 extra = escort brigade_model = 0 strength = 40 experience = 10 }
	}

airunit = {
	location = 1809 #Washington
	base = 1809 #Washington
	id = { type = 14800 id = 31 }
	name = "1st USAAF Bombardment Group"
		division = { id = { type = 14800 id = 32 } name = "2nd USAAF Tactical Bomb. Wing" type = tactical_bomber model = 0 extra = escort brigade_model = 0 experience = 10 }
	}

airunit = {
	location = 889 #Panama canal
	base = 889 #Panama canal
 	id = { type = 14800 id = 33 }
	name = "5th USAAF Bombardment Group"
		division = { id = { type = 14800 id = 34 } name = "5th USAAF Tactical Bomb. Wing" type = tactical_bomber model = 0 extra = escort brigade_model = 0 experience = 10 }
	}

airunit = {
	location = 1896 #Salt Lake City
	base = 1896 #Salt Lake City 
	id = { type = 14800 id = 35 }
	name = "7th USAAF Bombardment Group"
		division = { id = { type = 14800 id = 36 } name = "1st USAAF Tactical Bomb. Wing" type = tactical_bomber model = 0 extra = escort brigade_model = 0 experience = 10 }
	}

airunit = {
	location = 1795 #New York
	base = 1795 #New York
	id = { type = 14800 id = 37 }
	name = "US Army Airforce" 
		division = { id = { type = 14800 id = 38 } name = "9th USAAF Fighter Wing" type = interceptor model = 1 experience = 10 }
		division = { id = { type = 14800 id = 39 } name = "12th USAAF Tactical Bomb. Wing" type = tactical_bomber model = 0 extra = escort brigade_model = 0 experience = 10 }
	}
	
###############################################
# dormant ex-AVG / Flying Tigers
###############################################
airdivision = { id = { type = 14800 id = 40 } name = "23rd Fighter Group"  type = interceptor model = 2 dormant = yes experience = 20 }
airdivision = { id = { type = 14800 id = 41 } name = "412th Fighter Group" type = interceptor model = 5 dormant = yes strength = 25   }
#US Eagles sqdrs 
airdivision = { id = { type = 14800 id = 42 } name = "4th Fighter Group"   type = d_01   model = 3 dormant = yes experience = 45 }
##################################################################
# USN - United states navy
##################################################################

navalunit = { 
	name = "Battleforce Battleships" 
	id = { type = 14800 id = 100 } 
	location = 1734 #Pearl Habor
	base = 1734 #Pearl Habor
	division = { id = { type = 14800 id = 101 } name = "USS Nevada" type = battleship model = 1 experience = 20 } 
	division = { id = { type = 14800 id = 102 } name = "USS Arizona" type = battleship model = 2 extra = naval_improved_hull_l experience = 20 } 
	division = { id = { type = 14800 id = 103 } name = "USS Pennsylvania" type = battleship model = 2 extra = naval_improved_hull_l experience = 20 } 
	division = { id = { type = 14800 id = 104 } name = "USS Oklahoma" type = battleship model = 1 experience = 20 } 
	division = { id = { type = 14800 id = 105 } name = "USS Tennessee" type = battleship model = 2 experience = 20 } 
	division = { id = { type = 14800 id = 106 } name = "USS California" type = battleship model = 2 experience = 20 } 
	division = { id = { type = 14800 id = 107 } name = "USS Colorado" type = battleship model = 3 experience = 20 } 
	division = { id = { type = 14800 id = 108 } name = "USS West Virginia" type = battleship model = 3 experience = 20 } 
	division = { id = { type = 14800 id = 109 } name = "USS Maryland" type = battleship model = 3 experience = 20 } 
} 


navalunit = { 
name = "Atlantic Fleet Battleships" 
id = { type = 14800 id = 110 } 
location = 1812 #Norfolk 
base = 1812 #Norfolk 
division = { id = { type = 14800 id = 111 } name = "USS New Mexico" type = battleship model = 2 experience = 20 } 
division = { id = { type = 14800 id = 112 } name = "USS Mississippi" type = battleship model = 2 experience = 20 } 
division = { id = { type = 14800 id = 113 } name = "USS Idaho" type = battleship model = 2 experience = 20 } 
division = { id = { type = 14800 id = 114 } name = "USS Arkansas" type = battleship model = 1 extra = naval_improved_hull_l experience = 20 } 
division = { id = { type = 14800 id = 115 } name = "USS New York" type = battleship model = 1 extra = naval_improved_hull_l experience = 20 } 
division = { id = { type = 14800 id = 116 } name = "USS Texas" type = battleship model = 1 extra = naval_improved_hull_l experience = 20 } 
} 



navalunit = { 
name = "Carrier Division One" 
id = { type = 14800 id = 117 } 
location = 1812 #Norfolk 
base = 1812 #Norfolk
division = { id = { type = 14800 id = 118 } name = "USS Lexington" type = carrier model = 0 extra = CAG brigade_model = 0 experience = 20 } 
division = { id = { type = 14800 id = 119 } name = "USS Ranger" type = light_carrier model = 2 extra = light_cag experience = 20 } 
} 


navalunit = { 
name = "Carrier Division Two" 
id = { type = 14800 id = 120 } 
location = 1886 #San Diego 
base = 1886 #San Diego 
division = { id = { type = 14800 id = 121 } name = "USS Saratoga" type = carrier model = 0 extra = CAG brigade_model = 0 experience = 20 } 
division = { id = { type = 14800 id = 561 } name = "USS Wright" type = escort_carrier model = 1 experience = 20 }
division = { id = { type = 14800 id = 562 } name = "USS Jason" type = escort_carrier model = 0 experience = 20 }
} 


navalunit = { 
name = "Asiatic Fleet" 
id = { type = 14800 id = 123 } 
location = 1886 #San Diego 
base = 1886 #San Diego
division = { id = { type = 14800 id = 124 } name = "USS Houston" type = heavy_cruiser model = 4 extra = floatplane experience = 20 } 
division = { id = { type = 14800 id = 125 } name = "USS Memphis" type = light_cruiser model = 3 experience = 20 } 
division = { id = { type = 14800 id = 126 } name = "USS Marblehead" type = light_cruiser model = 3 experience = 20 } 
} 


navalunit = { 
name = "Atlantic Fleet Cruisers" 
id = { type = 14800 id = 127 } 
location = 1812 #Norfolk 
base = 1812 #Norfolk 
division = { id = { type = 14800 id = 128 } name = "USS Augusta" type = heavy_cruiser model = 4 extra = floatplane experience = 20 } 
division = { id = { type = 14800 id = 129 } name = "USS Louisville" type = heavy_cruiser model = 4 extra = floatplane experience = 20 } 
division = { id = { type = 14800 id = 130 } name = "USS Tuscaloosa" type = heavy_cruiser model = 5 extra = floatplane experience = 20 } 
division = { id = { type = 14800 id = 131 } name = "USS Indianapolis" type = heavy_cruiser model = 4 extra = floatplane experience = 20 } 
division = { id = { type = 14800 id = 132 } name = "USS Concord" type = light_cruiser model = 3 experience = 20 } 
division = { id = { type = 14800 id = 133 } name = "USS Cincinnati" type = light_cruiser model = 3 experience = 20 } 
division = { id = { type = 14800 id = 134 } name = "USS Milwaukee" type = light_cruiser model = 3 experience = 20 } 
division = { id = { type = 14800 id = 135 } name = "USS Omaha" type = light_cruiser model = 3 experience = 20 } 
} 



navalunit = { 
name = "Scouting Force Cruisers" 
id = { type = 14800 id = 136 } 
location = 1886 #San Diego 
base = 1886 #San Diego 
division = { id = { type = 14800 id = 137 } name = "USS Pensacola" type = heavy_cruiser model = 4 extra = floatplane experience = 20 } 
division = { id = { type = 14800 id = 138 } name = "USS Salt Lake City" type = heavy_cruiser model = 4 extra = floatplane experience = 20 } 
division = { id = { type = 14800 id = 139 } name = "USS Chicago" type = heavy_cruiser model = 4 extra = floatplane experience = 20 } 
division = { id = { type = 14800 id = 140 } name = "USS Northampton" type = heavy_cruiser model = 4 extra = floatplane experience = 20 } 
division = { id = { type = 14800 id = 141 } name = "USS Chester" type = heavy_cruiser model = 4 extra = floatplane experience = 20 } 
division = { id = { type = 14800 id = 142 } name = "USS Portland" type = heavy_cruiser model = 4 extra = floatplane experience = 20 } 
} 


navalunit = { 
name = "Battle Force Cruisers" 
id = { type = 14800 id = 143 } 
location = 1734 #Pearl Habor 
base = 1734 #Pearl Habor 
division = { id = { type = 14800 id = 144 } name = "USS New Orleans" type = heavy_cruiser model = 5 extra = floatplane experience = 20 } 
division = { id = { type = 14800 id = 145 } name = "USS Astoria" type = heavy_cruiser model = 5 extra = floatplane experience = 20 } 
division = { id = { type = 14800 id = 146 } name = "USS Minneapolis" type = heavy_cruiser model = 5 extra = floatplane experience = 20 } 
division = { id = { type = 14800 id = 147 } name = "USS San Francisco" type = heavy_cruiser model = 5 extra = floatplane experience = 20 } 
division = { id = { type = 14800 id = 148 } name = "USS Richmond" type = light_cruiser model = 3 experience = 20 } 
division = { id = { type = 14800 id = 149 } name = "USS Trenton" type = light_cruiser model = 3 experience = 20 } 
division = { id = { type = 14800 id = 150 } name = "USS Raleigh" type = light_cruiser model = 3 experience = 20 } 
division = { id = { type = 14800 id = 151 } name = "USS Detroit" type = light_cruiser model = 3 experience = 20 } 
} 



navalunit = { 
name = "Submarine Fleet Reserve" 
id = { type = 14800 id = 152 } 
location = 1805 #Philadelphia 
base = 1805 #Philadelphia 
division = { id = { type = 14800 id = 153 } name = "USS S-14" type = submarine model = 0 experience = 5 } 
division = { id = { type = 14800 id = 154 } name = "USS S-15" type = submarine model = 0 experience = 5 } 
division = { id = { type = 14800 id = 155 } name = "USS S-16" type = submarine model = 0 experience = 5 } 
division = { id = { type = 14800 id = 156 } name = "USS S-17" type = submarine model = 0 experience = 5 } 
division = { id = { type = 14800 id = 157 } name = "USS S-48" type = submarine model = 0 experience = 5 } 
division = { id = { type = 14800 id = 158 } name = "USS R-1" type = nuclear_submarine model = 1 experience = 5 } 
division = { id = { type = 14800 id = 559 } name = "USS R-8" type = nuclear_submarine model = 1 experience = 5 } 
division = { id = { type = 14800 id = 159 } name = "USS R-12" type = nuclear_submarine model = 1 experience = 5 } 
division = { id = { type = 14800 id = 160 } name = "USS R-15" type = nuclear_submarine model = 1 experience = 5 } 
division = { id = { type = 14800 id = 161 } name = "USS R-16" type = nuclear_submarine model = 1 experience = 5 } 
division = { id = { type = 14800 id = 162 } name = "USS R-17" type = nuclear_submarine model = 1 experience = 5 } 
division = { id = { type = 14800 id = 163 } name = "USS R-18" type = nuclear_submarine model = 1 experience = 5 } 
division = { id = { type = 14800 id = 164 } name = "USS R-19" type = nuclear_submarine model = 1 experience = 5 } 
division = { id = { type = 14800 id = 558 } name = "USS R-20" type = nuclear_submarine model = 1 experience = 5 } 
division = { id = { type = 14800 id = 165 } name = "USS R-3" type = nuclear_submarine model = 1 experience = 5 } 
division = { id = { type = 14800 id = 167 } name = "USS R-6" type = nuclear_submarine model = 1 experience = 5 } 
division = { id = { type = 14800 id = 168 } name = "USS R-7" type = nuclear_submarine model = 1 experience = 5 } 
division = { id = { type = 14800 id = 417 } name = "USS R-9" type = nuclear_submarine model = 1 experience = 5 } 
division = { id = { type = 14800 id = 418 } name = "USS O-2" type = nuclear_submarine model = 1 experience = 5 } 
division = { id = { type = 14800 id = 419 } name = "USS O-3" type = nuclear_submarine model = 1 experience = 5 } 
division = { id = { type = 14800 id = 420 } name = "USS O-4" type = nuclear_submarine model = 1 experience = 5 }
division = { id = { type = 14800 id = 421 } name = "USS O-6" type = nuclear_submarine model = 1 experience = 5 } 
division = { id = { type = 14800 id = 422 } name = "USS O-7" type = nuclear_submarine model = 1 experience = 5 } 
division = { id = { type = 14800 id = 423 } name = "USS O-8" type = nuclear_submarine model = 1 experience = 5 } 
division = { id = { type = 14800 id = 424 } name = "USS O-9" type = nuclear_submarine model = 1 experience = 5 }  
division = { id = { type = 14800 id = 425 } name = "USS O-10" type = nuclear_submarine model = 1 experience = 5 }
} 

navalunit = { 
name = "Submarine School of New London" 
id = { type = 14800 id = 434 } 
location = 1789 #Boston (New London) 
base = 1789 #Boston (New London)
division = { id = { type = 14800 id = 435 } name = "USS S-20" type = submarine model = 0 experience = 5 } 
division = { id = { type = 14800 id = 436 } name = "USS S-22" type = submarine model = 0 experience = 5 } 
division = { id = { type = 14800 id = 437 } name = "USS R-10" type = nuclear_submarine model = 1 experience = 5 } 
division = { id = { type = 14800 id = 438 } name = "USS R-11" type = nuclear_submarine model = 1 experience = 5 } 
division = { id = { type = 14800 id = 439 } name = "USS R-13" type = nuclear_submarine model = 1 experience = 5 } 
division = { id = { type = 14800 id = 440 } name = "USS R-14" type = nuclear_submarine model = 1 experience = 5 } 
division = { id = { type = 14800 id = 441 } name = "USS R-2" type = nuclear_submarine model = 1 experience = 5 } 
division = { id = { type = 14800 id = 442 } name = "USS R-4" type = nuclear_submarine model = 1 experience = 5 } 
division = { id = { type = 14800 id = 443 } name = "USS R-5" type = nuclear_submarine model = 1 experience = 5 } 
}

navalunit = { 
name = "Submarine Division 19" 
id = { type = 14800 id = 169 } 
location = 889 #Panama canal
base = 889 
division = { id = { type = 14800 id = 170 } name = "USS S-10" type = submarine model = 0 experience = 5 } 
division = { id = { type = 14800 id = 171 } name = "USS S-11" type = submarine model = 0 experience = 5 } 
division = { id = { type = 14800 id = 172 } name = "USS S-12" type = submarine model = 0 experience = 5 } 
division = { id = { type = 14800 id = 173 } name = "USS S-13" type = submarine model = 0 experience = 5 } 
division = { id = { type = 14800 id = 174 } name = "USS S-42" type = submarine model = 0 experience = 5 } 
} 


navalunit = { 
name = "Asiatic Fleet Submarine Division" 
id = { type = 14800 id = 180 } 
location = 1734 #Pearl Habor 
base = 1734 #Pearl Habor
division = { id = { type = 14800 id = 181 } name = "USS S-30" type = submarine model = 0 experience = 5 } 
division = { id = { type = 14800 id = 182 } name = "USS S-31" type = submarine model = 0 experience = 5 } 
division = { id = { type = 14800 id = 183 } name = "USS S-32" type = submarine model = 0 experience = 5 } 
division = { id = { type = 14800 id = 184 } name = "USS S-34" type = submarine model = 0 experience = 5 } 
division = { id = { type = 14800 id = 185 } name = "USS S-35" type = submarine model = 0 experience = 5 } 
division = { id = { type = 14800 id = 186 } name = "USS S-36" type = submarine model = 0 experience = 5 } 
division = { id = { type = 14800 id = 187 } name = "USS S-38" type = submarine model = 0 experience = 5 } 
division = { id = { type = 14800 id = 188 } name = "USS S-39" type = submarine model = 0 experience = 5 } 
division = { id = { type = 14800 id = 189 } name = "USS S-40" type = submarine model = 0 experience = 5 } 
division = { id = { type = 14800 id = 190 } name = "USS S-41" type = submarine model = 0 experience = 5 } 
} 

navalunit = { 
name = "Submarine Division 11" 
id = { type = 14800 id = 207 } 
location = 1734 #Pearl Habor 
base = 1734 #Pearl Habor
division = { id = { type = 14800 id = 208 } name = "USS S-44" type = submarine model = 0 experience = 5 } 
division = { id = { type = 14800 id = 209 } name = "USS S-18" type = submarine model = 0 experience = 5 } 
division = { id = { type = 14800 id = 210 } name = "USS S-46" type = submarine model = 0 experience = 5 } 
division = { id = { type = 14800 id = 211 } name = "USS S-33" type = submarine model = 0 experience = 5 } 
division = { id = { type = 14800 id = 212 } name = "USS S-43" type = submarine model = 0 experience = 5 } 
}

navalunit = { 
name = "Submarine Division 17" 
id = { type = 14800 id = 219 } 
location = 1734 #Pearl Habor 
base = 1734 #Pearl Habor
division = { id = { type = 14800 id = 426 } name = "USS S-37" type = submarine model = 0 experience = 5 } 
division = { id = { type = 14800 id = 427 } name = "USS S-21" type = submarine model = 0 experience = 5 } 
division = { id = { type = 14800 id = 428 } name = "USS S-24" type = submarine model = 0 experience = 5 } 
division = { id = { type = 14800 id = 429 } name = "USS S-25" type = submarine model = 0 experience = 5 } 
} 

navalunit = { 
name = "Submarine Division 7" 
id = { type = 14800 id = 213 } 
location = 1734 #Pearl Habor 
base = 1734 #Pearl Habor
division = { id = { type = 14800 id = 214 } name = "USS S-23" type = submarine model = 0 experience = 5 } 
division = { id = { type = 14800 id = 215 } name = "USS S-26" type = submarine model = 0 experience = 5 } 
division = { id = { type = 14800 id = 216 } name = "USS S-27" type = submarine model = 0 experience = 5 } 
division = { id = { type = 14800 id = 217 } name = "USS S-28" type = submarine model = 0 experience = 5 } 
division = { id = { type = 14800 id = 218 } name = "USS S-29" type = submarine model = 0 experience = 5 } 
division = { id = { type = 14800 id = 430 } name = "USS S-1" type = submarine model = 0 experience = 5 } 
}

navalunit = { 
name = "Submarine Reserve Division 14" 
id = { type = 14800 id = 431 } 
location = 1734 #Pearl Habor 
base = 1734 #Pearl Habor
division = { id = { type = 14800 id = 432 } name = "USS S-45" type = submarine model = 0 experience = 5 } 
division = { id = { type = 14800 id = 433 } name = "USS S-47" type = submarine model = 0 experience = 5 } 
}

navalunit = { 
name = "Submarine Division 12" 
id = { type = 14800 id = 220 } 
location = 1886 #San Diego 
base = 1886 #San Diego
division = { id = { type = 14800 id = 221 } name = "USS Barracuda" type = d_08 model = 0 experience = 5 } 
division = { id = { type = 14800 id = 222 } name = "USS Bass" type = d_08 model = 0 experience = 5 } 
division = { id = { type = 14800 id = 223 } name = "USS Bonita" type = d_08 model = 0 experience = 5 } 
division = { id = { type = 14800 id = 224 } name = "USS Narwhal" type = d_08 model = 1 experience = 5 } 
division = { id = { type = 14800 id = 225 } name = "USS Dolphin" type = d_08 model = 0 experience = 5 } 
division = { id = { type = 14800 id = 226 } name = "USS Cachalot" type = Submarine model = 1 experience = 5 } 
division = { id = { type = 14800 id = 227 } name = "USS Cuttlefish" type = Submarine model = 1 experience = 5 } 
}

navalunit = { 
name = "Submarine Division 13" 
id = { type = 14800 id = 228 } 
location = 1886 #San Diego 
base = 1886 #San Diego
division = { id = { type = 14800 id = 229 } name = "USS Nautilus" type = d_08 model = 1 experience = 5 } 
}

navalunit = { 
name = "Submarine Division 20" 
id = { type = 14800 id = 230 } 
location = 1886 #San Diego 
base = 1886 #San Diego
division = { id = { type = 14800 id = 231 } name = "USS Argonaut" type = d_08 model = 1 experience = 5 } 
} 

navalunit = { 
name = "Submarine Division 21" 
id = { type = 14800 id = 560 } 
location = 1886 #San Diego 
base = 1886 #San Diego
division = { id = { type = 14800 id = 549 } name = "USS Porpoise" type = Submarine model = 2 experience = 5 } 
division = { id = { type = 14800 id = 550 } name = "USS Pike" type = Submarine model = 2 experience = 5 } 
} 

navalunit = { 
name = "Destroyer Flotilla 1" 
id = { type = 14800 id = 244 } 
location = 1734 #Pearl Habor 
base = 1734 #Pearl Habor 
division = { id = { type = 14800 id = 245 } name = "USS Sproston" type = destroyer model = 1 strength = 20 experience = 20 } # scrapped in december 1936
division = { id = { type = 14800 id = 246 } name = "USS Hogan" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 248 } name = "USS Howard" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 249 } name = "USS Stansbury" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 254 } name = "USS Schley" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 256 } name = "USS Crane" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 257 } name = "USS Rathburne" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 258 } name = "USS Talbot" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 259 } name = "USS Waters" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 260 } name = "USS Dent" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 261 } name = "USS Whipple" type = destroyer model = 1 experience = 20 }
division = { id = { type = 14800 id = 618 } name = "USS Williamson" type = destroyer model = 1 experience = 20 }
division = { id = { type = 14800 id = 619 } name = "USS Zane" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 625 } name = "USS Wadsworth" type = destroyer model = 1 strength = 20 experience = 20 } # wrecked july 36
division = { id = { type = 14800 id = 262 } name = "USS Aylwin" type = destroyer model = 2 experience = 20 } 
division = { id = { type = 14800 id = 263 } name = "USS Dale" type = destroyer model = 2 experience = 20 } 
division = { id = { type = 14800 id = 264 } name = "USS Dewey" type = destroyer model = 2 experience = 20 } 
division = { id = { type = 14800 id = 265 } name = "USS Farragut" type = destroyer model = 2 experience = 20 } 
division = { id = { type = 14800 id = 266 } name = "USS Hull" type = destroyer model = 2 experience = 20 } 
division = { id = { type = 14800 id = 267 } name = "USS Macdonough" type = destroyer model = 2 experience = 20 } 
division = { id = { type = 14800 id = 268 } name = "USS Monaghan" type = destroyer model = 2 experience = 20 } 
} 


navalunit = { 
name = "Destroyer Flotilla 2" 
id = { type = 14800 id = 269 } 
location = 1886 #San Diego 
base = 1886 #San Diego
division = { id = { type = 14800 id = 270 } name = "USS Tucker" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 275 } name = "USS Manley" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 278 } name = "USS Barker" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 279 } name = "USS Barry" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 280 } name = "USS Borie" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 282 } name = "USS Brooks" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 283 } name = "USS Broome" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 284 } name = "USS Bulmer" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 285 } name = "USS Dahlgren" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 286 } name = "USS Abbot" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 287 } name = "USS Bagley" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 288 } name = "USS Alden" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 289 } name = "USS Bainbridge" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 290 } name = "USS Dorsey" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 291 } name = "USS Lea" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 292 } name = "USS Lamberton" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 293 } name = "USS Montgomery" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 576 } name = "USS Belknap" type = destroyer model = 1 experience = 20 } # in rotating reserve until 1940
division = { id = { type = 14800 id = 577 } name = "USS Borie" type = destroyer model = 1 experience = 20 }
division = { id = { type = 14800 id = 630 } name = "USS Chandler" type = destroyer model = 1 experience = 20 }
division = { id = { type = 14800 id = 579 } name = "USS Childs" type = destroyer model = 1 experience = 20 }
division = { id = { type = 14800 id = 583 } name = "USS Gillis" type = destroyer model = 1 experience = 20 } # in rotating reserve until 1940
division = { id = { type = 14800 id = 585 } name = "USS Greene" type = destroyer model = 1 experience = 20 } # in rotating reserve until 1940
division = { id = { type = 14800 id = 587 } name = "USS Hopkins" type = destroyer model = 1 experience = 20 }
division = { id = { type = 14800 id = 588 } name = "USS Hovey" type = destroyer model = 1 experience = 20 }
} 



navalunit = { 
name = "Destroyer Flotilla 3" 
id = { type = 14800 id = 294 } 
location = 1812 #Norfolk 
base = 1812 #Norfolk
division = { id = { type = 14800 id = 295 } name = "USS Gregory" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 296 } name = "USS Stringham" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 297 } name = "USS Colhoun" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 300 } name = "USS McKean" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 301 } name = "USS Gridley" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 304 } name = "USS Boggs" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 305 } name = "USS Kilty" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 306 } name = "USS Kennison" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 307 } name = "USS Ward" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 309 } name = "USS Hamilton" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 310 } name = "USS Tarbell" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 311 } name = "USS Fox" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 312 } name = "USS Taylor" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 313 } name = "USS Bell" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 314 } name = "USS Stribling" type = destroyer model = 1 strength = 20 experience = 20 } # wrecked in december 36 
division = { id = { type = 14800 id = 315 } name = "USS Israel" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 317 } name = "USS Upshur" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 318 } name = "USS Greer" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 319 } name = "USS Leary" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 320 } name = "USS Schenck" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 321 } name = "USS Herbert" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 322 } name = "USS Palmer" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 324 } name = "USS Walker" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 325 } name = "USS Crosby" type = destroyer model = 1 experience = 20 } 
} 


navalunit = { 
name = "Destroyer Flotilla 4" 
id = { type = 14800 id = 327 } 
location = 1812 #Norfolk 
base = 1812 #Norfolk 
division = { id = { type = 14800 id = 328 } name = "USS Gilmer" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 329 } name = "USS Goff" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 330 } name = "USS Hatfield" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 331 } name = "USS Humphreys" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 332 } name = "USS John D. Edwards" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 333 } name = "USS John D. Ford" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 334 } name = "USS Kane" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 335 } name = "USS King" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 336 } name = "USS Noa" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 337 } name = "USS Overton" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 338 } name = "USS Parrot" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 339 } name = "USS Paul Jones" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 340 } name = "USS Peary" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 599 } name = "USS Perry" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 341 } name = "USS Pillsbury" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 342 } name = "USS Pope" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 600 } name = "USS Preble" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 601 } name = "USS Pruitt" type = destroyer model = 1 experience = 20 } # converted to minelayer
division = { id = { type = 14800 id = 343 } name = "USS Reuben James" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 344 } name = "USS Worden" type = destroyer model = 2 experience = 20 } 
division = { id = { type = 14800 id = 346 } name = "USS Little" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 347 } name = "USS Kimberly" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 349 } name = "USS Dallas" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 350 } name = "USS Decatur" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 351 } name = "USS Edsall" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 352 } name = "USS Roper" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 353 } name = "USS Breckinridge" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 354 } name = "USS Barney" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 355 } name = "USS Blakeley" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 356 } name = "USS Biddle" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 357 } name = "USS Du Pont" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 358 } name = "USS Bernadou" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 359 } name = "USS Ellis" type = destroyer model = 1 experience = 20 } 
} 


navalunit = { 
name = "Destroyer Squadron 27" 
id = { type = 14800 id = 360 } 
location = 889 #Panama canal 
base = 889 
division = { id = { type = 14800 id = 361 } name = "USS Elliot" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 365 } name = "USS Anthony" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 366 } name = "USS Lawrence" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 620 } name = "USS Allen" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 367 } name = "USS Litchfield" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 368 } name = "USS McCormick" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 592 } name = "USS Long" type = destroyer model = 1 experience = 20 } # in rotating reserve
division = { id = { type = 14800 id = 593 } name = "USS MacLeish" type = destroyer model = 1 experience = 20 }
division = { id = { type = 14800 id = 574 } name = "USS Ballard" type = destroyer model = 1 experience = 20 } # in rotating reserve
} 


navalunit = { 
name = "Destroyer Squadron 28" 
id = { type = 14800 id = 369 } 
location = 1874 #Seattle
base = 1874 #Seattle 
division = { id = { type = 14800 id = 371 } name = "USS Sands" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 604 } name = "USS Semmes" type = destroyer model = 1 experience = 20 } # converted to experimental ship
division = { id = { type = 14800 id = 606 } name = "USS Sicard" type = destroyer model = 1 experience = 20 }
division = { id = { type = 14800 id = 372 } name = "USS Simpson" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 607 } name = "USS Southard" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 608 } name = "USS Stewart" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 609 } name = "USS Sturtevant" type = destroyer model = 1 experience = 20 } # in rotating reserve until 1940
division = { id = { type = 14800 id = 610 } name = "USS Thornton" type = destroyer model = 1 experience = 20 } # in rotating reserve until 1940
division = { id = { type = 14800 id = 611 } name = "USS Tracy" type = destroyer model = 1 experience = 20 }
division = { id = { type = 14800 id = 612 } name = "USS Trever" type = destroyer model = 1 experience = 20 }
division = { id = { type = 14800 id = 374 } name = "USS Truxtun" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 613 } name = "USS Turner" type = destroyer model = 1 experience = 20 } # rebuilt to barge 1936
division = { id = { type = 14800 id = 614 } name = "USS Wasmuth" type = destroyer model = 1 experience = 20 }
division = { id = { type = 14800 id = 375 } name = "USS Cole" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 376 } name = "USS J Fred Talbott" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 377 } name = "USS Dickerson" type = destroyer model = 1 experience = 20 } 
} 


navalunit = { 
name = "Destroyer Squadron 29" 
id = { type = 14800 id = 378 } 
location = 1874 #Seattle
base = 1874 #Seattle 
division = { id = { type = 14800 id = 379 } name = "USS Breese" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 380 } name = "USS Gamble" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 381 } name = "USS Ramsay" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 382 } name = "USS Tattnall" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 383 } name = "USS Badger" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 385 } name = "USS Babbit" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 628 } name = "USS Chew" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 386 } name = "USS Jacob Jones" type = destroyer model = 1 experience = 20 } 
division = { id = { type = 14800 id = 388 } name = "USS Aron Ward" type = destroyer model = 1 experience = 20 } 
} 



navalunit = { 
name = "Atlantic Transport Flotilla" 
id = { type = 14800 id = 391 } 
location = 1795 #New York 
base = 1795 #New York 
division = { id = { type = 14800 id = 392 } name = "M/S Abner Doubleday" type = transport model = 0 experience = 20 } 
division = { id = { type = 14800 id = 393 } name = "M/S Brigham Young" type = transport model = 0 experience = 20 } 
division = { id = { type = 14800 id = 394 } name = "M/S William B. Travis" type = transport model = 0 experience = 20 } 
division = { id = { type = 14800 id = 395 } name = "M/S Peter Stuyvesant" type = transport model = 0 experience = 20 } 
division = { id = { type = 14800 id = 396 } name = "M/S Henry L. Benning" type = transport model = 0 experience = 20 } 
division = { id = { type = 14800 id = 397 } name = "M/S Casimir Pulaski" type = transport model = 0 experience = 20 } 
division = { id = { type = 14800 id = 398 } name = "M/S Sam Houston" type = transport model = 0 experience = 20 } 
division = { id = { type = 14800 id = 399 } name = "M/S Francis Scott Key" type = transport model = 0 experience = 20 } 
division = { id = { type = 14800 id = 400 } name = "M/S Walter Reed" type = transport model = 0 experience = 20 } 
division = { id = { type = 14800 id = 401 } name = "M/S Dolly Madison" type = transport model = 0 experience = 20 } 
division = { id = { type = 14800 id = 402 } name = "M/S Frederick Douglas" type = transport model = 0 experience = 20 } 
division = { id = { type = 14800 id = 403 } name = "M/S Clara Barton" type = transport model = 0 experience = 20 } 
} 

navalunit = { 
name = "Pacific Transport Flotilla" 
id = { type = 14800 id = 404 } 
location = 1887 #Los Angeles 
base = 1887 #Los Angeles 
division = { id = { type = 14800 id = 405 } name = "M/S Charles Goodyear" type = transport model = 0 experience = 20 } 
division = { id = { type = 14800 id = 406 } name = "M/S Anthony Wayne" type = transport model = 0 experience = 20 } 
division = { id = { type = 14800 id = 407 } name = "M/S John Hancock" type = transport model = 0 experience = 20 } 
division = { id = { type = 14800 id = 408 } name = "M/S Samuel Dexter" type = transport model = 0 experience = 20 } 
division = { id = { type = 14800 id = 409 } name = "M/S Stephen C. Crane" type = transport model = 0 experience = 20 } 
division = { id = { type = 14800 id = 410 } name = "M/S William McKinley" type = transport model = 0 experience = 20 } 
division = { id = { type = 14800 id = 411 } name = "M/S George A. Custer" type = transport model = 0 experience = 20 } 
division = { id = { type = 14800 id = 412 } name = "M/S August Belmont" type = transport model = 0 experience = 20 } 
division = { id = { type = 14800 id = 413 } name = "M/S Emily Dickinson" type = transport model = 0 experience = 20 } 
division = { id = { type = 14800 id = 414 } name = "M/S Molly Pitcher" type = transport model = 0 experience = 20 } 
division = { id = { type = 14800 id = 415 } name = "M/S Antonin Dvorak" type = transport model = 0 experience = 20 } 
division = { id = { type = 14800 id = 416 } name = "M/S J. E. B. Stuart" type = transport model = 0 experience = 20 } 
} 

#navalunit = { 
#name = "Subic Bay Flotilla" 
#id = { type = 14800 id = 444 } 
#location = 1565 # Manila 
#base = 1565 # Manila 
#division = { id = { type = 14800 id = 445 } name = "USS Rochester" type = battlecruiser model = 0 strength = 20 experience = 20 } # 
#} 

navalunit = { 
name = "USS Cheyenne" 
id = { type = 14800 id = 446 } 
location = 1805 # Philadelphia 
base = 1805 # Philadelphia 
division = { id = { type = 14800 id = 447 } name = "USS Cheyenne" type = heavy_cruiser model = 1 strength = 20 experience = 20 } # 
} 

navalunit = { 
name = "Gunboat Flotilla" 
id = { type = 14800 id = 634 } 
location = 1887 # Los Angeles
base = 1887 # Los Angeles
division = { id = { type = 14800 id = 635 } name = "USS Asheville" type = d_09 model = 0 experience = 20 }
division = { id = { type = 14800 id = 636 } name = "USS Tulsa" type = d_09 model = 0 experience = 20 }
division = { id = { type = 14800 id = 637 } name = "USS Sacramento" type = d_09 model = 0 experience = 20 }
} 

###############################################
# dormant USS Wyoming
###############################################
navaldivision = { id = { type = 14800 id = 448 } name = "USS Wyoming" type = battleship model = 1 dormant = yes strength = 50 experience = 20 extra = naval_anti_air_l } # USS Wyoming, partly disarmed and armor plating removed, used for gunnery training
###############################################
# dormant USS Rochester
###############################################
navaldivision = { id = { type = 14800 id = 445 } name = "USS Rochester" type = battlecruiser model = 0 dormant = yes strength = 20 experience = 20 } # 
###############################################
# dormant USS Langley
###############################################
navaldivision = { id = { type = 14800 id = 122 } name = "USS Langley" type = escort_carrier model = 2 dormant = yes experience = 20 } # conversion CVL to CVE decided in 1935, begun in mid 1936
navaldivision = { id = { type = 14800 id = 631 } name = "USS Langley" type = light_carrier model = 0 extra = light_cag dormant = yes experience = 20 }
###############################################
# dormant destroyers for bases
###############################################

navaldivision = { id = { type = 14800 id = 273 } name = "USS Conner" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Britain. Renamed HMS Leeds
navaldivision = { id = { type = 14800 id = 271 } name = "USS Craven" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Britain. Renamed HMS Lewes
navaldivision = { id = { type = 14800 id = 274 } name = "USS Stockton" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Britain. Renamed HMS Ludlow
navaldivision = { id = { type = 14800 id = 571 } name = "USS Abel P. Upshur" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Britain. Renamed HMS Clare
navaldivision = { id = { type = 14800 id = 572 } name = "USS Aulick" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Britain. Renamed HMS Burnham
navaldivision = { id = { type = 14800 id = 573 } name = "USS Bailey" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Britain. Renamed HMS Reading
navaldivision = { id = { type = 14800 id = 575 } name = "USS Bancroft" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Canada. Renamed HMCS St. Francis
navaldivision = { id = { type = 14800 id = 578 } name = "USS Branch" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Britain. Renamed HMS Beverley
navaldivision = { id = { type = 14800 id = 581 } name = "USS Edwards" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Britain. Renamed HMS Buxton
navaldivision = { id = { type = 14800 id = 586 } name = "USS Herndon" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Britain. Renamed HMS Churchill
navaldivision = { id = { type = 14800 id = 590 } name = "USS Hunt" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Britain. Renamed HMS Broadway
navaldivision = { id = { type = 14800 id = 591 } name = "USS Laub" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Britain. Renamed HMS Burwell
navaldivision = { id = { type = 14800 id = 594 } name = "USS Mason" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Britain. Renamed HMS Broadwater
navaldivision = { id = { type = 14800 id = 595 } name = "USS McCalla" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Britain. Renamed HMS Stanley
navaldivision = { id = { type = 14800 id = 596 } name = "USS McCook" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Canada. Renamed HMCS St. Croix
navaldivision = { id = { type = 14800 id = 597 } name = "USS McLanahan" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Britain. Renamed HMS Bradford
navaldivision = { id = { type = 14800 id = 370 } name = "USS Meade" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Britain. Renamed HMS Ramsey
navaldivision = { id = { type = 14800 id = 602 } name = "USS Rodgers" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Britain. Renamed HMS Sherwood
navaldivision = { id = { type = 14800 id = 603 } name = "USS Satterlee" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Britain. Renamed HMS Belmont
navaldivision = { id = { type = 14800 id = 605 } name = "USS Shubrick" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Britain. Renamed HMS Ripley
navaldivision = { id = { type = 14800 id = 373 } name = "USS Swasey" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Britain. Renamed HMS Rockingham
navaldivision = { id = { type = 14800 id = 615 } name = "USS Welborn C. Wood" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Britain. Renamed HMS Chesterfield
navaldivision = { id = { type = 14800 id = 616 } name = "USS Welles" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Britain. Renamed HMS Cameron
navaldivision = { id = { type = 14800 id = 626 } name = "USS Aaron Ward" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Britain. Renamed HMS Castleton
navaldivision = { id = { type = 14800 id = 627 } name = "USS Abbot" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Britain. Renamed HMS Charlestown
navaldivision = { id = { type = 14800 id = 387 } name = "USS Buchanan" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Britain. Renamed HMS Campbeltown
navaldivision = { id = { type = 14800 id = 308 } name = "USS Claxton" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Britain. Renamed HMS Salisbury
navaldivision = { id = { type = 14800 id = 326 } name = "USS Cowell" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Britain. Renamed HMS Brighton
navaldivision = { id = { type = 14800 id = 390 } name = "USS Crowninshield" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Britain. Renamed HMS Chelsea
navaldivision = { id = { type = 14800 id = 629 } name = "USS Doran" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Britain. Renamed HMS St. Marys
navaldivision = { id = { type = 14800 id = 345 } name = "USS Evans" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Britain. Renamed HMS Mansfield
navaldivision = { id = { type = 14800 id = 302 } name = "USS Fairfax" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Britain. Renamed HMS Richmond
navaldivision = { id = { type = 14800 id = 363 } name = "USS Foote" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Britain. Renamed HMS Roxborough
navaldivision = { id = { type = 14800 id = 389 } name = "USS Hale" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Britain. Renamed HMS Caldwell
navaldivision = { id = { type = 14800 id = 252 } name = "USS Haraden" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # Initially to Britain and then on to Canada. Renamed HMS Columbia then HMCS Columbia
navaldivision = { id = { type = 14800 id = 250 } name = "USS Hopewell" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Britain. Renamed HMS Bath
navaldivision = { id = { type = 14800 id = 364 } name = "USS Kalk" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Canada. Renamed HMCS Hamilton
navaldivision = { id = { type = 14800 id = 247 } name = "USS MacKenzie" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Canada. Renamed HMCS Annapolis
navaldivision = { id = { type = 14800 id = 362 } name = "USS Maddox" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Britain. Renamed HMS Georgetown
navaldivision = { id = { type = 14800 id = 277 } name = "USS Philip" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Britain. Renamed HMS Lancaster
navaldivision = { id = { type = 14800 id = 299 } name = "USS Ringgold" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Britain. Renamed HMS Newark
navaldivision = { id = { type = 14800 id = 298 } name = "USS Robinson" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Britain. Renamed HMS Newmarket
navaldivision = { id = { type = 14800 id = 348 } name = "USS Sigourney" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Britain. Renamed HMS Newport
navaldivision = { id = { type = 14800 id = 323 } name = "USS Thatcher" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Canada. Renamed HMCS Niagara
navaldivision = { id = { type = 14800 id = 251 } name = "USS Thomas" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Britain. Renamed HMS St. Albans
navaldivision = { id = { type = 14800 id = 303 } name = "USS Tillman" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Britain. Renamed HMS Wells
navaldivision = { id = { type = 14800 id = 384 } name = "USS Twiggs" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Britain. Renamed HMS Leamington
navaldivision = { id = { type = 14800 id = 276 } name = "USS Wickes" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Britain. Renamed HMS Montgomery
navaldivision = { id = { type = 14800 id = 255 } name = "USS Williams" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Canada. Renamed HMCS St. Clair
navaldivision = { id = { type = 14800 id = 316 } name = "USS Yarnall" type = destroyer model = 1 strength = 70 dormant = yes experience = 20 } # To Britain. Renamed HMS Lincoln

##################################################
#converted DDs; maybe implement them later?
##################################################
#division = { id = { type = 14800 id = 617 } name = "USS William B. Preston" type = destroyer model = 1 experience = 20 } # out of commission in 1922, back in action in 1939 as seaplane tender
#division = { id = { type = 14800 id = 598 } name = "USS Osmond Ingram" type = destroyer model = 1 experience = 20 } # out of commission in 1922, back in action in 1939 as seaplane tender
#division = { id = { type = 14800 id = 589 } name = "USS Hulbert" type = destroyer model = 1 experience = 20 } # out of commission in 1922, back in action in 1939 as seaplane tender
#division = { id = { type = 14800 id = 584 } name = "USS Goldsborough" type = destroyer model = 1 experience = 20 } # out of commission in 1922, back in action in 1939 as seaplane tender
#division = { id = { type = 14800 id = 580 } name = "USS Clemson" type = destroyer model = 1 experience = 20 } # out of commission in 1922, back in action in 1939 as seaplane tender
#division = { id = { type = 14800 id = 582 } name = "USS George E. Badger" type = destroyer model = 1 experience = 20 } # out of commission until 1934, then Coast Guard, back in action in 1939 as seaplane tender



convoy_development = {
        id = { type = 14800 id = 1400 }
        cost = 0.1
        size = 99
        type = transports
        date  = {  year = 1964 }
		unitcost = yes
        }
		
brigade_development = {
        id = { type = 14800 id = 1401 }
        name = "ASW 1936"
		cost = 0.04
        size = 30
        type = naval_asw
		model = 0
        date  = {  year = 1941 }
		unitcost = yes
        }
		
brigade_development = {
        id = { type = 14800 id = 1402 }
        name = "ASW 1936"
		cost = 0.04
        size = 30
        type = naval_asw
		model = 0
        date  = {  year = 1941 }
		unitcost = yes
        }
		
brigade_development = {
        id = { type = 14800 id = 1403 }
        name = "ASW 1936"
		cost = 0.04
        size = 30
        type = naval_asw
		model = 0
        date  = {  year = 1941 }
		unitcost = yes
        }
		
brigade_development = {
        id = { type = 14800 id = 1404 }
        name = "ASW 1936"
		cost = 0.04
        size = 30
        type = naval_asw
		model = 0
        date  = {  year = 1941 }
		unitcost = yes
        }
		
#brigade_development = {
#        id = { type = 14800 id = 1405 }
#        cost = 0.25
#        size = 20
#        type = engineer
#		model = 0
#        date  = {  year = 1940 }
#		unitcost = yes
#        }

brigade_development = {
        id = { type = 14800 id = 1406 }
        name = "Capital Improved Hull 1936"
		cost = 0.04
        size = 10
        type = naval_improved_hull_l
		model = 0
        date  = {  year = 1941 }
		unitcost = yes
        }
		
brigade_development = {
        id = { type = 14800 id = 1407 }
        name = "Torpedoes 1936"
		cost = 0.05
        size = 20
        type = naval_torpedoes_s
		model = 0
        date  = {  year = 1941 }
		unitcost = yes
        }
		
brigade_development = {
        id = { type = 14800 id = 1408 }
        name = "Floatplane 1930"
		cost = 0.02
        size = 30
        type = floatplane
		model = 0
        date  = {  year = 1941 }
		unitcost = yes
        }

division_development = {
	name = "USS Yorktown"
	type = carrier
	extra = cag
	model = 1
	cost = 0.5 #5
	 #experience = 20
	new_model = no unitcost = yes	 
	id = { type = 14800 id = 539 }
	date = { year = 1937 month = september day = 29 }
	}

division_development = {
	name = "USS Enterprise"
	type = carrier
	extra = cag
	model = 1
	cost = 0.5 #5
	 #experience = 20
	new_model = no unitcost = yes	 
	id = { type = 14800 id = 540 }
	date = { year = 1938 month = may day = 11 }
	}

	division_development = {
	name = "USS Quincy"
	type = heavy_cruiser
	model = 5
	cost = 0.2 #2
	 #experience = 20
	new_model = no unitcost = yes
    extra = floatplane
	id = { type = 14800 id = 501 }
	date = { year = 1936 month = june day = 9 }
	}

	division_development = {
	name = "USS Vincennes"
	type = heavy_cruiser
	model = 5
	cost = 0.2 #2
	 #experience = 20
	new_model = no unitcost = yes
    extra = floatplane
	id = { type = 14800 id = 517 }
	date = { year = 1937 month = february day = 23 }
	}

	division_development = {
	name = "USS Wichita"
	type = heavy_cruiser
	model = 7
	cost = 0.2 #2
	 #experience = 20
	new_model = no unitcost = yes
	extra = floatplane
	id = { type = 14800 id = 518 }
	date = { year = 1939 month = february day = 15 }
	}

	division_development = {
	name = "USS Brooklyn"
	type = light_cruiser
	model = 4
	cost = 0.15 #1.5
	 #experience = 20
	new_model = no unitcost = yes
	id = { type = 14800 id = 541 }
	date = { year = 1937 month = september day = 29 }
	}

	division_development = {
	name = "USS Philadelphia"
	type = light_cruiser
	model = 4
	cost = 0.15 #1.5
	 #experience = 20
	new_model = no unitcost = yes
	id = { type = 14800 id = 542 }
	date = { year = 1937 month = september day = 22 }
	}

	division_development = {
	name = "USS Savannah"
	type = light_cruiser
	model = 4
	cost = 0.15 #1.5
	 #experience = 20
	new_model = no unitcost = yes
	id = { type = 14800 id = 543 }
	date = { year = 1938 month = february day = 9 }
	}

	division_development = {
	name = "USS Nashville"
	type = light_cruiser
	model = 4
	cost = 0.15 #1.5
	 #experience = 20
	new_model = no unitcost = yes
	id = { type = 14800 id = 544 }
	date = { year = 1938 month = june day = 5 }
	}

	division_development = {
	name = "USS Phoenix"
	type = light_cruiser
	model = 4
	cost = 0.15 #1.5
	 #experience = 20
	new_model = no unitcost = yes
	id = { type = 14800 id = 545 }
	date = { year = 1938 month = october day = 2 }
	}

	division_development = {
	name = "USS Boise"
	type = light_cruiser
	model = 4
	cost = 0.15 #1.5
	 #experience = 20
	new_model = no unitcost = yes
	id = { type = 14800 id = 546 }
	date = { year = 1938 month = august day = 11 }
	}

	division_development = {
	name = "USS Honolulu"
	type = light_cruiser
	model = 4
	cost = 0.15 #1.5
	 #experience = 20
	new_model = no unitcost = yes
	id = { type = 14800 id = 547 }
	date = { year = 1938 month = june day = 14 }
	}
	
	division_development = {
	name = "USS Selfridge"
	type = d_09
	model = 3
	cost = 0.06 #0.6
	 #experience = 20
	new_model = no unitcost = yes
	id = { type = 14800 id = 509 }
	date = { year = 1936 month = november day = 25 }
	}

	division_development = {
	name = "USS Balch"
	type = d_09
	model = 3
	cost = 0.06 #0.6
	 #experience = 20
	new_model = no unitcost = yes
	id = { type = 14800 id = 510 }
	date = { year = 1936 month = october day = 19 }
	}
	
	division_development = {
	name = "USS Drayton"
	type = destroyer
	model = 3
	cost = 0.06 #0.6
	 #experience = 20
	new_model = no unitcost = yes
	id = { type = 14800 id = 511 }
	date = { year = 1936 month = september day = 0 }
	}	

	division_development = {
	name = "USS Reid"
	type = destroyer
	model = 3
	cost = 0.06 #0.6
	 #experience = 20
	new_model = no unitcost = yes
	id = { type = 14800 id = 512 }
	date = { year = 1936 month = november day = 0 }
	}
	
	division_development = {
	name = "USS Tucker"
	type = destroyer
	model = 3
	cost = 0.06 #0.6
	 #experience = 20
	new_model = no unitcost = yes
	id = { type = 14800 id = 513 } 
	date = { year = 1936 month = july day = 22 }
	}

	division_development = {
	name = "USS Smith"
	type = destroyer
	model = 3
	cost = 0.06 #0.6
	 #experience = 20
	new_model = no unitcost = yes
	id = { type = 14800 id = 514 } 
	date = { year = 1936 month = september day = 8 }
	}

	division_development = {
	name = "USS Preston"
	type = destroyer
	model = 3
	cost = 0.06 #0.6
	 #experience = 20
	new_model = no unitcost = yes
	id = { type = 14800 id = 515 } 
	date = { year = 1936 month = october day = 26 }
	}
	
	division_development = {
	name = "USS Dunlap"
	type = destroyer
	model = 3
	cost = 0.06 #0.6
	 #experience = 20
	new_model = no unitcost = yes
	id = { type = 14800 id = 516 }
	date = { year = 1936 month = june day = 0 }
	}

	division_development = {
	name = "USS Craven"
	type = destroyer
	model = 3
	cost = 0.06 #0.6
	 #experience = 20
	new_model = no unitcost = yes
	id = { type = 14800 id = 519 } 
	date = { year = 1937 month = september day = 0 }
	}

	division_development = {
	name = "USS Gridley"
	type = destroyer
	model = 3
	cost = 0.06 #0.6
	 #experience = 20
	new_model = no unitcost = yes
	id = { type = 14800 id = 520 }
	date = { year = 1937 month = june day = 23 }
	}	

	division_development = {
	name = "USS Case"
	type = destroyer
	model = 3
	cost = 0.06 #0.6
	 #experience = 20
	new_model = no unitcost = yes
	id = { type = 14800 id = 521 }
	date = { year = 1936 month = september day = 14 }
	}

	division_development = {
	name = "USS Cassin"
	type = destroyer
	model = 3
	cost = 0.06 #0.6
	 #experience = 20
	new_model = no unitcost = yes
	id = { type = 14800 id = 522 }
	date = { year = 1936 month = august day = 20 }
	}

	division_development = {
	name = "USS Conyngham"
	type = destroyer
	model = 3
	cost = 0.06 #0.6
	 #experience = 20
	new_model = no unitcost = yes
	id = { type = 14800 id = 523 }
	date = { year = 1936 month = november day = 3 }
	}

	division_development = {
	name = "USS Cummings"
	type = destroyer
	model = 3
	cost = 0.06 #0.6
	 #experience = 20
	new_model = no unitcost = yes
	id = { type = 14800 id = 524 }
	date = { year = 1936 month = november day = 24 }
	}

	division_development = {
	name = "USS Cushing"
	type = destroyer
	model = 3
	cost = 0.06 #0.6
	 #experience = 20
	new_model = no unitcost = yes
	id = { type = 14800 id = 525 }
	date = { year = 1936 month = august day = 27 }
	}

	division_development = {
	name = "USS Downes"
	type = destroyer
	model = 3
	cost = 0.06 #0.6
	 #experience = 20
	new_model = no unitcost = yes
	id = { type = 14800 id = 526 }
	date = { year = 1937 month = january day = 14 }
	}

	division_development = {
	name = "USS Fanning"
	type = destroyer
	model = 3
	cost = 0.06 #0.6
	 #experience = 20
	new_model = no unitcost = yes
	id = { type = 14800 id = 527 }
	date = { year = 1937 month = october day = 7 }
	}

	division_development = {
	name = "USS Flusser"
	type = destroyer
	model = 3
	cost = 0.06 #0.6
	 #experience = 20
	new_model = no unitcost = yes
	id = { type = 14800 id = 528 }
	date = { year = 1936 month = october day = 0 }
	}

	division_development = {
	name = "USS Lamson"
	type = destroyer
	model = 3
	cost = 0.06 #0.6
	 #experience = 20
	new_model = no unitcost = yes
	id = { type = 14800 id = 529 }
	date = { year = 1936 month = october day = 20 }
	}

	division_development = {
	name = "USS Mahan"
	type = destroyer
	model = 3
	cost = 0.06 #0.6
	 #experience = 20
	new_model = no unitcost = yes 
	id = { type = 14800 id = 530 }
	date = { year = 1936 month = september day = 17 }
	}

	division_development = {
	name = "USS Perkins"
	type = destroyer
	model = 3
	cost = 0.06 #0.6
	 #experience = 20
	new_model = no unitcost = yes
	id = { type = 14800 id = 531 }
	date = { year = 1936 month = september day = 17 }
	}

	division_development = {
	name = "USS Shaw"
	type = destroyer
	model = 3
	cost = 0.06 #0.6
	 #experience = 20
	new_model = no unitcost = yes
	id = { type = 14800 id = 532 }
	date = { year = 1936 month = september day = 17 }
	}

	division_development = {
	name = "USS Clark"
	type = d_09
	model = 3
	cost = 0.06 #0.6
	 #experience = 20
	new_model = no unitcost = yes
	id = { type = 14800 id = 533 }
	date = { year = 1936 month = may day = 19 }
	}

	division_development = {
	name = "USS McDougal"
	type = d_09
	model = 3
	cost = 0.06 #0.6
	 #experience = 20
	new_model = no unitcost = yes
	id = { type = 14800 id = 534 }
	date = { year = 1936 month = december day = 22 }
	}

	division_development = {
	name = "USS Moffett"
	type = d_09
	model = 3
	cost = 0.06 #0.6
	 #experience = 20
	new_model = no unitcost = yes
	id = { type = 14800 id = 535 }
	date = { year = 1936 month = august day = 27 }
	}

	division_development = {
	name = "USS Phelps"
	type = d_09
	model = 3
	cost = 0.06 #0.6
	 #experience = 20
	new_model = no unitcost = yes
	id = { type = 14800 id = 536 }
	date = { year = 1936 month = february day = 25 }
	}

	division_development = {
	name = "USS Porter"
	type = d_09
	model = 3
	cost = 0.06 #0.6
	 #experience = 20
	new_model = no unitcost = yes
	id = { type = 14800 id = 537 }
	date = { year = 1936 month = august day = 24 }
	}

	division_development = {
	name = "USS Winslow"
	type = d_09
	model = 3
	cost = 0.06 #0.6
	 #experience = 20
	new_model = no unitcost = yes
	id = { type = 14800 id = 538 }
	date = { year = 1937 month = february day = 16 }
	}
	
		division_development = {
	name = "USS Bagley"
	type = destroyer
	model = 3
	cost = 0.06 #0.6
	 #experience = 20
	new_model = no unitcost = yes
	id = { type = 14800 id = 563 }
	date = { year = 1937 month = june day = 11 }
	}
		
		division_development = {
	name = "USS Blue"
	type = destroyer
	model = 3
	cost = 0.06 #0.6
	 #experience = 20
	new_model = no unitcost = yes
	id = { type = 14800 id = 564 }
	date = { year = 1937 month = august day = 13 }
	}
		
		division_development = {
	name = "USS Helm"
	type = destroyer
	model = 3
	cost = 0.06 #0.6
	 #experience = 20
	new_model = no unitcost = yes
	id = { type = 14800 id = 565 }
	date = { year = 1937 month = october day = 15 }
	}
		
		division_development = {
	name = "USS Henley"
	type = destroyer
	model = 3
	cost = 0.06 #0.6
	 #experience = 20
	new_model = no unitcost = yes
	id = { type = 14800 id = 566 }
	date = { year = 1937 month = august day = 13 }
	}
		
		division_development = {
	name = "USS Jarvis"
	type = destroyer
	model = 3
	cost = 0.06 #0.6
	 #experience = 20
	new_model = no unitcost = yes
	id = { type = 14800 id = 567 }
	date = { year = 1937 month = october day = 26 }
	}
		
		division_development = {
	name = "USS Mugford"
	type = destroyer
	model = 3
	cost = 0.06 #0.6
	 #experience = 20
	new_model = no unitcost = yes
	id = { type = 14800 id = 568 }
	date = { year = 1937 month = august day = 15 }
	}
		
		division_development = {
	name = "USS Patterson"
	type = destroyer
	model = 3
	cost = 0.06 #0.6
	 #experience = 20
	new_model = no unitcost = yes
	id = { type = 14800 id = 569 }
	date = { year = 1937 month = september day = 21 }
	}
		
		division_development = {
	name = "USS Ralph Talbot"
	type = destroyer
	model = 3
	cost = 0.06 #0.6
	 #experience = 20
	new_model = no unitcost = yes
	id = { type = 14800 id = 570 }
	date = { year = 1937 month = october day = 13 }
	}
	
		division_development = { 
	name = "USS Davis"
	type = d_09
	model = 4
	cost = 0.06 #0.6
	new_model = no unitcost = yes
	id = { type = 14800 id = 621 }
	date = { year = 1938 month = november day = 8 }
	}
			
		division_development = {
	name = "USS Sampson"
	type = d_09
	model = 4
	cost = 0.06 #0.6
	new_model = no unitcost = yes
	id = { type = 14800 id = 622 }
	date = { year = 1938 month = august day = 18 }
	}
			
		division_development = {
	name = "USS Somers"
	type = d_09
	model = 4
	cost = 0.06 #0.6
	new_model = no unitcost = yes
	id = { type = 14800 id = 623 }
	date = { year = 1937 month = december day = 0 }
	}
			
		division_development = {
	name = "USS Warrington"
	type = d_09
	model = 4
	cost = 0.06 #0.6
	new_model = no unitcost = yes
	id = { type = 14800 id = 624 }
	date = { year = 1938 month = february day = 8 }
	}
	
		division_development = {
	name = "USS Erie"
	type = d_09
	model = 2
	cost = 0.06 #0.6
	new_model = no unitcost = yes
	id = { type = 14800 id = 632 }
	date = { year = 1936 month = july day = 1 }
	}
	
		division_development = {
	name = "USS Charleston"
	type = d_09
	model = 2
	cost = 0.06 #0.6
	new_model = no unitcost = yes
	id = { type = 14800 id = 633 }
	date = { year = 1936 month = july day = 1 }
	}
	
		division_development = {
	name = "USS Shark"
	type = submarine
	model = 2
	cost = 0.05 #0.5
	new_model = no unitcost = yes
	id = { type = 14800 id = 557 }
	date = { year = 1936 month = january day = 25 }
	}
	
			division_development = {
	name = "USS Tarpon"
	type = submarine
	model = 2
	cost = 0.05 #0.5
	new_model = no unitcost = yes
	id = { type = 14800 id = 556 }
	date = { year = 1936 month = march day = 15 }
	}
	
	division_development = {
	name = "USS Perch"
	type = submarine
	model = 2
	cost = 0.05 #0.5
	new_model = no unitcost = yes
	id = { type = 14800 id = 555 }
	date = { year = 1936 month = november day = 19 }
	}
		division_development = {
	name = "USS Pickerel"
	type = submarine
	model = 2
	cost = 0.05 #0.5
	new_model = no unitcost = yes
	id = { type = 14800 id = 554 }
	date = { year = 1937 month = january day = 26 }
	}
	
		division_development = {
	name = "USS Permit"
	type = submarine
	model = 2
	cost = 0.05 #0.5
	new_model = no unitcost = yes
	id = { type = 14800 id = 553 }
	date = { year = 1937 month = march day = 17 }
	}
	
		division_development = {
	name = "USS Plunger"
	type = submarine
	model = 2
	cost = 0.05 #0.5
	new_model = no unitcost = yes
	id = { type = 14800 id = 552 }
	date = { year = 1936 month = november day = 19 }
	}
	
		division_development = {
	name = "USS Pollack"
	type = submarine
	model = 2
	cost = 0.05 #0.5
	new_model = no unitcost = yes
	id = { type = 14800 id = 551 }
	date = { year = 1937 month = january day = 15 }
	}
}